### PR TITLE
export plugin: hide all serverside-saving sections on MAST

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request uses the existing `server_is_remote` app-wide setting to hide the sections in the export plugin that would result in saving a file serverside (i.e. not through the file dialog).

To test: set `server_is_remote=False` in the config yaml file or set `viz.plugins['Export']._obj.serverside_enabled=False`.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
There is conflict in change log.

Also probably need approval from @havok2063 ?

**Comment by kecnry** [comment]
> There is conflict in change log

Yep, I'll rebase before merge (shouldn't hold up reviews though).  I don't think we need a review from @havok2063 (although he's welcome to) - this is the same machinery we've used in the past and they already have implemented on their end.

**Review by pllim — APPROVED** [review]
Code looks like code. Thanks!

**Review by bmorris3 — APPROVED** [review]
I reviewed this PR on Friday but didn't actually submit the review 🤦🏻‍♂️ 

This makes sense, thanks!

**Pull request merged**
