### PR TITLE
Add Mosviz NIRISS example notebook

### PR DESCRIPTION
**Pull request by javerbukh**

### CODE REVIEW

**Review by ibusko — COMMENTED** [review]
After displaying data, there is a long stack trace reporting "ValueError: FITS header values must contain standard printable ASCII characters; '\nPhotometry information\n\n\nInformation about the coordinates in the file\n' contains characters not representable in ASCII or non-printable characters.".

**Review by ibusko — COMMENTED** [review]
The notebook was saved in the repo with info messages showing up. Shouldn't it be saved with cleared output?

**Comment by pllim** [comment]
There is also a warning that the download can take very long, but the notebook basically forces you to download (albeit cached) and unpack into a new temporary directory every run.

**Comment by javerbukh** [comment]
@ibusko good catch! I'll fix that in the next commit.
@pllim Isn't that what the current MosvizExample notebook does? I based this one off of that.

**Comment by pllim** [comment]
@javerbukh , yes, but I also added some notes in #650 on how to bypass that once you already have the data locally, FWIW.

**Comment by javerbukh** [comment]
Gotcha, I'll update that.

**Comment by javerbukh** [comment]
Updated the notebook, thank you for your comments!

**Review by pllim — APPROVED** [review]

**Review by ibusko — APPROVED** [review]

**Comment by pllim** [comment]
Does this fix any of the following NIRISS related issues?

https://github.com/spacetelescope/jdaviz/issues?q=is%3Aissue+is%3Aopen+NIRISS+

**Comment by javerbukh** [comment]
Nope. But I'll start working on some of them now.

**Pull request merged**
