### PR TITLE
Set minimum dependency for scikit-image

### LINKED ISSUE #490: Issue with scikit-image on installation
Not sure what the cause of the issue is but it is known to happen on Mac OS. @PatrickOgle can you link the version of your conda environment and what version number of `scikit-image` that does not work on installation and then the version that does work after running the fix?

Solution for this issue (to be documented in readthedocs):
```
pip uninstall scikit-image
conda install scikit-image
```

### PR DESCRIPTION
**Pull request by javerbukh**
Potentially fixes #490

### CODE REVIEW

**Review by rosteen — APPROVED** [review]
At least doesn't break anything for me, I'll be curious to see whether it fixes @PatrickOgle 's problem.

**Review by PatrickOgle — COMMENTED** [review]
scikit-image problem still occurs for scikit-image=0.18.1 installed via  'pip install jdaviz'

**Comment by duytnguyendtn** [comment]
Small clarifying comment @PatrickOgle. My understanding is that `pip install jdaviz` will always pull from PyPI release. Did you mean to say `pip install .` or `pip install -e .` to signify you installed from this PR specifically?

**Comment by pllim** [comment]
Both `pip install` and `pip install -e` will pull missing dependencies from PyPI. If you wish to specify `conda` env setup, you need to provide a `conda` env YAML file instead.

**Comment by duytnguyendtn** [comment]
@pllim I think it's ok for the dependencies themselves to be pulled from PyPI, just that the `setup.cfg` for jdaviz 1.1 released in PyPI doesn't enforce `scikit-image>=0.18.1`. I just wanted to verify that @PatrickOgle's test installation actually used the new `setup.cfg` file in this PR, rather than the old one released in jdaviz 1.1. I believe installing via `pip install .` will use your local setup.cfg to resolve the right versioning, right?

**Comment by PatrickOgle** [comment]
I used pip install, but that is not my point.  My point is that the existing pip-install installs 0.18.1.  Maybe the dependency should be >0.18.1,   not >= 0.18.1.

**Comment by pllim** [comment]
0.18.1 is the current latest release -- https://github.com/scikit-image/scikit-image/releases

Theoretically, it should respect the deps pin in `setup.cfg`, yes. But check the log carefully. Sometimes that pin is overwritten by a different pin if there are multiple pins in the stack.

**Review by duytnguyendtn — APPROVED** [review]
I'm submitting my approval in that jdaviz works for me with this change, but I would note @PatrickOgle's comment here that the bug seems to be persistent with this change

**Comment by PatrickOgle** [comment]
Apparently there is a problem with  0.18.1  with MAC OSX <10.15. @javerbukh provided this reference:
https://stackoverflow.com/questions/65431999/it-seems-that-scikit-learn-has-not-been-built-correctly

So we are left with the "pip uninstall scikit_image; conda install scikit_image solution as the quickest.  
Another suggestion from @rosteen (which takes a long time to install):
pip install -U --no-binary scikit-image scikit-image

**Comment by duytnguyendtn** [comment]
Now that we've found the root cause, since it doesn't seem to be a minimum version issue, is this PR needed anymore? (See #491 for more context)

**Comment by javerbukh** [comment]
Since this does not actually solve anything, we've decided to close this PR.

**Pull request closed without merging**
