### PR TITLE
Removed unused icons in tool bar

### PR DESCRIPTION
**Pull request by ibusko**
Unused icons were removed. Note that, instead of changing the vue specs file, we had changed the config file of each viztool, the "Import" button would had disappeared as well.

Should we keep the removed code as commented-out, or remove it entirely? Is there a chance that it could come back in the future?

image

### CODE REVIEW

**Review by rosteen — COMMENTED** [review]
@ibusko can you rebase this to master and do a push? I'm pretty sure that will fix the failing test.

The only thing I don't like about this is that the subset selection button is right next to the Import button - I think it would look nicer with a little space in between. Not sure the best way to add that off the top of my head.

I'm inclined to say it would be ok to remove the code rather than commenting it out - we can always look back in the history to retrieve it on the off chance we would want it again, right?

**Comment by ibusko** [comment]
@rosteen I also feel the navbar a bit cramped with no space whatsoever in between the Import button and the region selector. Maybe there is a "blank space" icon of sorts, somwehere? I am looking at icon libraries; do you know which one we use?

**Comment by rosteen** [comment]
I know there's a `v-spacer` vuetify element that might be what we want, but I couldn't figure out exactly where to put it to do what we want here in the 2 minutes I messed with it.

**Comment by ibusko** [comment]
Found it:

image

**Comment by rosteen** [comment]
Nice, I think that looks much better!

**Review by rosteen — APPROVED** [review]

**Review by javerbukh — APPROVED** [review]
Looks good!

**Pull request merged**
