### PR TITLE
ENH: Adding Plot Options toggle for mouseover info/marker

### PR DESCRIPTION
**Pull request by bmorris3**
### Description

Originally implemented as a PR on top of https://github.com/spacetelescope/jdaviz/pull/1894 (https://github.com/pllim/jdaviz/pull/9/), the commit in this PR (to main) allows users to see or hide the mouseover marker and info, by adding a toggle in the "Settings" dropdown in the Plot Options plugin:

https://user-images.githubusercontent.com/3497584/213061391-b3a17923-39d0-463b-9827-156c4f51dcee.mov

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

[🐱](https://jira.stsci.edu/browse/JDAT-3038)

### CODE REVIEW

**Comment by pllim** [comment]
Where does this PR stand now? Were we waiting for UI/UX advise? Were we waiting for PO feedback? Is this still relevant if we have to move the mouseover info somewhere else?

**Comment by bmorris3** [comment]
> Where does this PR stand now? 

I'm not sure, @pllim. @camipacifici?

**Comment by kecnry** [comment]
> Where does this PR stand now?

I had left a number of comments on the [original PR](https://github.com/pllim/jdaviz/pull/9) that I think still stand.

**Comment by kecnry** [comment]
See #1953 for a proposed migration of this logic into the markers plugin integration within the mouseover display.

**Pull request closed without merging**
