### PR TITLE
user API for links control

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request extends on #1401 and provides user-API access to the links control plugin.

[Plugin User API docs](https://jdaviz--1640.org.readthedocs.build/en/1640/api/jdaviz.configs.imviz.plugins.links_control.links_control.LinksControl.html#jdaviz.configs.imviz.plugins.links_control.links_control.LinksControl)

**TODO**:
- [x] add PR to changelog if before next release, otherwise add new entry (waiting until PR is accepted otherwise to avoid constant merge conflicts)

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
I am also not sure about this one. This plugin exposes an existing API. This feels... recursive.

https://jdaviz.readthedocs.io/en/latest/api/jdaviz.configs.imviz.helper.link_image_data.html

**Review by javerbukh — APPROVED** [review]
I'll leave the last word up to @pllim but this looks good to me!

**Comment by kecnry** [comment]
@pllim - so what do you propose?  I think our options would be:
* having this be one of the only plugins without an exposed API
* make the helper-method private
* if the API lives in the helper, then maybe the functionality for the UI should not be in the plugin tray and should be moved to the app-level toolbar
* live with it in both places, but try to isolate plugin code to plugins going forward

**Comment by pllim** [comment]
> having this be one of the only plugins without an exposed API

It is a possibility and easy to do. People who use API wouldn't use this plugin anyway. This plugin is only for those who does not want to use API or is stuck in the "standalone" app.

> make the helper-method private

No. It is already advertised as public.

> maybe the functionality for the UI should not be in the plugin tray and should be moved to the app-level toolbar

It is also possible but more work. We could have a pixel/WCS toggle but with approx always on. To also add in approx would introduce 3 options, not sure how toggle works with that. 🤷 

> try to isolate plugin code to plugins going forward

Isn't this the first option?

**Comment by kecnry** [comment]
> People who use API wouldn't use this plugin anyway. This plugin is only for those who does not want to use API or is stuck in the "standalone" app.

I don't entirely agree with this.  I suspect many people will use the API first and then try to write reproducible code that will walk through those same steps.  The plugin APIs provide an easy transition to them, as the APIs mimic the exact same options available in the plugin.  So if someone uses the plugin to change linking, then the plugin API for that is probably easier to find/learn than the helper method with different syntax.  If someone _starts_ using Jdaviz with the API, then they may find the helper method easier to access.

>> try to isolate plugin code to plugins going forward

> Isn't this the first option?

What I mean is that if we were creating this plugin now, I would advocate for not having the helper-method at all, or at least not public.  But I agree, in this case it already does exist, so we should avoid removing it.  I think that alone is an excuse for having the two ways to do the same thing... and we just need to keep this in mind as we develop new functionality to try to avoid it in the future.  But ultimately some things will move from plugins to core functionality, or vice versa, and we can't always predict that.

**Comment by pllim** [comment]
Personally, I would find it annoying if the existing helper API is removed. What I can now do in one line, I would need multiple lines to accomplish using the plugin API.

**Comment by kecnry** [comment]
> What I can now do in one line, I would need multiple lines to accomplish using the plugin API.

I think this is a good thing to keep in mind going forward as well.  If we were designing this from scratch now (which we're not), we could have a similar helper-method at the plugin level to pass multiple options and update the linking.  There are similar calls to that implemented in the spectral extraction plugin now, and might be a good pattern to try to follow elsewhere.

But we're not designing this from scratch and already have the method in the helper and the UI in the plugin... my opinion is that duplicated functionality is less confusing than having the exposed API lacking for the plugin just because it exists elsewhere as well 🤷  but I'm curious to hear what others think as well.

**Comment by rosteen** [comment]
I think my take is that it is ok to both consistently expose APIs for all of the plugins, _and_ have convenient helper functions for commonly used things that are perhaps shorter or more concise to use than the plugin API itself.

**Review by pllim — APPROVED** [review]
Okay, let's get this in then but please add a change log first. Thanks!

**Comment by kecnry** [comment]
ah, lost my chance to squash & merge 😢 😂

**Comment by pllim** [comment]
Ooops, sorry. It is only 3 commits though and they look atomic enough. 😬

**Pull request merged**
