### PR TITLE
BUG: Fix DataTools logic

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to fix `DataTools` logic so it does not crash when `file_path` is `None`.

I did not add test because I don't know how exactly it was triggered by the user.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)? [🐱](https://jira.stsci.edu/browse/JDAT-3229)

### CODE REVIEW

**Comment by pllim** [comment]
@camipacifici , I cannot reproduce your error on my machine. Might be Apple evilness.

**Comment by camipacifici** [comment]
Hum...now the import button is grayed out...

Screen Shot 2023-03-24 at 4 24 27 PM

**Comment by pllim** [comment]
Okay then maybe this patch is wrong. What is the actual value of `self._file_upload.file_path` when you encounter that problem (without this patch)?

**Comment by camipacifici** [comment]
So, I have clicked import file and navigated to the first file of interest. When I click on the file, `self._file_upload.file_path` is the path to the actual file.
I click on import file a second time and click on '../', the trace back is triggered and `self._file_upload.file_path` is `None`.

**Review by camipacifici — APPROVED** [review]
Works now! Thank you

**Comment by pllim** [comment]
I still cannot reproduce this problem, so I didn't add a test. What *appears* to be happening on Cami's machine is that somehow the `file_path` (which is a traitlet that passes through a `os.stat` check) somehow temporarily gets a `None` state. This PR basically tells the plugin to "skip over" that state when it happens, and proceeds to process the valid state that it ends up in. I hope this makes sense lol.

**Review by kecnry — APPROVED** [review]
code change looks reasonable to me, thanks!

**Pull request merged**
