### PR TITLE
export plugin: auto filename

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request uses the existing `AutoTextField` component for the filename entry in the export plugin.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by rosteen — COMMENTED** [review]
Functionality works, but I would prefer to replace spaces with underscores rather than hyphens. Right now you can get somethings like "Plot-Options-stretch_hist.png", and I don't like them being mixed (and have a general preference for underscores in filenames in general). I'm open to being outvoted on that though.

**Comment by kecnry** [comment]
I actually agree.  I originally did hyphens because that is what is used in viewer names ("spectrum-viewer") and so will find there way in the filenames for viewer exporting unless we replace those... but that case won't be mixed as you noted for plugin plots.  For now, I'll just replaces all spaces and colons with underscores but leave _existing_ hyphens alone.

**Review by rosteen — APPROVED** [review]
Sounds like a good compromise, thanks! LGTM now.

**Review by haticekaratay — APPROVED** [review]
Tested with Cubeviz and Specviz. Looks good to me!

**Pull request merged**
