### PR TITLE
basic plugin search

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements a search bar at the top of the plugin tray with simple exact-match search on plugin titles to filter plugins in the expansion panels.
* currently synced across multiple instances of the app - may want to have it per-instance in the future (but using 'data' on the app-level seems not to work)
* currently exact match on the plugin label only.  Could extend this to search full text or tags, etc.  Could also create a "command palette" and/or keyboard shortcut to immediately focus the search field (as future work).
* NOTE: cannot filter the input list to `v-expansion-panels` as that disrupts the `tray_items_open` list of indices, so instead we hide the child `v-expansion-panel-header`/`v-expansion-panels-content` items.

https://user-images.githubusercontent.com/877591/163860380-9f1e0564-e6f1-4699-88e3-6312e9aca13c.mov

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
Magical! Except the user text in search bar does not respond to dark theme.

Screenshot 2022-04-20 135629

**Comment by kecnry** [comment]
> Except the search bar does not respond to dark theme.

Wasn't actually the search bar, but the entire plugin sidebar.  I now fixed that to be responsive to the themes
<div>
Screen Shot 2022-04-21 at 1 15 35 PM
Screen Shot 2022-04-21 at 1 15 17 PM
</div>

**Review by pllim — APPROVED** [review]
Awesome. Thanks!

**Review by javerbukh — APPROVED** [review]
Works great!

**Pull request merged**
