### PR TITLE
spectrum-2d-viewer: set custom toolbar tools

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request sets the toolbar tools on the spectrum-2d-viewer (in both mosviz and specviz2d) to match those in spectrum-viewer (1d and 2d pan/zoom, but only xrange region selection).  This was a blocker for #776 and confirms that that is still a remaining issue even with xrange subsets.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by javerbukh — APPROVED** [review]

**Comment by rosteen** [comment]
We should probably wait to merge this until the `xrange` tool in the 2D viewer doesn't break everything. Ok, not everything, but after using that tool in the 2D viewer it no longer works in the 1D viewer either.

**Comment by kecnry** [comment]
@rosteen - is that a separate bug from #776?

**Comment by kecnry** [comment]
After investigating further, it seems that using xrange in the 2d spectrum viewer is leaving the selection tool on "no selection (create new)" whereas the behavior after creating a subset in the 1d spectrum viewer is to immediately select the new subset.  Once the xrange in the 2d spectrum viewer is used (actually _used_ to create a subset, not just enabling the tool), this behavior breaks in the 1d spectrum viewer as well.

I do think this is separate from #776, but looks very similar to #810 (as moving the selection is creating new subsets since it is not changing from "no selection").

**Comment by rosteen** [comment]
Agreed that it looks very similar to #810 which, side note, should have been closed since the bug was fixed on main. I think it was resolved by a glue-jupyter fix.

**Comment by pllim** [comment]
So... is this okay to merge?

**Comment by kecnry** [comment]
Yep, I think we decided that this doesn't introduce any new bugs and the syncing issues are out of scope as they also exist in main.  So as long as @rosteen doesn't have any objections, I'll consider that as a second approval and merge before end of day.

**Comment by rosteen** [comment]
Go for it.

**Review by rosteen — APPROVED** [review]

**Pull request merged**
