### PR TITLE
feat: support Voila dark theme (--theme=dark)

### LINKED ISSUE #415: Dark mode?
```python
VoilaConfiguration.theme = 'dark'
```

### PR DESCRIPTION
**Pull request by mariobuikhuizen**
Fixes the dark mode not being activated in #669.

Fix #415

### CODE REVIEW

**Comment by pllim** [comment]
Hmm, I don't see any changes to `cli.py`. Is the `--theme` command added magically?

**Comment by mariobuikhuizen** [comment]
Oh, I understood #415 the wrong way.

**Comment by pllim** [comment]
Update: I moved Erik's commit from #669 here. I also modified the CLI option to be `--theme` so it is consistent with upstream naming. I can see the dark theme in `voila` now though it is not that obvious for Imviz. Alas, I am unable to get the Viz to show in Jupyter Lab (glue-viz/glue-jupyter#239), so maybe you can check that part.

**Comment by mariobuikhuizen** [comment]
#665 (dark theme in lab) is fixed by upgrading to ipyvuetify 1.7.0, not by this PR. Jupyter Lab and Voila use different mechanisms to select the dark theme.

**Comment by pllim** [comment]
@mariobuikhuizen , are you saying that this PR is now invalid?

**Comment by mariobuikhuizen** [comment]
No no, the PR is good for #669 and #415, but is not needed for #665

**Comment by pllim** [comment]
@mariobuikhuizen , are you okay with the two commits I added to this PR?

**Comment by mariobuikhuizen** [comment]
Yes @pllim, looks good to me 👍

**Review by pllim — APPROVED** [review]

**Review by ibusko — APPROVED** [review]
Dark theme works.

**Pull request merged**
