### PR TITLE
BUG: expose attr+meth from the catalog plugin to the user API

### PR DESCRIPTION
**Pull request by bmorris3**
The current user API for the catalog search plugin doesn't expose any plugin-specific attrs/methods. It'd be handy to select a catalog and execute the search from the API, so I've put in the missing method in this PR.

### Change log entry

- [X] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — CHANGES_REQUESTED** [review]
It is a little too early for this. API might change when we add more features to this plugin. e.g., https://github.com/spacetelescope/jdaviz/issues/1547

**Comment by bmorris3** [comment]
Closing as planned planned but deferred.

**Comment by pllim** [comment]
Deferred to where?

**Comment by kecnry** [comment]
We have tickets for each of the remaining plugins that don't have user-exposed APIs yet, including catalogs [:cat:](https://jira.stsci.edu/browse/JDAT-2762)

**Pull request closed without merging**
