### PR TITLE
fix: add Voila >= 0.2.8 support

### PR DESCRIPTION
**Pull request by mariobuikhuizen**

### CODE REVIEW

**Review by havok2063 — APPROVED** [review]
Presumably this would also address https://github.com/spacetelescope/jdaviz/issues/552?

**Review by ibusko — APPROVED** [review]
I verified it works with 0.2.8. It also seems to fix #552

**Comment by mariobuikhuizen** [comment]
I don't know if it fixes #552, since the reporter of the issue said it was not solved by downgrading Voila to 0.2.7.

**Comment by havok2063** [comment]
@mariobuikhuizen sometimes I've found that a `voila` version alone isn't enough to solve an issue.  That we have have to pin specific versions of dependencies, e.g. `traitlets` or `jupyter-server`.   Could that be an issue in the user's case?  What dependency versions should we make sure users have for voila `0.2.7` or above?

**Pull request merged**
