### PR TITLE
Rename monochromatic color mode and add descriptions

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request renames the "Monochromatic" color mode option to "Color" and adds descriptions within the dropdown.  Setting `color_mode = 'monochromatic'` from the plot options plugin API is still supported with a deprecation message.

https://github.com/spacetelescope/jdaviz/assets/877591/0210160e-fc7b-42b8-aca1-da5f8b1eb57e

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by cshanahan1 — COMMENTED** [review]
There are several notebooks ([imviz_colorbar_mpl.ipynb](https://github.com/kecnry/jdaviz/blob/59aeab0b0d7bb835c70c4dc5f45a55e866772696/notebooks/concepts/imviz_colorbar_mpl.ipynb#L138), [cubeviz_ndarray_gif.ipynb](https://github.com/kecnry/jdaviz/blob/59aeab0b0d7bb835c70c4dc5f45a55e866772696/notebooks/concepts/cubeviz_ndarray_gif.ipynb#L273), [imviz_dithered_gwcs.ipynb](https://github.com/kecnry/jdaviz/blob/59aeab0b0d7bb835c70c4dc5f45a55e866772696/notebooks/concepts/imviz_dithered_gwcs.ipynb#L116)) that have references to 'monochromatic' that need to be updated.

**Review by cshanahan1 — COMMENTED** [review]
There are also a few references to "monochromatic" in [docs/imviz/displayimages.rst](https://github.com/kecnry/jdaviz/blob/59aeab0b0d7bb835c70c4dc5f45a55e866772696/docs/imviz/displayimages.rst#L315) that need to be updated.

**Comment by cshanahan1** [comment]
Otherwise looks good to me and ill approve once those are fixed!

**Comment by kecnry** [comment]
@cshanahan1  - good call!  Do you see anywhere else that I missed in the docs?

**Pull request merged**
