### PR TITLE
App toolbar buttons dodge mouseover info

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request hides the toolbar buttons (except for the sidebar hamburger button) during active mouseover to avoid conflict between the mouseover information and the buttons on narrow screens.  This also improves the styling and layout of the mouseover information to avoid displacement in the layer icon when entering/leaving mouseover.

https://github.com/spacetelescope/jdaviz/assets/877591/938e637a-2e0f-4266-8ba7-72afe620446d

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
So I remember how I got myself into the situation where I cannot access the "hamburger" now. On 16" laptop, I run the ImvizDitheredExample notebook on Lab, and then I pop out the view for display to the side so the display can only take up half the screen width. With your patch, this is what I see.

### During mouseover

Screenshot 2024-05-21 102910

### Not doing mouseover

Screenshot 2024-05-21 102947

Not sure how best to fix _this_ problem.

**Comment by pllim** [comment]
Do we need to hide the rest of the top bar (import data, new selection, new viewer)? Is that possible?

**Comment by kecnry** [comment]
I think we'll ultimately need a minimum supported width for the app - I'm not sure if that fits in the scope here or not?  My goal was to just improve the situation for narrow-_er_ (but not necessarily narrow-_est_) app layouts 🤔

**Review by pllim — APPROVED** [review]
If "narrowest" is out of scope, then this seems to work. Thanks!

**Pull request merged**
