### PR TITLE
CLI: Replace click with argparse

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to remove our dependency of `click`, as stated in https://github.com/spacetelescope/jdaviz/pull/1372#issuecomment-1150513370 . User should notice no difference, so I don't think this needs a change log. Also see https://docs.python.org/3/library/argparse.html

Please try out the different CLI options in case I missed something.

p.s. I think it might be slightly faster without click but you should double check in case I am hallucinating.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)? [🐱](https://jira.stsci.edu/browse/JDAT-2514)

### CODE REVIEW

**Comment by pllim** [comment]
Did a rebase to resolve conflict. FYI.

**Review by kecnry — COMMENTED** [review]
I'm getting the following error when passing verbosity/history_verbosity:

```
nbf.write(notebook_template.replace('DATA_FILENAME', filepath).replace('JDAVIZ_VERBOSITY', verbosity).replace('JDAVIZ_HISTORY_VERBOSITY', history_verbosity).strip())  # noqa: E501
TypeError: replace() argument 2 must be str, not list
```

Is it possible that `parser.add_argument('--verbosity', nargs=1, choices=_verbsoity_levels, ...)` (and similar for all `choices` arguments) results in a list with a single element instead of a string?

**Comment by pllim** [comment]
Hmm... I'll double check.

**Comment by pllim** [comment]
I was trying to be explicit with `nargs` but looks like it caused more trouble than its worth, so I stopped using it altogether. The CLI seems to parse fine with several different variations when I tried it locally. Please re-review. Thanks!

**Review by kecnry — APPROVED** [review]
Seems to work well now!

**Pull request merged**
