### PR TITLE
Imviz: Aperture photometry plugin with viewer-agnostic data/subset dropdown menus

### PR DESCRIPTION
**Pull request by pllim**
### Description

As pointed out by @orifox , Simple Aperture Photometry plugin should not depend on what is shown in the default viewer because it should work for data shown on any viewer. To avoid overcomplicating the logic, I am simply displaying data and subsets across the whole app, not depending on the viewer anymore. So now the plugin should even work if no data is displayed as long as it is loaded, but why would anyone do that... who knows?

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by javerbukh — APPROVED** [review]
Works as expected but I also do not know why someone would want to see aperture photometry data for data that is not in the viewer 🤷‍♂️

**Comment by pllim** [comment]
The original problem was @orifox had two viewers with Data 1 in Viewer 1 and Data 2 in Viewer 2, and he wanted photometry on Data 2 but because of the logic, Data 2 is not an option because it is not selected in Viewer 1. Given the existing complains about performance, grabbing everything from the app is easier to implement than trying to listen to even more events or pooling all viewers, which is kinda unnecessary when you know the Data and Subset are both global anyway.

If you really want me to poll the viewers, I can... If not, let's get this in, eh?

**Review by ibusko — APPROVED** [review]
Works fine for me.

**Comment by pllim** [comment]
Thanks for the reviews!

**Pull request merged**
