### PR TITLE
Allow user to load data through show()

### PR DESCRIPTION
**Pull request by duytnguyendtn**
### Description

Inspired by @camipacifici's comment in https://github.com/spacetelescope/jdaviz/pull/965#issuecomment-966361293, this PR allows users to chain additional arguments in `viz.show()`, to which the viz tool will pass onwards to `viz.load_data()`. This effectively allows the user to, in a single command, display the tool and load the data immediately. Effectively, the following commands are now possible to do both simultaneously:

`viz.show("/path/to/data.fits")`
`viz.show("/path/to/data.fits", loc="sidecar")`
`viz.show(my_spectrum_1d)`
`viz.show(my_spectrum_1d", data_label="My Awesome Spectra", loc="inline")`

I indicated in https://github.com/spacetelescope/jdaviz/pull/965#issuecomment-967275228 that this would probably need some discussion to refine it, so here we are! Very curious to hear everyone's thoughts! :)

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
✔️ Changing `load_spectrum` to `load_data`. Might even want to consider deprecating `load_spectrum` with a warning but okay with alias too if it is too widely used.
❌ Overloading `show` to also `load_data`. This complicates the API and also is against the philosophy of "there should be one and only one obvious way to do something".

**Review by kecnry — COMMENTED** [review]
I tend to agree with @pllim - I think if I were a user, I'd almost expect passing data to `show` to be temporary (not be added to the app object and then persistent for future `show` calls, for example).  I think supporting passing data directly to the helper's init might feel more intuitive:

```
specviz = Specviz(data, data_label)
specviz.show()
```

**Comment by pllim** [comment]
> Specviz(data, data_label)

Then how do you load multiple data? How do you load stuff after the init? Any implementation that would still require us to keep `load_data` is redundant.

**Comment by kecnry** [comment]
> Then how do you load multiple data? How do you load stuff after the init? Any implementation that would still require us to keep load_data is redundant.

Similar to this PR, this would just be a shorthand for the case of loading a single data set, and the user would still have access to `load_data`.  Yes, it would be redundant, so if we want to avoid any redundancy at all, then we should just leave it as is since we'll always need to have `load_data` even if we were to support complex syntax to handle multiple data in init or show.

**Comment by camipacifici** [comment]
Thank you very much for addressing my comment! Looks nice, but all the objections make sense to me.
In some sense, it would be convenient for cubeviz, where we do not encourage the users to load multiple cubes in the same instance, and mosviz, where the loading happens all at once, but I see how it can be redundant and even confusing for specviz and imviz.
I have no strong reasons to keep pursuing this idea.

**Comment by pllim** [comment]
> I have no strong reasons to keep pursuing this idea.

Should we close this *without* merge?

**Comment by pllim** [comment]
I think the consensus is we abandon this. Also it has conflicts now, so closing. Thanks anyway!

**Pull request closed without merging**
