### PR TITLE
Make Imviz panning more seamless

### LINKED ISSUE #564: Imviz pan/zoom needs improvements (lag in pan)
Follow up of #513 . Can be improved in the following ways:

- [x] When I am in pan/zoom mode (i.e., push that arrows button), once I left-click on display to enable it, clicking on display again does not disable it. Moving the mouse outside of display also does not disable it. As a result, as I mouse over back to the arrows button to get out of pan/zoom, the image moves with me, panning it to a place that is undesirable. This renders pan/zoom mode unusable. (Fixed by updating `bqplot`.)
- [x] There is no "zoom to fit" or "pan back to default position" options. See glue-viz/glue-jupyter#218 -- #575 
- [x] In fact, I can't figure out how to zoom. The pan/zoom seems to only pan. Scroll wheel does not zoom as advertised (works for standalone viola app but not in notebook). -- Is this caused by bqplot/bqplot#1304 ? Yes, check again when bqplot/bqplot#1347 is released (bqplot 0.12.27).
- [ ] When it does pan, there is a lag in loading the parts of image that come into view. [🐱](https://jira.stsci.edu/browse/JDAT-1646) [🐱](https://jira.stsci.edu/browse/JDAT-1642)
  - #667
  - glue-viz/glue-jupyter#246
  - [ ] https://github.com/spacetelescope/jdaviz/issues/564#issuecomment-891949262

### PR DESCRIPTION
**Pull request by astrofrog**
### Description

This pull request uses the option added in https://github.com/glue-viz/glue-jupyter/pull/246 to expand the image fixed resolution buffer beyond the edge of the axes, making panning more seamless:

Peek 2021-09-14 16-00

This is IMHO an improvement over the default behavior right now but it is not perfect - if one pans too fast one might still reach the 'edge' of the buffer and have to wait for it to refresh. We can make the padding larger but then it will take longer to compute, so we need to find the right balance.

There is another - separate - improvement I would like to make which is to only compute the buffer when the mouse button is released during panning, instead of every 0.5 seconds during panning, but this will be done in a separate PR and may not happen before the MVP deadline, so I wanted to at least get this quick fix in.

The glue-jupyter v0.9 release is in progress so this currently requires glue-jupyter dev, but in <1h it should work fine (and the CI can be restarted once glue-jupyter v0.9 is visible [on PyPI](https://pypi.org/project/glue-jupyter/))

Fixes #564

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
So, is this still going to happen?

https://github.com/spacetelescope/jdaviz/issues/564#issuecomment-891949262

**Comment by pllim** [comment]
Going to restart the jobs so they pick up new glue-jupyter release.

**Comment by astrofrog** [comment]
> So, is this still going to happen?

As noted in the description above - not in this PR. I don't think this is specifically MVP critical if what is in this PR is good enough.

**Comment by astrofrog** [comment]
glue-jupyter v0.9 is out for the record, so this should work properly now.

**Comment by astrofrog** [comment]
glue-jupyter v0.9 is out for the record, so this should work properly now.

**Comment by pllim** [comment]
Did you drop Python 3.7 or something? I am going to try restart the jobs again.

**Comment by pllim** [comment]
> As noted in the description above - not in this PR. I don't think this is specifically MVP critical if what is in this PR is good enough.

I am just not sure if I should open a follow-up issue for it for just forget about it.

**Comment by astrofrog** [comment]
I won't forget about it but feel free to open an issue at glue-jupyter 😀

**Comment by pllim** [comment]
Care to rebase to resolve conflict? 😅

**Comment by pllim** [comment]
I rebased locally and am using `glue-jupyter` 0.9, but I cannot say I can see much difference compared to what is already in `main`. I am interested to see if @rosteen , @javerbukh , or @ojustino feel otherwise.

**Comment by pllim** [comment]
I guess I like to pan too much around 47-Tuc. Maybe someone with a more realistic science use case will be happy enough with this... 🤷

**Comment by astrofrog** [comment]
Just for ease of comparison:

**Before**

Peek 2021-09-14 22-32


**After**

Peek 2021-09-14 16-00

**Review by pllim — APPROVED** [review]
I guess it doesn't hurt... 😸

**Review by ojustino — APPROVED** [review]
Side by side, I do notice that there's more area over which you can pan before the lag appears. People who pan aggressively won't notice much, but I think this is a good contribution for those who don't.

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
