### PR TITLE
upgrade upload-artifact to v4

### PR DESCRIPTION
**Pull request by Migelo**
### Description

This pull request upgrades the upload-artifact action to v4 following the closing of https://github.com/actions/upload-artifact/issues/485 by release [4.3.5](https://github.com/actions/upload-artifact/releases/tag/v4.3.5) which allows the v4 action to handle a large amount of files in the artifact zip file.

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
The decision to use v3 was intentional, see https://github.com/spacetelescope/jdaviz/pull/2855

But perhaps not needed anymore? 🤷‍♀️

**Comment by pllim** [comment]
Hard to tell whether this fix works or not given a seemingly unrelated error: `Error: Error: Timed out waiting for: tcp:8866`

I will defer to @rosteen

**Comment by Migelo** [comment]
> The decision to use v3 was intentional, see #2855

You are right! The underlying issue of "too many open files" described in the pull request you quote was addressed in the issue https://github.com/actions/upload-artifact/issues/485 which just recently got fixed in the following pull request https://github.com/actions/toolkit/pull/1771 2 weeks ago.

**Review by pllim — APPROVED** [review]
Only one way to find out. Thanks!

**Review by rosteen — APPROVED** [review]
Since the fix was released, seems like we can go back to v4. Thanks!

**Pull request merged**
