### PR TITLE
UI/UX tweaks for layer tabs

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements tweaks after discussions with @Jenneh to improve the UI/UX experience of the layer tabs introduced in #2566.  This PR:

* adds support for styling the tabs for colormaps (instead of just showing as gray), in a way that will also allow us to expose the representation in the colormap dropdown in the future
* allows showing color and colormap side-by-side and merging duplicate entries (3 viewers with 1 colormap and 1 color will now show half and half, instead of 1/3 and 2/3)
* updates the tooltip text on the tabs
* small padding tweaks, and shrinking size of tabs to fit more without needing to scroll
* changes the tab "outline" color from orange to blue
* separates the multiselect button into layer and viewer with a deprecation warning (deprecated method does not work on properties or setters, so had to use a logger warning)
* prevents deselecting all tabs
* smarter handling of visibility of stretch histogram, now allowing interacting with the stretch histogram when multiple viewers but a single layer are selected, and no longer clearing the marks which resulted in vmin/vmax marks disappearing.

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by javerbukh** [comment]
Created a subset in viewer 0, then created two new viewers, added 3 datasets to them, and changed the color mode to monochromatic. I believe after one of the last two steps I triggered the following traceback:
```
File ~\Documents\STScI\jdaviz\jdaviz\core\template_mixin.py:1370, in LayerSelect._on_viewer_selected_changed(self, msg)
   1368 for layer in new_viewer.state.layers:
   1369     layer.add_callback('color', self._update_layer_items)
-> 1370     layer.add_callback('cmap', self._update_layer_items)
   1371     if hasattr(layer, 'bitmap_visible'):
   1372         layer.add_callback('bitmap_visible', self._update_layer_items)

File ~\anaconda3\envs\jdaviz-dev-3.8\lib\site-packages\echo\core.py:288, in HasCallbackProperties.add_callback(self, name, callback, echo_old, priority)
    286     prop.add_callback(self, callback, echo_old=echo_old, priority=priority)
    287 else:
--> 288     raise TypeError("attribute '{0}' is not a callback property".format(name))

TypeError: attribute 'cmap' is not a callback property
```

**Review by javerbukh — APPROVED** [review]
Just need to figure out how to replace the scrollbar (agreed that that can be a follow up effort), otherwise this looks great!

**Comment by rosteen** [comment]
> > leads to the histogram being collapsed to a single bin
> 
> Do you have glue 1.16+ as pinned (see #2529)?

I did not, I'll retest after upgrading...

**Comment by rosteen** [comment]
Alright, that fixed that issue. One more small thing, which may be a pre-existing bug that doesn't need to hold up this PR: clicking the "locked" overlay to sync mismatched `visible` states doesn't update the visibility toggle in the viewers like I would expect if it's syncing to non-visible with `imviz-1` selected first (syncing to make both visible when `imviz-0` was selected first worked):



https://github.com/spacetelescope/jdaviz/assets/39831871/13d95692-b6e5-4f37-8252-342672552c57

**Comment by kecnry** [comment]
Yes, as long as its isolated to the visibility toggle, that is a known bug that we have scheduled to address soon.

**Review by rosteen — APPROVED** [review]
Great, it's difficult to keep up with everything sometimes. In that case, approved.

**Pull request merged**
