### PR TITLE
fix subset layer default behavior

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request fixes the case where removing and then re-adding a data layer in a viewer results in "as steps" being enabled by default.  Plot options are lost anyways when the layer is deleted, so we need to re-apply any jdaviz-implemented layer defaults (as-steps, line-width, etc) when a data layer is removed and then re-added to a viewer.

This also fixes the case of "as steps" defaults only being applied to the first subset layer when the same subset is being drawn on multiple data layers simultaneously.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by javerbukh** [comment]
I still see subsets with step plots if I do the following (shown in the video below):

1. Create Subset in spectrum viewer
2. Add gaussian smoothed spectrum
3. See the gaussian spectra's subset as a step plot

https://user-images.githubusercontent.com/7179333/189366849-910857e2-c06e-484b-969b-f39c72dc7d06.mov

**Comment by kecnry** [comment]
@javerbukh - I cannot seem to reproduce


https://user-images.githubusercontent.com/877591/189415405-a7c92e2a-a854-4f8c-9df4-4335b06bec81.mov

**Review by javerbukh — APPROVED** [review]
Looks like I am/was having conda issues. Seems to be resolved now, you are correct I no longer see that behavior. Nice work!

**Review by pllim — APPROVED** [review]
I am not familiar with the workflow but I think it works as you described in the PR. 😸

**Pull request merged**
