### PR TITLE
MNT: Add issue templates

### PR DESCRIPTION
**Pull request by pllim**
Add issue templates for bug reports and feature requests for each viz. There is a bit of duplication but it is necessary to apply different labels.

### CODE REVIEW

**Review by ibusko — COMMENTED** [review]
Maybe the bug report templates should have an explicit reminder to reference data files, whenever the bug seems to be data-driven. The "Additional context" section perhaps should mention something like "Additional context (e.g. data files)".

**Comment by pllim** [comment]
@ibusko , can you please provide me with the changes you have in mind as code suggestion in one of the bug template? I can then propagate it into the other ones. Thanks!

**Comment by ibusko** [comment]
@pllim I added a sort of reminder to line 70 in the cubeviz bug report template. It's only a suggestion, because I don't know if these things can be modified at will or not. Perhaps there is software upstream that expects specific wording and such?

**Comment by pllim** [comment]
> expects specific wording and such?

Naw... Only the stuff between the `---` at the top means something. The rest is for humans.

**Comment by pllim** [comment]
Pushed a commit. What about now?

**Review by ibusko — APPROVED** [review]
LGTM. Great addition to our setup!

**Comment by pllim** [comment]
For completeness, you can see the `astropy` issue templates in action over at https://github.com/astropy/astropy/issues/new/choose . Only you'll have 8 to choose from instead of 2.

**Review by rosteen — APPROVED** [review]
Looks good, thanks!

**Comment by pllim** [comment]
Hopefully not overkill...

Screenshot 2021-04-26 101715

**Comment by pllim** [comment]
Bug template in action:  #569

**Pull request merged**
