### PR TITLE
Line List Plugin: unit choices for custom lines

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull implements a dropdown with choices for the units of custom lines in the line list plugin, making use of shared code with the unit conversion plugin (moving some of the code from that class into `jdaviz.core`.

* defaults to the units in the viewer
* excludes units that no one would ever want to use for the spectral axis (light years, AU, etc)

Screen Shot 2022-02-10 at 2 01 12 PM

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by javerbukh — APPROVED** [review]
Looks good! One question though, should the Line Lists plugin update the values of the lines when the units change? I don't think it did before so that might just be outside the scope of this PR or just not the functionality we want.

**Comment by kecnry** [comment]
> should the Line Lists plugin update the values of the lines when the units change? I don't think it did before so that might just be outside the scope of this PR or just not the functionality we want.

Agreed its out of scope here but something we should reconsider.  The current (unchanged) behavior is to always show the lines in the user-provided units and convert them internally for plotting.  Maybe an option either in the line list or unit conversion plugin would be useful as I can see the benefits of both leaving them fixed and converting them?

**Comment by rosteen** [comment]
Looks pretty good, I only found one thing that I suspect is on main as well. If you have a plot in Angstrom (or maybe it's because I had already added a line in Angstrom), adding a line in Hertz throws an astropy error that Hertz isn't convertible to Angstrom. I have the feeling that there's somewhere in the code not using spectral equivalencies. I would be ok deferring this to a separate bugfix PR unless you want to track it down and fix it now, here's the trace:

```
---------------------------------------------------------------------------
UnitConversionError                       Traceback (most recent call last)
~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/quantity.py in to_value(self, unit, equivalencies)
    892             try:
--> 893                 scale = self.unit._to(unit)
    894             except Exception:

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/core.py in _to(self, other)
   1097 
-> 1098         raise UnitConversionError(
   1099             f"'{self!r}' is not a scaled version of '{other!r}'")

UnitConversionError: 'Unit("Angstrom")' is not a scaled version of 'Unit("Hz")'

During handling of the above exception, another exception occurred:

UnitConversionError                       Traceback (most recent call last)
~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/ipyvue/VueTemplateWidget.py in _handle_event(self, _, content, buffers)
     58                 getattr(self, "vue_" + event)(data, buffers)
     59             else:
---> 60                 getattr(self, "vue_" + event)(data)
     61 
     62 

~/projects/jdaviz/jdaviz/configs/default/plugins/line_lists/line_lists.py in vue_add_custom_line(self, event)
    498         temp_table["colors"] = [temp_dict["colors"]]
    499         temp_table["redshift"] = [temp_dict["redshift"]]
--> 500         temp_table = self._viewer.load_line_list(temp_table, return_table=True)
    501 
    502         # Add line to Custom lines in local list

~/projects/jdaviz/jdaviz/configs/specviz/plugins/viewers.py in load_line_list(self, line_table, replace, return_table, show)
    176             self.spectral_lines = line_table
    177         else:
--> 178             self.spectral_lines = table.vstack([self.spectral_lines, line_table])
    179             self.spectral_lines = table.unique(self.spectral_lines, keys='name_rest')
    180 

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/table/operations.py in vstack(tables, join_type, metadata_conflicts)
    649     col_name_map = OrderedDict()
    650 
--> 651     out = _vstack(tables, join_type, col_name_map, metadata_conflicts)
    652 
    653     # Merge table metadata

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/table/operations.py in _vstack(arrays, join_type, col_name_map, metadata_conflicts)
   1405             idx1 = idx0 + len(array)
   1406             if name in array.colnames:
-> 1407                 col[idx0:idx1] = array[name]
   1408             else:
   1409                 # If col is a Column but not MaskedColumn then upgrade at this point

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/quantity.py in __setitem__(self, i, value)
   1238         if not self.isscalar and 'info' in self.__dict__:
   1239             self.info.adjust_indices(i, value, len(self))
-> 1240         self.view(np.ndarray).__setitem__(i, self._to_own_unit(value))
   1241 
   1242     # __contains__ is OK

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/quantity.py in _to_own_unit(self, value, check_precision)
   1527     def _to_own_unit(self, value, check_precision=True):
   1528         try:
-> 1529             _value = value.to_value(self.unit)
   1530         except AttributeError:
   1531             # We're not a Quantity.

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/quantity.py in to_value(self, unit, equivalencies)
    894             except Exception:
    895                 # Short-cut failed; try default (maybe equivalencies help).
--> 896                 value = self._to_value(unit, equivalencies)
    897             else:
    898                 value = self.view(np.ndarray)

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/quantity.py in _to_value(self, unit, equivalencies)
    801         if not self.dtype.names or isinstance(self.unit, StructuredUnit):
    802             # Standard path, let unit to do work.
--> 803             return self.unit.to(unit, self.view(np.ndarray),
    804                                 equivalencies=equivalencies)
    805 

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/core.py in to(self, other, value, equivalencies)
   1133             return UNITY
   1134         else:
-> 1135             return self._get_converter(Unit(other),
   1136                                        equivalencies=equivalencies)(value)
   1137 

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/core.py in _get_converter(self, other, equivalencies)
   1064                             pass
   1065 
-> 1066             raise exc
   1067 
   1068     def _to(self, other):

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/core.py in _get_converter(self, other, equivalencies)
   1049         # if that doesn't work, maybe we can do it with equivalencies?
   1050         try:
-> 1051             return self._apply_equivalencies(
   1052                 self, other, self._normalize_equivalencies(equivalencies))
   1053         except UnitsError as exc:

~/opt/anaconda3/envs/viz_dev/lib/python3.9/site-packages/astropy/units/core.py in _apply_equivalencies(self, unit, other, equivalencies)
   1025         other_str = get_err_str(other)
   1026 
-> 1027         raise UnitConversionError(
   1028             f"{unit_str} and {other_str} are not convertible")
   1029 

UnitConversionError: 'Angstrom' (length) and 'Hz' (frequency) are not convertible
```

**Review by rosteen — APPROVED** [review]
I confirmed that the bug I noticed is present on main. Approving this, will re-review if you want to fix it here but otherwise we can follow up on it later.

**Comment by rosteen** [comment]
Good to know. I would hope people would define their lines in the unit of their data anyway, but you never know.

**Pull request merged**
