### PR TITLE
line analysis plugin: basic linear continuum support

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements support for handling a linear continuum during line analysis.

* option to provide width (as a fraction of the full-width of the selected line region) or a custom subset.  Either way, a line is fitted to these points and subtracted/divided before passing to specutils
* data dropdown now defaults to first data entry instead of blank
* added spinner while results are computing/updating instead of clearing and re-populating
* form validation logic to make sure not using the same subset as the line and to make sure a reasonable value of width is passed
* visual feedback of adopted region/continuum (only visible while plugin is opened)

NOTE: styling in recording slightly out of date, see https://github.com/spacetelescope/jdaviz/pull/1060#issuecomment-1030090719

https://user-images.githubusercontent.com/877591/152432673-915dcfce-ac7d-4994-8915-367760118c26.mov

**TODO:**
- [x] width in data-units relative to width of line region (0-1, defaulting at 1)
- [x] update computed statistics when referenced subset is updated
- [x] visual feedback of adopted region/continuum
- [x] support for unit conversion in visual feedback line
- [x] look into negative equivalent width
- [x] update line analysis docs
- [x] coverage

Postpone for future work:
* consistent API in specutils to avoid if-statements in jdaviz?
* support to pass continuum directly to specutils?
* subsets/regions break during unit conversion (so using this with a defined subset and then changing units also breaks) [:cat:](https://jira.stsci.edu/browse/JDAT-2123)

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by Jenneh** [comment]
A few thoughts:

- The area where the line is over the spectra, the turquoise does not contrast enough with the spectra line. I don’t think it will be easy to pick a single color that contrasts with both the background and the spectra line color that works for both the thick and thin part of the line.
- possible solution: add a 1px white line around the line.
- possible solution: use a mid-color turquoise and darken the spectra line

- I like the idea of automatically viewing and hiding the relevant lines based on what menus are open. Perhaps we can follow that pattern in other menus also. I think @orifox  had mentioned he found all the eye icons confusing in the plugins
- My only concern is that there may be a science reason to keep them visible even if the menu is closed. (I don’t know what that would be)

**Comment by kecnry** [comment]
Iterated back and forth with @Jenneh and we came up with a nice styling that uses the same blue as the import button (and now the inactive slice slider in #1013) along with a white shadow (which we can also easily re-use for other purposes).

Screen Shot 2022-02-04 at 10 07 38 AM
.

**Review by javerbukh — APPROVED** [review]
This works great! I noticed a bug with unit conversion but that appears to originate in `main`, so I documented it [here](https://github.com/spacetelescope/jdaviz/issues/1067). This definitely needs a science review in addition to the developer ones, but otherwise looks good!

**Review by pllim — COMMENTED** [review]
Since Jesse says this needs science review, I am going to reserve the second approval for PO.

**Comment by camipacifici** [comment]
It is really nice! I might have found a small bug (see screenshot). I selected the continuum region as Subset 2 and although it updated the line fit, it did not draw the blue line on the entire range.
Screen Shot 2022-02-08 at 10 32 34 AM

**Comment by camipacifici** [comment]
Tried a different line. Everything updated nicely, but the centroid value is off. I rechecked the line before and also there the centroid value was off. Am I missing something?
Screen Shot 2022-02-08 at 10 47 28 AM
I will double check all the returned numbers next.

**Comment by camipacifici** [comment]
Thank you!
Since the line is a fit to the continuum regions, it would be ideal to see it from the left edge of the left-side continuum to the right edge of the right-side continuum.

**Comment by kecnry** [comment]
@camipacifici 

> Since the line is a fit to the continuum regions, it would be ideal to see it from the left edge of the left-side continuum to the right edge of the right-side continuum.

Ok, I changed that and you should now see something like:

Screen Shot 2022-02-08 at 12 36 17 PM

**Comment by kecnry** [comment]
Marked as draft until we can pin a specutils release that includes the fix mentioned above and implement support for the visual indication of a continuum fitted to a region only to the left or right of the line region.

**Comment by kecnry** [comment]
Re-opening this with the newly released specutils 1.7 pinned (which should fix the centroid discrepancy noted by @camipacifici - thanks @rosteen).

**Review by javerbukh — APPROVED** [review]
Looks good to me!

**Comment by camipacifici** [comment]
Sorry! Just tested it in Mosviz and it does not work properly.
Here is a screenshot
Screen Shot 2022-02-24 at 11 16 31 AM

**Pull request merged**
