### PR TITLE
remove state-sync for data menu open

### LINKED ISSUE #2581: Data menu broken in Imviz extra viewer on Lab
I see this on main currently so it was not caused by whatever the rotation PR is doing. Only see it on Lab. Works fine on Notebook in the same env. Using WSL2 (Debian/Ubuntu) on Windows 10/11, with Chrome browser (but @kecnry could reproduce it in OSX). cc @mariobuikhuizen 

Workflow to reproduce:

1. Run Imviz example notebook and load both images.
2. Go to the cell that says `imviz.show()` but do not run it yet. Right click on it and select "Create New View for Cell Output".
3. Now run `imviz.show()`.
4. Use the "popped out" version of the Imviz viewer.
5. Make a new viewer. Load either image A or B. See that Data menu in `imviz-1` misbehaves.
6. See screenshots. The screenshots also have markers loaded but you don't need those to reproduce the bug.

Screenshot 2024-01-17 112025

imviz-0 is okay:

Screenshot 2023-11-28 145235

but imviz-1 is broken in Lab but not Notebook:

Screenshot 2023-11-28 145326

[🐱](https://jira.stsci.edu/browse/JDAT-4021)

### PR DESCRIPTION
**Pull request by kecnry**
### Description

As an alternate option to #2669, this decouples each data-menu from other instances in the same viewer (so only a single menu will be open if multiple instance of the app are being shown).

Fixes #2581

Close #2669

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
Is this a possible side effect? I was switching between linked pan/zoom and linked box-zoom in the first viewer. And then all of a sudden, the order of the tools switched in the first viewer without warning or error. I was caught by surprised.

Screenshot 2024-01-23 181120

**Comment by pllim** [comment]
p.s. I rebased this PR on top of `main` before I tested it.

**Comment by kecnry** [comment]
I cannot imagine how that would possibly be related to this, but if you can consistently reproduce here but not on main, I can investigate.

**Review by pllim — APPROVED** [review]
If that tool swapping thing is unrelated, then your patch also fixed the original problem.

I guess it is up to POs to see what users would prefer? Thanks!

**Comment by kecnry** [comment]
> I guess it is up to POs to see what users would prefer?

This was discussed today and the decision was to move forward with review on this PR, and if it doesn't show any major drawbacks, go with this approach since it's a less-significant behavior change.

**Pull request merged**
