### PR TITLE
Specviz: Implement a SpectrumList loader 

### PR DESCRIPTION
**Pull request by ibusko**
EDIT:

- [ ] Add tests.

### Description

This pull request enables specviz to load multiple spectrum files from a directory, using the loading abilities of SpectrumList:

```
specviz.load_spectrum(<path-to-dir>)
```

The first spectrum in the list is automatically displayed. Still TBD is a way to combine/overplot the entire set of spectra.

This PR is a clone of #867 . See the reviews and discussion in there. I had to create a new fork and this new PR  since my previous fork was apparently busted by an odd attempt at rebasing. 

image

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by orifox** [comment]
@ibusko I just tested this and it looks good. I think rather than worrying about combining the spectrum, I would prefer to see all the spectra in the list turned "on" and the x-range (wavelength) scaled to the min and max over the entire list.

**Comment by ibusko** [comment]
There is a bunch of imviz files that show up as modified, even though I never touched them. Rebasing doesn't fix the issue. I am afraid yet another new PR must be open, with just the modifications in the specviz parser that are required to implement this feature.

**Comment by pllim** [comment]
Yikes, `+1,700 −656`, yeah, that's not good.

**Comment by pllim** [comment]
Not sure what happened but if you create a new branch for this work, make sure you grab the latest `main` first. Example:

```
git fetch upstream main
git checkout upstream/main -b specviz-load-multi-spec-try2
```

Do not create the branch from your fork, especially if your fork is outdated.

**Comment by ibusko** [comment]
See PR #1014 for a (perhaps) better version of this.

**Comment by pllim** [comment]
Closing as duplicate then. Let's continue at #1014. Thanks!

**Pull request closed without merging**
