### PR TITLE
Fix Cubeviz movie export

### PR DESCRIPTION
**Pull request by rosteen**
There was a line pertaining to `Path` filenames, but `_normalize_filename` now turns everything into a string. Exporting movies works for me now.

Not sure what we're milestoning things at at this point...

### CODE REVIEW

**Comment by pllim** [comment]
I don't see any `resolve()` calls in `_normalize_filename` and I forgot why we need it. Are you sure we don't anymore?

**Comment by rosteen** [comment]
> I don't see any `resolve()` calls in `_normalize_filename` and I forgot why we need it. Are you sure we don't anymore?

I added it back in, it _probably_ isn't needed for any of our cases but it's good to have it in to handle some weirder edge cases of what people might input in the field, I think.

**Review by gibsongreen — APPROVED** [review]
Videos are now downloading with content!

**Comment by pllim** [comment]
@gibsongreen , is the recording "cutting off" still an issue at all?

**Review by pllim — APPROVED** [review]
LGTM. Thanks!

**Comment by pllim** [comment]
@rosteen , if auto merge fails, take it off auto merge and use your admin power.

**Comment by gibsongreen** [comment]
> @gibsongreen , is the recording "cutting off" still an issue at all?

@pllim The two issues I had seen was 1, on main that videos were not exporting at all, and 2, after https://github.com/spacetelescope/jdaviz/issues/2896 only blank videos. This was for my local system so maybe cutting off was happening for someone else but this PR enabled the slice range I selected to download as I would expect

**Pull request merged**
