### PR TITLE
plot options: spinner for contour settings

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request adds a spinner overlay in the contour setting of plot options when there is a change in any of the contour settings (as they can take a while to be processed).

Approximately 85% of the time spent during this is in skimage `find_contours` so although it would be nice to optimize, it might be difficult for us to do so.  If contours are ever optimized to the point where the lag would not result in user-confusion, the overlay can easily be removed (or this entire PR reverted if no other plot option makes use of the infrastructure for a spinner).

https://user-images.githubusercontent.com/877591/199064421-b8c3ab63-3c64-44a7-9fc6-f780053f2e08.mov

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Maybe we should add a "tips and tricks" kinda doc to tell user to zoom into object of interest first before contouring. I gather that the performance is better if the number of pixels being displayed is smaller?

**Review by pllim — APPROVED** [review]
I don't grok the JS stuff but I think the solution is reasonable. Thanks!

**Comment by kecnry** [comment]
> Maybe we should add a "tips and tricks" kinda doc to tell user to zoom into object of interest first before contouring. I gather that the performance is better if the number of pixels being displayed is smaller?

I didn't test that... it might be a bit faster, but it seems that most of the time is spent _computing_ the locations, not so much drawing them (unless callbacks are confusing that).

>  I don't grok the JS stuff 

Most of that is indentation and wrapping the old content with the spinner component (copy-pasted from line analysis).

**Review by bmorris3 — COMMENTED** [review]
This looks reasonable, even if the contours do not look reasonable 😅. Would it be sensible to ask POs if we should write a ticket to investigate if a better contour algorithm is possible? I know this is a hard problem, and yet I can't help but wonder if we can do better. cc @camipacifici

**Comment by camipacifici** [comment]
@bmorris3 Point taken :)

**Comment by kecnry** [comment]
> if we should write a ticket to investigate if a better contour algorithm is possible?

For future reference if we do revisit this, we don't call this directly, it is bqplot that calls skimage to determine the contours, so any optimization would likely need to happen there.

**Review by javerbukh — APPROVED** [review]
Works well, thanks!

**Pull request merged**
