### PR TITLE
markers: ensure units stored as string

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request ensures the units in the markers plugin are in string and fixes adding a marker to the spectrum viewer followed by one of the cube viewers.  This bug is confirmed to not be present in 3.10.x, so should not need backporting or a changelog entry.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
So, is it `astropy.unit.Unit` now? If so, using `unit.to_string(format=something)` is more explicit. So if you want FITS compliant units, you do `to_string(format="fits")`.

**Comment by kecnry** [comment]
at this point I just want to ensure that what is stored is a string, is casting not ok for that, do we need to check the type and call `to_string` if it is a unit object?

**Comment by pllim** [comment]
> just want to ensure that what is stored is a string

Well, what would it be if not a string nor Unit? It can't suddenly be a number, can it?

I think you can cast `str(Unit)` but you cannot control the format that way. It has a default but I don't remember on top of my head.

**Comment by pllim** [comment]
Can't tell what is better. I guess this works for now if you need something that can cover other data types as well. If a day comes when we must roundtrip back to FITS format or something, we can reconsider.

**Comment by pllim** [comment]
If this is to fix a bug, do we need a new regression test?

**Comment by pllim** [comment]
Since adding tests are not easy and the diff looks uncontroversial, I think we can proceed without tests. Thanks!

**Pull request merged**
