### PR TITLE
TST: Add RC testing workflow and update existing

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to enable any maintainer to activate the workflow dispatch to test the next astropy release candidate instead of having to create a one-off throwaway PR.

Also minor updates to existing workflows.

### Blocked by

* #1613

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)? [🐱](https://jira.stsci.edu/browse/JDAT-3074)

### CODE REVIEW

**Comment by pllim** [comment]
Ugh... legit deprecation warning from pre-release...

**Comment by pllim** [comment]
I guess I will shelf this until after we can unpin ipy...somethingsomething

**Comment by pllim** [comment]
Huh... failures might be real. Looks like the new `rc-testing` is picking up `voila 0.5.0a0`. @maartenbreddels , any ideas what in that alpha release might break Jdaviz?

**Comment by pllim** [comment]
Nevermind, nothing to do with voila.

* Dev job failure is due to the new glue unit support: https://github.com/glue-viz/glue/pull/2296
* RC job failure is due to `astroquery.sdss` changes on server-side.

**Comment by dhomeier** [comment]
> * Dev job failure is due to the new glue unit support: [Added ability to convert units in profile viewer glue-viz/glue#2296](https://github.com/glue-viz/glue/pull/2296)

6 out of 9 fixed in glue_astronomy 0.6.1; thanks for your contribution!

**Comment by pllim** [comment]
There are still 4 failures in the dev job. FYI.

**Comment by dhomeier** [comment]
Are the test_slice and test_region_spectral_spatial definitely connected to the units PR, too? I see the slice is somehow set from a wavelength with a unit, but don't have an idea how that would change its length.

**Comment by pllim** [comment]
> don't have an idea how that would change its length

That I am not sure but astropy/specutils#999 isn't even merged yet so it can't be that. Maybe fix the two you know are tied to glue unit support first and see if the other two magically goes away. All we can do is the process of elimination.

**Comment by dhomeier** [comment]
Already tested on my machine; it just fixes those two (and would obviate the need for glue-astronomy>=0.6.1). 🤷

**Comment by pllim** [comment]
OK, let's just worry about 2/4 first and defer the other two for later. Thanks!

**Comment by pllim** [comment]
There is also a possibility that the other 2 would involve Jdaviz fixes to work with new unit support (e.g., calling internal API without unit no longer works) but I am just wildly guessing. A dev would have to investigate.

**Comment by dhomeier** [comment]
`test_slice` definitely indicates a regression. With the glue update, the `spectrum_viewer.native_marks` the wavelength is selected in are apparently just a list of indices rather than the values in Angstrom. In the CubevizExample notebook:
```python
sv = cubeviz.app.get_viewer(cubeviz._default_spectrum_viewer_reference_name)
sv.native_marks[0].x
# glue 1.6.1
array([ 3621.59598486,  3622.42998418,  3623.26417555, ..., 10353.80559518])
# glue-dev
array([ 0, 1, 2, 3, ..., 73])
```
Thus apparently in `Slice` the last native_mark is selected.
The spectrum-viewer window in the notebook looks correspondingly broken.

**Comment by astrofrog** [comment]
I think I've found where the remaining failures are coming from - more soon.

**Comment by astrofrog** [comment]
I think https://github.com/glue-viz/glue/pull/2358 fixes the remaining issues?

**Comment by pllim** [comment]
Looks like I cannot test your branch here because your fork has no tags and glue-astronomy is pinning.

```
The conflict is caused by:
    The user requested glue-core 0.1.dev6554+gd212e9b (from git+https://github.com/astrofrog/glue.git@fix-unit-update)
    glue-astronomy 0.6.2.dev3+g71ded78 depends on glue-core>=1.6.1
```

**Comment by dhomeier** [comment]
Should be ready to merge in a minute or so, tests are looking good!

**Comment by pllim** [comment]
Dev job passed!

**Comment by pllim** [comment]
RC now passes, so I removed it from `pull_request` trigger. Going forward, it can be manually triggered by a maintainer but it also runs weekly after merge.

I wouldn't worry about the coverage.

This is ready for review. FYI.

**Review by kecnry — COMMENTED** [review]
Do the changes in the catalogs plugin warrant a changelog entry?

**Comment by pllim** [comment]
There are now discussions to revert this upstream at https://github.com/astropy/astroquery/issues/2659 so I don't think we need a change log. Let's wait and see. Merging.

**Pull request merged**
