### PR TITLE
DEV: Allow symlink in Windows for editable install

### LINKED ISSUE #1282: DEV: Use symlink on Windows when possible
From @vidartf

https://github.com/spacetelescope/jdaviz/pull/1218#issuecomment-1095105519

*For non-ancient versions of Windows, symlinks work as non-admin as long as you put your computer in "developer mode" (found in the settings panel "Developer settings"). As such, my only request would be to try to use symlinks also on Windows, and only try the copying if for some reason symlinks fail. That makes things much easier for me (I don't get the workaround solution when not needed, and the code doesn't just assume I cannot use symlinks just because I'm on Windows).*

cc @maartenbreddels

Note: This was not done in #1234 because I didn't have time to think much about how to cleanly decouple the solutions in Windows for (a) symlink and (b) dev on different disks. We should revisit this though in the future...

[🐱](https://jira.stsci.edu/browse/JDAT-2394)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address https://github.com/spacetelescope/jdaviz/pull/1218#issuecomment-1095105519 by allowing symlink on Windows when it is possible.

For my own Windows setup, symlink is impossible because Miniconda is on C drive by source code in on D. With this patch, I confirmed that it still makes a full copy as in #1218 without crashing. Imviz seems to work in notebook and standalone modes.

For my WSL2 setup, I can confirm that this patch still does symlink, as expected. Imviz seems to work in notebook but I cannot test the standalone portion due to voila-dashboards/voila#773 , though I don't see why it wouldn't work.

Devs who review this should check that the files are copied or symlinked properly and at least run a quick example notebook. You should install this PR branch with `pip install -e .`. @duytnguyendtn , since you are on Windows, maybe you can see if it does symlink without error for "modern Windows". If you get that admin permission error again with this patch, then maybe this is not possible after all.

Maybe @vidartf and @maartenbreddels are interested to review too?

Fixes #1282

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by javerbukh — APPROVED** [review]
Works for me on Windows!

**Comment by javerbukh** [comment]
When I tried to run it again, however, I got the following traceback. Any idea what happened?
```
Traceback (most recent call last):
  File "C:\Users\javer\anaconda3\envs\jdaviz-dev-2.7\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\javer\anaconda3\envs\jdaviz-dev-2.7\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\javer\anaconda3\envs\jdaviz-dev-2.7\Scripts\jupyter-lab.exe\__main__.py", line 7, in <module>
  File "C:\Users\javer\anaconda3\envs\jdaviz-dev-2.7\lib\site-packages\jupyter_server\extension\application.py", line 594, in launch_instance
    serverapp.start()
  File "C:\Users\javer\anaconda3\envs\jdaviz-dev-2.7\lib\site-packages\jupyter_server\serverapp.py", line 2815, in start
    self.start_ioloop()
  File "C:\Users\javer\anaconda3\envs\jdaviz-dev-2.7\lib\site-packages\jupyter_server\serverapp.py", line 2801, in start_ioloop
    self.io_loop.start()
  File "C:\Users\javer\anaconda3\envs\jdaviz-dev-2.7\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\javer\anaconda3\envs\jdaviz-dev-2.7\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\javer\anaconda3\envs\jdaviz-dev-2.7\lib\asyncio\base_events.py", line 1844, in _run_once
    handle = self._ready.popleft()
IndexError: pop from an empty deque
```

**Comment by pllim** [comment]
Is that just with this patch or also on `main`? I had problem with Lab (not with this branch) and I had to reinstall the Lab extensions. 🤷

**Comment by javerbukh** [comment]
I'll check.

**Comment by javerbukh** [comment]
So it works most of the time on this branch, all the time on `main`. I would be really interested if someone else on a different windows setup could test it out though because it could just be my machine.

**Comment by pllim** [comment]
@javerbukh , is your problem same as jupyterlab/jupyterlab#11934 ?

**Comment by javerbukh** [comment]
Yes!

**Review by duytnguyendtn — APPROVED** [review]
Such strong irony that I'm providing a review from the macOS side, rather than the Windows side!

Checked all the tools on macOS and everything seems to look good to me! I'll take that @javerbukh's review for the Windows side clears this to be merged!

**Comment by pllim** [comment]
> clears this to be merged

I cannot be sure since @javerbukh says he only sees that Lab problem with this patch! Jesse, what say you?

**Comment by javerbukh** [comment]
I think it's ok since the bug is upstream. If we open an issue for the bug then I am ok merging this.

**Comment by pllim** [comment]
Is noting this under known issues sufficient?

**Comment by pllim** [comment]
Okay, I opened #1391 for that known issue. I'll merge this. 🤞 

Thanks for all the reviews!

**Pull request merged**
