### PR TITLE
Add elliptical ROI button to imviz

### LINKED ISSUE #635: JDAT-1485: Imviz region support: Add ellipse
PO wants to draw ellipses, not just circles. Blocked by glue-viz/glue-astronomy#31 .

Rotating them is out of scope here and is part of #634 (JDAT-1484). Also see #518.

https://jira.stsci.edu/browse/JDAT-1485

### PR DESCRIPTION
**Pull request by javerbukh**
~~Requires https://github.com/glue-viz/glue-jupyter/pull/241~~
Elliptical ROI functionality added in glue-jupyter v0.7

Resolves #635 

Screen Shot 2021-06-30 at 2 58 29 PM

Screenshot is slightly outdated, a better icon for elliptical ROI is being used.

### CODE REVIEW

**Review by ibusko — COMMENTED** [review]
The button creates a circular region; I couldn't figure out how to make it elliptical.

**Review by ibusko — APPROVED** [review]
Works as expected.

**Comment by pllim** [comment]
As discovered by @rosteen , "get region" for this new shape does not work without glue-viz/glue-astronomy#32 . If this is merged before `glue-astronomy` with that patch can be released, we need to open a new issue as follow up.

**Review by pllim — COMMENTED** [review]
I see the same "lag in moving it" and "get region breakage" that @rosteen reported.

I will withhold approval until we know whether to wait for new `glue-astronomy` release or not.

Nice work otherwise!

**Comment by rosteen** [comment]
Not sure if this possibility was mentioned offline, but now that the required `glue-astronomy` PR was merged we could change that requirement pin to the dev version and create a follow-up issue here to update the pin to the newest version once an actual `glue-astronomy` release happens.

**Comment by pllim** [comment]
> pin to the dev version

There was a precedent... I think that is acceptable.

**Comment by pllim** [comment]
Confirmed that "get region" is fixed with `glue-astronomy` dev version:

```python
>>> regions = imviz.app.get_subsets_from_viewer('viewer-1')
>>> regions
{'Subset 1': <EllipsePixelRegion(PixCoord(x=1539.462646484375, y=1322.1376953125), width=626.53564453125, height=88.5322265625, angle=0.0 deg)>}
```

The lag still there.

**Comment by rosteen** [comment]
@javerbukh If you update the `glue-astronomy` dependence to the dev version I'll approve and merge this, and create a follow-up issue to update the dependence after the next `glue-astronomy` release.

**Comment by javerbukh** [comment]
@rosteen Done, thank you!

**Review by pllim — APPROVED** [review]

**Review by rosteen — APPROVED** [review]

**Comment by pllim** [comment]
FWIW, I opened #711 and #712 as follow up issues. I'll leave the merge for @rosteen . Thanks, everyone!

**Pull request merged**
