### PR TITLE
redshift slider select wide enough to avoid overflow

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request fixes a minor annoyance in the width of the select element (between redshift and RV) in the specviz redshift slider.  See before and after screenshots below.

Screen Shot 2021-12-07 at 10 20 40 AM

Screen Shot 2021-12-07 at 10 20 23 AM

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by rosteen — APPROVED** [review]
Nice. Somehow I never thought to change this despite it bugging me.

**Comment by pllim** [comment]
Screenshot 2021-12-07 170031

Is fixing RV value getting cut off in scope here or not? This screenshot was taken using this PR branch.

**Comment by kecnry** [comment]
Updated the PR to also set a min-width on the text input with room for 6 digits (and while I was at it, I fixed the text-input to not crash when putting in non-numeric characters).  We may want to consider a dynamic width at some point, but that proved to be a bit tricky to avoid jittering and encroaching on the space of the slider itself.

Screen Shot 2021-12-08 at 9 47 26 AM

**Review by pllim — APPROVED** [review]
Let's get this in. Thanks!

**Pull request merged**
