### PR TITLE
Single select replaces other selected items in multi select

### PR DESCRIPTION
**Pull request by duytnguyendtn**
### Description

When switching to single select from multi select, the data menu will now default to the "first" data entry and de-toggle the other data elements

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by kecnry — APPROVED** [review]
Elegant solution and seems to work quite efficiently - thanks!!

**Comment by kecnry** [comment]
(since there is now a merge commit from main, let's make sure to squash when merging)

**Comment by duytnguyendtn** [comment]
Whoops I didn't think the "resolve conflict" button would do that...

**Review by haticekaratay — APPROVED** [review]
I have tested it locally and looks good to me. Thanks!

**Comment by duytnguyendtn** [comment]
Thanks for the eyes! Merging now

**Pull request merged**
