### PR TITLE
Add new line lists to the Specviz plugin

### PR DESCRIPTION
**Pull request by ibusko**
Since we now have a significant number of line lists, I re-arranged their sequence in the main drop-down menu where the user picks up individual lists. I tried to group together (more or less) lists that refer to similar species, such as atomic lists first, then molecular lists, and so on. 

Please, do check that the ordering is OK, or convenient, or whatever criterion we should have for it. I also choose names for the lists that may not be the best from a user's perspective. E.g. since we have already an H2 list, I named the new one H2-alt, since it seems to be an alternate (and shorter) form of H2 (they resort to the same basic line computation reference, although the alt list has one more decimal place for the rest value).

### CODE REVIEW

**Comment by PatrickOgle** [comment]
@ibusko Please replace list of PAH features (from E. Sturm) with my compilation from E. Sturm et al. 2000 and  Smith, J. D. T. et al.

**Review by rosteen — APPROVED** [review]
Looks good to me, I was able to view and load them in the line list UI.

**Review by PatrickOgle — APPROVED** [review]
New line lists appear in jdaviz.  Will add an issue to decide between or merge the three H2 line lists, as a new PR.

**Comment by eteq** [comment]
LGTM too, so merged!

**Pull request merged**
