### PR TITLE
plugin API hints

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements the infrastructure for in-UI plugin API hints, as well as implementing the hints for a number of (but not all) plugins.

https://github.com/user-attachments/assets/0911b15f-2df6-49d5-a694-dbe9f5bf6b89

The diff is large, but mostly boilerplate.  The basic concept is:
* a button in the plugin template that toggles `api_hints_enabled` traitlet (also available to toggle from the API).  This button is added when jdaviz is running in a notebook _and_ the following properties are _all_ passed to `j-tray-plugin`: `config` and `plugin_key` (used to show the line for accessing the plugins from `config.plugins[...]`), as well as `:api_hints_enabled.sync`.
* any UI element can opt-in to reacting to `api_hints_enabled` to change the label.  In some cases this is done by passing `api_hint` and `:api_hints_enabled='api_hints_enabled'` to a re-usable component, and in other cases its done directly inline with `:label='api_hints_enabled ? 'plg.whatever = ' : 'Normal Label'`.  When manually changing the label/content, the `api-hint` class should also be added (re-usable components do this for you).
* use the `api-hint` CSS class to style API hints in orange, monospace text to differentiate them from other labels.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by gibsongreen** [comment]
I think this will be an awesome addition, especially for new users!

The only thing in testing in the UI that I thought could be improved were the button hints. When you're in the normal UI, it's clear what a hint or title is versus the button. When you're using the API hints, all the hints, including the button hint, are in the same or similar color. It threw me off for a moment that you could still click the API hint button. The background of the button still does change color when you hover. 

I don't know if it'd be better to distinguish the button with a different color when the API hints are active, or if the API hint can go under the normal button.

Screenshot 2024-08-09 at 2 15 27 PM

____

Screenshot 2024-08-09 at 2 15 18 PM

____

Screenshot 2024-08-09 at 2 38 35 PM

**Comment by kecnry** [comment]
> It threw me off for a moment that you could still click the API hint button. The background of the button still does change color when you hover.

> I don't know if it'd be better to distinguish the button with a different color when the API hints are active, or if the API hint can go under the normal button.

Good ideas - I'll give both of those a try next week and we can see how they look.  We likely will want to send this to @Jenneh when she's back as well and iterate further on the style as we hear feedback from her and users.  For now I was mainly focused on making sure all the different types of input had support and there was some consistent styling to make the API hints standout from everything else.

**Review by javerbukh — APPROVED** [review]
The code seems really well done and from my testing everything works as expected, nice job! I think this would benefit from some stress testing during a hack hour and maybe a crash course from you on implementing plugins with these features, but as the work stands it looks good to merge!

**Review by gibsongreen — APPROVED** [review]
Did a second pass on testing and looking through the code, everything checks out!

**Pull request merged**
