### PR TITLE
popout plugins

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request extends on #977 and puts popout buttons in each of the plugins.

image

image

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by rosteen** [comment]
Yesss, I've been waiting for this to finally be possible. So far in my testing it works well, I only have one complaint that the alignment of text and such in the popout is right up against the edge of the window. I have the feeling that might need an upstream change, but if you have an idea of how to do it here then I'd like to see it. Otherwise we can open an issue upstream for @mariobuikhuizen.

Screen Shot 2022-06-28 at 9 42 17 AM

**Comment by kecnry** [comment]
I don't think it's a problem upstream, the problem is that we add the padding in the expansion-panel itself rather than the plugin content.  Let me see if I can easily move the padding to the plugin content in a way that doesn't require us to repeat it in each plugin.

**Comment by kecnry** [comment]
@rosteen - I think I fixed the padding concern, please confirm.  Note that we still have some CSS styles that are defined at higher levels in the app that do not get applied when popping out (the color of "ADD COMPONENT", for example).  We should probably move these styles into the appropriate places, but I think that can be done later (or we can leave this as a draft until we have time to devote to that).

**Comment by rosteen** [comment]
Thanks, I'll check it out is a minute. Mario also mentioned at tagup that the popout has a CSS tag associated with it, if we want specific styling in this case that might be another useful way to go about it.

**Review by rosteen — APPROVED** [review]
That looks much better, thanks!

**Review by duytnguyendtn — COMMENTED** [review]
I love this feature! So glad to have it in `jdaviz` finally! Thanks @kecnry!! I have two questions/comments

1) I noticed the large count of changed files is largely just adding the button to all the plugins. I was wondering if there's a way to avoid all this duplicated code, and rather just have it up one level at the base plugin level. Do you think there's a way to have the button populated by default to all plugins? I don't know if it would be too busy, but maybe something like the line-list plugin where we put the color picker in the title?
2) For my own curiosity, I noticed when you pop out the whole app, you lose the ability to pop out the individual plugins. Where is that logic? I couldn't find anything that pointed to that logic in the code review. Mainly for my own edification

**Comment by kecnry** [comment]
> I was wondering if there's a way to avoid all this duplicated code, and rather just have it up one level at the base plugin level.

I considered putting it in `j-docs-link` but then the case of plot-options makes that complicated since there is another button for toggling advanced mode.  Do you think its worth trying to generalize that somehow?

> For my own curiosity, I noticed when you pop out the whole app, you lose the ability to pop out the individual plugins. Where is that logic?

I believe that is in the popout button itself (in ipypopout) - it knows to hide itself in the popout window.  I definitely didn't include any of that logic here.

**Comment by duytnguyendtn** [comment]
> Do you think its worth trying to generalize that somehow?

I'd advocate for yes. Ideally, I would love the pop out feature to be a no-op/come-for-free when someone creates a new plugin. We've advertised that people can contribute their own plugins and I think we should try to provide as much functionality to them for minimal effort as possible

**Comment by kecnry** [comment]
@duytnguyendtn - I agree that's most clean from a "developing a new plugin perspective". The drawback is that the plugin description is now limited to text only (since it is passed as a property instead of as a slot, and I couldn't figure out a way to get nested custom elements to work that way, although that doesn't mean its impossible).  There were only two places where we didn't have this already, so I was able to do that as long as we're ok with the two following changes (and losing the ability to customize this description header per-plugin).

**Plot options**:

The advanced mode toggle is now bumped down a row rather than being in the description header.

<div>
image
image
</div>

**Line analysis**:

The link to specutils docs is now in the results section instead of in the description header.

<div>
image
image
</div>

**Comment by duytnguyendtn** [comment]
I actually REALLY like this behavior; you just pass in your description, link, and popout button and you're good to go! I think this is a fair exchange for the abstraction. I'll submit a formal approval soon! Thanks a bunch :)

Not sure if you care enough about the commit msg, but I noticed a small typo:

> * description must now be >>test<< only

**Review by duytnguyendtn — APPROVED** [review]
Looks great! Thanks so much Kyle!

One small visual change I thought was odd (though not show stopper), the style of one of the buttons changed its color?

image

**Comment by pllim** [comment]
I think the color is a known issue from #977 . Either @mariobuikhuizen or @kecnry brought it up at some point, but feel free to correct me if I misremember.

**Comment by kecnry** [comment]
Yes, any styling that we do at higher levels won't be passed on because it doesn't belong to the element in the popout window (at least I'm assuming that's what's going on). Fixing this will require a significant refactoring of css code within jdaviz that I suggest we postpone for an actual ticket.

**Pull request merged**
