### PR TITLE
Linelist bugfix

### PR DESCRIPTION
**Pull request by rosteen**
Fixes a couple bugs with loading preset line lists from the notebook. I'm hoping to have this included in 1.0.2

### CODE REVIEW

**Review by javerbukh — APPROVED** [review]
This all looks great and I think should definitely make it into v1.0.2.

I will post the following interaction however that seemed like something was missing, but doing  `plot all` seemed to fix it.
1) Load Common Stellar
2) Zoom out
3) Load CO
4) Change CO color to cyan
5) Remove CO
6) Does not appear that all lines were re-added
7) Re-load CO
8) Still not all lines there
9) Click `plot all` and everything appears.

I think having "click `plot all`" as a troubleshooting fix would be nice to have in the documentation, but otherwise I think any reasonable user will try this as a fix anyway (we hope).

**Comment by ibusko** [comment]
I get this error when pip-installing:

Exception:
Traceback (most recent call last):
  File "/Users/busko/Projects/software/miniconda3/envs/jdaviz/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/Users/busko/Projects/software/miniconda3/envs/jdaviz/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 315, in run
    resolver.resolve(requirement_set)
  File "/Users/busko/Projects/software/miniconda3/envs/jdaviz/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/busko/Projects/software/miniconda3/envs/jdaviz/lib/python3.7/site-packages/pip/_internal/resolve.py", line 357, in _resolve_one
    add_req(subreq, extras_requested=available_requested)
  File "/Users/busko/Projects/software/miniconda3/envs/jdaviz/lib/python3.7/site-packages/pip/_internal/resolve.py", line 314, in add_req
    use_pep517=self.use_pep517
  File "/Users/busko/Projects/software/miniconda3/envs/jdaviz/lib/python3.7/site-packages/pip/_internal/req/constructors.py", line 328, in install_req_from_req_string
    if req.url and comes_from.link.netloc in domains_not_allowed:
AttributeError: 'NoneType' object has no attribute 'netloc'

I am sure it has to do with my environment. Just don't know what changed since the last time I installed jdaviz. Any recent changes in installation requirements?

**Comment by rosteen** [comment]
@ibusko We updated the glue-jupyter version requirement, but I've never seen the error you ran into.

**Comment by ibusko** [comment]
I have the new glue-jupyter 0.2.1 installed.

**Comment by ibusko** [comment]
I can run tests under pycharm with the same python environment. It's just the pip install that doesn't go.

**Comment by rosteen** [comment]
Maybe try upgrading your pip version? Looks like a pip bug or network error to me

**Review by ibusko — APPROVED** [review]
I think it was a network error. It works now. I couldn't see the behavior @javerbukh mentioned, but I might have used slightly different sequences of actions. But it looks good to go.

**Comment by javerbukh** [comment]
Sounds good, merging.

**Pull request merged**
