### PR TITLE
TST: Use new remote data for test_spectrum_on_top

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to re-enable the remote test skipped in #1736 by replacing it with another file suggested by Tyler Pauly from pipeline team.

*[The old file] should no longer be created - it was the result of a duplicate association created (`jw01529-o004_spec3_001_asn.json == jw01529-c1002_spec3_001_asn.json`), and so the file `jw01529-o004_t002_miri_p750l_s2d.fits` should hold the relevant data. The duplicate association bug has been fixed, so some `c1xxx` associations are intentionally no longer created. If the old `c` type association is on hand, you can check to see if it fell under this issue by checking the full member list - if all listed members fall under one observation group (i.e., `o004`), the association will no longer be generated.*

Out of scope:
* #1739

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set?
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by duytnguyendtn — APPROVED** [review]
Test passed on my end, but I did run into a warning at an outdated package in my stack:

Is there a need to indicate somewhere that `gwcs>0.18.1` is required for the tests to pass?

<details>
<summary>envmain\lib\site-packages\asdf\asdf.py:349: AsdfWarning</summary>

```
========================================================================================================= FAILURES ========================================================================================================= 
___________________________________________________________________________________________________ test_spectrum_on_top ___________________________________________________________________________________________________ 

specviz2d_helper = <jdaviz.configs.specviz2d.helper.Specviz2d object at 0x00000158E8D9A500>

    @pytest.mark.remote_data
    def test_spectrum_on_top(specviz2d_helper):
        fn = download_file('https://mast.stsci.edu/api/v0.1/Download/file/?uri=mast:jwst/product/jw01529-o004_t002_miri_p750l_s2d.fits', cache=True)  # noqa

>       specviz2d_helper.load_data(spectrum_2d=fn)

jdaviz\configs\specviz2d\plugins\spectral_extraction\tests\test_spectral_extraction.py:173:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  
jdaviz\configs\specviz2d\helper.py:160: in load_data
    self.app.load_data(spectrum_2d, parser_reference="mosviz-spec2d-parser",
jdaviz\app.py:531: in load_data
    msg = parser(self, file_obj, **kwargs)
jdaviz\configs\mosviz\plugins\parsers.py:313: in mos_spec2d_parser
    data = Spectrum1D.read(data)
envmain\lib\site-packages\astropy\nddata\mixins\ndio.py:59: in __call__
    return self.registry.read(self._cls, *args, **kwargs)
envmain\lib\site-packages\astropy\io\registry\core.py:212: in read
    data = reader(*args, **kwargs)
envmain\lib\site-packages\specutils\io\default_loaders\jwst_reader.py:391: in jwst_s2d_single_loader
    spectrum_list = _jwst_s2d_loader(filename, **kwargs)
envmain\lib\site-packages\specutils\io\default_loaders\jwst_reader.py:440: in _jwst_s2d_loader
    with asdf.open(filename) as af:
envmain\lib\site-packages\asdf\asdf.py:1790: in open_asdf
    return AsdfFile._open_impl(
envmain\lib\site-packages\asdf\asdf.py:921: in _open_impl
    return fits_embed.AsdfInFits._open_impl(
envmain\lib\site-packages\asdf\fits_embed.py:283: in _open_impl
    return cls._open_asdf(
envmain\lib\site-packages\asdf\asdf.py:888: in _open_asdf
    self._check_extensions(tree, strict=strict_extension_check)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

self = <asdf.fits_embed.AsdfInFits object at 0x00000158E9076200>
tree = {'asdf_library': {'author': 'The ASDF Developers', 'homepage': 'http://github.com/asdf-format/asdf', 'name': 'asdf', '...>, 'var_rnoise': <array (unloaded) shape: [387, 44] dtype: >f4>, 'wht': <array (unloaded) shape: [387, 44] dtype: >f4>}
strict = False

    def _check_extensions(self, tree, strict=False):
        """
        Compare the user's installed extensions to metadata in the tree
        and warn when a) an extension is missing or b) an extension is
        present but the file was written with a later version of the
        extension's package.

        Parameters
        ----------
        tree : AsdfObject
            Fully converted tree of custom types.
        strict : bool, optional
            Set to `True` to convert warnings to exceptions.
        """
        if "history" not in tree or not isinstance(tree["history"], dict) or "extensions" not in tree["history"]:
            return

        for extension in tree["history"]["extensions"]:
            installed = None
            for ext in self._user_extensions + self._plugin_extensions:
                if (
                    extension.extension_uri is not None
                    and extension.extension_uri == ext.extension_uri
                    or extension.extension_uri is None
                    and extension.extension_class in ext.legacy_class_names
                ):
                    installed = ext
                    break

            filename = f"'{self._fname}' " if self._fname else ""
            if extension.extension_uri is not None:
                extension_description = f"URI '{extension.extension_uri}'"
            else:
                extension_description = f"class '{extension.extension_class}'"
            if extension.software is not None:
                extension_description += " (from package {}=={})".format(
                    extension.software["name"],
                    extension.software["version"],
                )
    
            if installed is None:
                msg = ("File {}was created with extension {}, which is " "not currently installed").format(
                    filename, extension_description
                )
                if strict:
                    raise RuntimeError(msg)
                else:
                    warnings.warn(msg, AsdfWarning)

            elif extension.software:
                # Local extensions may not have a real version.  If the package name changed,
                # then the version sequence may have been reset.
                if installed.package_version is None or installed.package_name != extension.software["name"]:
                    continue
                # Compare version in file metadata with installed version
                if parse_version(installed.package_version) < parse_version(extension.software["version"]):
                    msg = ("File {}was created with extension {}, but older package ({}=={}) " "is installed.").format(
                        filename,
                        extension_description,
                        installed.package_name,
                        installed.package_version,
                    )
                    if strict:
                        raise RuntimeError(msg)
                    else:
>                       warnings.warn(msg, AsdfWarning)
E                       asdf.exceptions.AsdfWarning: File 'file:///C:/Users/Duy/.astropy/cache/download/url/2f630089dfba8a3739b4836439706e4d/contents' was created with extension URI 'asdf://asdf-format.org/astronomy/gwcs/extensions/gwcs-1.0.0' (from package gwcs==0.18.2), but older package (gwcs==0.18.1) is installed.

envmain\lib\site-packages\asdf\asdf.py:349: AsdfWarning
```

</details>

**Comment by pllim** [comment]
> Is there a need to indicate somewhere that gwcs>0.18.1 is required for the tests to pass?

I dunno if that will open a can of worms or not. MAST can change that file anytime. The next time they run the pipeline, they might require a even higher version of gwcs. We will never know.

**Comment by duytnguyendtn** [comment]
> We will never know.

Fair point; I figured that adding a note isn't saying "The tests are guaranteed to work with `gwcs>0.18.1`, it's more saying the tests will DEFINITELY fail if `gwcs<0.18.1`. Feel free to take it or leave it; this is a fairly simple error msg anyways

**Comment by pllim** [comment]
@duytnguyendtn , I added a commit with your suggestion. Please double check. Thanks!

**Review by duytnguyendtn — APPROVED** [review]
Beautiful! Thanks @pllim!

**Comment by pllim** [comment]
Thanks for the review!

**Pull request merged**
