### PR TITLE
Mosviz hotfix

### PR DESCRIPTION
**Pull request by javerbukh**
### Description

This pull request fixes some bugs that appeared after all of today's merges. There is still one bug that @rosteen may need to take a look at (feel free to commit to this PR) where the images do not appear in `MosvizExample.ipynb` when selecting new rows.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
The failure is also on `main` after merging #823

**Comment by pllim** [comment]
I don't see any upstream changes between the last success and first failure in main, so must have been something from the last few merges/rebases.

https://github.com/spacetelescope/jdaviz/runs/3477117021?check_suite_focus=true

https://github.com/spacetelescope/jdaviz/runs/3477413672?check_suite_focus=true

**Comment by rosteen** [comment]
Just pushed a commit to fix this, the zooming to slit case needed to handle not being able to find the slit info in the header more gracefully (by not zooming) in the same way as missing RA/Dec info is handled in the zooming to object case.

**Comment by pllim** [comment]
You are so good at "hacking" coverage now. 😆

**Comment by rosteen** [comment]
This CI running is apparently using the one 1995 Gateway computer with dial-up connection on the AWS network (or whatever cloud service it uses)

**Comment by pllim** [comment]
Action is sluggish in other repos too. I don't know why their status page is all green. I blame the hurricane.

**Review by rosteen — APPROVED** [review]
All checks except the known dev dependency failure are now passing.

**Review by pllim — APPROVED** [review]
I didn't run the notebook but I like the green CI. Five stars!

**Pull request merged**
