### PR TITLE
Snackbar fix

### PR DESCRIPTION
**Pull request by ibusko**
Attempt at fixing ticket JDAT-1559: stacking snackbar messages.

Snackbar vuetify elements (\<v-snackbar \>) cannot be drawn at arbitrary places on screen; they just support `top`, `bottom`, `left`, `right` properties. Thus there is no way to stack them say, as a column on screen. People found a solution via a `VSnackbarQueue` that displays snackbar messages one after the other, as the `Close` button is clicked, or each message times out in turn. Unfortunately, this class is not implemented in `ipyvuetify`.

As a stopgap solution, I implemented a queuing mechanism here.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Works like magic! Also the messages disappear on their own one by one before they annoy me. This is perfect.

**Comment by rosteen** [comment]
This is looking great, except for one thing: it breaks the "Fittimg model to cube..." (with spinning icon) message that is supposed to display while the parallel cube fitting is happening in Cubeviz. The cube still fits, but I get a traceback and the in-progress message never appears:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/Users/rosteen/opt/anaconda3/envs/viz_dev/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rosteen/projects/jdaviz/jdaviz/utils.py", line 95, in sleep_function
    self.close_current_message(state)
  File "/Users/rosteen/projects/jdaviz/jdaviz/utils.py", line 62, in close_current_message
    _ = self.queue.pop()
IndexError: pop from an empty deque
```

**Comment by pllim** [comment]
Re: cubeviz -- Should "snackbar" also work as a "progress bar"? 🤔  Is there no other way to show progress?

**Comment by ibusko** [comment]
The problem with the cube fitting has to do with the snackbar message for the progress being sent with an infinite timeout. This is a case I didn't know happened in jdaviz, so the logic in the snackbar queue breaks. I will add a fix that, to be simple, will just check for the requested mode, "standard" or "loading" and, in case it is loading, falls back in the non-queued mode of operation.

**Comment by ibusko** [comment]
I think the bug with progress messages is fixed.

**Review by rosteen — APPROVED** [review]
I'm happy to go into the weekend celebrating the triumphant return of the cube fitting message. This looks good to me! It even surfaced snackbar messages that I had forgotten existed, since they had been covered up by messages triggered at similar times.

**Comment by pllim** [comment]
Forgotten snacks... 😸

**Pull request merged**
