### PR TITLE
Update minimum required version of glue-jupyter to v0.6

### PR DESCRIPTION
**Pull request by astrofrog**
This does four things:

* Ensures we now use SVG icons, so no converting icons to PNG
* Fixes the vertical alignment of the subset select menu (the fix here was done in https://github.com/spacetelescope/jdaviz/pull/615 but required a new release of glue-jupyter to take effect)
* Fixes the aliasing issues @eteq (I think) saw before where some pixels weren't appearing square at certain zoom levels
* Perhaps the biggest change, the image will now adjust its size/aspect ratio to the whole available view:

Screenshot_2021-06-08_16-24-28

I will take this out of draft once the glue-jupyter v0.6 release is live and rebase to restart the CI.

### CODE REVIEW

**Review by rosteen — APPROVED** [review]

**Comment by pllim** [comment]
I think Jennifer Kotler mentioned the desire to have display centered, so does this auto-fill make that request moot?

**Comment by pllim** [comment]
Does this also fix #666 , @astrofrog ?

**Comment by rosteen** [comment]
I think the answer to @pllim's first question is yes, but I'm not 100% sure. 

This looks good to me, with the caveat that it makes the previously square images in the Cubeviz image viewers are now sort of squished rectangles. I think the solution there is to increase the height of the app and adjust the heights of the viewers...I can make a followup issue for that.

**Comment by rosteen** [comment]
Screenshot of what I was talking about above:

Screen Shot 2021-06-08 at 1 44 28 PM

**Comment by pllim** [comment]
With this patch, pan/zoom icon is broken.

Screenshot 2021-06-08 143026

**Review by pllim — APPROVED** [review]
I took the liberty to rebase and fix the Imviz icon. Hope you don't mind. LGTM now.

Does this also mean we can delete all the PNG files inside `icons` dir?

**Comment by astrofrog** [comment]
@rosteen the squished images you are mentioning is the fourth bullet point I mentioned in the description of this PR - it is deliberate so we should maybe discuss this more on the next SME tag up if you think this doesn't make sense?

**Comment by astrofrog** [comment]
(Or indeed we can discuss in a separate issue)

**Review by pllim — CHANGES_REQUESTED** [review]
Actually, `glue-jupyter` 0.6 broke region selection. So we cannot accept this. In fact, we need to go the other way and pin to `glue-jupyter<=0.5` until this is fixed. Thanks to @javerbukh for discovering this.

**Comment by pllim** [comment]
I opened #677 and closing this without merge.

**Pull request closed without merging**
