### PR TITLE
TST: Update expected answer from astropy PR 14519

### LINKED ISSUE #2086: TST: test_register_model_with_uncertainty_weighting fails in astropy dev
Look in the dev job:

```
FAILED jdaviz/configs/default/plugins/model_fitting/tests/test_plugin.py::
    test_register_model_with_uncertainty_weighting - assert False
 +  where False = <function allclose at ...>(0.0007063584243707317, 0.0003657, rtol=0.01)
 +    where <function allclose at ...> = np.allclose
```

@bmorris3 knows what caused this.

[🐱](https://jira.stsci.edu/browse/JDAT-3197)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to update new results affected by astropy/astropy#14519 now that uncertainties are propagated.

Fixes #2086

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Dev job passes now with this patch.

**Review by kecnry — APPROVED** [review]
woah, that's quite a significant change!  The implementation itself works for me as long as @bmorris3 agrees these are expected.

**Review by bmorris3 — APPROVED** [review]
Looks good for now. 

A note for the future though (which I'm also investigating for #2039) – we should make a set of tests for fitting routines that are:

1) based on synthetic data for which we can derive analytic results _and uncertainties_, to show the jdaviz answer and uncertainty are as expected (these could be designed to be light-weight and fast)

2) based on in-flight data, to ensure the jdaviz results are consistent with published results. These are tricky because, e.g., results can change with recalibration, remote-data are required, real fits are slower. But we don't need to add these particular tests to CI?

**Comment by pllim** [comment]
Thanks!

**Pull request merged**
