### PR TITLE
Pinning min version of asdf-transform-schemas

### PR DESCRIPTION
**Pull request by bmorris3**
This PR specifies a minimum version for `asdf-transform-schemas`. @mustaric pointed out that if a user loads
JWST/MIRI i2d observations into Imviz like so:
```python
from jdaviz import Imviz

imviz = Imviz()
imviz.load_data('JWST_Data_PID????/jw*_miri_f770w_i2d.fits')
imviz.show()
```
with `asdf-transform-schemas==0.2.2` installed, the `load_data` call produces the following two warnings:
```
2022-10-21 12:53:34,247 - stpipe - WARNING - /Users/bmmorris/miniconda3/envs/jdaviz/lib/python3.9/site-packages/asdf/schema.py:301: AsdfWarning: Unable to locate schema file for 'tag:stsci.edu:asdf/transform/property/bounding_box-1.0.0': 'http://stsci.edu/schemas/asdf/transform/property/bounding_box-1.0.0'
  warnings.warn(msg.format(tag, schema_uri), AsdfWarning)

2022-10-21 12:53:34,324 - stpipe - WARNING - /Users/bmmorris/miniconda3/envs/jdaviz/lib/python3.9/site-packages/asdf/yamlutil.py:300: AsdfConversionWarning: tag:stsci.edu:asdf/transform/property/bounding_box-1.0.0 is not recognized, converting to raw Python data structure
  warnings.warn(
```
`asdf-transform-schemas==0.3` introduced schemas for supporting bounding boxes (see astropy/asdf-astropy#69 and their [release notes](https://github.com/asdf-format/asdf-transform-schemas/releases/tag/0.3.0)), which prevents the warnings from being raised on load in jdaviz.

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — CHANGES_REQUESTED** [review]
I don't think this is our problem. The pipeline requirements are going to keep changing, so this is a game we can never win. Maybe we can put such things under "known issues" like "if you see stpipe warnings when you try to load JWST file, try to update your pipeline packages".

**Review by duytnguyendtn — COMMENTED** [review]
Hmm... I'm torn on this one... In principle, I agree with @pllim's stance that this error seems irrelevant to `jdaviz` specifically. However, I don't know whether our agreements with the JWST MO include "warning-free" loading of JWST products. Pinging @camipacifici

**Comment by bmorris3** [comment]
> I don't think this is our problem. 

For what it's worth, I 99% agree with you on this, @pllim. It's not `jdaviz`'s mission statement to be self-consistent Python package managers for users of JWST data products.

My 1% disagreement is that we [claim support for these JWST data products in our docs](https://jdaviz.readthedocs.io/en/latest/#jwst-instrument-modes-in-jdaviz). An alternative to putting this requirement in `install_requires` could be to offer a small `jwst_requirements.txt` file or similar, which a user could use to install JWST-related dependencies, but that would be hard to test and take some effort to maintain.

If it's easy to do (or, even better, already done), small PRs like this are a low-effort option. Either way. I'm happy keeping or binning this PR.

**Comment by duytnguyendtn** [comment]
If this were an *error* I think this discussion would be different. Just to confirm, does the data still load properly without this min version?

**Comment by bmorris3** [comment]
> If this were an _error_ I think this discussion would be different. Just to confirm, does the data still load properly without this min version?

Yes, the data loads. This is the warning @mustaric reported:
```
2022-10-17 16:40:22,729 - stpipe - WARNING - /Users/smullally/miniconda3/envs/jwst/lib/python3.9/site-packages/asdf/schema.py:301: AsdfWarning: Unable to locate schema file for 'tag:stsci.edu:asdf/transform/property/bounding_box-1.0.0': 'http://stsci.edu/schemas/asdf/transform/property/bounding_box-1.0.0'
  warnings.warn(msg.format(tag, schema_uri), AsdfWarning)
```
I think if the ASDF package can't find the schema file, it skips the `bounding_box` feature and continues to handle the file. Maybe @mustaric can confirm?

**Comment by kecnry** [comment]
If its just a warning, I think I'd agree to not change our requirements to be even more strict.  Can we catch the warning and either suppress it (if we're sure it has no consequence on our features) or provide our own warning with a suggestion to update the upstream package?

**Comment by bmorris3** [comment]
> An alternative to putting this requirement in `install_requires` could be to offer a small `jwst_requirements.txt` file or similar, which a user could use to install JWST-related dependencies, but that would be hard to test and take some effort to maintain.

Turns out that the `jwst` module [does something like this already](https://github.com/spacetelescope/jwst/blob/master/requirements-dev.txt#L3). Maybe we should just suggest in future issues to install the `jwst` requirements and let those devs handle their dependencies? Those future users would simply need to do something like:
```
git clone https://github.com/spacetelescope/jwst.git
cd jwst
pip install -r requirements-dev.txt
pip install -e .
```

**Comment by camipacifici** [comment]
I agree that if the data loading is not affected (but we need to be sure about this), we do not have to worry...for now. Thinks will keep changing and we will get more of these warnings going forward.
I like the ideas of providing our own warning if possible and adding it to the known issues.

**Comment by camipacifici** [comment]
Is the warning appearing if one installs the pipeline and jdaviz in the same environment?

**Comment by bmorris3** [comment]
@camipacifici Here's @mustaric's related question in the `#jdaviz` slack channel: 
```
Is there something amiss with my installation?  It’s a conda environment 
with only jdaviz and the pipeline installed. jdaviz is 3.0.1. asdf is 
2.13.0.  The data is exclusive access, so I can’t just give you a link 
to the data.  It is a miri level-3, i2d.fits, full readout.
```

**Comment by pllim** [comment]
We should not tell people how to manage their pipeline env, that is SCSB's job, see https://github.com/spacetelescope/stenv .

Should we:

(a) Close this issue without doing anything?
(b) Write up a generic known issue to close this issue?

**Comment by bmorris3** [comment]
> Should we:
> 
> (a) Close this issue without doing anything?
> (b) Write up a generic known issue to close this issue?

I'm going to opt for option (a). It's always possible that someone can find this PR and its discussion if they hit a similar error. If that's the case, this PR resolves the issue even without being merged. Closing. Thanks all!

**Comment by bmorris3** [comment]
@yaolun and Will Best report that now old versions of `asdf-transform-schemas` raise errors, instead of just warnings. Might be time to reconsider this PR.

**Comment by havok2063** [comment]
just an FYI, we've had to pin this to in our requirements in MAST to get things to load properly in Jdaviz.

**Comment by pllim** [comment]
@havok2063 , this is now tracked in #1925 and we're still waiting for upstream release.

**Pull request closed without merging**
