### PR TITLE
Updated minimum versions of glue-core and glue-jupyter

### LINKED ISSUE #335: Specviz: axes get autoscaled at every operation
Whether the axis limits have been set with the zoom features or with commands, they reset at every operation. This happens in the notebook, with jdaviz 1.0.3.

EDIT - blocked by:

* glue-viz/glue-jupyter#247
* glue-viz/glue#2223 [🐱](https://jira.stsci.edu/browse/JDAT-1745)

### PR DESCRIPTION
**Pull request by astrofrog**
### Description

This fixes issues with the y limits in the profile viewer resetting e.g. for every subset update, and also fixes a bug that caused the limits of the image viewer to reset when adding markers or additional image datasets to the image viewer.

In short, this will make it so that the profile and image viewer limits will only be reset automatically when the reference data is changed, not when additional datasets or subsets are added or modified in the viewers.

I have tested that this means making subsets in Specviz does not reset the limits - however changing object in MOSViz does change the limits because the reference data is changed.

This also fixes the home button in the profile viewer to ensures it resets both the x and y limits.

EDIT:

* ~#760~
* fix #335

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
OK pls ping me when the jobs pass and I can review for Imviz. Thanks!

**Comment by astrofrog** [comment]
@pllim - ready for review!

**Review by rosteen — APPROVED** [review]
Looks good to me!

**Comment by pllim** [comment]
This does not address #760 . Imviz pan/zoom still resets when markers are added via `viewer.add_markers` but it is not critical to fix for 2.0.

**Review by camipacifici — APPROVED** [review]
Looks good to me too!

**Comment by pllim** [comment]
RTD will catch up on its own. Merging so spectrum stuff is fixed. We can worry about Imviz later. Thanks!

**Pull request merged**
