### PR TITLE
Automatically load first object on data load in Mosviz

### PR DESCRIPTION
**Pull request by rosteen**
### Description
I didn't see an issue for this, but it seemed like the easiest thing to do out of the outstanding features from Jenn's wireframe that we haven't implemented yet so I just did it. Nice little quality of life change.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by rosteen** [comment]
Adding new lines and increasing test coverage for free, you love to see it.

**Review by pllim — APPROVED** [review]
Can't get the NIRISS notebook to work (a different problem) but this works as advertised on NIRSpec notebook.

Screenshot 2021-08-31 093405

The selected row is "too bright" on dark mode but that is also a different problem.

I noticed the checkbox is not checked, is that expected?

**Comment by rosteen** [comment]
That's expected - the checkbox has nothing to do with whether the row is selected, which is an understandable point of confusion with users.

**Comment by pllim** [comment]
Then what is the checkbox for? 🤨

**Comment by rosteen** [comment]
You can export only the checked rows to a CSV or astropy table (or theoretically make a subset out of them, I think).

**Review by javerbukh — APPROVED** [review]
Looks good!

**Comment by ojustino** [comment]
I don't see why it wouldn't.

**Pull request merged**
