### PR TITLE
Update glue pin

### PR DESCRIPTION
**Pull request by rosteen**
Glue 1.14.0 fixes the green subset layer bug.

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Yes!!!!

**Comment by pllim** [comment]
@meeseeksdev backport to v3.7.x

**Comment by pllim** [comment]
@rosteen , looks like you need to do a manual backport if you really want to backport this. Though traditionally we do not bump minversion in bug fix releases.

**Comment by rosteen** [comment]
@pllim we discussed this before you joined tag-up, The consensus was to include this in 3.7.1, since it seems a little silly to make the release 3.8 just because of a pin bump to fix a nasty bug. Any strenuous objections?

**Comment by pllim** [comment]
Since this is technically a bug maybe a change log was needed after all? 🤷

**Comment by rosteen** [comment]
Yeah I'll add a changelog entry when I backport/do the bugfix release.

**Comment by pllim** [comment]
Sounds good. Thanks!

**Pull request merged**
