### PR TITLE
BUG: Let mastviz use Imviz

### LINKED ISSUE #1037: [BUG] Imviz: creating a single image viewer with tabs disabled breaks
**Describe the bug**
In instantiating Imviz for a single image, with the display tabs disabled, the image begins to load but ultimately fails with a `KeyError` on `imviz-0`.  In MAST we disable the tabs because 1. they are ugly and 2. we don't need them.  

**To Reproduce**

```
from jdaviz.app import Application
from jdaviz import Imviz
from jdaviz.core.config import get_configuration

dataim = 'jw00736-o037_t001_miri_f770w_i2d.fits'

# create a mast config dict
mastconfig = {}

vis = {'menu_bar': False, 'toolbar': False, 'tray': False, 'tab_headers': False}

cc = get_configuration('imviz')
cc['settings']['viewer_spec'] = cc['settings'].get('configuration', 'default')
cc['settings']['configuration'] = 'mastviz'
cc['settings']['visible'] = vis
cc['toolbar'].remove('g-data-tools') if cc['toolbar'].count('g-data-tools') else None
cc['toolbar'].remove('g-viewer-creator') if cc['toolbar'].count('g-viewer-creator') else None
cc['toolbar'].remove('g-image-viewer-creator') if cc['toolbar'].count('g-image-viewer-creator') else None
mastconfig.update(cc)

app = Application(mastconfig)
im = Imviz(app)
im.load_data(dataim)
```
Full traceback below

**Expected behavior**
I expect the image to load successfully.  The internal viewer labels, e.g. `imviz-0`, should still exist whether the tabs are being displayed or not.    

**Additional context (e.g. data files)**

Traceback
```
KeyError                                  Traceback (most recent call last)
<ipython-input-22-ebc6741466e7> in <module>
----> 1 im.load_data(dataim)

~/Work/git/havok2063/jdaviz/jdaviz/configs/imviz/helper.py in load_data(self, data, parser_reference, **kwargs)
    137                     kw['data_label'] = data_label
    138 
--> 139                 self.app.load_data(
    140                     filepath, parser_reference=parser_reference, **kw)
    141 

~/Work/git/havok2063/jdaviz/jdaviz/app.py in load_data(self, file_obj, parser_reference, **kwargs)
    360                 # If the parser returns something other than known, assume it's
    361                 #  a message we want to make the user aware of.
--> 362                 msg = parser(self, file_obj, **kwargs)
    363 
    364                 if msg is not None:

~/Work/git/havok2063/jdaviz/jdaviz/configs/imviz/plugins/parsers.py in parse_data(app, file_obj, ext, data_label, show_in_viewer)
     59         else:  # Assume FITS
     60             with fits.open(file_obj) as pf:
---> 61                 _parse_image(app, pf, data_label, show_in_viewer, ext=ext)
     62     else:
     63         if data_label is None:

~/Work/git/havok2063/jdaviz/jdaviz/configs/imviz/plugins/parsers.py in _parse_image(app, file_obj, data_label, show_in_viewer, ext)
    139         app.add_data(data, data_label)
    140         if show_in_viewer:
--> 141             app.add_data_to_viewer("imviz-0", data_label)
    142 
    143     if len(app.data_collection) <= 1:  # No need to link, we are done.

~/Work/git/havok2063/jdaviz/jdaviz/app.py in add_data_to_viewer(self, viewer_reference, data_path, clear_other_data, ext)
    788         if data_id is not None:
    789             data_ids.append(data_id)
--> 790             self._update_selected_data_items(viewer_item['id'], data_ids)
    791         else:
    792             raise ValueError(

~/Work/git/havok2063/jdaviz/jdaviz/app.py in _update_selected_data_items(self, viewer_id, selected_items)
   1117                                               viewer_id=viewer_id,
   1118                                               sender=self)
-> 1119             self.hub.broadcast(add_data_message)
   1120 
   1121         # Remove any deselected data objects from viewer

~/anaconda3/envs/havokve/lib/python3.8/site-packages/glue/core/hub.py in broadcast(self, message)
    213             logging.getLogger(__name__).info("Broadcasting %s", message)
    214             for subscriber, handler in self._find_handlers(message):
--> 215                 handler(message)
    216 
    217     def __getstate__(self):

~/Work/git/havok2063/jdaviz/jdaviz/configs/imviz/plugins/aper_phot_simple/aper_phot_simple.py in _on_viewer_data_changed(self, msg)
     52         # NOTE: Unlike other plugins, this does not check viewer ID because
     53         # Imviz allows photometry from any number of open image viewers.
---> 54         viewer = self.app.get_viewer_by_id(self._selected_viewer_id)
     55         self.dc_items = [lyr.layer.label for lyr in viewer.state.layers
     56                          if layer_is_image_data(lyr.layer)]

~/Work/git/havok2063/jdaviz/jdaviz/app.py in get_viewer_by_id(self, vid)
    409         This is useful when reference name is `None`.
    410         """
--> 411         return self._viewer_store[vid]
    412 
    413     def get_data_from_viewer(self, viewer_reference, data_label=None,

KeyError: 'imviz-0'
```

[🐱](https://jira.stsci.edu/browse/JDAT-2073)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to let `mastviz` use Imviz.

Fixes #1037

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Failure is unrelated, see #1039

**Review by havok2063 — APPROVED** [review]
This looks good to me.  Tested it out and it works with the display tabs hidden.  I also tested a custom `mycustomconfig` configuration name and that also loaded ok.

**Review by kecnry — APPROVED** [review]
LGTM.  Doesn't seem to affect any functionality in imviz (not that I would have expected anything to break since it seems to fallback on the current defaults if not overriding the configuration).  

There was temporarily some UI-code that read the config string to determine some layout options, but I think that has since all been removed.  In theory, supporting custom options for `configuration` could cause some issues if we ever do rely on that string though (or perhaps we just need a policy to NOT ever rely on the string because it can be customized).

**Comment by pllim** [comment]
Thanks for the reviews!

**Pull request merged**
