### PR TITLE
fix padding in logger overlay for non-dense top bar

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request fixes the padding in the logger overlay (introduced in #1352) to account for the increased size in the main app toolbar in specviz2d (changed when adding the mouseover information in #1608).

Before:
Screen Shot 2022-10-11 at 3 16 37 PM

After:
Screen Shot 2022-10-11 at 3 17 18 PM

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by bmorris3 — APPROVED** [review]
Looks good! It took me a while to see the difference in the before/after, so I'm glad we've got your eyes on the UI and not me 😅

**Comment by pllim** [comment]
I still don't see any difference. 😆

**Comment by bmorris3** [comment]
> I still don't see any difference. 😆

The reddish/orange line under the main app toolbar has moved downward ⬇️

**Comment by kecnry** [comment]
@rosteen - any changes you want to the changelog location for this (milestoned as a bugfix) before merge?

**Comment by kecnry** [comment]
> I still don't see any difference

I think the icon was offset as well and I just didn't capture that in the before screenshot.  I knew there was some place the toolbar height differences were hardcoded elsewhere when reviewing #1608, but couldn't remember where.... turns out it was this and hopefully not MAST.

**Comment by pllim** [comment]
Ah. I see it now. :shipit:

**Comment by rosteen** [comment]
> @rosteen - any changes you want to the changelog location for this (milestoned as a bugfix) before merge?

If you want to add the new section here feel free, but otherwise I can add it in another PR and move this entry there.

**Pull request merged**
