### PR TITLE
specviz2d/mosviz: matched mouseover markers

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request creates matched/linked mouseover markers between the 1d and 2d spectrum viewers in both specviz2d and mosviz, with the aim to make the possible non-linear mapping between the two viewers more obvious and intuitive feeling to users.  This also adds the corresponding wavelength in the mouseover coordinates info (in the top app bar) when mousing over the 2d spectrum viewer.

https://github.com/spacetelescope/jdaviz/assets/877591/ba8f6663-d393-434c-b675-df61c231f911

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Huh, I always thought the two viewer limits are linked. But if not, I guess this would be a nice improvement.

**Comment by bmorris3** [comment]
@pllim Matching viewer limits could help, but if there are gaps, as in the example notebook, there's still a non-intuitive mapping from one viewer's axis to the other:

https://github.com/spacetelescope/jdaviz/assets/3497584/5adea11b-6d46-4a2c-a92f-e8a99895b473

**Comment by kecnry** [comment]
They are, but one is in pixels and the other in wavelength and that is not guaranteed to be a linear mapping.  See #2219

**Review by bmorris3 — APPROVED** [review]
This is helpful! 

The only improvement we could consider (in another PR/in the future) is that we might want to consider how we arrange the mouseover info. If you hover on the 2D spectrum, you see:

Screen Shot 2023-11-27 at 12 33 00

and hovering on the 1D spectrum you see:

Screen Shot 2023-11-27 at 12 33 08

My very tiny gripe here is that 1D gets "flux" on the bottom row and 2D gets "Value" on the top row. If you try to compare the extracted 1D counts to the 2D spectrum's counts at the same wavelength, it's visually jarring to parse the difference in the mouseover info. Similarly, 2D gets "pixel" and 1D gets "cursor" – these have different meanings, but it might still take an extra second to reason through.

**Comment by pllim** [comment]
It is possible to have multiple spectra on the bottom viewer in Mosviz, right? Might also wanna check that out if that is the case.

**Comment by kecnry** [comment]
> It is possible to have multiple spectra on the bottom viewer in Mosviz, right? Might also wanna check that out if that is the case.

In specviz2d as well, that should be supported here without problem (and is the reason why the marker is just a vertical line rather than tracing the spectrum).

**Review by rosteen — APPROVED** [review]
I think this looks good. I don't love that the hover markers are the same color as the extracted spectra, but that's a conversation for another day. I also think I unearthed an unrelated bug, which I'll investigate and open another issue for (something to do with linking and model fitting not playing well together).

**Comment by kecnry** [comment]
woops missed that a test was failing because the marker count on the viewer increased.  Updating that test now and will merge as long as it doesn't require any major changes.

**Pull request merged**
