### PR TITLE
spectral-extraction: support floats when possible

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request allows floats (instead of enforcing integers) for all trace positions, widths, and separations.

### Blocked by

- [x] New specreduce release. See https://github.com/spacetelescope/jdaviz/pull/1652#issuecomment-1249353509

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge.

Bugfixes > Specviz2d:
Spectral-extraction plugin: support floats for all input trace positions, separations, and widths.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
The changes look reasonable but does existing test need to be updated to pass in some floating point values?

**Comment by kecnry** [comment]
> does existing test need to be updated to pass in some floating point values?

Good idea.  I updated one of the tests to pass a float.  I think the actually functionality of handling floats is the responsibility of specreduce, not jdaviz, but making sure the float traitlet sets without an error is worth having here.

**Review by pllim — APPROVED** [review]
LGTM. Thanks!

**Comment by pllim** [comment]
I cannot tell if this is a bug or just the test case needs updating.

```
>           raise ValueError("background regions overlapped")
E           ValueError: background regions overlapped
```

**Comment by kecnry** [comment]
Holding up on merging this until a new release of specreduce can be pinned here (tests pass locally for me on specreduce main, but not on 1.1.0, so seems like this requires https://github.com/astropy/specreduce/pull/125 in order to avoid a background overlap error when passing floats).

**Pull request merged**
