### PR TITLE
spectral-extraction: support import/export trace via glue-astronomy

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request extends on #1514 to add support for displaying traces as glue data objects (and therefore importing trace objects via `app.add_data`).  

This also supports flexible workflows where the background and extraction step reference different traces (including the case of offsetting an auto/kosmos trace within the app, or loading a custom trace from the API):

https://user-images.githubusercontent.com/877591/189728882-90cb90be-257c-4a9a-8813-dd56ef36454c.mov

[updated spectral extraction docs](https://jdaviz--1556.org.readthedocs.build/en/1556/specviz2d/plugins.html#spectral-extraction)

- [x] requires https://github.com/glue-viz/glue-astronomy/pull/72 being merged, released, and pinned here.
- [x] blocked by #1554 being merged, this rebased on top of that, and then re-implement support for extract_trace API

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
moved back to draft until can be rebased on top of #1554 and `export_trace(add_data=True)` API can be re-introduced here.

**Comment by rosteen** [comment]
Did the required `glue-astronomy` release happen yet?

**Comment by kecnry** [comment]
Yes, it was included in glue-astronomy 0.5.0, and #1587 pinned that for jdaviz before this PR got merged (so the pin no longer shows in the diff after rebase).

**Comment by rosteen** [comment]
One question so far from testing: in plot options, if you choose the trace layer for a trace that has been exported, you get the profile plot options. But changing the line width field doesn't change the trace line. Should you get the 2D image options here instead?

So far the import/export functionality looks ok, although I'm wondering if it's expected that exporting an `Auto` trace gets you an `ArrayTrace` rather than a `KosmosTrace` object? This drops any of the useful information like `window`, `guess`, etc.

**Comment by kecnry** [comment]
> if you choose the trace layer for a trace that has been exported, you get the profile plot options. But changing the line width field doesn't change the trace line. Should you get the 2D image options here instead?

hmm, good point.  The traces are being plotted with points instead of lines.  We could either change this or could hide the linewidth option for traces.  Anyone have preferences/opinions?

image

> I'm wondering if it's expected that exporting an Auto trace gets you an ArrayTrace rather than a KosmosTrace object? This drops any of the useful information like window, guess, etc.

Technically the data-object should be able to reproduce the input trace object.  Once applying an offset, the input parameters would no longer reproduce the trace and so are dropped (by glue-astronomy).  For the case of an offset of zero, we could probably expose the original object... but then is that confusing that the type changes based on whether the offset is exactly zero?

**Comment by rosteen** [comment]
I think either option for the trace styling (changing it to a line or just hiding line width) would be fine. Did you happen to implement either since the last time I looked at this PR? (I guess I'll see in a moment when I update my local branch and test)

**Comment by rosteen** [comment]
```
a = KosmosTrace(specviz2d.app.data_collection[0].get_object(statistic=None).flux, bins=25, window=7)
specviz2d.app.add_data(a, data_label = "test trace")
```

If I plot the Glue data object that is created from this, it looks like a straight line (the gray line below), but the extraction still seems to work properly. I seem to remember talking about this before but can't remember the resolution, and it still bothers me. Also, if I export the imported trace and then plot _that_ Glue data object, it looks like the trace I expect. Is there a way to get the imported trace to plot properly?

Screen Shot 2022-09-21 at 4 19 52 PM

**Comment by kecnry** [comment]
@rosteen - I fixed the linking in the case of loading a trace directly from specreduce (rather than an object output from the plugin) and also hide the line width option as the traces are currently plotted as a scatter type with markers instead of lines.

**Comment by rosteen** [comment]
That fixed the problem I was seeing, thanks. I think the last objection I have is that we've been trying to move away from making users access the app-level methods, in favor of helper methods and such, so I'm hesitant to say in the docs that `specviz2d.app.add_data()` is the way to load traces from the notebook. Maybe a simple `load_trace` wrapper around that in the helper would be reasonable?

**Review by rosteen — APPROVED** [review]
Thanks for addressing all of my comments, looks good to me now.

**Comment by camipacifici** [comment]
The workflow of creating and using different traces is nice and I find it intuitive.

Got a traceback with the following workflow: (not sure it is in scope with this PR or needs a new issue)
- in notebook show GUI + spectral extraction plugin
- create and export 2 flat traces (named trace and traceoffset)
- keep one of them selected under "Trace"
- in the notebook, call `sp_ext = specviz2d.app.get_tray_item_from_name('spectral-extraction')` and `trace = sp_ext.export_trace()`
- `trace` is an `ArrayTrace` [it would be nice if it carried the name I gave it in the plugin]
- now i do `sp_ext.import_trace(trace)` and I hit the following traceback
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In [19], line 1
----> 1 sp_ext.import_trace(trace)

File ~/opt/miniconda3/envs/pr1556/lib/python3.10/site-packages/jdaviz/configs/specviz2d/plugins/spectral_extraction/spectral_extraction.py:504, in SpectralExtraction.import_trace(self, trace)
    502     self.trace_bins = trace.bins
    503 else:  # pragma: no cover
--> 504     raise NotImplementedError(f"trace of type {trace.__class__.__name__} not supported")

NotImplementedError: trace of type ArrayTrace not supported

- `specviz2d.load_trace(trace, data_label='my trace')` works

**Comment by kecnry** [comment]
@camipacifici - I was able to "fix" some of that:
* offsetting a `FlatTrace` now gives another `FlatTrace`, which can be imported back into the plugin
* offsetting a `KosmosTrace` still must give an `ArrayTrace`, which still cannot be imported into the plugin.  This would require upstream changes to specreduce (and I'm not convinced that is something we would want in specreduce).
* when trying to import an `ArrayTrace` into the plugin, the error message now suggests loading directly with `viz.load_trace`.  

The reason an `ArrayTrace` cannot be imported into the plugin is because it only contains the array itself, which is not something that can be modified in the plugin.  An alternative option would be for `sp_ext.load_trace(ArrayTrace(...))` to use `viz.load_trace` and then automatically select that same entry, but that would require some automatic labeling logic.  @javerbukh - how would this play with your #1672?  Could we generate the label before calling `load_trace` so we then know in the plugin what label to select from the dropdown?

**Comment by javerbukh** [comment]
Using that PR, you should be able to call `app.return_data_label(<trace object>)` before calling `viz.load_trace` to get the automated data label. That is, unless `viz.load_trace` allows the user to use a custom data label.

**Comment by kecnry** [comment]
@javerbukh - thanks!  I'll look into that if your PR gets in first.  Otherwise we can do that as a follow-up effort and raising the error will hopefully be sufficient until then (or we can block this PR until that can be added if anyone feels it needs to be there).

**Review by camipacifici — APPROVED** [review]
Thank you for addressing that error. Looks good to me.

**Pull request merged**
