### PR TITLE
FEAT: Annulus draw tool for Imviz

### LINKED ISSUE #2191: Drag and draw annulus with hardcoded width
**Reporter:** pllim

As proposed by @kecnry , here is the desired workflow:

1. User select new shape tool from the existing shapes drop-down.
2. User click and drag to draw. At this point, it is basically the circle draw tool.
3. When finalized, this tool magically creates an annulus shape with hardcoded width (proposed: `inner_radius = outer_radius * 0.5`).
4. To modify the annulus shape, user has to edit it manually in the Subset Tools plugin.

New features to be implemented:

a. A new shape tool that subclass the circular shape but then turns it into annulus when finalized.
b. Subset Tools plugin needs special logic so that user can edit only the following for annulus (which is a very special case of compound subset): One center, inner radius, outer radius. @javerbukh proposed maybe we can subclass subset state or attach metadata to the state.

Under the hood:

```
Annulus subset state
|___ ROI state --> CircularROI
|___ Invert state --> ROI state --> Circular ROI
```
where
```pyhon
subset_state.state1.roi.xc == subset_state.state2.state1.roi.xc
```
and
```python
subset_state.state1.roi.yc == subset_state.state2.state1.roi.yc
```
and
```python
subset_state.state1.roi.radius > subset_state.state2.state1.roi.radius
```

Also see https://github.com/glue-viz/glue-astronomy/blob/336e2cca4a93025e34e4a0d4313b4031f2f794dc/glue_astronomy/translators/regions.py#L52

This needs new glue-astronomy release upstream (>0.7).

[🐱](https://jira.stsci.edu/browse/JDAT-3379)

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### LINKED ISSUE #2241: BUG: Ellipse translation in app.get_subsets() is wrong
https://github.com/spacetelescope/jdaviz/blob/7ffaa2691bb4cfd4efaece83177b1f171463579f/jdaviz/app.py#L1009

is wrong because `glue` defines *radius* while `regions` defines *width and height*. Really, we should be using the translators already vetted and in place here: https://github.com/glue-viz/glue-astronomy/blob/main/glue_astronomy/translators/regions.py

The complication is that to use the upstream translator directly the way we do the translation in this method, we also need to modify upstream.

I already have the fixes but I open an issue anyway so users are aware, because this bug is very subtle. Fixes here:

* https://github.com/glue-viz/glue-astronomy/pull/93
* https://github.com/spacetelescope/jdaviz/pull/2240

[🐱](https://jira.stsci.edu/browse/JDAT-3480)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to build on https://github.com/glue-viz/glue-jupyter/pull/356 and https://github.com/glue-viz/glue-astronomy/pull/93 to add an annulus draw tool in Imviz. All the features available for other shapes should also be applicable here (e.g., recentering, editing, drag to move).

| Light mode | Dark mode |
| --- | --- |
| Screenshot 2023-06-21 131737 | Screenshot 2023-06-21 130843 |

Ignore the icon below (see new icons above):

Screenshot 2023-06-06 135858

```python
>>> imviz.get_interactive_regions()
{'Subset 1': <CircleAnnulusPixelRegion(
    center=PixCoord(x=1132.8839679560447, y=1882.707397411802),
    inner_radius=75.0, outer_radius=97.3707275390625)>}
```

* Fixes #2191 
* Fixes #2241

### TODO

- [x] Add tests.
- [x] Update package pins.
    - `glue-core` pin is being updated over at #2201 , so depending on the order of merge, we might or might not need it here.
    - Cannot update `glue-jupyter` pin until https://github.com/glue-viz/glue-jupyter/pull/356 is merged and released.
    - Cannot update `glue-astronomy` pin until https://github.com/glue-viz/glue-astronomy/pull/93 is merged and released.
- [x] Need to fix icon. 😿 (Thanks, @Jenneh !)

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by rosteen** [comment]
I just opened https://github.com/pllim/jdaviz/pull/11 to fix the issue mentioned above.

**Comment by camipacifici** [comment]
Found a couple of probably unrelated bugs that I will report elsewhere.
The annulus works great! The recenter in plot option is kind of useless though. It uses the center of mass in the annulus (as expected), but it is not the behavior a user would need here. Maybe better to disable recenter for annulus?

**Comment by camipacifici** [comment]
An upgrade could be the ability to recenter based on the center of another subset ;)

**Comment by pllim** [comment]
@camipacifici , I disabled recentering for annulus now. I'd rather not do any significant upgrades until we figure out https://github.com/spacetelescope/jdaviz/issues/2238 .

Thanks for the reviews, everyone! If this looks good now, please approve.

**Review by rosteen — APPROVED** [review]
Looks good to me now! Thanks.

**Review by javerbukh — APPROVED** [review]
Looks good!

**Pull request merged**
