### PR TITLE
DO NOT MERGE: Debug pytest 8 compatibility (rc_testing)

### LINKED ISSUE #2643: Test suite will fail when pytest 8.0 is released
As the Windows job in `rc-testing` shows. Asked over at https://github.com/pytest-dev/pytest/issues/9765#issuecomment-1874511717

Example log: https://github.com/spacetelescope/jdaviz/actions/runs/7383949691/job/20085994919

[🐱](https://jira.stsci.edu/browse/JDAT-4095)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address https://github.com/pytest-dev/pytest/issues/9765#issuecomment-1879527433

Fixes #2643

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by lesteve** [comment]
Naively, it looks like your root `conftest.py` does not seem to be loaded somehow on Windows? You could try `pytest --trace-config` that would give some information.

**Comment by pllim** [comment]
@lesteve , I added a `pytest --trace-config` but I am not sure what I should be looking for.

https://github.com/spacetelescope/jdaviz/actions/runs/7466468232/job/20317888491?pr=2654

**Comment by lesteve** [comment]
Sorry you should add `--trace-config` to the `pytest` command that runs your test, not run `pytest --trace-config` on its own.

This in principle gives you information about which conftest.py are loaded, so grep `conftest.py` in it and double-check whether your `conftest.py` defining the fixtures is indeed loaded.

**Comment by pllim** [comment]
Hmm it says 

`PLUGIN registered: <module 'jdaviz.conftest' from 'D:\\a\\jdaviz\\jdaviz\\.tox\\py310-test-predeps\\lib\\site-packages\\jdaviz\\conftest.py'>`

Is it not supposed to be this file? https://github.com/spacetelescope/jdaviz/blob/main/jdaviz/conftest.py

**Comment by pllim** [comment]
Huh, @lesteve , the error goes away when I upgrade from Python 3.10 to Python 3.11 for the Windows job. Does this make sense to you?

**Comment by pllim** [comment]
Anyways, I switch to Python 3.11 on main. Moving on. Thanks for your help!

**Comment by lesteve** [comment]
> Huh, @lesteve , the error goes away when I upgrade from Python 3.10 to Python 3.11 for the Windows job. Does this make sense to you?

It does not, but yeah Scipy reported that the issue for them only happens with Python 3.9 and Python 3.10 indeed.

**Comment by lesteve** [comment]
Just to make sure the Pytest PR https://github.com/pytest-dev/pytest/pull/11708 does not break something unexpectedly, would you mind trying with Python 3.11 and your debug branch?

**Comment by pllim** [comment]
> would you mind trying with Python 3.11 and your debug branch?

I think I did in the last run of this PR. See https://github.com/spacetelescope/jdaviz/actions/runs/7467463759/job/20321031619?pr=2654

**Comment by lesteve** [comment]
OK great, I missed that indeed. This is good to know that the Pytest PR did not break something unexpectedly.

**Pull request closed without merging**
