### PR TITLE
Implement Specviz2d configuration

### PR DESCRIPTION
**Pull request by rosteen**
Creates a Specviz2d configuration that pulls out just the spectrum viewers from Mosviz. You can start up the app in the usual way, and load either a 2D spectrum file, a 1D spectrum file, or both. In the first case, the 2D spectrum is summed along the non-dispersion axis to create a rough "quick-look" 1D spectrum. The axes of the two viewers are linked as in Mosviz. 

This example assumes that there's a list of corresponding 2D and 1D spectra filenames in `spectra_2d` and `spectra_1d`:
```
sv = Specviz2d()
sv.app

# Load only 2D spectrum
sv.load_data(spectrum_2d = spectra_2d[2], spectrum_2d_label="test 2D")
# Load both
sv.load_data(spectrum_2d = spectra_2d[2], spectrum_2d_label="test 2D", spectrum_1d = spectra_1d[2], spectrum_1d_label = "test 1D")
```

Note that this currently attaches meters to the spectral axis, since in the s2d file I was looking at the `CUNIT3` value (microns) didn't seem to match the values in the `WAVSTART` and `WAVEND` keywords (e.g. 1.66E-06), which I used to create the spectral axis for the quicklook 1D spectrum when collapsing the 2D spectrum. I also currently have the flux as unitless, since I don't fully grasp how to go from "DN/s" units in the 2D spectrum to e.g. Jy in the 1D spectrum (I imagine this involves using the `PHOTMJSR` and `PIXAR_SR` header keywords).

### CODE REVIEW

**Comment by rosteen** [comment]
I expect that this will need a little more work, but moving to ready for review to get another pair of eyes on it in case there's something major I haven't noticed. Biggest thing on my radar is improving the creation of the spectral axis in the case that the 1D spectrum needs to be created by collapsing a 2D input.

**Review by javerbukh — APPROVED** [review]
Looks good! The only comment I will make is that data does not load automatically when the 
`sv.load_data(spectrum_2d = spectra_2d, spectrum_2d_label="test 2D")`
line is run, but otherwise this works great!

Screen Shot 2021-01-27 at 9 57 53 AM

**Comment by havok2063** [comment]
For the test JWST data I'm using, it doesn't load.  I get the following error: `ValueError: No celestial axes found in WCS`.  I suspect you might need to fold in https://github.com/spacetelescope/jdaviz/pull/377.  When I switch to your original test data, it works but the default data does not display automatically.  The data loads but to display I need to manually select the data in each viewer.  

For the case where the input is only a 2d spectrum file, is it possible to overlay a (toggle-able) line indicating the row the 1d spectrum was extracted from?  For the case where both files are input, I'm not sure if there is something similar that can be done regarding overlaying an extraction boundary?

**Review by havok2063 — COMMENTED** [review]
See previous comment regarding file loading issues and line overlays.

**Comment by rosteen** [comment]
It seemed like there was still ongoing discussion about how exactly the issue behind #377 is going to be resolved, so I decided to hold off on basing this on that branch. If it makes more sense to do that so we can test on the most up to date data I can do that, I was just planning to wait to finalize this until there's a definitive resolution for the WCS error. 

In regards to the line overlay, I'm not extracting based on a particular row, I'm summing over the non-dispersion axis. Do you think it would be reasonable/advisable to throw a warning snackbar message up in the case of only loading a 2D spectrum telling the user that they should definitely not trust the "quicklook" 1D spectrum for any science, and that they should use a proper extraction for any real work?

I'll update to automatically display the loaded data in the viewers, that slipped off my to-do list.

**Comment by havok2063** [comment]
Re: the line overlay, I think it's reasonable to display a snackbar message indicating that's a simple quicklook and shouldn't be used for science.  Is there any other way to indicate on the 2d image what has been extracted?  

I think it's fine to test and continue to use the "working" data for now, which comes from the calibration pipeline version 0.16.1, but the newer data should start to take precedence at some point.  MAST work is being done with data from 0.17.1.  We're beginning to hit up against some boundaries where ongoing MAST work being completed depends on several jdaviz/specutils work items getting finished and merged, plus bug fixes on the JWST pipeline side.  It might be worth spec-ing out a roadmap.

**Comment by ibusko** [comment]
What would be a good file to test this? I get header keyword errors when using 0.16.1

**Comment by havok2063** [comment]
The only files that work for me are the original ones y'all used for developing MosViz, the ones in the Box folder zip file `mosviz_nirspec_data_0.3`.   It was a link originally shared amongst the jdaviz team a while back, I don't remember the link unfortunately.  Those files have a CAL_VER of `0.16.1.dev4+gf949d57f`  which maybe aren't from the final build for 0.16.1?

**Comment by ibusko** [comment]
I got it working with older files from `mosviz_nirspec_data_0.3`. So, yes, it seems that these are not from the same 0.16.1 version in `test_data`.

**Review by ibusko — APPROVED** [review]
LGTM

**Comment by duytnguyendtn** [comment]
Does anyone know why the RTD build is failing here?

**Comment by pllim** [comment]
Have you rebased against the `master` branch lately?

**Comment by rosteen** [comment]
Rebased, looks like all the tests are passing now.

**Comment by javerbukh** [comment]
Merging.

**Pull request merged**
