### PR TITLE
Add Specviz plugins to Cubeviz and Mosviz

### PR DESCRIPTION
**Pull request by rosteen**
Adds Specviz plugins to the other configs, to operate on the data in their 1D spectrum viewers. Also updates the Mosviz config to use the `specviz-profile-viewer` for its 1D viewer, to enable all the associated functionality.

### CODE REVIEW

**Comment by rosteen** [comment]
I think this test failure is unrelated, since I'm seeing it on another branch as well. Anyone have bandwidth to look into it? (@dtn5ah @javerbukh)

**Review by javerbukh — APPROVED** [review]
Seems like unit conversion works well with cubeviz, but when I do it in mosviz, I cannot tell if the flux axis is actually being updated or not, since I cannot see the numbers. The spectral axis does look like it is being updated so I assume both axes work, although I will leave the final answer up to a PO or scientist.

**Comment by rosteen** [comment]
Looks like the most recent CI run failed due to an internet glitch, I'm going to try pushing again so they will rerun, since I fixed the test that was failing before. I'd like to see it succeed...

**Comment by rosteen** [comment]
Tests passing now! We have two approvals, but I would really like a PO eye on this one I think. I'll mention it offline at the review meeting today.

**Review by eteq — APPROVED** [review]
This looks good to me!  One concern to raise is that we don't really have a way to have `pytest` test that this functionality is working as expected.  But there's a whole can of worms there, so that doesn't need to hold up this PR unless there's an immediately obvious way to do that.

**Pull request merged**
