### PR TITLE
DOC: Update glue-core intersphinx

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to get us out of a *sticky* situation.

Close #2380

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
@astrofrog , two warnings left related to linking to specific sections instead of intersphinx. How best to resolve these?

```
docs/dev/ui_description.rst:271: WARNING: undefined label: 'glue:state-viewer'
docs/imviz/import_data.rst:13: WARNING: undefined label: 'glue:linking-framework'
```

**Comment by astrofrog** [comment]
Change :glue: to :glue-qt: and add the glue-qt line from the glue-jupyter intersphinx config.

To be clear this doesn't mean you need to add glue-st as a dependency. In future those links will change to :glue: again once I move those docs sections to glue-core but for now all the glue docs live at docs.glueviz.org

You also don't have to call that intersphinx entry glue-qt you could call it glueviz instead and then use :glueviz:

**Comment by astrofrog** [comment]
@pllim - in glue-jupyter I am renaming glue-qt to glueviz to avoid confusion, you could use the same terminology here and use `:glueviz:`

**Comment by pllim** [comment]
Thanks! RTD is green now, though would be nice to be able to link to stable doc instead of latest down the road.

**Review by astrofrog — APPROVED** [review]

**Pull request merged**
