### PR TITLE
Change RA/Dec significant figures from 4 to 6 in aperture photometry plugin

### PR DESCRIPTION
**Pull request by camipacifici**
### Description

This addresses the issue of not having enough significant figures in the coordinates in the aperture photometry plugin.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by kecnry — APPROVED** [review]
Works for me, thanks!  (Just needs a changelog entry and CI to finish running/pass)

**Review by bmorris3 — APPROVED** [review]
This looks good. I'm curious though if it makes more sense to display centroids in sexigesimal? Six digits is quite a lot of numbers to read.

**Comment by camipacifici** [comment]
Thank you!

I believe we discussed this at some point and degrees are fine. They just needed enough significant figures.

**Comment by pllim** [comment]
LGTM. Thanks!

**Pull request merged**
