### PR TITLE
TST: Fix test header for CI, add more info

### PR DESCRIPTION
**Pull request by pllim**
Fix test header for CI. Also add more info.

This is part of #476 that deals with test header. Close #628.

# Python 3.8 with coverage checking, all deps, and remote data

## Before this patch

```
============================= test session starts ==============================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py38-test-alldeps-cov/.pytest_cache

Running tests with Astropy version 4.2.1.
Running tests in jdaviz docs.

Date: 2021-04-28T20:52:17

Platform: Linux-5.4.0-1046-azure-x86_64-with-glibc2.2.5

Executable: /home/runner/work/jdaviz/jdaviz/.tox/py38-test-alldeps-cov/bin/python

Full Python Version: 
3.8.9 (default, Apr  8 2021, 12:01:33) 
[GCC 9.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.20.2
Scipy: 1.6.3
Matplotlib: 3.4.1
h5py: 3.2.1
Pandas: 1.2.4

Using Astropy options: remote_data: any.
```

## With this patch

```
============================= test session starts ==============================
platform linux -- Python 3.8.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
cachedir: .tox/py38-test-alldeps-cov/.pytest_cache

Running tests with jdaviz version 1.2.dev104+g9c7b696.
Running tests in jdaviz docs.

Date: 2021-04-29T21:15:43

Platform: Linux-5.4.0-1046-azure-x86_64-with-glibc2.2.5

Executable: /home/runner/work/jdaviz/jdaviz/.tox/py38-test-alldeps-cov/bin/python

Full Python Version: 
3.8.9 (default, Apr  8 2021, 12:01:33) 
[GCC 9.3.0]

encodings: sys: utf-8, locale: UTF-8, filesystem: utf-8
byteorder: little
float info: dig: 15, mant_dig: 15

Package versions: 
Numpy: 1.20.2
Scipy: 1.6.3
Matplotlib: 3.4.1
h5py: 3.2.1
Pandas: 1.2.4
astropy: 4.2.1
pyyaml: 5.4.1
specutils: 1.2
spectral-cube: 0.5.0
asteval: 0.9.23
click: 7.1.2
echo: 0.5
idna: 2.10
traitlets: 5.0.5
bqplot: 0.12.26
bqplot-image-gl: 1.3.2
glue-core: 1.0.1
glue-jupyter: 0.4
glue-astronomy: 0.1
ipyvue: 1.5.0
ipyvuetify: 1.6.2
ipysplitpanes: 0.2.0
ipygoldenlayout: 0.4.0
voila: 0.2.10
vispy: 0.6.6
gwcs: 0.16.1
asdf: 2.7.3
jwst: 1.1.0

Using Astropy options: remote_data: any.
```

### CODE REVIEW

**Comment by pllim** [comment]
Hmm... why the tox path changed? Investigating.

**Comment by pllim** [comment]
What a mess. I'll have to think about this.

**Comment by pllim** [comment]
Thanks to @mcara , the `tox` path problem is solved. This is now ready for final review.

**Review by duytnguyendtn — APPROVED** [review]
Definitely appreciate showing the Jdaviz version and more of the underlying packages, so I'll approve, but I noticed the pytest configure requires you to spell out each package by name. I'm concerned for when we add other packages that we'll remember to come in and add it here. As well as what happens if we no longer require one of these packages, will the test gracefully skip the header, or will it fail? Is there a way to automatically just print out the entire stack without having to specify each module manually @pllim?

**Comment by pllim** [comment]
> I'm concerned for when we add other packages that we'll remember to come in and add it here.

The concern is real. Though if you forget, the worst thing that happens is the log does not report the new dependency's version when you want to check for it. In that case, you would open a PR to add it to the list, and then rebase your other PR to show it.

> what happens if we no longer require one of these packages, will the test gracefully skip the header, or will it fail?

Depends. If this dependency is pulled in anyway by another dependency, it will be there and still reported. If it no longer exists in the test env, then it will be reported as missing. I don't think anything will crash. I can easily test this theory in a separate PR.

> Is there a way to automatically just print out the entire stack without having to specify each module manually

AFAIK, no. There were discussions at astropy/pytest-astropy-header#18 but no consensus. It is not an easy problem to solve, as each package's needs are different.

**Review by javerbukh — APPROVED** [review]
Looks good! I appreciate you testing Duy's concerns in the other PR.

**Pull request merged**
