### PR TITLE
Cubeviz prototype

### PR DESCRIPTION
**Pull request by nmearl**
This PR includes the cubeviz prototype. It does this in a bit of haphazard way by including new viewers that listen for particular data loading events. These viewers are specific to the test manager dataset and therefore will to be generalized in the future. There are still some standing issues with the layouting in the notebook case. Otherwise, this fills the criteria of providing a cubeviz prototype.

### CODE REVIEW

**Comment by astrofrog** [comment]
I can review this tomorrow!

**Comment by astrofrog** [comment]
@nmearl - I pushed two quick fixes, one which was a mistake I made before of not including the template notebooks in the package data, and the other was to make the jdaviz CLI pick up your new template.

**Comment by nmearl** [comment]
@astrofrog The getting stuck is some issue with Maarten's approach to the voila-vuetify template (which is what the nbconvert template included here is modeled after) implementation. I mentioned it to him in slack, and he said he'd take a look, but I haven't followed up. If you keep refreshing, or restarting the voila instance, it will eventually go through. I've never experienced the problem when using the default voila template.

Start-up time has always varied a lot for me as well -- sometimes fine, sometimes slow. Are you seeing the same thing when you just use the default voila template?

**Comment by astrofrog** [comment]
@nmearl - the default template starts up immediately. However I'm having issues with getting the viewers to show with that template.

**Comment by nmearl** [comment]
@astrofrog I think this is a characteristic of using Vue in the front-end template. It references external library files that have to get loaded every the page is loaded (e.g. it pulls down its own Vue and Vuetify js files from CDN). The way forward would be to either store the files locally, or implement a bare-bones _regular_ nbconvert template instead (though we lose the fancy animations and stuff).

**Comment by astrofrog** [comment]
This is looking great! I'm still finding that with Chrome I have to refresh several times to get past the 'Executing cell 1 of 1'. Things work better with Firefox. I wonder whether there is some sort of race condition going on when fetching the Vue JS as you mentioned?

A couple of minor things:

* I don't know if we want to show 'Executing cell ? of ?' since users don't necessarily even need to know there is a notebook behind the scenes. Maybe this is something for the JS console log instead?

* I noticed a small message at the bottom of the window when loading:

Screenshot 2019-11-20 at 16 02 24

Other than that, is this ready for a code review? I don't think there's going to be much to say there but I noticed a stray debug print statement. I can look at the code more closely if everything is otherwise ready to go.

**Pull request merged**
