### PR TITLE
Move plugins to tray area

### LINKED ISSUE #102: Change to showing plugins in sidebar instead of modal dialog
The current plugins pop up as modal dialogs.  Following some user testing and input from @jenneh the thinking is that a sidebar with fold-out panels for plugins is the preferred way to go.  So this issue is to implement that.

Some specific constraints:

* The plugins should be "acoordian-able" so that the user only sees those they have opened up
* The plugin pane should be hide-able
* bonus/could be in later PR: the plugin pane should be tear-off-able, or at least movable
* bonus/could be in later PR: the plugins in the pane should be re-orderable

One other bit of user feedback: having *lots* of panes that organize the plugins via some complicated scheme is an anti-feature, so we should avoid that.

### PR DESCRIPTION
**Pull request by nmearl**
Resolves #102. This PR moves the plugins from modal popups to accordion tray items as shown below.

Screen Shot 2020-05-05 at 12 32 52 PM

### CODE REVIEW

**Comment by javerbukh** [comment]
@nmearl After I pulled this down I had to go and get the latest developer versions of both glue-jupyter and glue (which I probably should've done already). Once that was done, it worked! I think the accordion tray on the right is the better approach as far as UI goes. 

I did run into an issue where after I had applied gaussian smooth, I received a notification of the new smoothed file, however when I tried to use the collapse plugin I did not receive any notification after pressing `apply`. I then released it was because I was trying to do it on an IVAR type and then MASK type, but I still think there should be some notification such as "cannot do [plugin name] on data of type IVAR/MASK/etc." This may be common knowledge to a scientist using this tool but I think there should be some kind of feedback anytime a person presses the `apply` button.

Overall though I think this is a great direction for the UI! Nice work!

**Comment by nmearl** [comment]
@javerbukh I've pushed up some changes that attempt to catch bad operations and show failures in error snackbar messages -- can you give this another go?

**Comment by javerbukh** [comment]
@nmearl Much better! I did notice though that successful operations under Collapse show up as grey bars, as opposed to the green ones for Gaussian operations. Unsuccessful Collapse operations show up as red, so that's good.

**Comment by rosteen** [comment]
Looking pretty good, I have one UI concern and one glue-jupyter error that I'm seeing (I think my underlying packages are all up to date with the dev repos). 

- With both plugins open in the tray, one can't get to the `apply` button in the collapse plugin because there's no scroll bar within the tray. Right now this can be solved by just closing the gaussian smooth plugin, but I think we need to be able to scroll here for the future when there are more plugins or more complicated plugins that overflow the available space. Having more limited space is certainly a downside of the transition from modal dialogue to accordion tray (I'm thinking of the model fitting plugin especially).

- It looks like the "data loaded successfully" snackbar (which I love, btw) is causing an error in glue-jupyter. Pretty sure my package dependencies are up to date, I tried in a clean env and got the same thing:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/opt/anaconda3/envs/viz_dev2/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/opt/anaconda3/envs/viz_dev2/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/projects/glue-jupyter/glue_jupyter/state_traitlets_helpers.py in update_state_from_json(self, json, widget)
    149         self._block_on_state_change = True
    150         try:
--> 151             update_state_from_dict(state, json)
    152         finally:
    153             self._block_on_state_change = False

~/projects/glue-jupyter/glue_jupyter/state_traitlets_helpers.py in update_state_from_dict(state, changes)
     56 
     57                 for k in callback_dict:
---> 58                     if k in changes[name]:
     59                         if isinstance(callback_dict[k], State):
     60                             update_state_from_dict(callback_dict[k], changes[name][k])

TypeError: argument of type 'bool' is not iterable
```

**Comment by rosteen** [comment]
Oh, and I should have noted above that the error I'm seeing isn't fatal/doesn't seem to interfere with using the app at all, I can continue working normally.

**Comment by nmearl** [comment]
@rosteen I've fixed the overflow issue (the down side of having a large monitor while development 😁 )

> It looks like the "data loaded successfully" snackbar (which I love, btw) is causing an error in glue-jupyter. Pretty sure my package dependencies are up to date, I tried in a clean env and got the same thing:

I'm not seeing this locally, can you manually update your `glue` and `glue-jupyter` installs?

```python
pip install git+https://github.com/glue-viz/glue --upgrade
pip install git+https://github.com/glue-viz/glue-jupyter --upgrade
```

**Comment by rosteen** [comment]
I double checked and I was indeed up to date on those packages, still seeing the errors. The scroll bar in the plugin tray looks good.

Also, seconding this comment from @javerbukh, it looks to me like a green success snackbar flashes momentarily and is then replaced by a second gray one. Perhaps the snackbar is getting triggered twice somehow in the `Collapse` case.

> @nmearl Much better! I did notice though that successful operations under Collapse show up as grey bars, as opposed to the green ones for Gaussian operations. Unsuccessful Collapse operations show up as red, so that's good.

**Comment by nmearl** [comment]
@rosteen Can you give it a try now?

> Also, seconding this comment from @javerbukh, it looks to me like a green success snackbar flashes momentarily and is then replaced by a second gray one. Perhaps the snackbar is getting triggered twice somehow in the Collapse case.

Huh, I didn't take his comment to mean that multiple snackbars were trying to get rendered. Just to confirm, you're seeing a snackbar that's grey initially, and then a green one replaces it with the same exact text?

**Comment by rosteen** [comment]
> Huh, I didn't take his comment to mean that multiple snackbars were trying to get rendered. Just to confirm, you're seeing a snackbar that's grey initially, and then a green one replaces it with the same exact text?

I thought that's what I was seeing, but it was fast enough I'm not sure it was the same text. Maybe my browser is slow and it was just showing the previous snackbar for a split second before rendering the new one? Either way I don't see happening after the last commit. The other error I was seeing is fixed as well.

**Pull request merged**
