### PR TITLE
unpin tox < 4

### LINKED ISSUE #1903: TST: Unpin "tox<4" when we can
Revert #1901 when we can. Blocked by:

* https://github.com/tox-dev/tox/issues/2612

### PR DESCRIPTION
**Pull request by kecnry**
This reverts commit f36f3b2cca7d1f91eafb7220c4c4835af48e0a17.

### Description

This pull request reverts #1901 

Fixes #1903

### CODE REVIEW

**Comment by pllim** [comment]
Interesting... I thought I would have to wait longer based on all the stuff astropy is seeing.

**Review by pllim — APPROVED** [review]
If CI is green, I don't see why not. Thanks for following up!

**Comment by bmorris3** [comment]
So speedy! 🚀

**Comment by jamesgilmorelyst** [comment]
You might want to be careful here, we have been experiencing similar issues an v4.0.11 worked for us, but not the latest 4.1.3 of tox. So issue might start to occur again!

**Pull request merged**
