### PR TITLE
Adds accessor for the 3D fit parameters in CubeViz

### PR DESCRIPTION
**Pull request by ibusko**
This implements the second simplest solution as proposed in https://github.com/spacetelescope/jdaviz/issues/241 : a raw attribute in the helper, but with individual parameters accessed by name . 

This makes the 3D fitter usable in a notebook.

The `Cube_fit` notebook in the concepts directory exercises this functionality.

### CODE REVIEW

**Comment by PatrickOgle** [comment]
Tried again to fit a small subset with a Constant plus Gaussian, but get a different error on the model fitting,
which doesn't deliver a data product:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/miniconda3/envs/jdaviz16/lib/python3.8/site-packages/ipyvue/VueTemplateWidget.py in _handle_event(self, _, content, buffers)
     48             event = content.get("event", "")
     49             data = content.get("data", {})
---> 50             getattr(self, 'vue_' + event)(data)
     51 
     52 

~/Desktop/jdat/jdaviz/jdaviz/configs/default/plugins/model_fitting/model_fitting.py in vue_model_fitting(self, *args, **kwargs)
    323 
    324         # Update component model parameters with fitted values
--> 325         self._update_parameters_from_fit()
    326 
    327         self.save_enabled = True

~/Desktop/jdat/jdaviz/jdaviz/configs/default/plugins/model_fitting/model_fitting.py in _update_parameters_from_fit(self)
    132             name = m["id"]
    133             if len(self.component_models) > 1:
--> 134                 m_fit = self._fitted_model[name]
    135             else:
    136                 m_fit = self._fitted_model

TypeError: 'QuantityModel' object is not subscriptable

**Comment by rosteen** [comment]
I just fixed the compound model bug in https://github.com/spacetelescope/jdaviz/pull/276 - that was something that was discussed in passing earlier in the year and fell off the radar, glad you mentioned it so I could fix it before release.

**Review by PatrickOgle — APPROVED** [review]
Accessor successfully returns a dictionary of 2D image arrays with associated units, one for each fit parameter.  The models are currently misfit, because the model fitting machinery does not reference the collapse method, but this is being fixed in another PR.

**Review by rosteen — APPROVED** [review]
Looks good to me, I was able to retrieve the fitted parameter arrays with the `fitted3d` property.

**Pull request merged**
