### PR TITLE
MNT: Bump bqplot minversion to 0.12.29

### LINKED ISSUE #327: Jupyter Lab JDAViz/Specviz Compatibility
There seems to be a lack of documentation on running `JDAViz` and `specviz` from within a Jupyter Lab environment. 
- With the basic installation of jupyter lab, the widget fails to load after:
```python
from jdaviz import SpecViz
specviz = SpecViz()
specviz.app
```

- After installing the jupyter lab extensions suggested by [glue-jupyter here](https://glue-jupyter.readthedocs.io/en/latest/installing.html#jupyter-lab), a strangely formatted widget does appear (see attached screenshot).
Screen Shot 2020-10-06 at 5 01 31 PM

### LINKED ISSUE #661: plots do not appear in jupyter lab
On the latest `main`, if I make a fresh install by making a new venv and then doing `pip install -e .` in the source directory, jdaviz loads just fine and yields in `jupyter notebook` *or* `voila`, yields:
image
whiche is just what it should.  However, in the same environment, jupyter lab yields:
image

which is missing the plot...

### PR DESCRIPTION
**Pull request by pllim**
Bump bqplot minversion to 0.12.29 for Jupyter Lab support. cc @maartenbreddels

Fix #327 
Fix #661

### CODE REVIEW

**Review by rosteen — APPROVED** [review]
Doesn't seem to break anything, but I'm having trouble with Jupyter Lab so I can't currently confirm that this fixes those issues. Approving, but I'd like someone to get it working in Lab...

**Review by ojustino — APPROVED** [review]
I added myself as a reviewer to report that Specviz seems to work as intended when I run it in Jupyter Lab... but I also never experienced issue #661 even while using version 0.12.27 of `bqplot`. The solution in #625 on its own was enough for me for whatever reason. As such, it might be good to get feedback from other Lab users.

**Comment by rosteen** [comment]
@ojustino Thanks, I think it's enough to know that this at least doesn't break Lab usage for you. I can figure out my problems separate from this simple version bump.

**Comment by pllim** [comment]
@rosteen , FWIW, I created a fresh conda env with Python 3 + Lab 3 and the "model" error is gone; viz works for that combo for me.

**Comment by rosteen** [comment]
I was about to ask if you had solved that problem, thanks!

**Comment by pllim** [comment]
One does wonder what went wrong with the old combo but one does not wish to jump into that particular rabbit hole.

**Comment by rosteen** [comment]
Another one agrees XD

I have it working now in a fresh environment as well.

**Pull request merged**
