### PR TITLE
improve data menu for long labels

### LINKED ISSUE #1381: Data dropdown not large enough
**Reporter: Camilla Pacifici**

The standard JWST filename does not fit.

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request:
* increase width of viewer data menu to fit default JWST labels (350px -> 430px)
* truncate (with ellipsis) any labels that are still too long, with priority for extensions at end of label
* menu width and `calc(100% - 80px)` for span width might need to be updated if any additional icons (besides the check and delete button) are added in the future.
* updates text in header to fit in single line

Screen Shot 2022-06-10 at 2 31 54 PM

Fixes #1381

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
@rosteen @Jenneh  - if we can shorten the text a bit (maybe removing "in this list"?) from the header (added in #1349), that will now fit on one line

**Comment by pllim** [comment]
Is it possible to truncate like this: `prefix...[ext]` ? This is because if you load a multi-extension FITS, all the prefix is going to look the same but extension will be different.

**Comment by rosteen** [comment]
I was about to approve this, but @pllim makes a great point. Maybe I'll approve anyway and let that hold up the second approval. 

Would that text fit on a single line with "Add more datasets here" instead of "Add more datasets to this list"?

**Comment by kecnry** [comment]
@pllim - this is currently a CSS solution which truncates based on width, in pixels.  Doing what you suggest would need to be a JS solution which truncates in the middle of the string based on characters - it definitely is possible but has some drawbacks since we don't use a fixed-width font.  

If we're willing to make the assumption that whatever is following the last instance of `[` has priority, then I could try to split the string there, give everything after that last `[` as much room as it needs, and then truncate everything to the left based on the remaining space.  That should effectively do what you want, but there could be some edge cases where it doesn't behave well (a long label that is wrapped entirely in square brackets, for example).  Is this worth trying?

**Comment by pllim** [comment]
> Is this worth trying?

I think so, especially in Cubeviz where one tends to load flux, uncertainty, and mask all with the same prefix. JS can do regex, right? If you don't wanna regex, yes, I think truncating at `[` is good enough for most cases. I have not seen any filename with `[` in it (but I dun wanna jinx it).

**Comment by kecnry** [comment]
@rosteen - I updated the text to fit in a single line (can always iterate with @Jenneh later) - saw your comment after I already committed, but I think its effectively the same.  Let me know if you suggest something else.

@pllim - truncation will now prioritize leaving the extension at the end (anything after the last instance of `[` will show after the ellipsis.

**Review by pllim — APPROVED** [review]
The truncation LGTM but I cannot tell whether the wrong color for "Flux Viewer" is related or not. If it is not related, we can merge this and fix the dark mode color in a separate PR. This screenshot was done with the standalone app with `--theme=dark`.

Screenshot 2022-06-10 150518

**Comment by kecnry** [comment]
> I cannot tell whether the wrong color for "Flux Viewer" is related or not

unrelated, but easy enough to throw in here since its in the same file (along with a tooltip fix I had on another abandoned branch).

**Comment by pllim** [comment]
OK dark theme is fixed. LGTM!

**Comment by pllim** [comment]
I think https://github.com/spacetelescope/jdaviz/pull/1390#issuecomment-1152573787 count as second approval even though @rosteen never really click "approve"? 😆

**Review by rosteen — APPROVED** [review]

**Pull request merged**
