### PR TITLE
Link model fitting results so they plot in Mosviz

### PR DESCRIPTION
**Pull request by rosteen**
### Description

Our reductions in linking in Mosviz seem to have left fitted models out in the rain. This fixes it so that they once more plot over the selected data in the 1D spectrum viewer automatically after being fit. Seems a bit slower than I expected at the moment, but I think that's a separate issue.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by rosteen** [comment]
After this change I was unable to replicate the errors I was seeing trying to fit the most recent NIRSPEC data (the ceers_prism set) - I'll have to show @PatrickOgle to get them to happen again, I'm sure.

**Review by javerbukh — APPROVED** [review]
I am able to create models and see them plotted on the spectrum viewer, and get the model parameters in the notebook. Looks good!

**Review by PatrickOgle — APPROVED** [review]
PR, as demoed by @rosteen, works as advertised.  Nice work! One lien and one untested contigency:

The model seems to be linked to all of the rows, and should only be linked to the spectrum/row that was modeled. Second, this was not tested on data processed with older JWST pipeline versions that are used in existing Jupyter notebooks.

**Comment by rosteen** [comment]
Unfortunately there's not a way to link only to one dataset, since the 1D spectra are all linked together the model ends up linked to all. This relates to a point that made me stop working on removing the `Data` button from Mosviz - this is exactly the use case where a user still might need that to show/hide data that isn't controlled by clicking on the table rows. I think the strategy we'll end up wanting is filtering out the data controlled by the table from that menu and only showing things like the fitted models.

**Pull request merged**
