### PR TITLE
re-usable component to show quantity with significant decimal digits

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request creates yet another re-usable component (used in the output from line analysis for now), to have the UI round quantities based on the uncertainty *or* a default precision.  If an uncertainty is available, both the value and uncertainty are rounded to the second significant ~decimal~ digit in the uncertainties ~(currently no rounding is done for digits left of the decimal)~.  Note that this might not be entirely perfect - javascript treatment of numbers can be a bit funny... but the full underlying floats are untouched via the API.

Before and after screenshots in line analysis:
<div>
Screen Shot 2022-04-12 at 12 07 40 PM
Screen Shot 2022-04-12 at 12 05 42 PM
</div>

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by javerbukh** [comment]
I'm trying this PR with the example notebooks in a new conda environment and I'm getting NaNs in line analysis. I'm creating a subset in the spectrum viewer (in both cubeviz and specviz) and setting that as the spectral region in line analysis.

**Comment by javerbukh** [comment]
Getting a mix of 0s and NaNs now.
Screen Shot 2022-04-14 at 11 01 28 AM

**Comment by javerbukh** [comment]
Works well in Specviz though! Is it not working the same in cubeviz because the spectrum does not have an uncertainty value?

**Comment by kecnry** [comment]
Ok, I rewrote the logic entirely to be based on precision instead of number of decimal places and haven't managed to find a case where it breaks, but please do try!  If this isn't robust enough... we may have to handle it on the python side, Javascript can be a pain to deal with numbers.

**Comment by javerbukh** [comment]
Before I create a subset, everything looks as expected in cubeviz. But after selecting a subset, I get the following screen. Everything works well in specviz.
Screen Shot 2022-04-15 at 8 47 49 AM
.

**Comment by kecnry** [comment]
Can you compare to the list of dictionaries storing the results (`viz.app.get_tray_item_from_name('specviz-line-analysis').results`)?  If those show empty entries, nans, etc, then the formatting isn't the issue and I think its probably out-of-scope here.  If the dictionary does show results and the formatting is somehow choking and showing NaNs, then I should be able to track down what's going on if you send me the values.

**Review by javerbukh — APPROVED** [review]
Tried it out and you are correct, the results on the backend are NaNs and 0s. I'll go ahead and approve since everything else is working as expected!

<details>

```
[{'function': 'Line Flux',
  'result': '9.607043970686176e-07',
  'uncertainty': '',
  'unit': '1e-17 erg m / (Angstrom cm2 s)'},
 {'function': 'Equivalent Width',
  'result': '-1.6298725716548473e-09',
  'uncertainty': '',
  'unit': 'm'},
 {'function': 'Gaussian Sigma Width',
  'result': 'nan',
  'uncertainty': '',
  'unit': 'm'},
 {'function': 'Gaussian FWHM',
  'result': 'nan',
  'uncertainty': '',
  'unit': 'm'},
 {'function': 'Centroid',
  'result': '6.675966140764623e-07',
  'uncertainty': '',
  'unit': 'm'}]
```

</details>

**Review by duytnguyendtn — COMMENTED** [review]
I ran into an Jesse's nan issue, but when I extracted the parameters, the line flux actually returns a value, which isn't showed in the UI (and as usual, Mosviz is the problem config again 😅). Thoughts @kecnry?

image

image

**Comment by duytnguyendtn** [comment]
I interpret 0 uncertainty as the same as not having an uncertainty. I would just drop the 0+/-, similar to how the centroid appears in the above screenshot. Maybe a PO is needed here?

**Comment by kecnry** [comment]
I like that solution for now (and implemented it in the latest commit), and will open a follow-up ticket for investigating why the flux is returning 0 uncertainty in the first place. [:cat:](https://jira.stsci.edu/browse/JDAT-2340)

**Review by duytnguyendtn — APPROVED** [review]
Thanks for the quick fix! Looks good to me

image

**Pull request merged**
