### PR TITLE
MNT: Pin specutils to stable minversion

### PR DESCRIPTION
**Pull request by pllim**
Erik released specutils two days ago.

### CODE REVIEW

**Review by rosteen — APPROVED** [review]
Was on the to-do list for build prep, beat me to it. Thanks.

**Comment by pllim** [comment]
Ops, sorry 😅

**Review by javerbukh — APPROVED** [review]
Looks good! I imagine we will need to update this again once the NDData cube -> Specutils PRs are merged.

**Comment by javerbukh** [comment]
Merging.

**Pull request merged**
