### PR TITLE
MNT: Officially list matplotlib as dependency

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to officially acknowledge matplotlib as a required dependency. It has been since #183 .

https://github.com/spacetelescope/jdaviz/blob/85614cdabd33427b34844f864a8ba5b56be06649/jdaviz/configs/specviz/plugins/viewers.py#L15

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Perhaps but maybe there is no point to refactor given I will re-introduce matplotlib dependency again in #983 (Imviz Compass) because `bqplot` cannot do `imshow` (bqplot/bqplot#284 has been open for 6 years).

**Comment by pllim** [comment]
> I didn't realize there were more matplotlib dependencies coming

I wasn't looking at this for fun... 😹

**Comment by pllim** [comment]
Thanks for the quick review!

**Comment by samwelborn** [comment]
Hi. I don't know your software, but browsing through bqplot's forums for another issue I stumbled over here.
I'm using [bqplot-imagegl]( https://github.com/glue-viz/bqplot-image-gl) for my app, and it may work for you.

Here's my app: https://github.com/samwelborn/tomopyui
Here's a demo:
Animation_1

(looks a lil funky because of gif compression) 

You can find the image plotting stuff under [tomopyui.widget.plot.py](https://github.com/samwelborn/tomopyui/blob/main/tomopyui/widgets/plot)

**Comment by rosteen** [comment]
@samwelborn Thanks for the suggestion - we actually already use bqplot-image-gl (and in fact our needs have driven some of the development of that package!).

**Comment by samwelborn** [comment]
Very cool, and thanks for pushing its development forward. Would be interested in seeing how it is implemented in your app, I'll give it a try when I have some time. Any features that you see from my gif that could be implemented in jdaviz? Feel free to grab them.

Depending on my time, I may (maybe with @ianhi, see https://github.com/ianhi/hyperslicer/issues/1) make the image viewer into a package.

**Pull request merged**
