### PR TITLE
Added pan_x and pan_y icons

### PR DESCRIPTION
**Pull request by Jenneh**

### CODE REVIEW

**Comment by Jenneh** [comment]
@rosteen Can you review? Thanks!

**Comment by Jenneh** [comment]
I noticed I also committed slightly out of date logos. I will update those once I have final copies.

**Comment by rosteen** [comment]
The panzoom icons all look good, I'll wait to approve the PR until you update the logos so we're not merging outdated ones.

**Comment by Jenneh** [comment]
@rosteen I believe I have updated the logos. If all looks good can we merge them in?

**Pull request merged**
