### PR TITLE
improvements to is_active ping logic

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request aims fix lag and "flickering" issues within the `is_active` ping logic, hopefully for the last time 🤞 .

See:
* #2295 
* #2326 
* #2386

**TODO**: 
- [x] attempt to write a robust test that can mimic slow behavior in a method without requiring large test data and somehow test against flickering
- [ ] manual testing on different machines with different data across all applicable plugins
- [ ] if this change is insufficient, consider implementing dynamic timeout rates that adjust based on time to call methods

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by camipacifici** [comment]
Tested where I was seeing the flickering (it is a notebook where I first load a bunch of spectra in mosviz and then I load one in specviz2d) and it is gone. Works well, thank you!

**Review by pllim — APPROVED** [review]
Approving by proxy based on Cami's comment. Thanks!

**Comment by pllim** [comment]
Up to you if you want to add a change log since I don't think this flicker shows up for everyone?

**Comment by kecnry** [comment]
I'm still hoping to come up with a robust regression test for this (which is why I'm keeping it in draft), but its not an easy thing to test.

**Comment by kecnry** [comment]
Re-milestoned to 3.7 since this builds on #2386 which was not backported and we're likely not doing a 3.6.3 release anyways.

**Review by javerbukh — APPROVED** [review]
Tried in Imviz and Mosviz and couldn't replicate the original bug. LGTM!

**Review by pllim — APPROVED** [review]
I don't grok the test but something is better than nothing. My approval stands. Thanks!

**Pull request merged**
