### PR TITLE
support cubeviz.get_data(function=True)

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request extends #1984, #2072, and #2106 to add support for `cubeviz.get_data(..., function=True)` which looks up and adopts the collapse-function from the spectrum-viewer to return the collapsed spectrum.

Compare the following:
```
cubeviz.get_data(...) # cube
cubeviz.get_data(..., function=True) # collapsed spectrum
cubeviz.specviz.get_data(...) # collapsed spectrum, same as above
cubeviz.get_data(..., funtion='minimum') # collapsed spectrum, overrides function from that set in the viewer
```

Should this motivate changing the kwarg from "function" to "collapse"?  Would that be more intuitive to the user?  (Ah, but that was already released in 3.4 so probably shouldn't break existing API... would `function='viewer'` be better?

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by javerbukh — APPROVED** [review]
Looks good, thanks!

**Review by rosteen — APPROVED** [review]
I don't love this, but it works and might be the best way to go with the new `get_data` behavior. This is just the downside of moving away from `get_data_from_viewer`, it feels like there should be a more convenient method. Maybe we could add a `get_collapsed_spectra` method 🤔 (not here, later).

**Comment by cshanahan1** [comment]
looks good to me :)

**Review by cshanahan1 — APPROVED** [review]

**Comment by kecnry** [comment]
thanks for the reviews - if anyone has suggestions for further iteration, let's make sure not to forget those!

**Pull request merged**
