### PR TITLE
Fix infinite toggle loop

### LINKED ISSUE #185: Switching between data in code causes infinite loop
The following code, which is used to switch from visualizing an old spectrum to a new one, causes an infinite loop:
```
        # Replace old spectrum with new one with updated units.
        self.app.add_data(converted_spec, new_label)
        self.app.add_data_to_viewer("spectrum-viewer", new_label)
        self.app.remove_data_from_viewer("spectrum-viewer", old_label)
```
This bug usually comes after the second round of unit conversion. Example:

Jul-02-2020 10-33-34

### PR DESCRIPTION
**Pull request by nmearl**
Resolves #185. Fixes an issue when manipulating the data collection that could result in an infinite loop occurring with the toggled data list items.

🚨**NOTE FOR FUTURE REFERENCE**🚨 Please, do not attempt to alter application state from within plugins! This can have obviously unintended consequences due to event ordering!

### CODE REVIEW

**Comment by nmearl** [comment]
@rosteen, locally, does this solve the looping issue seen in #185 with the unit conversion plugin?

**Comment by rosteen** [comment]
No, I'm still able to replicate the looping with the unit conversion as well.

**Comment by nmearl** [comment]
I cannot replicate with this PR -- are you testing with the Specviz Unit Conversion notebook?

**Comment by rosteen** [comment]
I was using the Specviz hack hour notebook. I had to change units 6 or 7 times before the flickering/looping started, but through persistence was able to break it.

**Pull request merged**
