### PR TITLE
Update to new MAST URIs in example notebooks

### PR DESCRIPTION
**Pull request by rosteen**
Apparently MAST changed these paths....

Fix https://github.com/spacetelescope/jdaviz/issues/1758

### CODE REVIEW

**Comment by bmorris3** [comment]
Related: #1760, #1762

We've got to find a better way... 😱

**Comment by kecnry** [comment]
Does this replace #1762 (so there is a consistent source for specviz and cubeviz)?

**Comment by rosteen** [comment]
Whoops, missed those. It surprises me that #1762 works, since I see `c1001` replaced with `o004` in MAST.

Screen Shot 2022-10-21 at 2 07 31 PM

**Comment by pllim** [comment]
I dunno what is the difference between `cXXXX` and `oXXX` in the names.  I just use what MAST people tell me to use when I complain to them the old name stopped working. 😹

**Review by pllim — APPROVED** [review]
LGTM. Thanks!

**Comment by pllim** [comment]
I don't see why this needs to be delayed. Merging this so notebooks won't be broken anymore. Thanks!

**Comment by pllim** [comment]
Follow up issue at https://github.com/spacetelescope/jdaviz/issues/1765

**Comment by pllim** [comment]
@rosteen , after you manually backport this, please remove the `Still Needs Manual Backport` label. Thanks!

**Comment by havok2063** [comment]
> I dunno what is the difference between `cXXXX` and `oXXX` in the names. I just use what MAST people tell me to use when I complain to them the old name stopped working. 😹

There is the info, but it's still sometimes not clear.
"""
AC_ID is the Association Candidate ID. It is used in a number of filenames. It consists of a letter (o, c, a or r) followed by 3-4 digits

o001 - o999 Observation specified in a program (visible to user in APT) 
c1000 - c2999 AC specified in a program (visible to user in APT) 
a3000 - a4999 AC specified in DMS, self-discoverable via ASN Generator (visible to user in Archive UI) 
r5000 - r9999 Reserved for future use (archive operator procedure)
"""

**Pull request merged**
