### PR TITLE
BUG: Fix Line Profile not handling dithered data in Imviz

### LINKED ISSUE #1285: Imviz: Line profile plugin to handle sky coordinates in dithered images
**Reporter: Camilla Pacifici**

Loaded multiple dithered images. Matched them by WCS. Blinked a couple of times. Found an interesting object in one of the images. Zoomed to the object. Open the line profile plugin. With cursor on object, hit "l". The position given in the top bar is different from the position recorded by the line profile (see screenshot).

The 2 ACS images of the example notebook work for testing.

Maybe related to github issue #1238?

[🐱](https://jira.stsci.edu/browse/JDAT-2397)

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to report correct X and Y when "l" is pressed over dithered data that is not the reference data. You can try this out by linking the Imviz example notebook by WCS and then press "l" and then blink and then press "l" again.

I also moved entries from #1224 to the correct section. They were bug fixes, not API changes.

Fixes #1285 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by camipacifici** [comment]
Thank you for finding a fix! I tried again with the two ACS images.
I noticed that if I do not blink first, the pixel coordinates are not correct. They are then correct after one blink.
Before blinking, coordinates 2075,927 at the center of the object.
Screen Shot 2022-05-04 at 10 58 01 PM
After one blink, coordinates stay the same but we are on the other dither.
Screen Shot 2022-05-04 at 10 58 22 PM
After another blink, coordinates are now 2088,941.
Screen Shot 2022-05-04 at 10 58 40 PM

**Comment by pllim** [comment]
Note to self: Workflow like this

1. Load data in Imviz example notebook.
2. Link them by WCS.
3. Zoom in to object of interest.
4. Mouseover it. Note the X and Y.
5. Blink.
6. Note the X and Y do not change. This is wrong. It should have changed, which implies X and Y from Step 4 were actually pixel coordinates for the reference image.
7. Blink again. X and Y now disagree with those in Step 4.

**Comment by pllim** [comment]
@camipacifici , good catch! But the bug reported at https://github.com/spacetelescope/jdaviz/pull/1293#issuecomment-1118120046 is not related to this bug I am trying to fix with this PR. You can see this bug even without using Line Profile.

For this new bug, the solution is not immediately clear to me because the fix that came in mind is to manually trigger a "mousemove" event

https://github.com/spacetelescope/jdaviz/blob/7814b4abe82f073d05ab5b185c99ac024ea9f39f/jdaviz/configs/imviz/plugins/viewers.py#L161-L163

and the end of load logic in the `if` here

https://github.com/spacetelescope/jdaviz/blob/7814b4abe82f073d05ab5b185c99ac024ea9f39f/jdaviz/configs/imviz/helper.py#L184

but I have no idea how to grab the cursor info at this stage of operation. Since @astrofrog wrote the initial coordinates display logic, maybe he has an idea. But regardless fixing it is a separate ticket.

**Comment by camipacifici** [comment]
Gotcha! Thank you for creating the next ticket!

**Review by rosteen — APPROVED** [review]
As far as I understand the bug and desired behavior, it seems like this fixes it.

**Review by kecnry — APPROVED** [review]
I'd vote to prioritize the follow-up ticket as I can see how that could be confusing... and that might need some refactoring to get that done.  But no sense in that holding this up, so let's get this in in the meantime.

**Pull request merged**
