### PR TITLE
Astrowidgets: Option to apply some settings to all layers

### LINKED ISSUE #1477: Document how to auto-scale in Imviz for multiple images at once
**Reporter: pllim**

There is a need to add user documentation on how to use https://github.com/spacetelescope/jdaviz/pull/1343 to accomplish #750 .

Desired workflow:

1. Load two images in Imviz.
2. Interactively adjust scale (stretch? percentile?) in an image.
3. Have the settings automatically applied to the other image.

[🐱](https://jira.stsci.edu/browse/JDAT-2670)

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to add option into the Astrowidgets mixin to allow applying stretch, cuts, or colormap settings to all the viewer image layers at once.

Pro: This is a requested feature by @hcferguson .

Con: This deviates from the Astrowidgets API because I have to introduce a glue-specific property. Maybe @eteq has opinion on this front. @kecnry might have opinions too in case this deviates from his grand plan to unified APIs.

Fixes #1477 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)? [🐱](https://jira.stsci.edu/browse/JDAT-2670)

### CODE REVIEW

**Comment by kecnry** [comment]
If this is something that is wanted in astrowidgets anyways, then that's fine (although from your PR description, it sounds like this deviates from the astrowidgets API).  I still personally prefer exposing (and documenting) a clean API to the existing plugin that has a much more general version of this functionality that applies across all viewer-types, not just image viewers.  If this is high-priority, I'd be happy to update #1401 for an example of how that might work with the plot options plugin and then we can decide which is more convenient?

**Comment by hcferguson** [comment]
Not sure if I'm doing something wrong installing from your branch, but my notebook just hangs when I do `imviz = Imviz()`. I fetched your branch, checked out must-all-the-layers and did a `pip install -e .` 
The log from jupyter is below 

```[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: 013e47d0-41cd-4b4a-9ee9-651663e0dc4e
[W 15:48:36.504 NotebookApp] 404 GET /static/jupyter-vue.js?v=20220823154807 (::1) 6.310000ms referer=http://localhost:8889/notebooks/must-all-the-layers.ipynb
[W 15:48:38.766 NotebookApp] 404 GET /static/jupyter-vuetify.js?v=20220823154807 (::1) 0.990000ms referer=http://localhost:8889/notebooks/must-all-the-layers.ipynb
[W 15:48:39.150 NotebookApp] 404 GET /static/jupyter-splitpanes.js?v=20220823154807 (::1) 0.980000ms referer=http://localhost:8889/notebooks/must-all-the-layers.ipynb
[W 15:48:39.158 NotebookApp] 404 GET /static/jupyter-golden-layout.js?v=20220823154807 (::1) 0.910000ms referer=http://localhost:8889/notebooks/must-all-the-layers.ipynb
[W 15:49:06.406 NotebookApp] 404 GET /static/bqplot.js?v=20220823154807 (::1) 1.750000ms referer=http://localhost:8889/notebooks/must-all-the-layers.ipynb
```

**Comment by pllim** [comment]
@hcferguson , I haven't seen that myself but try with a fresh conda env?

**Comment by pllim** [comment]
p.s. Just in case, I have rebased to pick up changes to `main`.

**Comment by pllim** [comment]
Superseded by https://github.com/spacetelescope/jdaviz/pull/1704

**Pull request closed without merging**
