### PR TITLE
Model component name sanitization/validation

### LINKED ISSUE #1002: [Bug]: Forbid problematic characters in model labels.
### Description
If users name their model components in the Model Fitting plugin something like "model-1" (with a dash in it), the dash will be interpreted as a subtraction operator and cause the fitting to crash. We need to do some checking/sanitizing of the model label strings to ensure this doesn't happen.

[🐱](https://jira.stsci.edu/browse/JDAT-2019)

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request ensures that model names are valid and will not cause issues within the equations (by containing operators, etc).  This is done in python by validating and raising an error, and in JS by stripping non-valid characters when the element loses focus (tab or clicking away).  Alternatively, this could be done with rules (showing red text for an invalid entry), but that would require intervention by the user (but also gives a chance to explain the reason).

**NOTE**: failing CI seems unrelated but probably should be fixed before merge.

https://user-images.githubusercontent.com/877591/147768549-ba0bfd01-6cd6-4a15-ac2f-58e94c527300.mov

Fixes #1002

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
@kecnry , if you would approve and merge #1019 and then rebase this, CI would pass.

**Comment by pllim** [comment]
What if the stripping results in duplicate name with an existing model, what is the desired behavior in that case?

**Comment by kecnry** [comment]
@pllim - added errors for the duplicate name case which you can see in action below:

https://user-images.githubusercontent.com/877591/147939624-5f6deece-0c0e-4891-8920-ca39d86726b8.mov

Note that the form validator doesn't automatically rerun when adding a component, but the error would still be raised by python.  We could override this with a hack, but I think the immediate red text after clicking "add component" might just add confusion.

**Comment by pllim** [comment]
Thanks for the screen capture. LGTM!

**Review by rosteen — APPROVED** [review]
LGTM, although testing this surfaced a bug in the plugin that is also present on main, I'll make a separate issue for that. As @pllim said, I'd prefer rebasing and seeing the CI pass before merging once #1019 is in.

**Comment by rosteen** [comment]
Having just approved this, I do have one minor concern with the behavior. Currently this strips invalid characters from the label without any sort of warning to the user. Could this be frustrating, e.g. if a user types "C-1" for the label, clicks away, doesn't notice that the label was automatically changed, and then gets an error when they try to use "C-1" in the model equation? I know that vuetify's validation can turn the field red and add a red warning message (you can see this if the field is left blank) - maybe it would be better to use that strategy? Might be a Jenn question.

**Comment by kecnry** [comment]
Rebased and test coverage added (pending CI passing).

@rosteen - I had considered that alternative, but my thoughts were that validating would require a lengthy (and confusing) string to explain how to fix the input when its just as easy to just automatically "fix" it.  The pros to validation of course would be that there are no surprises and it "teaches" the user what is needed going forward.  The cons are that it requires more user intervention and might be difficult to explain precisely.  I can switch to validation if that is preferred (but obviously doing both doesn't make sense as stripping would never trigger the red warning).  One other thing to keep in mind is our future plans to auto-populate the equation, which would minimize the chances of confusion during the use-case that you bring up.

**Pull request merged**
