### PR TITLE
Remove unused message classes

### PR DESCRIPTION
**Pull request by larrybradley**
It appears these message classes are not used anywhere in the code.

Discovered in #872.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Needs a rebase due to conflict from your other PR.

**Comment by larrybradley** [comment]
done

**Review by pllim — APPROVED** [review]
I am all for removing unused code!

**Review by rosteen — APPROVED** [review]
For what it's worth, my guess is that a lot of these were intended to be used in the "default" `jdaviz` configuration where users could manually add and remove the viewers they wanted in the app. But since they're not being used I have no objection to removing them.

**Comment by pllim** [comment]
Pinging @havok2063 just in case...

**Comment by havok2063** [comment]
Skimming through the commit history, they may have been introduced when we were exploring how best to save the complete state of Jdaviz.  The use case is that users could work in Jdaviz, either in viewers created off the `default` configuration, or within the pre-designed helpers, save the state of the application and any analysis (into a file, e.g JSON), then reload the entire application state later on.  This is useful for users using Jdaviz in the web to quickly inspect a data product, but who then want to save their state and transition to Jdaviz in their local laptops without having to redo everything.  This idea was complicated but not impossible to implement, but got de-prioritized over time.  (I still think this would be a pretty powerful feature to enable a truly seamless user workflow experience).   Since these message classes aren't currently being used, then it's probably fine to remove them.

**Pull request merged**
