### PR TITLE
mosviz image-viewer: allow using astrowidgets api

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request adds the `AstrowidgetsImageViewerMixin` to the `MosvizImageView` to allow access to `add_markers` within mosviz.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
@pllim - was all of this covered by #1571 (if so I'll close the PR instead of leaving it as a draft)?

**Comment by pllim** [comment]
I did not touch Mosviz at all. So I think this is not yet resolved for Mosviz.

**Comment by kecnry** [comment]
Ok, I'll leave this for now then.  I'm guessing if/when we revisit it, we'll want to make use of your new `ImageConfigHelper` instead of just using the astrowidgets mixin.

**Comment by pllim** [comment]
I don't remember what motivated this but your original post says "add_markers". That method is from Astrowidgets, so we cannot just move it into ImageConfigHelper.

**Pull request closed without merging**
