### PR TITLE
BUG: Fix model fitting crashing when param is fixed

### LINKED ISSUE #1686: Model Fitting Specviz: Error on fixing Gaussian mean
### Description
When fitting a Gaussian in the specviz Model Fitting Plugin, I get the following error if I fix the
mean and fit the model.  The fit does appear to work, but there is this  error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/science/lib/python3.8/site-packages/ipyvue/VueTemplateWidget.py in _handle_event(self, _, content, buffers)
     58                 getattr(self, "vue_" + event)(data, buffers)
     59             else:
---> 60                 getattr(self, "vue_" + event)(data)
     61 
     62 

~/miniconda3/envs/science/lib/python3.8/site-packages/jdaviz/configs/default/plugins/model_fitting/model_fitting.py in vue_apply(self, event)
    446             self.vue_fit_model_to_cube()
    447         else:
--> 448             self.vue_model_fitting()
    449 
    450     def vue_model_fitting(self, *args, **kwargs):

~/miniconda3/envs/science/lib/python3.8/site-packages/jdaviz/configs/default/plugins/model_fitting/model_fitting.py in vue_model_fitting(self, *args, **kwargs)
    489             self._update_parameters_from_QM()
    490         else:
--> 491             self._update_parameters_from_fit()
    492 
    493         # Also update the _initialized_models so we can use these values

~/miniconda3/envs/science/lib/python3.8/site-packages/jdaviz/configs/default/plugins/model_fitting/model_fitting.py in _update_parameters_from_fit(self)
    143                     if submodel_index is not None:
    144                         std_name = f"{std_name}_{submodel_index}"
--> 145                     temp_param[0]["std"] = self._fitted_model.stds[std_name]
    146 
    147                 temp_params += temp_param

~/miniconda3/envs/science/lib/python3.8/site-packages/astropy/modeling/fitting.py in __getitem__(self, param)
    129     def __getitem__(self, param):
    130         if isinstance(param, str):
--> 131             i = self.param_names.index(param)
    132         elif isinstance(param, int):
    133             i = param

ValueError: 'mean' is not in list
```

### Additional context

Jdaviz version 2.10.0
astropy version 5.1
data: 1D Spectrum1D extracted with specreduce, fitting full wavelength range.
model_fitting_bug

[🐱](https://jira.stsci.edu/browse/JDAT-2814)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to fix #1686 . 

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
that explains why I couldn't reproduce... I must have set the parameter to "fixed" after already running one instance of the fitter 🤦   Thanks!

**Comment by pllim** [comment]
Kyle, do you think this is the correct fix? I am not very sure how to write a test for this either. Feel free to take over if you want. I have a few more things to catch up on and this isn't high on my priority list.

**Review by PatrickOgle — APPROVED** [review]
Tried PR on same example where fixing Gaussian mean was giving error.  Error appears to have been fixed.

**Comment by pllim** [comment]
While adding a new test, I can't help attempting to clean other tests in the test file but should not be any significant change to the test content.

The fix is 2 lines, but the test is many more. 😆

**Review by kecnry — APPROVED** [review]
I'm quite surprised this was the culprit, but it seems to fix it.  Thanks!

I'm not sure we need to update all the tests to call `plugin._obj` instead of `get_tray_item_from_name`, but it also doesn't hurt and we can just slowly migrate them as we update the tests anyways.  To some extent, I guess it makes it clear in the test when a private API call is necessary.

**Comment by pllim** [comment]
Thanks for the reviews!

**Pull request merged**
