### PR TITLE
Update standalone.yml

### PR DESCRIPTION
**Pull request by pllim**
### Description

* Bump upload-artifact to get rid of warnings.
* Bump to Python 3.11 for speed.
* Enable pull request build by label (but no OSX and no uploads).
* Only run on this repo, not forks.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Oh huh... I was giving up but looks like build standalone job passed here. Maybe there is hope.

**Comment by rosteen** [comment]
> Oh huh... I was giving up but looks like build standalone job passed here. Maybe there is hope.

The MacOS build was skipped, was that intentional?

**Comment by rosteen** [comment]
Actually wait - I just realized that this needs the label to run, what's the reason for leaving out the OSX build?

**Comment by pllim** [comment]
> what's the reason for leaving out the OSX build?

It has many extra steps and was failing very early with errors I have no interest in debugging. Yes, I am betting it is the license stuff they need money for. 🤑

**Pull request merged**
