### PR TITLE
Remove extra unit multiplication in fitting backend

### LINKED ISSUE #324: Incorrect units in Model Fitting output
It looks like the units are getting added to the model fitting plugin results on the backend when they already exist, which leaves the result with the square of the correct units. Should be an easy fix.

### PR DESCRIPTION
**Pull request by rosteen**
Closes #324

### CODE REVIEW

**Comment by rosteen** [comment]
More context: I noticed when trying to use the model fitting plugin output for continuum subtraction that the units of the output's flux were the square of the original data flux units. There was an extra unit multiplication that wasn't needed on the backend, simple fix to remove it.

**Review by ibusko — APPROVED** [review]
I suspect the extra unit was needed before fixes were applied elsewhere in specutils in the spectrum1d handling of units. We never got back here to re-verify. Good catch!

**Review by javerbukh — APPROVED** [review]
Looks good! I was able to load the fitted model in the specviz viewer and do a unit conversion, so I assume that fixes the problem.

**Comment by javerbukh** [comment]
LGTM.

**Pull request merged**
