### PR TITLE
Use pixel_to_pixel in _get_real_xy method

### PR DESCRIPTION
**Pull request by pllim**
### Description

As far as we are concerned `pixel_to_pixel` from `astropy.wcs.utils` is interchangeable with the code it is replacing.

https://github.com/astropy/astropy/blob/87963074a50b14626fbd825536f384a6e96835af/astropy/wcs/utils.py#L803

Pro: We are using "blessed" functionality from astropy core lib.

Con: I am not sure if this is worth it. The astropy function has extra processing that we don't really need. If not worth it, we should just close without merging.

Why this PR? Because I didn't know this function existed until Tom R pointed it out today.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
> I am not sure if this is worth it. The astropy function has extra processing that we don't really need. If not worth it, we should just close without merging.

Is there any time cost associated with the extra processing?  Does that processing add any checks that benefit us?  Otherwise, I agree that I'm not sure its worth it... this doesn't really simplify the code from our end and this is called *often* (on every mouse move).

**Comment by pllim** [comment]
> Is there any time cost associated with the extra processing? 

Pretty sure there is but I'll have to time it later when I get the chance. Will report back.

**Comment by pllim** [comment]
Interesting... the timing is actually comparable, but maybe others can do a sanity check. I did it in notebook like this:

```python
from astropy.io import fits
from astropy.utils.data import download_file
from astropy.wcs import WCS
from astropy.wcs.utils import pixel_to_pixel

acs_47tuc_1 = download_file('https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HST/product/jbqf03gjq_flc.fits', cache=True)
acs_47tuc_2 = download_file('https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:HST/product/jbqf03h1q_flc.fits', cache=True)

with fits.open(acs_47tuc_1) as pf:
    w1 = WCS(pf[1].header, pf)

with fits.open(acs_47tuc_2) as pf:
    w2 = WCS(pf[1].header, pf)
```

```python
%timeit list(map(float, w2.world_to_pixel(w1.pixel_to_world(100, 100))))
```
```
# 1.4 ms ± 5.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

```python
%timeit list(map(float, pixel_to_pixel(w1, w2, 100, 100)))
```
```
1.4 ms ± 6.23 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
```

**Review by kecnry — APPROVED** [review]
Ok, since this doesn't add any additional overhead, I don't see any harm and it does slightly simplify reading the code.

**Comment by pllim** [comment]
Thanks! Given the holidays, I think 1 approval is enough for this.

**Pull request merged**
