### PR TITLE
Data menu visibility toggles

### PR DESCRIPTION
**Pull request by kecnry**
### Blocked by

- [x] Bug fix for linking that @javerbukh will probably take on (see #1412 - test and then rebase back onto main once 1412 is merged)

### Description

This pull request changes the behavior of the per-viewer data menus so that the check/radio buttons affect the _visibility_ of all layers associated with that data entry rather than their loaded/unloaded state in the viewer.  In doing so, it hopes to address a few annoying use-cases:
* phantom subsets appearing for data entries where the layer was hidden in the plot options plugin.  The visibility of the subset layer now defaults to that of the "parent" data layer and the data menu is a more convenient way of turning off the visibility as well as seeing "mixed state" to re-enable the visibility of both the data and subset layers rather than having to turn multiple things on manually in the plot options.
* some layer options changed in plot options are discarded when unloading a data entry from the viewer. By making the checkmarks/radio affect visibility, users will likely use this more often and the options won't be lost (they still might be lost if intentionally unloading)
* hiding the reference data does not have the unintended consequences as unloading (axes labels/limits reverting, etc)

This PR also separates the `layer.visible` from `layer.state.bitmap_visible` and `layer.state.contour_visible` for image layers in the plot options plugin.

**Before** (note the phantom subset appearing and how the changes to linewidth are lost when unchecking/checking in the data menu):

https://user-images.githubusercontent.com/877591/173679546-dc79e0d7-7e05-480c-a41b-76e5b46d7979.mov

**After** (note that both of these annoyances are improved but that unloading/loading will still lose linewidth changes):

https://user-images.githubusercontent.com/877591/173679691-62170a2f-05a4-4f6f-9c8e-96ad091db4de.mov

**Screenshots in other configs**:
Screen Shot 2022-06-14 at 4 11 06 PM

Screen Shot 2022-06-14 at 4 11 28 PM

TODO before ready for review: 
- [x] consider reworking imviz blinking to make use of radio-mode and toggle visibility (and then restore original state).  This might fix a current clash with the visibility toggles in imviz.  Edit: managed to fix clash, will defer possible blinking rewrite to a future work
- [x] test/fix behavior in cubeviz image viewers
- [x] decide how to handle image/contour visibility in plot options vs _layer_ visibility in data menu (deferred, see below)
- [x] rebase on top of #1402
- [x] screenrecordings in PR
- [x] review from @Jenneh 
- [x] Fix dark mode for menu expansion icons
- [x] Spatial subset default visibility should follow parent data layer state (should it follow `layer.visible` or `layer.state.bitmap_visible` or both?)

Possible follow-up efforts:
* rewrite blinking infrastructure to temporarily enter single-select mode and cycle?
* ~for image viewers, check in this menu toggles layer visibility, but plot options have separate eye icons for the image and contours, which might cause some confusion.  Should the plot options show the layer visibility at the top and have the image/contour moved back to their respective sections?~ (ended up adding to this PR)

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by javerbukh** [comment]
1. In cubeviz notebook
2. Create gaussian smooth data, plot in flux viewer

The flux viewer becomes completely black. Deselecting the flux cube does not fix it, only removing the flux cube from the viewer does that. Bug or intended functionality?

**Comment by javerbukh** [comment]
In Imviz, if I have both data checked and then go to blink, only one of them is checked if I look at the dropdown again. I know that now controls visibility but I think that may be a confusing interaction. From our conversations though I imagine that might just have to be how it is in order to get this functionality merged.

Tested with mosviz and specviz and works well there.

**Comment by kecnry** [comment]
Regarding the gaussian (spatial) smooth in cubeviz - I suspect that is the same underlying linking issues as with moment maps (see #1402, #1405).  I don't think this PR introduces those bugs, just makes it easier to have both enabled at the same time.... but definitely not intended functionality and something we should fix asap.  If anyone thinks that should block merge of this PR, that's fine with me, but I think _fixing_ it should be handled separately.

As for blinking... to some extent I'd consider this an improvement as it shows which layer is made visible by the blinking.  The previous "unchecked" state that used to depict unloaded data would now show as an entry being demoted to below the expanded section of the menu.

**Comment by javerbukh** [comment]
Yes but to trigger that same interaction on `main`, you would need to:

1. Gaussian smooth, do not plot in viewer
2. Make flux viewer checkboxes instead of radio
3. Select smoothed data
4. Go to plot options
5. Make flux cube invisible

Meanwhile plotting in viewer on `main` works as expected. I agree with you that the underlying bug is not introduced in this PR, so I am ok with merging. But I do think we would need to make the fix for linking plugin data (at least for gaussian smooth) a priority.

**Review by pllim — COMMENTED** [review]
As noted before, for the handful of our existing users, this is a significant UI/UX change, so I think we need a user facing documentation to go with this. Just a change log is insufficient. Maybe the main page with a note like, "Starting with Jdaviz vX.Y, such and such has changed and so on..."

It is nice that the checkboxes follow the blinking in Imviz, although the update sometimes lags a little but should be okay.

Dark mode strikes again! (The down arrows.)

Screenshot 2022-06-17 163848

I no longer understand what the eye icon means in Plot Options. It does not follow blink anymore. Note that the eye is not crossed out even when the image is no longer checked under Data.

Screenshot 2022-06-17 164823

When I have only one layer visible but then I draw a Subset, I see the one that is invisible have a gray checked box. I don't know what this means.

Screenshot 2022-06-17 171010

So, I have one image visible and one Subset drawn, then I proceeded to add custom regions in the example notebook (the cell that ends with `imviz.load_static_regions(my_regions)`) but it no longer works. I get errors like `IndexError('index 2050 is out of bounds for axis 0 with size 2048')`. Same problem with adding markers via API in the example notebook.

**Comment by pllim** [comment]
Re: `IndexError('index 2050 is out of bounds for axis 0 with size 2048')` -- I might have accidentally changed which one was the reference data when I played with the "x" toggles. If I restart the kernel and just blink without clicking any "x", the regions and markers work. So chuck that under user error and future work. FYI.

**Comment by pllim** [comment]
Since this is blocked by linking bug, I am removing "ready for final review" label and change this back to draft to prevent accidental merge. Thanks for your understanding!

**Comment by kecnry** [comment]
> As noted before, for the handful of our existing users, this is a significant UI/UX change, so I think we need a user facing documentation to go with this.

I think we need a policy for this.  But I also would argue that from the _user_ perspective, the high-level behavior is unchanged, so I'm hesitant to add more docs that we'll need to maintain.  If you/anyone insists on docs to cover the change, let me know where/what you'd suggest and I can add them.

> Dark mode strikes again! (The down arrows.)

Added to todo list before re-opening (although was not technically introduced in this PR).

> I no longer understand what the eye icon means in Plot Options. It does not follow blink anymore. Note that the eye is not crossed out even when the image is no longer checked under Data.

That has not changed in this PR but is a scenario we might want to consider changing.  The plot options now expose `layer.state.bitmap_visible` and `layer.state.contour_visible`, but there is also an (unexposed in plot options) `layer.visible` switch which is what blinking is controlling.  In order to see the image, both `layer.visible` and `layer.state.bitmap_visible` must be True.  My proposal to clean this up a bit would be to expose `layer.visible` in the visibility section of plot options, and move bitmap/contour to their respective subsection.

> When I have only one layer visible but then I draw a Subset, I see the one that is invisible have a gray checked box. I don't know what this means.

This is an indication of mixed visibility state (some layers associated with that data entry are visible, but not all).  I will try to change the default visibility of a spatial subset to follow the parent data layer in the same way that is done for spectral subsets.

**Comment by pllim** [comment]
> If you/anyone insists on docs to cover the change, let me know where/what you'd suggest and I can add them.

Maybe a giant warning on landing page (root-level `index.html`)? If that is too jarring, a note might work too. The goal is to lessen surprise for existing users, especially if a bunch of AAS really downloaded it recently.

**Comment by kecnry** [comment]
How about adding more text to https://jdaviz.readthedocs.io/en/latest/specviz/displaying.html#selecting-showing-data-sets explaining changing visibility vs loading/unloading?  This section is currently specviz-specific, but is the only existing place where we cover the data menu.

**Comment by rosteen** [comment]
Ah, what you're describing sounds reasonable to me, but I don't see trashcan buttons attached to the "deactivated" list entries:

Screen Shot 2022-07-05 at 9 56 43 AM

**Comment by pllim** [comment]
> no trashcan button for the reference data

I asked Kyle not to let people delete reference data because of linking implications. We'll tackle that in a separate ticket (e.g., #1420).

**Review by rosteen — APPROVED** [review]
After a fresh install, I see the trash can in Lab. I approve.

**Pull request merged**
