### PR TITLE
Mosviz coordinates display panel for image and 2d spectrum viewers

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to enable coordinates display panel for image and 2D spectrum viewers in Mosviz.

I am not familiar with all the different data Mosviz is supposed to be able to load, so Mosviz experts should play with this.

Goes with:

* #1759 

Mousing over the image:

Screenshot 2022-11-01 165300

Mousing over the 2D spectrum:

Screenshot 2022-11-01 165318

Mousing over the 1D spectrum. There is no data icon label (B) because Kyle said it is cursor position, not actual data:

Screenshot 2022-11-01 165354

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)? [🐱](https://jira.stsci.edu/browse/JDAT-2897)

### CODE REVIEW

**Comment by kecnry** [comment]
There is even more overlap here than other configs because of the "lock row" button... which got me thinking: should we remove the "Import Data" button in mosviz as well (like we do for cubeviz)?  That would free up quite a bit of horizontal space and Import Data won't have anyway of assigning the new data to a specific row, afaik.

**Comment by pllim** [comment]
AFAIK the "Import Data" button is kinda useless right now, right? So 👍 to remove it from me.

**Comment by javerbukh** [comment]
I think removing it makes sense to me as well. One less place in the docs we have to explain the confusing directory structure that needs to exist in order to import mosviz data :sweat_smile:

**Comment by kecnry** [comment]
@pllim - do you think that belongs in scope here (to make room for the new coordinates display) or would you rather have this reviewed ignoring the space/overlap concern and have that as a follow-up?

**Comment by pllim** [comment]
If it is easy, I can try fit it in. Where in Cubeviz can I copy from? Thanks!

**Comment by kecnry** [comment]
https://github.com/spacetelescope/jdaviz/blob/105de83f45ebb97de678014961766cef5127aea3/jdaviz/app.vue#L41

needs to become something like:

```
<j-tooltip v-if="['cubeviz', 'mosviz'].indexOf(config) !== -1 && item.name == 'g-data-tools' && state.data_items.length !== 0"></j-tooltip>
```

**Comment by camipacifici** [comment]
> I think removing it makes sense to me as well. One fewer place in the docs we have to explain the confusing directory structure that needs to exist in order to import mosviz data 😅

Don't forget the stand alone app

**Comment by pllim** [comment]
Until https://github.com/spacetelescope/jdaviz/issues/601 is figured out, we don't need this button.

**Comment by kecnry** [comment]
> Don't forget the stand alone app

> Until https://github.com/spacetelescope/jdaviz/issues/601 is figured out, we don't need this button.

The snippet I suggested will only remove the button once/if data is already loaded, which should still work with #601.  If you'd rather remove it entirely for now, that's an option too, and we can re-introduce the "only visible when data isn't already loaded" logic when addressing #601.

**Comment by pllim** [comment]
I added a commit to hide the Import Data button after load as Kyle suggested. Better now?

### Before load

Screenshot 2022-11-02 115651

### After load

Screenshot 2022-11-02 115631

**Comment by camipacifici** [comment]
Nice!!

**Review by javerbukh — APPROVED** [review]
Looks good!

**Review by kecnry — APPROVED** [review]
Works well and I think is a useful addition, especially to bring consistency across all the tools.

The discrepancy between pixels meaning actual pixels in the 2d spectrum (even though we display them as if they have a shared x-axis in the viewers) and pixel coordinates meaning whatever the x-axis is in the 1d spectrum could be a point of confusion, but we can hopefully address that when generalizing the mouseover code and/or when adding more support for spectrum layers.

**Comment by pllim** [comment]
I thought it would take more work but glad not. Thanks for the reviews!

**Pull request merged**
