### PR TITLE
DOC: Fix logos and dark mode

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is an alternate fix for the logos based on https://github.com/astropy/astropy/pull/16639

Close #3243

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by haticekaratay** [comment]
Hi @pllim, 
Could you please add before and after screenshots demonstrating how the docs are built at the end? I'm asking because I'm currently testing it locally and wondering if this is what we expect to see in dark mode: 
image

**Comment by pllim** [comment]
Hmm. I removed the "Note" part. Not sure why you see that locally.

Before: https://jdaviz.readthedocs.io/en/latest/

After: https://jdaviz--3245.org.readthedocs.build/en/3245/

**Comment by haticekaratay** [comment]
> Hmm. I removed the "Note" part. Not sure why you see that locally.
> 
> Before: https://jdaviz.readthedocs.io/en/latest/
> 
> After: https://jdaviz--3245.org.readthedocs.build/en/3245/

Yes. I realized that later. Thanks!

**Comment by haticekaratay** [comment]
@pllim 
One more question: Should we invert the colors of the logo in dark mode, or keep them as they are? @kecnry 
image

**Comment by kecnry** [comment]
iirc, the backgrounds are white, not transparent, so inverting was the best temporary solution.  If we replace the logos with transparent backgrounds, then we can avoid inverting.

**Review by haticekaratay — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
@haticekaratay , thanks for the review! I will let you handle your JIRA ticket for this as you see fit.

**Comment by pllim** [comment]
Doc at 3.10.x actually not affected, so updated milestone. FYI.

**Pull request merged**
