### PR TITLE
TST: Fix specviz2d test failure

### LINKED ISSUE #2476: TST: Specviz2d remote data test fails
Did the data file change?

```
        # 3 new trace objects should have been loaded and plotted in the spectrum-2d-viewer
>       assert len(sp2dv.figure.marks) == 14
E       AssertionError: assert 15 == 14
E        +  where 15 = len([FRBImage(image=array([[[0, 0, 0, 0],\n        [0, 0, 0, 0],\n        [0, 0, 0, 0],\n        [0, 0, 0, 0],\n        [0, 0,...: 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}}, tooltip_style={'opacity': 0.9}, visible=False), ...])
E        +    where [FRBImage(image=array([[[0, 0, 0, 0],\n        [0, 0, 0, 0],\n        [0, 0, 0, 0],\n        [0, 0, 0, 0],\n        [0, 0,...: 'vertical', 'dimension': 'y'}, 'color': {'dimension': 'color'}}, tooltip_style={'opacity': 0.9}, visible=False), ...] = Figure(axes=[Axis(grid_lines='none', label='x: pixels', label_offset='40', scale=LinearScale(allow_padding=False, max=... padding_y=0.0, scale_x=LinearScale(allow_padding=False, max=-0.5, min=386.5), scale_y=LinearScale(max=43.5, min=-0.5)).marks
E        +      where Figure(axes=[Axis(grid_lines='none', label='x: pixels', label_offset='40', scale=LinearScale(allow_padding=False, max=... padding_y=0.0, scale_x=LinearScale(allow_padding=False, max=-0.5, min=386.5), scale_y=LinearScale(max=43.5, min=-0.5)) = <jdaviz.configs.mosviz.plugins.viewers.MosvizProfile2DView object at 0x7f1bf14d4d90>.figure

specviz2d/plugins/spectral_extraction/tests/test_spectral_extraction.py:67: AssertionError
```

### PR DESCRIPTION
**Pull request by pllim**
### Description

I don't know why it increased to 15. I just want the green checkmark back.

Fixes #2476 

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by kecnry — COMMENTED** [review]
We definitely need to track down what changed here.  At the least we should add a check on the length before to make sure that the _intention_ of the test of 3 new marks works, and then probably inspect the 12 marks before this to make sure nothing has been added (like an all-nan green layer...).

**Comment by pllim** [comment]
I haven't been following specviz2d development so I have no idea what is going on. And I cannot look at this more today. We can merge this to get green CI and open follow up ticket to debug next sprint?

**Comment by kecnry** [comment]
The extra mark that didn't used to be there seems to be a `GenericDensityMark` and only appears with glue-jupyter 0.19 (but not 0.18).  I'm guessing this was introduced by https://github.com/glue-viz/glue-jupyter/pull/398 (even though we aren't using a scatter viewer in specviz2d).  @astrofrog - is this expected?

I'll try to reproduce in the app and see what the mark itself is and if its "harmful" or safe to ignore and update the test.

**Review by kecnry — APPROVED** [review]
The marks itself seems to be harmless - its not visible by default, and even when made visible and the only mark, doesn't actually show anything.  So I say we can merge this for now to get CI green in other PRs, but we might want a follow-up ticket/issue to try to track down the cause upstream and revert this (maybe with an inline-comment in the test pointing to that, since otherwise `11+3=15` is going to confuse someone in the future).

**Comment by pllim** [comment]
> maybe with an inline-comment in the test pointing to that

Added a comment. Is that sufficient?

**Pull request merged**
