### PR TITLE
Imviz: Add Home button by bumping glue-jupyter minversion

### PR DESCRIPTION
**Pull request by pllim**
This allows Imviz user to go back to default pan/zoom. Requires a minversion bump of dependency, which is also included in this PR. Addresses part of #564 .

### CODE REVIEW

**Review by astrofrog — APPROVED** [review]

**Comment by astrofrog** [comment]
Note that other jdaviz tools might find this useful but beyond the scope of this PR.

**Comment by pllim** [comment]
I just found a bug with this. After I click Home, Pan/Zoom doesn't work anymore. Workflow to reproduce:

1. Open image.
2. Click pan/zoom, do some panning or zooming. It works.
3. Click home.
4. Click pan/zoom again. Now it does not work.

**Comment by pllim** [comment]
Bug update: If you click pan/zoom two more times (to deselect and select again), then it works again. 🤯

**Comment by pllim** [comment]
Wait a minute... I see the home button even without this PR! Am I going crazy? The bug still there though.

**Comment by pllim** [comment]
Maybe the Home is inherited automatically from somewhere! I'll update the PR to drop the tool addition.

**Comment by pllim** [comment]
CI failure does not appear related.

**Comment by pllim** [comment]
I still think this can go in despite the bug. I opened a bug report upstream. I don't think it is something we can fix here anyway.

**Review by rosteen — APPROVED** [review]

**Pull request merged**
