### PR TITLE
Moving color cycler to JdavizViewerMixin

### PR DESCRIPTION
**Pull request by bmorris3**
### Description

In #1674 I introduced a color cycler so that each new `data` added to an instance of the `Application` would have a distinct color (up to N colors). While testing #1864, @kecnry pointed out that (1) the cycler was accidentally broken by #1742, and (2) the color cycler should cycle on the _viewer_ level rather than the app level. I implement that here.

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by kecnry — APPROVED** [review]
Thanks for the quick fix (and sorry for breaking it in the first place)!

**Comment by kecnry** [comment]
I think test failures are unrelated?  But probably something we will want to have fixed for release - @pllim?

**Comment by rosteen** [comment]
> I think test failures are unrelated? But probably something we will want to have fixed for release - @pllim?

I just restarted test jobs on `main` to see if it happens there as well.

**Comment by rosteen** [comment]
The test seems to be passing on `main`...

**Comment by kecnry** [comment]
I think they somewhat randomly fail on the cube play button.  @bmorris3 - might be worth just restarting tests and if they eventually pass we can open a follow-up issue to write more robust tests?

**Comment by bmorris3** [comment]
The failure is indeed intermittent. I can't reproduce it locally, and rerunning the Actions succeeded. 🤷🏻‍♂️ 

Thanks for your help!

**Pull request merged**
