### PR TITLE
feat: show errors, stdout and stderr in the frontend

### PR DESCRIPTION
**Pull request by mariobuikhuizen**
Add ?debug to the URL to enable this feature. A bug icon will
appear in the bottom right-hand corner when an error occurs or
when there is output to stdout or stderr. Clicking the icon opens
the log.

### CODE REVIEW

**Comment by havok2063** [comment]
@mariobuikhuizen  can you post a screenshot of what this looks like?

**Comment by mariobuikhuizen** [comment]
Using the voila-vuetify example, but it will look the same for jdaviz:
Schermafbeelding 2020-12-01 om 12 14 06
Schermafbeelding 2020-12-01 om 12 14 34
Schermafbeelding 2020-12-01 om 12 15 09
Schermafbeelding 2020-12-01 om 12 22 18

**Review by rosteen — APPROVED** [review]
Looks good to me. I ran the Cubeviz example notebook in the browser app version of jdaviz and was able to see the warnings and such by clicking on the bug icon.

**Review by javerbukh — APPROVED** [review]
Great addition! Bug icon only shows up when an error or warning shows up, which i didn't realize at first but does make a lot of sense.

**Comment by javerbukh** [comment]
Merging.

**Pull request merged**
