### PR TITLE
Fix field label typo in Collapse plugin

### PR DESCRIPTION
**Pull request by rosteen**
Simple enough.

### CODE REVIEW

**Review by pllim — APPROVED** [review]

**Comment by duytnguyendtn** [comment]
Any idea why the RTD test failed? I don't see a traceback anywhere in the logs even indicating a failure

**Comment by pllim** [comment]
Yes, see #612 for the fix.

**Comment by javerbukh** [comment]
Merged #612. This should be good after a rebase.

**Comment by pllim** [comment]
I think you can just merge this regardless. It won't affect RTD in any way.

**Review by javerbukh — APPROVED** [review]
Much better.

**Comment by javerbukh** [comment]
I think @duytnguyendtn needs to hit the button on this one.

**Pull request merged**
