### PR TITLE
BUG: Also check for inf in spaxel tool

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to fix https://github.com/spacetelescope/jdaviz/issues/3362 .

The fix is so tiny... Do we really need a change log or test here, @rosteen ?

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)? [🐱](https://jira.stsci.edu/browse/JDAT-5044)

### CODE REVIEW

**Comment by rosteen** [comment]
This might fix the error traceback, but I don't think it results in the behavior that we want. Even if half the spectrum at a given spatial location is NaN, we still want to show the other half. I'm pretty sure this worked before but I don't know what would have changed to break it.

**Comment by pllim** [comment]
@rosteen good catch, my previous check was flawed. I changed `all` to `any`. Does this address your concern? The root of the problem is that the uncert has data that is all `inf` and it was not caught.

**Comment by rosteen** [comment]
> @rosteen good catch, my previous check was flawed. I changed `all` to `any`. Does this address your concern? The root of the problem is that the uncert has data that is all `inf` and it was not caught.

Well, it addresses the last concern, but now the original problem is back ☹️. Seems like any `inf` makes JSON sad, it doesn't have to be all `inf`.

**Comment by rosteen** [comment]
Might be helpful to test with this cube: https://stsci.box.com/shared/static/gts87zqt5265msuwi4w5u003b6typ6h0.gz

**Comment by pllim** [comment]
Oops maybe I should have added a test after all. I'll have to look into that when I have time. When I turn that warning into exception, traceback said it was from `_profile_viewer.set_limits` but I don't see how `inf` could mess that up. Will have to investigate more. Sorry for wasting your time.

**Comment by pllim** [comment]
Re: test -- I got to the point where I have the code to produce the warning without human interaction on notebook using MANGA.

https://github.com/spacetelescope/jdaviz/blob/48be1548a8b00be113966fbc8c354dd6fdac1026/jdaviz/configs/cubeviz/plugins/tools.py#L129

```python
viewer.toolbar.active_tool = viewer.toolbar.tools['jdaviz:spectrumperspaxel']
viewer.toolbar.active_tool._mouse_move_worker(32, 54)  # something like that
```

*But...* the warning only shows up when I am in an interactive notebook session.  When I code that into CI test and run it non-interactively, the test refuses to fail even when we turn warning into exception.

So I couldn't add a test to this PR after all.

**Review by rosteen — APPROVED** [review]
LGTM now, thanks!

**Pull request merged**
