### PR TITLE
TST: Cancel duplicate CI builds

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request adds the ability for GitHub Actions to cancel duplicate CI builds.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
is this for duplicate builds in the same PR or commit (when force pushing)?

**Comment by pllim** [comment]
@kecnry , it is copied from https://docs.github.com/en/actions/using-jobs/using-concurrency#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow but really I copied this from `photutils` implementation by @larrybradley . I hope `.workflow` here means a unique workflow ID and not just the name for the entire workflow across the repo. I *think* this incantation cancels a duplicate run tied to the same PR and should not touch a different PR or branch, but maybe Larry can confirm. If not, we can probably print out the `.workflow` and `.ref` and see for ourselves.

**Comment by kecnry** [comment]
That's a bit tough to test without merging... but I guess we can assume that's the case and we can always revert if it causes issues with our... "workflow"?

**Comment by pllim** [comment]
We already have that deployed over at astropy (e.g., https://github.com/astropy/astropy/blob/main/.github/workflows/ci_workflows.yml) and I have not noticed anything strange yet (but I also was not looking too closely).

**Review by kecnry — APPROVED** [review]

**Pull request merged**
