### PR TITLE
Fix specviz autoscale_x method with redshift

### LINKED ISSUE #412: Modifying Redshift Slider breaks Autoscale along the spectral axis
The title sounds SUPER similar to what @rosteen found in #404, but I think it's different. With the redshift applied, autoscale seems to set the bounds to the wrong values.

Reproducibility steps:

1. Load spectra
2. Set Redshift Slider
3. `specviz.autoscale_x()`

image

### PR DESCRIPTION
**Pull request by rosteen**
Fix #412

### CODE REVIEW

**Comment by ibusko** [comment]
I can display a line list and then, as I slide the redshift slider to any no-zero value, the lines keep displaying in a loop. I believe this was fixed already, so I must be using an older library or something.

**Comment by rosteen** [comment]
Performance with the redshift slider is known to be poor with lots of lines, I recommend in the docs to use it with no more than around a dozen lines. Maybe I should also throw a snackbar warning about that when a preset line list is loaded.

**Review by ibusko — APPROVED** [review]
Seems to be working as expected.

**Comment by javerbukh** [comment]
I'm getting the following traceback. It seems that removing the line causing the error fixes it and then works as intended.
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-b4cc3ee05785> in <module>
----> 1 specviz.autoscale_x()

~/Documents/jdadf_notebooks/jdaviz/jdaviz/configs/specviz/helper.py in autoscale_x(self)
    156 
    157         """
--> 158         self.x_limits("auto", "auto")
    159 
    160     def autoscale_y(self):

~/Documents/jdadf_notebooks/jdaviz/jdaviz/configs/specviz/helper.py in x_limits(self, x_min, x_max)
     93         ref_spec = self.get_spectra(ref_index, apply_slider_redshift=False)
     94         self._set_scale(scale, ref_spec.spectral_axis, x_min, x_max)
---> 95         self._set_scale(scale, spectral_axis, x_min, x_max)
     96 
     97     def y_limits(self, y_min=None, y_max=None):

NameError: name 'spectral_axis' is not defined
```

**Comment by rosteen** [comment]
Whoops, good catch @javerbukh . Deleted that line, should be good to go now I think.

**Review by javerbukh — APPROVED** [review]
Looks good!

**Comment by javerbukh** [comment]
Merging.

**Pull request merged**
