### PR TITLE
Backport PR #3123 on branch v3.10.x (Fix cube fit toggle with spectral subset selected)

### PR DESCRIPTION
**Pull request by meeseeksmachine**
Backport PR #3123: Fix cube fit toggle with spectral subset selected

### CODE REVIEW

**Review by pllim — APPROVED** [review]

**Comment by kecnry** [comment]
I should have paid more attention during the original PR - is this confirmed as a bug in 3.10 and not just main?

**Comment by kecnry** [comment]
The behavior for the cube toggle was changed in https://github.com/spacetelescope/jdaviz/pull/2827 which is milestoned as 4.0, so even though the diff seems to be able to backport, I'm not sure that the bug was present until then 🤔

**Comment by rosteen** [comment]
I'll double check.

**Comment by rosteen** [comment]
You're right, I milestoned that PR incorrectly. I'll close this and open a quick PR to move the changelog entry.

**Pull request closed without merging**
