### PR TITLE
Move set collapse function to init method

### PR DESCRIPTION
**Pull request by javerbukh**
### Description

This pull request is to address the problem that the Specviz viewer would reset it limits every time data was added. That line of code has been removed and the original code to set the collapse function to sum is in the init method

Follow-up of #1229 .

Close #1236

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
I see this in Cubeviz example notebook with your patch. Is it just me? 

Screenshot 2022-04-06 152027

**Comment by pllim** [comment]
Ah, sorry, I had glue-astronomy dev version installed and for some reason the pin in this package setup didn't uninstall it. 🤷

**Review by pllim — APPROVED** [review]
Works as advertised but I only ran the basic examples.

**Review by kecnry — APPROVED** [review]
This has the added benefit that a user-override of the function will stick if removing and re-adding data!

**Comment by pllim** [comment]
Thanks!

**Comment by javerbukh** [comment]
Thanks for helping me figure this out! You guys are the best 😄

**Pull request merged**
