### PR TITLE
Use subsets for spectrum-at-spaxel tool

### LINKED ISSUE #1374: Add ability to select multiple spaxels using spectrum at spaxel tool
**Reporter: Jesse Averbukh**

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### LINKED ISSUE #1375: Investigate using subsets for spectrum-at-spaxel tool
**Reporter: Jesse Averbukh**

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by javerbukh**
### Description

This pull request changes the spectrum-at-spaxel tool to use subsets instead of new Spectrum1D objects.

Fixes #1375
Fixes #1374

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Need to make flake8 happy. 😉

**Comment by javerbukh** [comment]
As flake8 commands! Also, since @Jenneh is on vacation for a few weeks, can we leave the UI decisions out of this PR and open new tickets for them? Specifically, whether this tool should be on it's own or under the subset section (also whether it is first, second, or third in that section) and how to change the icon to make it more clear what the tool actually does.

**Review by kecnry — APPROVED** [review]
Much faster, and I think actually creating a subset is going to be more convenient than a dataset that acts similar to a subset.  And as an added benefit, the code is much more concise!

I agree the icon and possibly its position can be deferred, but I'll add my opinion now anyways (feel free to ignore for this PR if the decision is to leave these changes for a future iteration).  This new implementation has behavior almost identical to the other subset tools, but not quite exactly the same, which I'm worried would add some user-confusion.  I would vote to have this behave exactly as the other subset selection tools (no alt-key or automatic-replace logic - unless we implement those across all the others as well), in the subset group of tools instead of its own entry, and with a consistent icon/tooltip.

**Review by duytnguyendtn — APPROVED** [review]
Works really well! I've always been a fan of the subset approach for this effort and I'm so glad you got it working :D

I will follow the same pattern as @kecnry and approve now while echoing my two cents about the icon. IMHO I think we should update the icon (it isn't intuitive to me at least) and I also believe it should go under the other subset tools dropdown. Though I see @PatrickOgle's opinion about this being a very pertinent scientific tool, I also think we're starting to creep back to the original overpopulated toolbar. We should be careful here

**Comment by javerbukh** [comment]
Ok, I am merging as is and creating new tickets to potentially move this to the subset section and change the icon. Thank you for the feedback!

**Pull request merged**
