### PR TITLE
Attempted first draft of citation instructions

### PR DESCRIPTION
**Pull request by ojustino**
### Description

I added the Zenodo link to the documentation's index page. Would we like it in the README, too?

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by rosteen** [comment]
I think adding a short section to the ReadMe too is a great idea. I hadn't thought about whether this was said anywhere in the docs, thanks!

**Comment by ojustino** [comment]
Thanks for the suggestion, @rosteen; I just added the instruction to the README.

Approvals are welcome should anyone want to give them, but since it seemed like @pllim wanted to weigh in on this, perhaps a subsequent merge should wait.

**Review by kecnry — APPROVED** [review]
Works for me - thanks!  (Built version of docs can be [previewed here](https://jdaviz--1511.org.readthedocs.build/en/1511/)).

I agree that we should wait for @pllim before merging, if possible.

**Comment by ojustino** [comment]
@pllim, I've drafted a version of that file and don't mind adding it here, but it looks like everyone who's interested would need to give me their ORCID. We would also need to add a step to our release procedure for updating the "version" and "date released" entries in `CITATION.cff`.

**Comment by ojustino** [comment]
I'm guessing the order of authors should also merit its own discussion...

**Comment by rosteen** [comment]
We determined offline that adding the Citation file can go in a separate PR. This has 2 approvals, so I'm going to go ahead and merge.

**Pull request merged**
