### PR TITLE
Backport PR 2862 onto v3.10.x (Prevent repeatedly updating previews in specviz2d spectral extraction)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to manually backport https://github.com/spacetelescope/jdaviz/pull/2862 onto v3.10.x

The diff don't match exactly. I think @kecnry should review.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
`F821 undefined name 'skip_if_not_tray_instance'`

Does something else need to get backported first?

**Comment by kecnry** [comment]
> F821 undefined name 'skip_if_not_tray_instance'

Probably just need the import

**Comment by pllim** [comment]
Re: https://github.com/spacetelescope/jdaviz/pull/2864#issuecomment-2101517565

I ended up removing it because that code isn't part of the diff I am backporting.

**Comment by pllim** [comment]
@rosteen has agreed to review this when he gets the chance.

**Review by rosteen — APPROVED** [review]
I tested to make sure it behaves the same as on main, looks good.

**Pull request merged**
