### PR TITLE
Attempt to fix subsets applying to multiple spectra

### LINKED ISSUE #1843: Specviz get_spectra() call does not return correctly with multiple spectra
**Reporter: Jesse Averbukh**

This is first mentioned by Cami in JDAT-2594. To see the behavior, add two spectra to Specviz, then add multiple subsets. Then run `specviz.get_spectra()`. The output should imply that the subsets have a spectral axis that starts where the second spectra starts (assuming it is at a higher wavelength). The expected behavior is that the subset has a spectral axis that corresponds to the spectrum it is attached to.

A question for others, what is the expected output when a subset is attached to multiple spectra?

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by javerbukh**
### Description

This pull request is to address subsets not being applied to multiple spectra. You can see some of the paradigms implemented here by putting the following code block into the SpecvizExample notebook:

```
from glue.core.roi import XRangeROI

file = "jw02732-c1001_t004_miri_ch1-longmediumshort-_x1d.fits"
file2 = "jw02732-c1001_t004_miri_ch2-longmediumshort-_x1d.fits"
specviz.load_spectrum(file)
specviz.load_spectrum(file2)

specviz.app.get_viewer("spectrum-viewer").apply_roi(XRangeROI(7, 8))
```
Then
`specviz.get_spectral_regions()` will return
```
{'Subset 1:jw02732-c1001_t004_miri_ch1-longmediumshort-_x1d': Spectral Region, 1 sub-regions:
   (7.000500195135828 um, 7.649500225961674 um) ,
 'Subset 1:jw02732-c1001_t004_miri_ch2-longmediumshort-_x1d': Spectral Region, 1 sub-regions:
   (7.511000228929333 um, 7.99900025210809 um) }

```

which sets the data label to a concatenation of Subset 1 and the spectra it is applied to.

`specviz.get_spectra('Subset 1', apply_slider_redshift=None)` returns
```
{'jw02732-c1001_t004_miri_ch1-longmediumshort-_x1d': <Spectrum1D(flux=<Quantity [22.06800698, 21.67234675, 18.13024819, ..., 67.15146685,
            66.67507554, 66.62986612] MJy / sr>, spectral_axis=<SpectralAxis [4.9005001 , 4.9015001 , 4.9025001 , ..., 7.64750023, 7.64850023,
    7.64950023] um>, uncertainty=StdDevUncertainty([6.66712587, 5.90540278, 5.63616389, ..., 5.74446156,
                    5.51737985, 5.41050451]))>,
 'jw02732-c1001_t004_miri_ch2-longmediumshort-_x1d': <Spectrum1D(flux=<Quantity [36.39466612, 36.53507052, 35.3381142 , ..., 53.61827448,
            53.18940731, 52.5410928 ] MJy / sr>, spectral_axis=<SpectralAxis [ 7.51100023,  7.51300023,  7.51500023, ..., 11.70500043, 11.70700043,
    11.70900043] um>, uncertainty=StdDevUncertainty([2.99726213, 2.74131887, 2.58385531, ..., 2.75868379,
                    2.70428171, 2.76932534]))>}
```

which is a dictionary of all of the spectra where Subset 1 is applied.

Is this implementation the direction we want to go in or do we want to pick one and be consistent with it app-wide? This PR introduces more bugs than it fixes so I will keep it in draft until we decide on a direction.

Fixes #1843

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
What if there are multiple Subsets?

**Comment by javerbukh** [comment]
The dict approach would be `[Subset 1: {label1: Spec1D, label2: Spec1d}, Subset 2: {label1: Spec1D, label2: Spec1d}]` and the other approach would be `[Subset 1:label1, Subset 1:label2, Subset 2: label1, Subset 2: label2]` with each being demonstrated by `specviz.get_spectral_regions()` and `specviz.get_spectra(apply_slider_redshift=None)`, respectively.

**Comment by pllim** [comment]
But wouldn't someone want `label1` with all the subsets applied? (I actually have no idea, might have to ask PO.) So something like this:

```python
{label1: Spectrum1D_with_all_subsets_as_combined_mask,
 label2: Spectrum1D_with_all_subsets_as_combined_mask,
 ...
}
```

**Comment by javerbukh** [comment]
I could definitely see that being a new app or helper level method, but I'm not sure about using that in `get_data_from_viewer`. @camipacifici @PatrickOgle @eteq do you have an opinion on this?

**Comment by kecnry** [comment]
> But wouldn't someone want `label1` with all the subsets applied?

What would that even mean?  Wouldn't we need to assume what logic operator to combine subsets?

**Comment by pllim** [comment]
> What would that even mean?

Say, if someone loads a spectrum, then have Subsets marking lines of interest. Then they want to export the spectrum out with stuff not of interest masked out?

If that is not a common case, then maybe Subsets should be exported just as boolean mask arrays. It makes little sense to export the same spectrum but only masked differently.

**Comment by javerbukh** [comment]
Work has moved to #1886 , closing this PR.

**Pull request closed without merging**
