### PR TITLE
Save viewer figure to PNG or SVG

### PR DESCRIPTION
**Pull request by rosteen**
This is working for the spectrum viewer, but I'm creating the PR as draft for now because the image viewers results in only the axes showing up in the saved images. I'm working on coming up with a fix for that.

### CODE REVIEW

**Comment by rosteen** [comment]
Moving to ready for review, since the image viewer issue is an underlying bug in bqplot ([bqplot issue 1174](https://github.com/bqplot/bqplot/issues/1174)). I commented there to hopefully get some more dev attention on the issue.

**Comment by dtn5ah** [comment]
Ok tried to test this again this morning. Neither button *seems* to be doing anything (or at least I can't find any evidence of a file being written), but no tracebacks either. Would agree with @javerbukh that we should probably have some kind of feedback
Windows 10.0.19041: Chrome 84.0.4147.105 64-bit, Edge 84.0.522.52 64-bit

**Comment by rosteen** [comment]
Thanks for the help figuring out that I was missing a commit here @dtn5ah .

I'm inclined to think that we should wait to merge until the bqplot bug in saving image marks is fixed, but I'm undecided. Thoughts, @eteq ?

**Comment by eteq** [comment]
Check-in on this - looks like bqplot/bqplot#1174 just got closed, does that mean this is now working, @rosteen ?

**Comment by rosteen** [comment]
Indeed, as I mentioned offline (and should have commented here) the related bqplot PRs were merged, but they haven't done a release yet with the fixes so I don't think that the fixes would be present in a jdaviz install. They're supposed to be doing a release with the fixes next week, so I was planning to keep an eye on that and merge this after the bqplot release.

**Comment by eteq** [comment]
Ok, cool.  Then I agree with your statement above that once it's released we can call this good!

**Comment by rosteen** [comment]
The bqplot dependencies were released, I checked a clean install off this branch and everything works. I rebased to master, will merge once the CI runs.

**Pull request merged**
