### PR TITLE
Viewer bar update

### LINKED ISSUE #525: JDAT-800: Break Gear Icon into Data and Display Icons
Gear icon currently has multiple hidden menus (Data, Layer, Viewer).  Break these into separate icons (Data, Display, Viewer).

https://jira.stsci.edu/browse/JDAT-800

### PR DESCRIPTION
**Pull request by javerbukh**
Resolves #525 

Replaces the "hammer and screwdriver" icon with a "Data" dropdown and three buttons to handle the rest of the functionality. Since I am inexperienced with front-end development, there are a few things I still have questions on.

- [x] When I hover over the viewer, it snaps to the center (i.e. scrolls down and takes the viewer bar out of view). I thought this was fixed, although it might be and I'm just in an older version. Follow up to this though, how can I make it so that the bar + viewer take up the entire height so that there is no need to scroll?
- [x] In codepen, the "Data" dropdown is in the center with the 3 buttons to the right edge, but for some reason the same code does not work here. Any ideas?
- [x] I would like to replace "Data" with the name of the viewer (something like `label=viewer.id`), how do I do that?
- [x] Clicking the plugin tray makes it so that the 3 right buttons are not visible. This may be a lower priority item, however.

Any advice from @mariobuikhuizen or any other person with CSS experience would be appreciated!

Screen Shot 2021-05-13 at 3 17 50 PM

### CODE REVIEW

**Comment by mariobuikhuizen** [comment]
Hi @javerbukh, https://github.com/glue-viz/bqplot-image-gl/pull/56 (which is not yet merged and released) indeed fixes the snapping, although if we fix the height issue there would be no room to snap any more.

**Comment by javerbukh** [comment]
That's what I'm thinking as well! I tried a few spots to adjust the height in `container.vue` but I could not find where it is set (for the viewer area height). Any theories as to where it could be?

**Comment by javerbukh** [comment]
Thank you for the fix @mariobuikhuizen !
Update to UI:
Screen Shot 2021-05-18 at 2 56 38 PM

**Comment by mariobuikhuizen** [comment]
Hi @javerbukh, you may have missed https://github.com/javerbukh/jdaviz/pull/5.

**Comment by javerbukh** [comment]
@mariobuikhuizen I did! Thank you for pointing me towards it!!

**Comment by javerbukh** [comment]
There is still the same viewer snapping interaction in mosviz when a mouse over event happens (the mouse is invisible in the attached GIF for some reason), but only on the top right 2 viewers. I'm not sure why this happens in only mosviz, do you have any thoughts @mariobuikhuizen ?
Jun-01-2021 14-26-43

**Comment by mariobuikhuizen** [comment]
You might not have the bqplot-image-gl with the snap fix installed: https://github.com/glue-viz/bqplot-image-gl/pull/56.

**Comment by pllim** [comment]
Note: If glue-viz/bqplot-image-gl#56 does fix the problem, a new `bqplot-image-gl` release would be nice so we can pin it here. Thanks!

**Comment by javerbukh** [comment]
@mariobuikhuizen I am getting errors anytime I try to download the dev version of bqplot-image-gl. I follow the install instructions but get a long traceback that includes:
```
    subprocess.CalledProcessError: Command '['/Users/javerbukh/opt/anaconda3/envs/bqplot_jdaviz-dev/bin/npm', 'run', 'build']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/javerbukh/opt/anaconda3/envs/bqplot_jdaviz-dev/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/javerbukh/Documents/jdaviz_dev/bqplot-image-gl/setup.py'"'"'; __file__='"'"'/Users/javerbukh/Documents/jdaviz_dev/bqplot-image-gl/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

```

**Comment by mariobuikhuizen** [comment]
Ah, yes, you'll need nodejs for building front-end code in bqplot-image-gl. If you use conda, it can be installed with `conda install -c conda-forge nodejs=12`.

**Comment by javerbukh** [comment]
That works, thank you!! I think the bqplot-image-gl instructions need to be updated since they only mention `conda install -c conda-forge nodejs`. Would you be able to do a bqplot-image-gl release soon so this PR can use the fix?

**Comment by mariobuikhuizen** [comment]
It will probably work with newer versions of nodejs, I just have the habit of using 12 because of some problems I have with newer versions on macOS.

@maartenbreddels is planning on releasing it shortly.

**Comment by mariobuikhuizen** [comment]
It's released: https://github.com/glue-viz/bqplot-image-gl/releases/tag/1.4.1 🎉

**Review by pllim — COMMENTED** [review]
I don't use Mosviz so I can't tell if it is working as intended or not but nothing crashed. For Imviz, I noticed a slight behavior change that might or might not be desirable. See below.

**Before this patch**

1. Go to "DATA".
2. Check/uncheck box as much as you want.
3. Close it when done.

**With this patch**

1. Click "DATA" to get drop-down menu.
2. Check/uncheck one box.
3. Drop-down menu disappears.
4. I have to click it again to check/uncheck another box; and repeat.

**Comment by PatrickOgle** [comment]
I am still seeing the snapping behavior when mousing over the spectrum viewers, using bqplot-image-gl 1.4.1.  If I make
the table viewer smaller, the behavior goes away.

**Review by PatrickOgle — APPROVED** [review]
Accomplishes the goal of splitting out the data, display, and kebob menus.  Looks visually pleasing and functionality of the dropdown menus remains intact.  I don't like where the toolbar pops up, covering the image, but that might be tackled in a future PR.  The snap-on-mouseover behavior is annoying, but can be suppressed by making the table viewer smaller.

**Review by pllim — APPROVED** [review]
I am approving to remove merge block though my comment at https://github.com/spacetelescope/jdaviz/pull/617#pullrequestreview-675654192 still stands.

**Comment by PatrickOgle** [comment]
One after-the fact comment.  I just noticed that the data dropdown disappears when you click a dataset. You have to pull it down for each dataset you select/deselect

**Comment by javerbukh** [comment]
@PatrickOgle The data dropdown no longer closes when you select data.

**Comment by pllim** [comment]
I can confirm that the dropdown now works as requested. Thanks!

I might submit a follow-up PR to clean up the notebook itself. It is out of scope here.

Also out of scope and maybe y'all talk about it: For Mosviz, it does not quite make sense to have "DATA" button in all the sub-viewers. If I don't know what I am doing, I can check the wrong box in the wrong viewer and see a spectacular traceback. Maybe you don't need DATA at all here, just use the table as a way to control what gets loaded in the other viewers. Perhaps can be explored during, refact..., uh, concious decoupling.

**Pull request merged**
