### PR TITLE
Backport PR #3319 on branch v4.0.x (Respect loaded mask cube properly in spectral extraction.)

### PR DESCRIPTION
**Pull request by rosteen**
Backporting #3319

### CODE REVIEW

**Comment by pllim** [comment]
Is there another PR need backporting first?

`E   DeprecationWarning: pkg_resources is deprecated as an API.`

**Comment by pllim** [comment]
Maybe you can cherry pick that into this PR too.

**Comment by rosteen** [comment]
> Is there another PR need backporting first?
> 
> `E DeprecationWarning: pkg_resources is deprecated as an API.`

Ahh, #3327 wasn't marked with the backport label. I'll cherry pick it here (or actually, will adding the label now still pick it up automatically?).

**Comment by rosteen** [comment]
> Hmm is there something else?
> 
> ```
> jdaviz/configs/cubeviz/plugins/tests/test_parsers.py::test_manga_cube - AssertionError: 
> Not equal to tolerance rtol=1e-07, atol=0
> 
> Mismatched elements: 1 / 1 (100%)
> Max absolute difference among violations: 7.23287482e-24
> Max relative difference among violations: 2.54951866e-06
>  ACTUAL: array(2.836964e-18)
>  DESIRED: array(2.836957e-18)
> ```

It looks like this is just a slightly too small RTOL on a very small number, the test has previously passed and this was just slightly outside the range. I think it's a precision thing.

**Comment by pllim** [comment]
Given the discussion on #3350 , should we revert the rtol change here?

**Review by kecnry — APPROVED** [review]

**Pull request merged**
