### PR TITLE
Pin GWCS for astropy 4.0.3 compatibility in tests

### PR DESCRIPTION
**Pull request by rosteen**
Edits the tox config to fix compatibility failure.

### CODE REVIEW

**Comment by rosteen** [comment]
Right now we have two tests (astropy40 and astropylts) that are both testing astropy 4.0.3. It seems to me like we should update one (probably LTS?) to test astropy 4.1, both to cover the new version and reduce our testing overlap. That's something that should be a follow up PR though, I think, so for now this just fixes the tests by pinning GWCS version to the last one that didn't require astropy 4.1

**Comment by eteq** [comment]
I think this is probably fine as it stands since I'm not sure there will be any matintainence releases anyway. but maybe the version specification should be something like `>=0.14, <0.15`?  That way if there's a 0.14.1 the pinning won't get in the way.

**Review by eteq — APPROVED** [review]
I think this is probably fine as it stands since I'm not sure there will be any matintainence releases anyway. but maybe the version specification should be something like `>=0.14, <0.15`?  That way if there's a 0.14.1 the pinning won't get in the way.

(I'm not sure if that's easy/possible in `tox.ini` files, so I'm "accepting" anyway - only worth doing that if it's "easy")

**Comment by rosteen** [comment]
I'm inclined to go ahead and cancel the stuck test. It passed before the most recent change, and the second set would have failed if that caused any problems. If anyone insists on throwing credits at it I can restart it.

**Review by ibusko — APPROVED** [review]

**Pull request merged**
