### PR TITLE
Preset palettes

### PR DESCRIPTION
**Pull request by javerbukh**
### Description

This pull request adds swatches to the color picker. The colors in the swatch were picked with consultation from OPO.

image

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Should fix the codestyle failure.

Does this need approval from PO?

Does the user facing doc need to be updated on how to best utilize this new feature and when does one need it?

**Review by pllim — COMMENTED** [review]
What an elegant solution! I didn't know I need this. I was skeptical at first but this shortcut is very nice when you can't be bothered to pick something from the full spectrum.

Need a change log though.

Do you think the user doc in Plot Options also need to be updated?

**Comment by pllim** [comment]
Not technically a bug fix, do we need to backport?

**Review by kecnry — APPROVED** [review]
Code looks good to me and I think this is a good incremental solution.  Agreed that this should probably be mentioned in the changelog, doesn't qualify for a bugfix, but I don't see any need for documentation (at least not until it fits into the bigger picture for RGB workflows).  It is self-discoverable and self-explanatory.

Would still like to see approval/comments from @PatrickOgle before merge though!

**Review by pllim — APPROVED** [review]
If Patrick doesn't use it, I will!

**Review by PatrickOgle — COMMENTED** [review]
I agree this is very elegant.  Nice work.

**Pull request merged**
