### PR TITLE
Update jdaviz developer installation instructions

### PR DESCRIPTION
**Pull request by gibsongreen**
### Description
In installation.rst, the order of development install instructions have been changed (primarily to move the editable environment to the last step). The addition of IPython magic commands were included as an optional suggestion for developers, and a brief description to code contribution instructions (hyperlink to astropy instructions) was added so a new developer can briefly understand what is hyperlinked; and a general suggestion to virtual environments is now suggested.

**Original Instructions**
original_dev_instruct
**Updated Instructions**
updated_dev_instruct

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
Should we also include advice that it is necessary to install without `-e` first to copy the template files?

**Comment by gibsongreen** [comment]
> Should we also include advice that it is necessary to install without `-e` first to copy the template files?

Yes that sounds like a good idea to me

**Review by kecnry — APPROVED** [review]
Works for me - thanks!

Rendered docs can be [previewed here](https://jdaviz--2569.org.readthedocs.build/en/2569/installation.html#developer-installation).

**Comment by pllim** [comment]
Thanks and congrats on your first PR!

**Pull request merged**
