### PR TITLE
DOC: Update RTD config

### PR DESCRIPTION
**Pull request by pllim**
~If you enable PR builder for RTD, we can test this. Otherwise, we won't know till merge.~

PR builder enabled -- See status check below.

Also removing `build_docs` from CI because it is not necessary once RTD PR builder is enabled.

### CODE REVIEW

**Comment by pllim** [comment]
Finally! See preview at https://jdaviz--397.org.readthedocs.build/en/397/

**Review by rosteen — APPROVED** [review]
This is great, everything looks good to me. Thanks!

**Review by javerbukh — APPROVED** [review]
Looks good!

**Comment by javerbukh** [comment]
Merging.

**Pull request merged**
