### PR TITLE
Fill in Cubeviz Pan/Zoom and Spectral Region sections

### PR DESCRIPTION
**Pull request by rosteen**
Just like the title says.

### CODE REVIEW

**Comment by rosteen** [comment]
FYI I'm submitting in this form to get the rest of the docs filled in, but I think we should have separate issues for:

1. Converting all the `seealso` sections to a form that doesn't use hard-coded URLs
2. Splitting out a "Common Viewer Functionality" (or some such) section that is separate from and at the same level as the Specviz/Cubeviz/Mosviz top level sections. Right now we're doing a lot of linking back to Specviz for this stuff, and there's no reason Specviz should really be the "default" config.

**Review by camipacifici — APPROVED** [review]
Looks good to me.
I agree on the "Common Viewer Functionality" idea.

**Review by javerbukh — APPROVED** [review]
Looks good!

**Comment by javerbukh** [comment]
Merging.

**Pull request merged**
