### PR TITLE
BUG: Fix typo on internal method

### PR DESCRIPTION
**Pull request by pllim**
### Description

Small typo but should still fix it.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by rosteen** [comment]
I swear I saw this fixed in another PR within the last couple of days, might be in review.

**Comment by rosteen** [comment]
Yeah, Kyle had also fixed this in https://github.com/spacetelescope/jdaviz/pull/3157, which is waiting on another PR to get in first.

**Comment by pllim** [comment]
If you don't want a trivial independent fix for this typo, feel free to close.  Otherwise we can merge so we do not have to wait for that other PR that is currently "stuck". Up to you/.

**Review by kecnry — APPROVED** [review]
This doesn't affect any functionality since both cases have the same typo, but doesn't hurt to get in sooner either.

**Comment by pllim** [comment]
Ok then, I merged it. One less typo to worry about. Hopefully the rebase will be easy for you. Thanks for your understanding!

**Pull request merged**
