### PR TITLE
image viewers: default to panzoom tools

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request makes pan/zoom tools the default tool for all image viewers, which effectively disables support (without then manually disabling the default pan/zoom tool) for manually editing a subset after it has been "finalized" and therefore _avoids_ #1200.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by duytnguyendtn — APPROVED** [review]
Tried it out and I personally really like this behavior outside of trying avoid #1200! My only thought is WHICH default zoom tool should be chosen; right now in cubeviz, my image viewer defaults to box zoom. I'm thinking of the user who isn't aware of this behavior; I think the 2D/bidirectional zoom might be less disruptive when the user is just clicking around, not realizing the zoom tool is selected. With box zoom, I could see the user accidentally drawing a very small region just clicking around and their viewer zooms in super far randomly

**Comment by kecnry** [comment]
Just to clarify the new defaults in this PR would be:
* imviz: 2d panzoom or linked panzoom (whichever is "primary" in that section of the nested toolbar - unlinked is currently the default primary)
* cubeviz image viewer: boxzoom or 2d panzoom (boxzoom is currently the default primary)
* mosviz image viewer: 2d panzoom

**Comment by duytnguyendtn** [comment]
> cubeviz image viewer: boxzoom or 2d panzoom (boxzoom is currently the default primary)

I would personally advocate for 2d panzoom being default primary, but I'm happy to be outvoted. And if the user **manually** changes that tool, I can be content with reselecting whichever zoom tool the user last selected

**Comment by kecnry** [comment]
> I would personally advocate for 2d panzoom being default primary, but I'm happy to be outvoted. And if the user manually changes that tool, I can be content with reselecting whichever zoom tool the user last selected.

I agree with you wrt this PR because of your concern about accidental clicks, but outside of that, I think boxzoom is the more useful tool to have available from the start, so I'm a bit torn.  That change is just one-line, so let's see what others think and I'm happy to change it here if that's the consensus.

**Comment by pllim** [comment]
I think this PR is not unreasonable. When people are over the display, most of the time they want to pan/zoom. The only thing I am not sure about is the cursor because in this mode, I cannot get the normal pointy cursor if I want to see what value a pixel is, so my instinct is then to deactivate pan/zoom to get the normal cursor back, which then exposes the bug this is trying to hide.

So... yeah, not sure if this will completely prevent the inevitable.

**Pull request closed without merging**
