### PR TITLE
profile viewer as_steps support

### LINKED ISSUE #385: Implement histogram-style (steps, not real histogram) plots for specviz
This was discussed in several places in #133 but I'm now realizing we never broke out an issue to specifically do this.  

The goal here is to implement "histogram-style" plots instead of "line plots" - i.e., have the points on the spectrum be plotted as the center of a "box"-like plot instead of joining the segments directly as a line.  For optical spectra this is typically more physical because they are closer to the concept of "flux in boxes" vs "samples from a continuous signal".

Not everyone agrees on what I just said there, so for this issue that should be an *option*.  After this is implemented we can discuss whether it should be the default (which is what I advocated for in #133, but others were less convinced.)

[🐱](https://jira.stsci.edu/browse/JDAT-601)

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request adds an `as_steps` switch in the plot options for profile viewer layers and sets defaults for new layers.  New data layers will default to `as_steps=False` (despite glue defaulting to True) and new subset layers will default to the current state of their "parent" data layer.

~**IMPORTANT**: This requires https://github.com/glue-viz/glue-jupyter/pull/309 to be accepted/merged/released (without that pinned, the switch will still show since the state object still exists in glue, but just won't do anything in the plot... in theory we could probably add a version check to hide the switch if we want to release this before or don't want to pin the latest glue-jupyter).~

**TODO**:
- [x] If this pins glue-jupyter to include as_steps support, then this should also be updated to remove the `GLUEJUPYTER_HAS_AS_STEPS` in #1599.
- [x] add coverage for slice if-statement added in #1599.

**Subset default logic**:

https://user-images.githubusercontent.com/877591/186478114-c503b792-ead0-4d5d-abe3-f8bfedc3250f.mov

**Uncertainty styling**:

https://user-images.githubusercontent.com/877591/186507631-b004b6ef-cb99-4e48-8b45-e77c82c27933.mov

Fixes #385

### Blocked by

* https://github.com/glue-viz/glue-jupyter/pull/309

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Just wondering -- how does the uncertainty supposed to look when spectrum is in histogram mode?

**Comment by pllim** [comment]
Also -- How will the WCS-TAB data behave in histogram mode?

**Comment by kecnry** [comment]
uncertainty doesn't look great (it just keeps the old styling and doesn't know to convert itself to steps).  I'll have to look to see whether that is something that needs to be changed in glue or glue-jupyter (but shouldn't affect logic in jdaviz).

**Comment by pllim** [comment]
> if you think it's in scope to change our internal implementation to react to "as step"

Will POs accept this patch without the same change to uncertainty? I think the answer would determine where this should go.

**Comment by kecnry** [comment]
I'll dig into the uncertainty logic in the meantime to see what it would take to support (I want to avoid duplicating logic in jdaviz that was implemented in glue... but if its possible to implement while avoiding that, I can do so here)

**Comment by kecnry** [comment]
plotting uncertainties in the same style would look like the following:

image


Do we want to always use this style, even when the data is not plotted as steps (this would actually be easier as I don't need to listen to per-layer state changes and call the per-viewer jdaviz method)?

image


Or do we want to have it toggle as well to showing the connected points?


image

**Comment by camipacifici** [comment]
Sorry it is not the easier one, but the second would be better when showing the spectra not as-steps.

**Comment by PatrickOgle** [comment]
I like option 3, but not 1 or two, which give me a headache.  Can we use thin lines on option 1 instead of bars?

**Comment by kecnry** [comment]
This PR now toggles between uncertainties plotted "as steps" and not, but keeps the fill-between logic (see video added to PR description).  We can later look into re-styling the uncertainties to be vertical lines instead of using fill-between [:cat:](https://jira.stsci.edu/browse/JDAT-2693).

**Review by camipacifici — APPROVED** [review]
Tested with a MIRI spectrum and it works well. Looks good to me!

**Comment by kecnry** [comment]
IWorking on the test coverage yet before merge, but otherwise this should be ready for reviews - seems the test I updated doesn't have uncertainties and so skips the relevant lines, so I'm working on adding another test that does hit those lines and makes sure that the uncertainties mark length doubles.

**Comment by pllim** [comment]
We have been bumping minversion as needed, so if that's easier, let's do that unless it is not released yet.

**Comment by kecnry** [comment]
It has been approved but not merged (see https://github.com/glue-viz/glue-jupyter/pull/309), but we can always just consider that PR as blocking merging this.

**Comment by pllim** [comment]
OK, I added "upstream fix required" label and a "blocked by" in the original post.

**Comment by kecnry** [comment]
glue-jupyter 0.13 is now released, is pinned in this PR, and the missing coverage from #1599 is implemented here to ensure slicing works both with and without `as_steps`.

**Review by duytnguyendtn — APPROVED** [review]
Works well for me in Specviz, Cubeviz, and Mosviz! Thanks!

**Pull request merged**
