### PR TITLE
Catalogs: Use SDSS DR 16, fix other dev failures

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to work around https://github.com/astropy/astroquery/issues/2673 but maybe we want it to see for a few days in case it is fixed upstream, then we do not need this patch.

Or if we need the CI to be green sooner, we can also merge this and then revert later. 🤷 

Also have to handle https://github.com/glue-viz/bqplot-image-gl/issues/99 so we can get the dev/remote-data job green, which was the purpose of this PR. But if we don't need this PR, I can take this part out too.

Also have to ignore a deprecation warning related to #1980 .

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
`Failed to build bqplot-image-gl` -- That is annoying. Why would bqplot-image-gl now tries to build from source?

**Comment by pllim** [comment]
Oh right, it is the dev job. But why has it started failing? There is no new commit there since Aug 2022.

**Review by javerbukh — APPROVED** [review]
I think I lean towards merge and revert later but I'm ok with being overruled. Will approve in the meantime.

**Comment by pllim** [comment]
Thanks! I will open follow-up issues.

**Comment by pllim** [comment]
@meeseeksdev backport to v3.3.x

**Pull request merged**
