### PR TITLE
Imviz regions setter/getter API

### LINKED ISSUE #622: JDAT-1472: Imviz regions setters/getters in the helper
This is broken out from some discussion around #518 - where that issue is about the UI items, this issue is focused on what should be added to the imviz helper.

Specifically, I think the following is desired:

- [x]  `load_regions`/`set_regions` (Open to opinions on the name, or implementer can just pick something that makes sense to them)
- [x]  `get_regions`

The loader method should take astropy regions, do the glupyter magic that needs to happen to make them into subset selections glue understands, and add them to the app (I think there's a built-in converter now, although @astrofrog might correct me if it's not fully-featured yet?). It should probably auto-show them, although maybe that should be a keyword argument?  It should work with either sky or pixel regions, but presumably would give an error if a sky region is given but there's no WCS.

The getter should return all the region selections.  There should be an option for sky vs pixel, although I don't really have a strong opinion about what the right default is (maybe pixel since that's the only one that will always work?).   I think there's already some machinery in jdaviz to help with this that's in the cubeviz helper - I can look into it more later, but @javerbukh might have some insight?

Both should default to operating on all the viewers in the `imviz` instance at the same time, but have a way to say "just this one". We *might* eventually want a concept of only operating on the "most recently clicked" or something, but that can be dealt with later.

https://jira.stsci.edu/browse/JDAT-1472

### PR DESCRIPTION
**Pull request by pllim**
Fix #622. Second attempt of #630. (It is easier to open a new PR than to resolve conflicts of that one...)

Note to self: Open follow-up issues about modifying regions, roundtripping, GWCS support...

### CODE REVIEW

**Comment by pllim** [comment]
So, using "reference data" got around the problem I encountered in #630 . 😸

**Review by rosteen — APPROVED** [review]
Looks good, I tested the code in the example notebook and it works. The API makes sense to me. I noted some performance issues in https://github.com/spacetelescope/jdaviz/issues/723, I don't think they need to hold up this ticket but should be a priority to fix, in my opinion.

**Review by ibusko — APPROVED** [review]
Code looks good. I tested with the example notebook and it works as expected.

**Comment by pllim** [comment]
Given there are 2 approvals, I am merging. Thanks, everyone!

p.s. I ran it locally after rebase and nothing broke. The lag is very apparent but out of scope, as Ricky said.

**Pull request merged**
