### PR TITLE
MNT: Unpin pytest and move it to test requirement

### LINKED ISSUE #395: Unpin pytest
Not sure why you have this:

https://github.com/spacetelescope/jdaviz/blob/9ce9b1f5f78392650afb62e7bc2d7e02ea66ee97/setup.cfg#L21

Eventually pytest 5 will fall out of sync with the other pytest plugins, and things will break.

### PR DESCRIPTION
**Pull request by pllim**
Fix #395

### CODE REVIEW

**Review by rosteen — APPROVED** [review]
I can't think of any reason it needed to be pinned... @eteq  @javerbukh any recollection?

**Review by javerbukh — APPROVED** [review]
Can't remember why this was the case either...good find!

**Comment by javerbukh** [comment]
Merging.

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
