### PR TITLE
fix redshift slider enabled/disabled from helper methods

### LINKED ISSUE #2013: plot_spectral_line API call fails to enable redshift slider
**Reporter: Kyle Conroy**

adding the first spectral line via ``plot_spectral_line`` does not enable the redshift slider or show the correct visibility state of that line in the Line Lists plugin.  Toggling the line visibility via the plugin then correctly handles the state.

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request fixes the redshift slider re-acting to helper methods: ``load_line_list``, ``plot_spectral_line``, ``plot_spectral_lines``, or ``erase_spectral_lines``.

Fixes #2013

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
I am trying to review this and I realized I have no idea how to use that API. Haha... This is what I tried to do:

1. Fire up Specviz example notebook.
2. Load the example data.
3. Create a subset (just for fun).
4. Run `specviz.plot_spectral_line("Halpha")` but I get a traceback.

```
File jdaviz/configs/default/plugins/line_lists/line_list_mixin.py:49, in LineListMixin.plot_spectral_line(self, line)
     45 def plot_spectral_line(self, line):
     46     """Convenience function to get to the viewer function"""
     47     self.app.get_viewer(
     48         self._default_spectrum_viewer_reference_name
---> 49     ).plot_spectral_line(line)

File jdaviz/configs/specviz/plugins/viewers.py:253, in SpecvizProfileView.plot_spectral_line(self, line, plot_units, **kwargs)
    250 if isinstance(line, str):
    251     # Try the full index first (for backend calls), otherwise name only
    252     try:
--> 253         line = self.spectral_lines.loc[line]
    254     except KeyError:
    255         line = self.spectral_lines.loc["linename", line]

AttributeError: 'NoneType' object has no attribute 'loc'
```

I must be doing something wrong.

**Comment by pllim** [comment]
Okay, nvm. It works if I do this first:

```python
from astropy.table import QTable

lt = QTable()
lt['linename'] = ['O III', 'Halpha']
lt['rest'] = [5007, 6563]*u.AA
specviz.load_line_list(lt)
```

**Comment by kecnry** [comment]
The line must already be loaded either from the API or the UI (we should arguably make that error message and the API docs more clear, but I think that's out of scope here?)

**Review by pllim — APPROVED** [review]
I don't grok the internals but the diff looks simple enough and `plot_spectral_line` enables the slider now. Thanks!

**Pull request merged**
