### PR TITLE
DOC: Note about offline docs

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to tell users where to download documentation for offline use because it is no longer shipped with package releases as of v2.7 onwards.

This is a follow-up of #1464 .

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
My only concern is that this takes up valuable space at the very top landing page of the docs... do enough people want offline docs that this is worth that real estate?  Do people not know where to find the downloads from the dropdown (drop up?) menu at the bottom-left of RTD?

We can always remove or move it later if you think its important to have in place now for anyone that might miss the packaged docs.

**Comment by pllim** [comment]
> valuable space

I'll be happy to move that text somewhere else if you want. I just don't know where.

> Do people not know where to find

Anything that requires them to open up something tiny at the bottom left, 90% of users won't find it on their own.

**Comment by rosteen** [comment]
Maybe move both notes below the first two paragraphs of text (before the instrument modes section), so they aren't the first thing the user sees?

**Comment by pllim** [comment]
Okay, I moved them. OK now?

**Review by rosteen — APPROVED** [review]

**Comment by pllim** [comment]
Thanks for the reviews!

**Pull request merged**
