### PR TITLE
Add jdaviz logo to GitHub readme 

### PR DESCRIPTION
**Pull request by ibusko**

### CODE REVIEW

**Comment by javerbukh** [comment]
I think this is a good addition, however I think we can place this logo at the top of the README to replace the text `JDAViz`. Does that sound good?

**Comment by ibusko** [comment]
The page looks way better with the logo at the top!

**Review by javerbukh — APPROVED** [review]
Looks great!

**Review by rosteen — APPROVED** [review]
Looks good!

**Comment by javerbukh** [comment]
Huh, I'm not seeing the updates from Ori's PR. Are you sure you rebased from the master branch?

**Review by dtn5ah — APPROVED** [review]
Love seeing that logo!

**Comment by ibusko** [comment]
@javerbukh the change I am committing is a 1-liner. The diff shows no conflicts, so I presume all previous PRs are in there already.

**Comment by rosteen** [comment]
Merging, doesn't need to be rebased if there are no conflicts as far as I know @javerbukh.

**Pull request merged**
