### PR TITLE
IPyWidgets on standalone webpage + electron

### PR DESCRIPTION
**Pull request by nmearl**
This PR demonstrates rendering ipywidgets on a standalone webpage as well as embedded in an electron app.

Currently, there are issues with displaying bqplot widgets -- this has to do with the custom `jupyter-astroimage` buried within the installation that is not registered with the node package manager on installation. The `jupyter-astroimage` package is not available on the npm registry and so currently is not identified when rendering on the page.

Currently attempting to work around this issue by manually linking the package as a local dependency.

### CODE REVIEW

**Comment by brechmos-stsci** [comment]
The bqplot stuff is super important for all this.  Do you think you will get it working today?

**Comment by havok2063** [comment]
I'm actually having the same issues trying to get any bqplot stuff or widget to display in the web page.  I get a bunch of errors regarding rendering children elements.  I even tried stripping it down to a barebones HBox widget and couldn't get it working.

**Comment by nmearl** [comment]
It's no longer an issue with bqplot, as I can display a raw bqplot just fine. I think it has to do with the glue implementation and its use in your cubeviz hack.

**Comment by havok2063** [comment]
I still have issues with the standard bqplot.  I pulled your most recent changes and this is what I see.  

Screen Shot 2019-05-16 at 2 09 59 PM

**Comment by nmearl** [comment]
This is a css issue. Try with the latest push.

**Comment by brechmos-stsci** [comment]
Could you rebase? I was just going to ck it, but I think it is behind a bit.

**Comment by nmearl** [comment]
Everything shows that it's update-to-date with master. Could you also give me write access to this repo?

**Comment by brechmos-stsci** [comment]
@eteq could you give Nick access? I don't believe I have the ability to give access to others (no Settings).

**Comment by nmearl** [comment]
@brechmos-stsci Please go ahead and review this based on the install instructions. I'd encourage you to write down the specific issues you're having here as well as the results of any extra debugging instructions.

**Comment by brechmos-stsci** [comment]
@nmearl is this branch ready for merge?  I believe one person has already installed and run this...  I can still go through and do a test install.

**Comment by nmearl** [comment]
This is ready for merging. Cami was successfully able to install and run the web app and electron app locally. @javerbukh intended to attempt to install as well in an effort to review the PR. If Cami is sufficient, this can be merged now.

**Pull request merged**
