### PR TITLE
Implement registries for plugins

### PR DESCRIPTION
**Pull request by nmearl**
This supports the effort of designing the default glue-jupyter application infrastructure in which layouts are composed of reference plugin objects living in registries. This PR defines the registries and their interactions.

### CODE REVIEW

**Comment by brechmos-stsci** [comment]
Only comment here is it might be helpful to have an example or two that are specific. The tests arethere but maybe a specific exmaple?

**Comment by nmearl** [comment]
@brechmos-stsci Can you elaborate a bit more?

**Comment by brechmos-stsci** [comment]
Is there somewhere that I can see an example of the way to actually do the registration?  Might be that I am just missing the point.  if so, I am fine.

**Comment by nmearl** [comment]
The registration is done using the [class decorator](https://github.com/spacetelescope/jdaviz/pull/42/files#diff-529ab32a6f51ed833c9d91e61a6fa213R10), used in the tests. Is that what you mean?

**Pull request merged**
