### PR TITLE
line-analysis: expose uncertainties when provided

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request exposes uncertainties (where available) in the line analysis plugin (centroid will require https://github.com/astropy/specutils/pull/938, line flux already exists, but is hidden if nan/inf).

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Seems to work as advertised using example from https://specutils.readthedocs.io/en/stable/spectrum1d.html#including-uncertainties . Thanks!

```python
import numpy as np
from astropy.nddata import StdDevUncertainty
from specutils import Spectrum1D

spec = Spectrum1D(spectral_axis=np.arange(5000, 5010)*u.AA,
                  flux=np.random.sample(10)*u.Jy,
                  uncertainty=StdDevUncertainty(np.random.sample(10) * 0.1))
specviz.load_spectrum(spec, data_label='test')
```

Screenshot 2022-03-28 141656

**Comment by pllim** [comment]
Do you want to add a test? 😉

**Comment by kecnry** [comment]
I'm worried any test will just test specutils more than jdaviz... any suggestions?

**Comment by pllim** [comment]
Maybe a simple test just to make sure the "+/-" stuff is displayed when uncertainty is present, and not when not? Simple regex match on the GUI text element should suffice if you don't care about the values?

**Comment by javerbukh** [comment]
Seems to work as expected in Specviz but in Cubeviz the results for line analysis seem to hang and all I see is the loading icon.
Screen Shot 2022-03-28 at 7 00 04 PM

**Comment by kecnry** [comment]
@javerbukh - I couldn't exactly reproduce the hang, but could get a traceback when the continuum was below zero and fixed that.  Can you check if that fixed what you were seeing as well?

**Pull request merged**
