### PR TITLE
Update to specutils 1.4.0

### PR DESCRIPTION
**Pull request by rosteen**
### Description

Simple enough. Depends on the imminent specutils release which should happen in the next...oh, say 10 minutes.

### CODE REVIEW

**Review by pllim — APPROVED** [review]

**Comment by rosteen** [comment]
Specutils release is done!

**Comment by rosteen** [comment]
Readthedocs didn't seem to find the new version, I reran the rest of the tests but that one didn't run? Probably safe to merge anyway.

**Comment by pllim** [comment]
Hold on, lemme see...

**Comment by pllim** [comment]
Going to close/re-open to kick off RTD again. Want to make sure we don't need to update RTD config.

**Pull request merged**
