### PR TITLE
user API for spectral extraction

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request extends on #1401 and provides user-API access to the spectral extraction plugin.

[Plugin User API docs](https://jdaviz--1639.org.readthedocs.build/en/1639/api/jdaviz.configs.specviz2d.plugins.spectral_extraction.spectral_extraction.SpectralExtraction.html#jdaviz.configs.specviz2d.plugins.spectral_extraction.spectral_extraction.SpectralExtraction)

**TODO**:
- [x] decide if #1600 or #1601 would result in API breaks that would then warrant delaying exposing this as public user API
- [x] add PR to changelog if before next release, otherwise add new entry (waiting until PR is accepted otherwise to avoid constant merge conflicts)

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by javerbukh** [comment]
In the Specviz2D notebook, I open the Spectral Extraction plugin and scroll down to Extraction Type, I see two options in the dropdown for `object Object` and `object Object`, selecting either causes a traceback. Is this a bug from outside the PR?
Screen Shot 2022-09-15 at 1 43 44 PM

traceback
<details>

```

---------------------------------------------------------------------------
TraitError                                Traceback (most recent call last)
File ~/opt/anaconda3/envs/testing_conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py:756, in Widget._handle_msg(self, msg)
    754         if 'buffer_paths' in data:
    755             _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 756         self.set_state(state)
    758 # Handle a state request.
    759 elif method == 'request_state':

File ~/opt/anaconda3/envs/testing_conda/lib/python3.8/site-packages/ipywidgets/widgets/widget.py:625, in Widget.set_state(self, sync_data)
    622 if name in self.keys:
    623     from_json = self.trait_metadata(name, 'from_json',
    624                                     self._trait_from_json)
--> 625     self.set_trait(name, from_json(sync_data[name], self))

File ~/opt/anaconda3/envs/testing_conda/lib/python3.8/site-packages/traitlets/traitlets.py:1609, in HasTraits.set_trait(self, name, value)
   1607     raise TraitError(f"Class {cls.__name__} does not have a trait named {name}")
   1608 else:
-> 1609     getattr(cls, name).set(self, value)

File ~/opt/anaconda3/envs/testing_conda/lib/python3.8/site-packages/traitlets/traitlets.py:689, in TraitType.set(self, obj, value)
    688 def set(self, obj, value):
--> 689     new_value = self._validate(obj, value)
    690     try:
    691         old_value = obj._trait_values[self.name]

File ~/opt/anaconda3/envs/testing_conda/lib/python3.8/site-packages/traitlets/traitlets.py:721, in TraitType._validate(self, obj, value)
    719     return value
    720 if hasattr(self, "validate"):
--> 721     value = self.validate(obj, value)  # type:ignore[attr-defined]
    722 if obj._cross_validation_lock is False:
    723     value = self._cross_validate(obj, value)

File ~/opt/anaconda3/envs/testing_conda/lib/python3.8/site-packages/traitlets/traitlets.py:2400, in Unicode.validate(self, obj, value)
   2398         msg = "Could not decode {!r} for unicode trait '{}' of {} instance."
   2399         raise TraitError(msg.format(value, self.name, class_of(obj)))
-> 2400 self.error(obj, value)

File ~/opt/anaconda3/envs/testing_conda/lib/python3.8/site-packages/traitlets/traitlets.py:827, in TraitType.error(self, obj, value, error, info)
    821 else:
    822     e = "The '{}' trait expected {}, not {}.".format(
    823         self.name,
    824         self.info(),
    825         describe("the", value),
    826     )
--> 827 raise TraitError(e)

TraitError: The 'ext_type_selected' trait of a SpectralExtraction instance expected a unicode string, not the dict {'label': 'Boxcar'}.
```

</details>

**Comment by kecnry** [comment]
@javerbukh - fixed, thanks for catching that (it was introduced in this PR by changing to a `SelectPluginComponent` but forgetting to update that one entry in the .vue file)

**Review by javerbukh — APPROVED** [review]
Code looks and works well, hoping someone with spectral extraction experience can test out that part more thoroughly. Nice work!

**Comment by kecnry** [comment]
Rebased on top of #1556 to now include `trace_dataset` in the user API.

**Review by pllim — APPROVED** [review]
Code looks like code.

At some point, there needs to be more user doc on how to use this complicated plugin, but let's get this one in so we can move on for now. Thanks!

**Pull request merged**
