### PR TITLE
Only run test_plugin_image_with_result in dev job

### LINKED ISSUE #2083: TST: Only run test_plugin_image_with_result in "allowed to fail" job
Have to figure out how to run `test_plugin_image_with_result` in `jdaviz/configs/imviz/tests/test_catalogs.py` only in the "allowed to fail" job without excluding other remote data tests as well.

Example log: https://github.com/spacetelescope/jdaviz/actions/runs/4431011530/jobs/7773460842

Upstream issue:

* https://github.com/astropy/astroquery/issues/2684
* https://github.com/astropy/astroquery/issues/2673#issuecomment-1450263389 (said we should contact `sciserver-helpdesk[at]jhu.edu`)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to abuse the `slow` tag that comes with `pytest-astropy` for this purpose.

Fixes #2083

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Coverage decreased because now the catalog test will not be counted as covered even though it will still run in the dev job that is allowed to fail. This is the cost to avoid SDSS server problem from blocking unrelated PRs for us.

**Comment by kecnry** [comment]
What is the benefit of marking as slow instead of remote data?  Will this make it "harder" for us to run tests locally since we now need to remember to enable both?

**Comment by pllim** [comment]
> What is the benefit of marking as slow instead of remote data?

Both the coverage job and the dev job run remote data. I need a new flag to ask coverage job to ignore it but dev job to pick it up.

> Will this make it "harder" for us to run tests locally since we now need to remember to enable both?

Yes, that is part of the cost.

If this is too much trouble, we can also close without merge, since SDSS server was fixed last night, but the same problem is going to come back again next time their server goes down.

**Review by kecnry — APPROVED** [review]
I think this is probably worth it, but curious if any devs run tests locally enough that they might have objections

**Comment by rosteen** [comment]
Ehh, I'm ambivalent about this. I mostly run non-remote-data tests locally anyway, I don't think an extra flag is a big deal.

**Comment by kecnry** [comment]
Sounds like no objections, thanks!

**Pull request merged**
