### PR TITLE
BUG: Fix Imviz linking data from file chooser

### LINKED ISSUE #1364: Imviz: loaded image stuck on weird plot options
**Reporter: Camilla Pacifici**

I did this in the standalone app. Did not test in notebook.
jdaviz version 2.6.1.dev3+g70eb5f1

To reproduce:
- load one image from command line (jdaviz imviz filename)
- load a second image with the import button
- image is in the data dropdown
- select second image
- it shows with some weird plot option and does not change if plot options are modified
- go to link control and relink images
- go to data dropdown and reselect the second image
- now it shows properly and the plot options are responding

[🐱](https://jira.stsci.edu/browse/JDAT-2485)

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to fix a bug where Imviz behaves weirdly because image loaded via file chooser (`IMPORT DATA`) is not linked to anything. File chooser itself is GUI driven and not tested, so I did not add any test for this.

Fixes #1364

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by camipacifici — APPROVED** [review]
Looks good to me!

**Review by javerbukh — APPROVED** [review]
Works for me!

**Comment by pllim** [comment]
Two approvals, let's get something merge at 5pm on a Friday! 🔥

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
