### PR TITLE
in-line styling to avoid conflicts when embedding

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request explicitly sets a few css styles that are otherwise overridden in the MAST embedded version of jdaviz, and will hopefully make the app look more consistent between the notebook and web versions.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
I think as long as @havok2063 or @Jenneh is happy, fine by me!

**Comment by kecnry** [comment]
There is no actual change to the styles, this is just defining some things in-line that can easily be overridden by external stylesheets otherwise (so I don't think @Jenneh needs to review).

**Review by havok2063 — APPROVED** [review]
Seems reasonable to me, especially if it gives us downstream folks more fine-grained control.

**Comment by havok2063** [comment]
If this fixes the current styling conflicts we see with Jdaviz 2.6.0, then maybe we also get this included in the hotfix release tomorrow, with the other bug fix.

**Comment by pllim** [comment]
Thanks, everyone!

**Pull request merged**
