### PR TITLE
Disable Unit Conversion plugin for now

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to temporarily disable Unit Conversion plugin until it can be refactored, which is tracked separately.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)? [🐱](https://jira.stsci.edu/browse/JDAT-2923)

### CODE REVIEW

**Comment by rosteen** [comment]
I think we should add a second sentence, something like "see [link to appropriate issue] for context/status". I don't think we currently have a single Github issue encompassing the unit conversion refactor that would be appropriate to link - I can make one and link the other related issues in its description.

**Comment by rosteen** [comment]
> How about a sentence in the known issues in the documentation, instead of an ad hoc github issue?

That would also work! I was about to hit the submit button on the new issue - do you think an issue directly tracking the refactor isn't needed?

**Comment by camipacifici** [comment]
If it is helpful also for the team, sure. If it is only to keep the users informed, I would go with the documentation instead.
Anyway, no strong feelings. I trust your judgement.

**Comment by duytnguyendtn** [comment]
I anticipate some additional conversation over the course of this refactor, especially when we get into the weeds of reviewing the Glue implementation and coordinating the release of our unit conversion refactor with improvements on the glue side. I think it would be useful to have a central place to coordinate strategy from a broader perspective rather than just in the PRs themselves.

👍 to a new ticket

**Comment by pllim** [comment]
Looks like Ricky created #1972 . Thanks!

**Comment by pllim** [comment]
I added a commit to add mention of #1972 . Is this good now?

**Comment by pllim** [comment]
Wut... CI failure can't be related.

**Comment by pllim** [comment]
Failure is unrelated.

**Review by rosteen — APPROVED** [review]
I confirmed that the test failures are also appearing in `main` on 3.9 locally. This looks good, although I do with that Github reference could be a hyperlink.

**Comment by pllim** [comment]
> Github reference could be a hyperlink

How do I do that?

**Comment by rosteen** [comment]
> > Github reference could be a hyperlink
> 
> How do I do that?

I don't know! That's why I approved anyway 😆

**Review by kecnry — APPROVED** [review]
Looks reasonable enough to me!  Is this considered as "too breaking" to backport though?  Or do we just want to get it out as soon as possible since the plugin in its current state is considered buggy?

> Github reference could be a hyperlink

Definitely possible, but not within the existing "disabled" infrastructure and probably not worth engineering something new since this should be temporary, imo.

**Comment by pllim** [comment]
During the tag up, we agreed to backport. I am going to rerun CI as due diligence though I don't see how this would affect the tests.

**Comment by pllim** [comment]
Thanks, all!

**Pull request merged**
