### PR TITLE
WIP: Added new info bar and use it to show the coordinate overlay

### LINKED ISSUE #514: JDAT-1224: Inspecting pixel WCS and value info
Display pixel (x, y), WCS (RA, Dec, Epoch, Frame), and data value (ADUs or flux) on mouseover.

1. Values should appear at right side of filename banner rather than hovering over the image. (See mockup.)
2. Only display values for viewer that the cursor is in. 

https://jira.stsci.edu/browse/JDAT-1224

# Open questions

- [ ] Is X and Y in cursor info 0-indexed or 1-indexed? Is there an option to allow user to specify this?

### PR DESCRIPTION
**Pull request by astrofrog**
This adds an info bar below the toolbar as per the mockups, and for now this is just used to show the coordinate overlay. At the moment there is just one global info bar, but we could always decide in future how to deal with the multi-viewer case (for now a global one is fine since there is only one mouse over coordinate available at any one time)

Screenshot 2021-04-22 at 11 38 32

This requires #505 and should be rebased once that is merged.

Fix #514

### CODE REVIEW

**Comment by pllim** [comment]
Since you are working on it here, I think it would be desirable to fix the position of `x`, `y`, `ICRS`, and `data` labels so they don't jump around. They currently jump when, say, `x=100` becomes `x=1`, and it is quite distracting to the eyes.

**Comment by pllim** [comment]
Also, will this PR completely fix #514 or just address part of it?

**Comment by astrofrog** [comment]
I think it will address it completely - I'll look into the jumping issues

**Comment by astrofrog** [comment]
@pllim - does this look better to you now?

**Comment by astrofrog** [comment]
Actually in the latest mock-ups the coordinates are in the main toolbar so I'll open another simpler PR to compare.

**Comment by astrofrog** [comment]
This has been superseded by https://github.com/spacetelescope/jdaviz/pull/557

**Pull request closed without merging**
