### PR TITLE
MNT: asdf and gwcs no longer optional dependencies

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to follow up on #785 and general Imviz upkeep after #766 made `asdf` and `gwcs` required dependencies.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
p.s. @ojustino , I remember you said you changed the background to be non-transparent in #785 , so I don't know why it is transparent again. The only change I made here is changing borders of `asdf` and `gwcs` to solid lines.

**Comment by ojustino** [comment]
@pllim, it may not have stuck because I wasn't able to add a fill to the "horizontal container" shape used to divide the figure into sections in the diagram editor. I figured it would be easier to add a background by inspection of the SVG code and did that instead.

However, it looks like the diagram editor doesn't recognize the background when I upload an SVG image where I've added one that way. It would probably be better to find a native solution, but I'm drawing a blank at the moment.

**Comment by ojustino** [comment]
As far as the core issue of the pull request, I didn't encounter any issues with installing this branch of `jdaviz` in a new conda environment.

**Comment by pllim** [comment]
@ojustino , can we defer the issue of the transparent SVG background then? I think with the current doc theme and the fact that ApJ will print on white paper, we should be good for now. 😬

**Comment by pllim** [comment]
I think this PR should be uncontroversial enough that we can merge with only 1 approval. 😉

**Review by ojustino — APPROVED** [review]
That's fine with me. Maybe we can look at it next time the figure is edited.

**Comment by pllim** [comment]
I created #828 for the flowchart background issue. Thanks for the review!

**Pull request merged**
