### PR TITLE
Rename helper test fixtures from 'app' to 'helper'

### PR DESCRIPTION
**Pull request by duytnguyendtn**
### Description

I ran into a small nomenclature discrepancy with our pytest fixtures that tripped me up after returning to jdaviz in who knows how long! Our test fixtures for the viz helpers are called `<spec | cube | mos | im>viz_app` which is slightly confusing to me at least, since they are the helpers and not the underlying apps (i.e. `<spec | cube | mos | im>viz.app`). This PR renames the test fixtures to `<spec | cube | mos | im>viz_helper` to be more explicit, and substitutes this change through all the unit tests. Since this has a lot of small changes, I figured I'd put this into its own PR

This naturally impacts all the devs in writing their unit tests, so we should advertise this change to everyone, and all should rebase before we stray too far.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by rosteen** [comment]
Fine with me, although I'm confused by the fact that this apparently decreased project test coverage. Any idea why?

**Comment by duytnguyendtn** [comment]
I was just about to ask that question too. I have no idea... I'll report back if I find something

**Comment by pllim** [comment]
I think we can ignore the coverage failure? Just looking at the diff, there is no change, as expected: https://app.codecov.io/gh/spacetelescope/jdaviz/compare/1064/diff

**Review by pllim — APPROVED** [review]
Does seem less confusing. Thanks!

**Review by rosteen — APPROVED** [review]

**Pull request merged**
