### PR TITLE
Added .ico and .svg files

### PR DESCRIPTION
**Pull request by Jenneh**
### Description

This pull request is to address ...

Fixes #<Issue Number>

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by kecnry — COMMENTED** [review]
It'll be handy to have these in the repo, even if they're not directly used in the docs yet.

Should all configs have both `.ico` and `.svg` (imviz only has ico)?  Do we want the naming to match the config exactly or just the prefix (mos vs imviz)?

**Review by bmorris3 — COMMENTED** [review]
These are great, and I agree with @kecnry – it'd be great to standardize the names.

**Comment by duytnguyendtn** [comment]
I commissioned these from Jenn and I was considering the naming as well. I believe Jenn is out of town for the next few weeks. My concern at the time was whether anything was using these icons and whether renaming things would break anything. Should probably do a quick grep through the repo to make sure

**Comment by pllim** [comment]
> It'll be handy to have these in the repo, even if they're not directly used in the docs yet.

I slightly disagree. This PR should also try to use them. Anything that ended up not used should not be version controlled here (maybe stash in Box?). Maybe one of us can take over as long as there are instructions on how these are intended to be used.

**Review by pllim — APPROVED** [review]
I think I finally found a use for these over at #2243 . Thanks for the foresight!

**Pull request merged**
