### PR TITLE
Add missing stat (Sum) to collapse plugin

### PR DESCRIPTION
**Pull request by rosteen**
Tiny fix of an oversight

### CODE REVIEW

**Review by PatrickOgle — CHANGES_REQUESTED** [review]
The Sum method appears to deliver a reasonable 2D product.  However, 
it is not clear that the wavelength range of the Region subset is being applied.
Please see github jdaviz issue #[268](https://github.com/spacetelescope/jdaviz/issues/268)

**Comment by PatrickOgle** [comment]
Not sure why the wavelength bounds weren't changing before. That aspect looks OK now.
Now I am struggling with repeating the collapse operation with the same region but resized bounds,
which errors out.  I have to restart the kernel to collapse with different wavelength bounds.  I do however
verify that smaller regions give a smaller flux sum, and that the Sum operation gives larger values than
the Mean operation, so it is passing these minimal sanity checks.

**Comment by rosteen** [comment]
@PatrickOgle I added an auto-incrementing integer to the labels to avoid overwriting the previously collapsed data on subsequent collapse operations.

**Review by javerbukh — APPROVED** [review]
Looks good and works as expected! I was able to do what we would call in the gaming community a "noob move" in that I collapsed a sum, and then used the returned dataset again to try to collapse it (for a second time). I do not think any scientist would ever do this but I just wanted to mention that it was possible to do.

Here is the traceback if you're interested:
```
~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/glue_astronomy/translators/spectral_cube.py in to_object(self, data_or_subset, attribute)
     33 
     34         if data_or_subset.ndim > 0 and data_or_subset.ndim != 3 and data_or_subset.ndim != 4:
---> 35             raise ValueError('Data object should have 3 or 4 dimensions in order to '
     36                              'be converted to a SpectralCube object.')
     37 

ValueError: Data object should have 3 or 4 dimensions in order to be converted to a SpectralCube object.
```

**Review by PatrickOgle — APPROVED** [review]
The new counter label for multiple collapse operations works.
I am still seeing strangeness with the wavelength bounds not matching the region
selected in the spectrum viewer, but will file a separate issue for this.

**Pull request merged**
