### PR TITLE
data-menu: show add data list for empty viewers

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request shows a list of data to add into a viewer when the viewer is empty _in place_ of the previous data-menu's behavior of opening for new viewers.

This definitely could benefit from some more styling, but is needed to reach feature parity with the former data-menu so that it can be deprecated.

https://github.com/user-attachments/assets/9d104061-bf88-4053-9181-abdccb8aaf8a

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by gibsongreen** [comment]
The UI looks good with the new updates, especially having an empty viewer that now enforces the user to load data and removing the ability to remove data entries across the entire app when in an empty viewer. 

When a new viewer is created, I think there should still be a option for the multi-select option, but in a way that lets the user chose multiple datasets to load into the viewer at once.
. 
Screenshot 2024-11-13 at 1 09 44 AM

Should we include a message similar to what is in the old data menu?

Screenshot 2024-11-13 at 1 06 37 AM


Screenshot 2024-11-13 at 12 43 55 AM

To show users where the new data menu is can we reintroduce auto-opening the data menu at app startup with the new menu?

This is on main where when you load a dataset that has DQ, when you toggle off the parent layer, the child layer remains visible. 

https://github.com/user-attachments/assets/09b6f457-8d88-494d-a6d2-bb5caa1a8777

**Comment by kecnry** [comment]
@gibsongreen - what do you think of this to help users find the right menu when there is no data?


https://github.com/user-attachments/assets/98809526-d943-4e44-b582-34a307321ab0

**Review by javerbukh — COMMENTED** [review]
This is looking good! I especially like the pulse you added for the button to add data. I think something like that would be beneficial for new users app-wide. The only issue I came across was when re-adding a viewer that had already been deleted. I can confirm that that bug does not exist on `main`.

1. Run imviz example notebook
2. Add new viewer (viewer 1)
3. Close viewer 1
4. Re-add new viewer
5. Try to select data

I then see the following traceback:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File [~\anaconda3\envs\test-strauss\Lib\site-packages\ipyvue\VueTemplateWidget.py:60](http://localhost:8888/lab/tree/notebooks/~/anaconda3/envs/test-strauss/Lib/site-packages/ipyvue/VueTemplateWidget.py#line=59), in Events._handle_event(self, _, content, buffers)
     58     getattr(self, "vue_" + event)(data, buffers)
     59 else:
---> 60     getattr(self, "vue_" + event)(data)

File [~\Documents\STScI\jdaviz\jdaviz\configs\default\plugins\data_menu\data_menu.py:354](http://localhost:8888/lab/tree/notebooks/~/Documents/STScI/jdaviz/jdaviz/configs/default/plugins/data_menu/data_menu.py#line=353), in DataMenu.vue_add_data_to_viewer(self, info, *args)
    353 def vue_add_data_to_viewer(self, info, *args):
--> 354     self.add_data(info.get('data_label'))

File [~\Documents\STScI\jdaviz\jdaviz\configs\default\plugins\data_menu\data_menu.py:351](http://localhost:8888/lab/tree/notebooks/~/Documents/STScI/jdaviz/jdaviz/configs/default/plugins/data_menu/data_menu.py#line=350), in DataMenu.add_data(self, *data_labels)
    349     raise ValueError(f"Data labels {unavailable} not able to be loaded into '{self.viewer_id}'.  Must be one of: {self.dataset.choices}")  # noqa
    350 for data_label in data_labels:
--> 351     self.app.add_data_to_viewer(self.viewer_id, data_label)

File [~\Documents\STScI\jdaviz\jdaviz\app.py:1646](http://localhost:8888/lab/tree/notebooks/~/Documents/STScI/jdaviz/jdaviz/app.py#line=1645), in Application.add_data_to_viewer(self, viewer_reference, data_label, visible, clear_other_data)
   1644 viewer_item = self._get_viewer_item(viewer_reference)
   1645 if viewer_item is None:
-> 1646     raise ValueError(f"Could not identify viewer with reference {viewer_reference}")
   1648 self.set_data_visibility(viewer_item, data_label, visible=visible, replace=clear_other_data)

ValueError: Could not identify viewer with reference
```

**Comment by kecnry** [comment]
I like both those ideas to use the pulsating more - let's keep that in mind for future work!

@javerbukh - looking into that issue now - I suspect it wasn't added by this PR since this is mostly UI logic, so I may make it as a separate PR

**Review by javerbukh — APPROVED** [review]
Looks good!

**Review by gibsongreen — APPROVED** [review]
LGTM!

**Pull request merged**
