### PR TITLE
fix top app bar style to align in notebook, popout, and mast

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements a minor styling tweak so that the app top-bar aligns with the rest of the app across notebook/lab/popout/mast.

Before (look at 1 pixel white space in the popout to the left and right of the top toolbar):
Screen Shot 2024-01-05 at 1 06 49 PM

After:

Screen Shot 2024-01-05 at 1 07 00 PM

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Thanks!

**Comment by pllim** [comment]
Did HST remote data change again? That's annoying. We can ignore it in this PR unless you want to fix it here.

```
imviz/tests/test_parser.py::TestParseImage::test_parse_hst_drz - assert (4299, 4219) == (4298, 4220)
  At index 0 diff: 4299 != 4298
  Full diff:
  - (4298, 4220)
  ?     ^    ^^
  + (4299, 4219)
  ?     ^    ^^
```

**Comment by kecnry** [comment]
> We can ignore it in this PR unless you want to fix it here.

Let's ignore for now so this PR stays just a small style change.  If it seems to persist, we can update separately.

**Comment by kecnry** [comment]
@pllim - can you please override and merge with admin if you're ok with ignoring for now?

**Pull request merged**
