### PR TITLE
DOC: Hide boolean mask support in load_regions

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to stop advertising that you can load boolean mask to make cute Space Invaders, as requested by @kecnry and @camipacifici .

Related issues:

* https://github.com/spacetelescope/jdaviz/issues/2638
* https://github.com/glue-viz/glue/issues/2474

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Re: @camipacifici 

> Did you figure out if masks can be extracted with get_something?

`imviz.get_interactive_regions()` does not return it.

`imviz.app.get_subsets()` does return it but AFAIK that is not considered a public API but maybe @kecnry can confirm.

**Comment by pllim** [comment]
Subset Tools does not list it.

It is not available as option for Aperture Photometry.

**Comment by kecnry** [comment]
> but AFAIK that is not considered a public API

not currently, no, but we are planning to make it public "soon"

**Comment by pllim** [comment]
When we do that, the public API portion can easily filter it out like `get_interactive_regions()` unless you want me to do that now in the non-public API for whatever reason. @javerbukh might have included it for some reason?

**Pull request merged**
