### PR TITLE
cubeviz spectral extraction live-previews

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements live-previews for spectral extraction in cubeviz.  Since this may become expensive and to mitigate potential lag, this also migrates the functionality to time expensive live-previews and temporarily disable them from lcviz to here as a decorator which is then used in the implementation of live-previews in cubeviz's spectral extraction.

lcviz can then remove its own implementation to make use of this PR in https://github.com/kecnry/lcviz/pull/3

NOTE: this screen recording was done with the timeout lowered to 0.1 seconds to show how the pausing works.  In the PR, this value is set to 0.3 and usually does not trigger for the default cube.  The "entire cube" does not display any preview because of a known bug where nans in the cube are resulting in a spectrum of entire nans (addressed by #2737).

https://github.com/spacetelescope/jdaviz/assets/877591/3336212b-c317-42dd-a879-45392ca54481

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by rosteen — COMMENTED** [review]
Seems to work for me (FWIW I do hit the 0.3 second limit with the example cube, my computer must be lazier), I'm going to spend a little more time understanding all the code before approving.

**Review by rosteen — APPROVED** [review]
Code looks good. Is there any way to add a test for the timeout? I don't see an easy way to do it since you can't set the timeout in the decorator dynamically/on the fly when calling the function, so you can't just set it to 0 for the test.

**Comment by kecnry** [comment]
I guess we could maybe test it with a fake plugin that just sleeps for half a second? 🤷‍♂️ Is that worth doing?

**Review by haticekaratay — APPROVED** [review]
I tested it in Cubeviz, and it behaves as described. Thank you for your work.

**Pull request merged**
