### PR TITLE
viewer toolbar: align to right

### LINKED ISSUE #659: Shift viewer toolbar under hammer and screwdriver to the right
**Reporter: Jesse Averbukh**

Currently, the icon to open the viewer toolbar is at the top right of the viewer, but the toolbar itself is still left-justified as it was when the icon was over on the left side. It would be nice if the viewer toolbars appeared on the right, to better align with the location of the button.

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request moves the alignment of the "hammer and screwdriver" toolbar to the right and the child "save" menu to the left so it does not overflow past the far right of the viewer.

Fixes #659

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Definitely feels more intuitive. Thanks!

p.s. Not sure what the "child save menu" is.

**Before**

Screenshot 2021-09-17 134041

**After**

Screenshot 2021-09-17 134430

**Comment by kecnry** [comment]
> p.s. Not sure what the "child save menu" is.

The menu with "save as png" and "save as svg" that pops up if you click on the save icon.  It used to extend to the right of the save icon, but that would now overflow past the edge of the viewer (if there are multiple viewers like in Cubeviz).  I changed that to always extend to the left so it doesn't overflow.

With that change (as is in the PR):
Screen Shot 2021-09-17 at 1 52 14 PM


Without that change:
Screen Shot 2021-09-17 at 1 53 16 PM

**Comment by pllim** [comment]
Ah! I obviously never try to click that button. 😆

Looks nice. Would approve again! -- ⭐⭐⭐⭐⭐

**Review by javerbukh — APPROVED** [review]
Great change, thank you!

**Pull request merged**
