### PR TITLE
BUG: Fix Imviz center/offset bounds check

### LINKED ISSUE #704: [BUG] Imviz: "White out" when center_on "off-screen, on-image"
As reported by @ojustino while reviewing #687 .

To reproduce:

1. Fire up Imviz.
2. Load some image.
3. Use `imviz.center_on` on a pixel location that is valid but far out from the displayed area.
4. See nothing being displayed and no error. Viewer also becomes non-functional and has to be reloaded.

Example use case from Justin:

```python
from astropy.coordinates import SkyCoord
from astropy.utils.data import download_file

from jdaviz.configs.imviz import Imviz

imviz = Imviz()

cygA1 = download_file('https://hla.stsci.edu/cgi-bin/getdata.cgi?dataset=hst_05368_01_wfpc2_f555w_pc_drz.fits', cache=True)
cygA2 = download_file('https://hla.stsci.edu/cgi-bin/getdata.cgi?dataset=hst_05368_01_wfpc2_f555w_wf_drz.fits', cache=True)

imviz.load_data(cygA1, data_label='cygA1')
imviz.load_data(cygA2, data_label='cygA2')

sky = SkyCoord('09h59m26.02s 40d44m17.92s')
imviz.center_on(sky)
```

[🐱](https://jira.stsci.edu/browse/JDAT-1577)

### PR DESCRIPTION
**Pull request by pllim**
Fix #704 .

I realize that I need this fix to profile for #564 , so quick turnaround to get this merged would make my life easier. Thanks!

### CODE REVIEW

**Review by rosteen — APPROVED** [review]
Looks good to me, I was able to see that it properly centered on out-of-view but on-image coordinates, as opposed to throwing a snackbar "out of bounds" warning on main.

**Comment by javerbukh** [comment]
I just noticed that the notebook imports photutils. Is this new? Should this be added as a dependency?

**Review by javerbukh — APPROVED** [review]
Looks good!

**Comment by pllim** [comment]
Re: photutils -- It is already under optional dependency. 😸 

https://github.com/spacetelescope/jdaviz/blob/b8e80f4ba42520dd1b2b74b69e3b3ef204807065/setup.cfg#L55

**Comment by pllim** [comment]
Thanks for the quick reviews! 🙇‍♀️

**Pull request merged**
