### PR TITLE
Set axes labels

### PR DESCRIPTION
**Pull request by javerbukh**
Set axes labels to look better and more accurately represent data. Currently the axes labels for some viewers are hard coded (such as "x: pixels" and "y: pixels" for the image viewer), but once header information is being passed through the `meta` attribute and being used in the plot, we can set these values to be more accurate.

Some examples of how the plots look now:
Screen Shot 2020-09-08 at 9 43 19 AM

After readjusting the size of the viewers:
Screen Shot 2020-09-08 at 9 43 39 AM
(The spectrum viewer says "Flux Density [Jy]". Once Unit Conversion is usable in mosviz, the user can change the units to mJy so that the numbers are not blocking the y axis label)

I would suggest in the documentation to mention that removing the axes labels all together is an option under the viewer tab, since this looks much better!
Screen Shot 2020-09-08 at 9 47 40 AM

### CODE REVIEW

**Comment by javerbukh** [comment]
I noticed there's a problem with the cubeviz view, I'm working on that now and should have a new commit this afternoon.

**Comment by javerbukh** [comment]
Cubeviz now updates correctly as well!
Screen Shot 2020-09-08 at 1 37 12 PM

This PR is now ready for review.

**Comment by javerbukh** [comment]
@rosteen Good catch on that bug! I noticed that it only happens in Mosviz, but when you hide and then show axes, and then select a different row, you immediately get the flashing bug. I am kind of stumped on how to proceed...I wonder if this is related to the slit viewer at all. I'll try to debug some more.

As to your second point, I've been trying to remove that empty space but none of the attributes for a `figure` seem to work for that. I've tried changing `fig_margin`, `min_aspect_ratio`, `max_aspect_ratio`, none of them seem to affect that bottom area.

@mariobuikhuizen and Maarten (I cannot tag his github account), do you think you could take a look at either of these two points, with the priority being the show/hide axes bug in this PR?

**Comment by javerbukh** [comment]
Removed the slit plugin to test, received the following traceback after hiding axes and then showing them, followed by selecting a new row:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/glue_jupyter/state_traitlets_helpers.py in update_state_from_json(self, json, widget)
    149         self._block_on_state_change = True
    150         try:
--> 151             update_state_from_dict(state, json)
    152         finally:
    153             self._block_on_state_change = False

~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/glue_jupyter/state_traitlets_helpers.py in update_state_from_dict(state, changes)
     68                         setattr(state, name, get_cmap(changes[name]))
     69                     else:
---> 70                         setattr(state, name, changes[name])
     71 
     72 

~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/echo/core.py in __setattr__(self, attribute, value)
    259 
    260     def __setattr__(self, attribute, value):
--> 261         super(HasCallbackProperties, self).__setattr__(attribute, value)
    262         if self.is_callback_property(attribute):
    263             self._notify_global(**{attribute: value})

~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/echo/core.py in __set__(self, instance, value)
     74         new = self.__get__(instance)
     75         if old != new:
---> 76             self.notify(instance, old, new)
     77 
     78     def setter(self, func):

~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/glue/utils/matplotlib.py in wrapper(*args, **kwargs)
    158 
    159         if len(DEFER_DRAW_BACKENDS) == 0:
--> 160             return func(*args, **kwargs)
    161 
    162         # Don't recursively defer draws. We just check the first draw_idle

~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/glue/viewers/matplotlib/state.py in notify(self, *args, **kwargs)
     22     @defer_draw
     23     def notify(self, *args, **kwargs):
---> 24         super(DeferredDrawCallbackProperty, self).notify(*args, **kwargs)
     25 
     26 

~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/echo/core.py in notify(self, instance, old, new)
    123             return
    124         for cback in self._callbacks.get(instance, []):
--> 125             cback(new)
    126         for cback in self._2arg_callbacks.get(instance, []):
    127             cback(old, new)

~/anaconda3/envs/mosviz_axes/lib/python3.8/site-packages/glue_jupyter/common/state_widgets/viewer_image.py in _sync_sliders_from_state(self, *not_used)
     70                 new_slices.append(self.viewer_state.slices[i].center)
     71             else:
---> 72                 new_slices.append(self.viewer_state.slices[i])
     73         self.viewer_state.slices = tuple(new_slices)
     74 

IndexError: list index out of range
```

**Comment by javerbukh** [comment]
@rosteen The bug you were seeing earlier is not being introduced in this PR, I opened the ticket #279 to track it. I think this PR is in a state to be merged then @dtn5ah @eteq .

**Review by rosteen — APPROVED** [review]
Approved, since the bug I was seeing apparently already existed and isn't related to this PR. I figured you had already tried making the 2D spectrum fill the viewer better, but I figured I'd check. Not a showstopper.

**Comment by javerbukh** [comment]
I fixed the merge conflict that was here. Could use another look from @PatrickOgle @eteq or @dtn5ah before merge.

**Review by camipacifici — APPROVED** [review]
Axes look good. The data hack (names of x-axis and y-axis) should be fixed in the near future.

**Comment by javerbukh** [comment]
Looks good to merge. We definitely have some work to do on mosviz and updating axes but that is being tracked in #279 .

**Pull request merged**
