### PR TITLE
BUG: Allow data_label as pos arg

### LINKED ISSUE #1617: parser_reference catch-all results in confusing behavior
**Reporter: Kyle Conroy**

when calling something like `imviz.load_data(data_file, 'my label')`, `'my label'` is a positional argument and so assigned to `parser_reference` even though the user likely wanted it to be set to `data_label`.  This in turn results in the parser defaulting to loading all image extensions, acting differently than if not passing a second argument at all.  This should probably raise an error saying that the parser reference is not a valid option.  We may also want to consider re-ordering the positional arguments so that this syntax would be supported for `data_label`.

[🐱](https://jira.stsci.edu/browse/JDAT-2712)

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to allow common user mistake passing in data_label as positional argument. This approach is kinda hacky but is less disruptive than throwing error if data_label is not a keyword argument.

Fixes #1617 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
I'm worried this is a slippery slope... although in this case it _might_ be worth the convenience.  Is switching the order of the positional arguments too big of an API break?  If we do stick with this, should we at least raise a warning?

**Comment by pllim** [comment]
> raise a warning?

Hmm. Maybe @rosteen can chime in here since he encountered this use case.

**Comment by rosteen** [comment]
Personally I think we should just switch the order of the keyword arguments so `data_label` comes first, since all the helper `load_data` methods use the `parser_reference` keyword explicitly and don't depend on the position of that keyword. Supporting the user ease of use case is more important than our internal use anyway (I don't think any user will ever use `parser_reference`).

**Comment by rosteen** [comment]
Right, I vote for pulling it out of `**kwargs` and making it explicit so it can be used positionally.

**Comment by pllim** [comment]
Re: https://github.com/spacetelescope/jdaviz/pull/1644#issuecomment-1245721590

This is made complicated that mosviz parser accepts `data_labels` and not `data_label`. Making it explicit is going to overcomplicate things. Any other ideas?

**Comment by rosteen** [comment]
I think that the Mosviz helper methods can be left as-is and not be affected by this. For example, `load_1d_spectra` already accepts `data_labels` explicitly as the second positional argument, and then passes it to `app.load_data` as a keyword. So it doesn't really matter if we put `data_label=None` in front of `parser_reference` elsewhere, the Mosviz parsers can just not care about `data_label` and get `data_labels` same as they do currently.

**Comment by pllim** [comment]
But what if you pass in `data_label='something'` to Mosviz (muscle memory from using other viz, etc) and then wonder why things don't work?

**Comment by pllim** [comment]
I'll have to think about this. If we make it explicit, it will also break existing API passing in `parser_reference` as positional argument.

**Comment by pllim** [comment]
Okay... I completely changed the implementation. Please re-review. Thanks!

**Review by rosteen — APPROVED** [review]
Looks good to me now, thanks!

**Review by kecnry — APPROVED** [review]
I'd personally like to also see the orders in mosviz and specviz2d changed to parallel this more closely, but realize that would definitely be considered an API-breaking change and require a lot more thought... so let's leave those out for now.

Specviz already supports `data_label` as the second positional argument in its `load_spectrum`.  We may also want to consider renaming that (with deprecation) to `load_data` to be more consistent, but that can also be handled later.

Was `parser_reference` ever passed anywhere in docs/examples notebooks that would justify the need for deprecation or a version bump here?  Otherwise, I don't see any issues with this as-is in a minor release.  Definitely will avoid some possible confusion when a user first start using jdaviz!

**Comment by pllim** [comment]
No, I think adding `parser_reference` to `Imviz.load_data` was a mistake on my part. And nowhere in the doc we ask people to use it. So I think we can change this for Imviz without any deprecation. Thanks for the reviews!

Deprecating `Specviz.load_spectrum` might be controversial because it is so widely used. If you feel strongly we should do it, please open a new ticket.

**Comment by kecnry** [comment]
> Deprecating `Specviz.load_spectrum` might be controversial because it is so widely used. If you feel strongly we should do it, please open a new ticket.

I agree, we'd definitely need a long (perhaps infinitely long) deprecation period.  At least having the alias for `load_data` and switching example notebooks to use that might be a good idea.  But also probably not high on the priority list 🤷

**Pull request merged**
