### PR TITLE
New color Imviz logo from Jenn

### PR DESCRIPTION
**Pull request by bmorris3**
### Description

Jenn has contributed a multi-color version of the Imviz logo. 

### Change log entry

- [X] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [X] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [X] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [X] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [X] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [X] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [X] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [X] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by pllim — APPROVED** [review]
Docs rendered fine. Thanks!

**Review by kecnry — COMMENTED** [review]
Is the png used anywhere?  Do we care about the change in resolution?

**Comment by pllim** [comment]
Hmm seems like for some reason, only Imviz has two different file formats. I am not sure.

**Comment by bmorris3** [comment]
> Is the png used anywhere? Do we care about the change in resolution?

I don't think the PNG logos are currently used anywhere. Currently each SVG has a PNG alongside it, which is handy if you're importing the graphic to an app that doesn't support SVG. Not strictly necessary for us though. 🤷🏻

**Comment by pllim** [comment]
@bmorris3 didn't add any new files though, so if we cannot decide now, we can punt this as tech debt for the future to remove duplicate PNG. Up to you.

**Comment by bmorris3** [comment]
> punt this as tech debt for the future to remove duplicate PNG

I'll do that. Thanks all!

**Pull request merged**
