### PR TITLE
BUG: Fix get_model_parameters for Gaussian1D

### LINKED ISSUE #975: [BUG] Specviz: Model Parameters Failing
**Describe the bug**
When trying to export model parameters in Specviz, I run into the following traceback:
```
>>> specviz.get_model_parameters(model_label="Model")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/93/k31j59sj2493rzfqxc8r5z0r000171/T/ipykernel_52724/2990741164.py in <module>
      1 # Retrieve the parameters from which our model was constructed:
----> 2 specviz.get_model_parameters(model_label="Model")

~/duydir/gitrepos/aas239-jwebbinar/envdryrun/lib/python3.8/site-packages/jdaviz/core/helpers.py in get_model_parameters(self, models, model_label, x, y)
    249         for key in parameters_cube:
    250             for param_name in parameters_cube[key]:
--> 251                 parameters_cube[key][param_name] = u.Quantity(
    252                     parameters_cube[key][param_name],
    253                     param_units[key].get(param_name, None))

~/duydir/gitrepos/aas239-jwebbinar/envdryrun/lib/python3.8/site-packages/astropy/units/quantity.py in __new__(cls, value, unit, dtype, copy, order, subok, ndmin)
    412         if unit is not None:
    413             # convert unit first, to avoid multiple string->unit conversions
--> 414             unit = Unit(unit)
    415 
    416         # optimize speed for Quantity with no dtype given, copy=False

~/duydir/gitrepos/aas239-jwebbinar/envdryrun/lib/python3.8/site-packages/astropy/units/core.py in __call__(self, s, represents, format, namespace, doc, parse_strict)
   2063 
   2064         else:
-> 2065             raise TypeError(f"{s} can not be converted to a Unit")
   2066 
   2067 

TypeError: {} can not be converted to a Unit

```

**To Reproduce**
1. Fit a model (in this case, a gaussian + constant model)
2. Manually edit a few parameters (amplitude, stdev) (not sure if this is related?)
3. Refit the model
4. Call `get_model_parameters`

**Expected behavior**
A dictionary of parameters should be returned, no tracdback

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Browser: Chrome 95.0.4638.69
 - Jupyter: 
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.4
ipython          : 7.15.0
ipykernel        : 5.3.0
jupyter client   : 5.3.4
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.6
traitlets        : 4.3.3

**Package versions (please complete the following information):**

appnope==0.1.0
asdf==2.6.0
asteval==0.9.18
astropy==4.0.1.post1
async-generator==1.10
attrs==19.3.0
backcall==0.1.0
bleach==3.1.5
Bottleneck==1.3.2
bqplot==0.12.12
bqplot-image-gl==0.5.0
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.1.1
echo==0.5.dev2+g982cb0b
entrypoints==0.3
fast-histogram==0.9
glue-astronomy==0.1.dev71+gebc0737
glue-core==0.16.0.dev306+g7fcd8283
glue-jupyter==0.2.dev158+gac55d30
glue-vispy-viewers==0.12.2
gwcs==0.13.0
h5py==2.10.0
idna==2.9
ipydatawidgets==4.0.1
ipygoldenlayout==0.3.0
ipykernel==5.3.0
ipympl==0.5.6
ipysplitpanes==0.1.0
ipython==7.15.0
ipython-genutils==0.2.0
ipyvolume==0.5.2
ipyvue==1.3.2
ipyvuetify==1.4.0
ipywebrtc==0.5.0
ipywidgets==7.5.1
jdaviz==0.1.dev415+g559ed1e
jedi==0.17.0
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.3
jupyter-server==0.1.1
jupyterlab-pygments==0.1.1
kiwisolver==1.2.0
MarkupSafe==1.1.1
matplotlib==3.2.1
mistune==0.8.4
mpl-scatter-density==0.6
nbconvert==5.6.1
nbformat==5.0.6
notebook==6.0.3
numpy==1.18.5
packaging==20.4
pandas==1.0.4
pandocfilters==1.4.2
parso==0.7.0
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.1.2
prometheus-client==0.8.0
prompt-toolkit==3.0.5
ptyprocess==0.6.0
Pygments==2.6.1
PyOpenGL==3.1.5
pyparsing==2.4.7
pyrsistent==0.16.0
python-dateutil==2.8.1
pythreejs==2.2.0
pytz==2020.1
PyYAML==5.3.1
pyzmq==19.0.1
qtconsole==4.7.4
QtPy==1.9.0
radio-beam==0.3.2
regions==0.4
requests==2.23.0
scipy==1.4.1
semantic-version==2.8.5
Send2Trash==1.5.0
six==1.15.0
spectral-cube==0.4.5
specutils==1.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.4
traitlets==4.3.3
traittypes==0.2.1
urllib3==1.25.9
voila==0.1.21
wcwidth==0.2.3
webencodings==0.5.1
widgetsnbextension==3.5.1
xlrd==1.2.0

**Additional context (e.g. data files)**
Using data from Cami's Redshift JDAT Notebook

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to remove special unit handling for Gaussian model because it breaks `viz.get_model_parameters`. Not sure why they were added but maybe it was needed at some point but it is no longer the case.

I cannot find any unit tests for the Model Fitting plugin, that this method is affected by. This method is also not in any other existing tests. So maybe adding a test for this fix is out of scope... 😬 

Fixes #975 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by ibusko — COMMENTED** [review]
Looks like unit tests that would cause the old code to crash but the new one to pass, would be useful here. Any idea on what was the particular case that caused the Gaussian fit to crash?

**Comment by pllim** [comment]
Since there is zero test right now, trying to write up a sensible test would take like 5-10x as long as writing the fix... 👀

**Comment by pllim** [comment]
The case is explained in  #975

**Review by rosteen — APPROVED** [review]
Confirmed that it was broken, and now it's not! Thanks 👍

**Comment by rosteen** [comment]
I think there are tickets open to add unit testing for some of the plugins where it's missing already, so I support that being a separate effort from this fix.

**Comment by kecnry** [comment]
Was this caused by a change in astropy (do we need to worry about older versions of astropy still relying on the old if-statement)?

**Comment by pllim** [comment]
`astropy.modeling` has been supporting units since v2.0 (astropy/astropy#4855). And the current LTS is v5.0. So, I don't think we need to worry about the old versions?

**Comment by pllim** [comment]
Still, doesn't hurt to do a test with this using astropy 4.3.x

https://github.com/spacetelescope/jdaviz/blob/e338e9bc5437ae7853fefe3da3aa942f37eea57c/setup.cfg#L21

**Comment by pllim** [comment]
Seems to work with `astropy` 4.3:

```python
>>> specviz.get_model_parameters()
{'Model':
 {'amplitude_0': <Quantity 29.58504463 1e-17 erg / (Angstrom cm2 s)>,
  'mean_0': <Quantity 6858.37344117 Angstrom>,
  'stddev_0': <Quantity 63.64975782 Angstrom>,
  'amplitude_1': <Quantity 54.63609656 1e-17 erg / (Angstrom cm2 s)>}}
```

```python
>>> cubeviz.get_model_parameters()
{'Model':
 {'slope': <Quantity 1364993.81048269 1e-17 erg / (Angstrom cm2 m s)>,
  'intercept': <Quantity 0.74306448 1e-17 erg / (Angstrom cm2 s)>},
 'Model_3d': {
  'slope': <Quantity [[-1.831916e-318, -1.831916e-318, -1.831916e-318, ...,
              -1.831916e-318, -1.831916e-318, -1.831916e-318],
             [-1.831916e-318, -1.831916e-318, -1.831916e-318, ...,
              -1.831916e-318, -1.831916e-318, -1.831916e-318],
             [-1.831916e-318, -1.831916e-318, -1.831916e-318, ...,
              -1.831916e-318, -1.831916e-318, -1.831916e-318],
             ...,
             [-1.831916e-318, -1.831916e-318, -1.831916e-318, ...,
              -1.831916e-318, -1.831916e-318, -1.831916e-318],
             [-1.831916e-318, -1.831916e-318, -1.831916e-318, ...,
              -1.831916e-318, -1.831916e-318, -1.831916e-318],
             [-1.831916e-318, -1.831916e-318, -1.831916e-318, ...,
              -1.831916e-318, -1.831916e-318, -1.831916e-318]] 1e-17 erg / (Angstrom cm2 m s)>,
  'intercept': <Quantity [[5.e-324, 5.e-324, 5.e-324, ..., 5.e-324, 5.e-324, 5.e-324],
             [5.e-324, 5.e-324, 5.e-324, ..., 5.e-324, 5.e-324, 5.e-324],
             [5.e-324, 5.e-324, 5.e-324, ..., 5.e-324, 5.e-324, 5.e-324],
             ...,
             [5.e-324, 5.e-324, 5.e-324, ..., 5.e-324, 5.e-324, 5.e-324],
             [5.e-324, 5.e-324, 5.e-324, ..., 5.e-324, 5.e-324, 5.e-324],
             [5.e-324, 5.e-324, 5.e-324, ..., 5.e-324, 5.e-324, 5.e-324]] 1e-17 erg / (Angstrom cm2 s)>}}
```

**Review by kecnry — APPROVED** [review]
Much cleaner and since it seems to work on our required minimum version of astropy, I think this is good to merge!

**Pull request merged**
