### PR TITLE
Correcting Zenodo link in readme

### PR DESCRIPTION
**Pull request by bmorris3**
In #1743 we changed the Zenodo links to always point to the latest release. I found one remaining URL to change in the README, which is fixed in this PR.

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by ojustino — APPROVED** [review]
That should be the last straggler.

**Review by rosteen — APPROVED** [review]
Good catch! Can't believe I missed that one.

**Review by kecnry — APPROVED** [review]
LGTM - maybe worth milestoning for the next bugfix just so it gets in sooner?

**Comment by pllim** [comment]
Doesn't hurt but people usually see the README in `main`. Almost no one grab the tarball and then untar it and read the README. 😆

**Pull request merged**
