### PR TITLE
imviz matched zoom: use center & radius instead of corners

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request fixes matched image box zoom when the matched viewers have different aspect ratios.'

~TODO: this breaks the old tests that expect the same limits to be returned~

**Before**:

https://github.com/user-attachments/assets/edda126e-7adc-4d89-9602-562db23b7df7

**After**:

https://github.com/user-attachments/assets/4f6108b0-b4a3-4de1-ac3b-32e1de9ba3e5

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by bmorris3 — COMMENTED** [review]
This looks better! I will test on Rampviz later, just wanted to log that this implementation looks good to me.

**Comment by kecnry** [comment]
Looks like there is still jittering in Rampviz with 3 viewers (but not with 2 viewers or Imviz with 3 viewers)... will continue to investigate and see if I can find a more general solution 🤞

**Review by bmorris3 — APPROVED** [review]
Woah! This looks a lot better now. There's still >1 zoom reset happening in the matched viewers, but it's happening really fast for me now.

Thank you!

**Comment by kecnry** [comment]
Oh I forgot I still need to update tests 🤦‍♂️  I'll put in draft and work on that - glad to hear it seems to have fixed the use-case though!

**Comment by kecnry** [comment]
Requires #3222 to pass remaining failing tests

**Review by bmorris3 — APPROVED** [review]
Test revisions make sense. Thanks!

**Review by rosteen — APPROVED** [review]
Agreed, looks fine.

**Pull request merged**
