### PR TITLE
Consolidate videos to one page in docs

### PR DESCRIPTION
**Pull request by camipacifici**
### Description

This pull request collects all new and old videos into one page easier to discover in the ToC. I deleted the old example pages and used the same links in the new page. I hope I did not break any links!

Fixes #<Issue Number>

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by javerbukh** [comment]
Couple of warnings from the readthedocs build:
```
/home/docs/checkouts/readthedocs.org/user_builds/camipacifici/checkouts/add-videos/docs/cubeviz/index.rst:57: WARNING: toctree contains reference to nonexisting document 'cubeviz/examples'
/home/docs/checkouts/readthedocs.org/user_builds/camipacifici/checkouts/add-videos/docs/imviz/index.rst:28: WARNING: toctree contains reference to nonexisting document 'imviz/examples'
/home/docs/checkouts/readthedocs.org/user_builds/camipacifici/checkouts/add-videos/docs/specviz/index.rst:40: WARNING: toctree contains reference to nonexisting document 'specviz/examples'
```

**Comment by pllim** [comment]
Re: warnings -- Please remove them from TOC listing in the affected `index.rst` files. Thanks!

**Comment by camipacifici** [comment]
Should be ready now. Thank you for catching this!

**Review by javerbukh — APPROVED** [review]
Glad these are in one location now, thanks!

**Pull request merged**
