### PR TITLE
DOC: Preparing change log for next release

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to prepare the change log for next release by doing the following:

* Fix existing formatting.
* Fix year typo of last release.
* Propose major version bump in accordance to https://semver.org/ (negotiable).
* Since we have not been updating it, I added vague entries for this next release. Though going forward, we need to be stricter about making sure PR authors add change log in their PRs (if applicable).

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)? No.

### CODE REVIEW

**Review by javerbukh — APPROVED** [review]
Looks good!

**Comment by havok2063** [comment]
I would bet there's a github action to auto-update a changelog by PRs, etc.

**Comment by pllim** [comment]
> auto-update a changelog by PRs

Kinda. `astropy` has adopted `towncrier` where PR provides a change log "fragment" and fragments get rendered into a change log during release time, but it is super confusing to maintain (easy for PR authors though), and probably overkill for this project. They also have a bot to enforce it.

**Comment by pllim** [comment]
I think one approval is enough...

**Comment by pllim** [comment]
p.s. Going forward, might want to rethink the subsections for the change log... Maybe broken down by feature/api/bug sub-category, and each by viz category, not unlike https://docs.astropy.org/en/latest/changelog.html

**Comment by havok2063** [comment]
The `astropy` approach could be overkill.  A quick search https://github.com/marketplace?type=actions&query=changelog+ shows some actions that look interesting enough to work out of the box with minimal setup.  e.g. `Changelog Reminder`, `Generate Changelog`, `Changelog Enforcer`.  Without me looking at any of the details of course.

**Comment by havok2063** [comment]
I like having sections in a changelog by release, with all line items under a release in a single list, but each line prefixed with `Bug`, `Feature`, `API`, etc, similar to how https://releases.readthedocs.io/en/latest/changelog.html renders things.  But lots of different ways to do it.

**Comment by pllim** [comment]
Since the currently change log was inherited from the old Astropy format, we can also use https://github.com/pllim/action-check_astropy_changelog .

Since this PR is merged, @havok2063 , feel free to open new issue if you feel passionately about change log check in this repo. Thanks!

**Pull request merged**
