### PR TITLE
Update the desktop-app base notebooks to use our new helpers

### PR DESCRIPTION
**Pull request by dtn5ah**
Jdaviz, when launched in desktop-app mode from the CLI, uses base notebooks in each of the configuration dirs to construct the voila view. Previously they each made a `jdaviz.app` call. This PR updates these notebooks to use our new `jdaviz.cubeviz`, `.specviz`, and `.mosviz` helpers

### CODE REVIEW

**Comment by dtn5ah** [comment]
I marked this as draft because it is built atop my other Windows Desktop PR #282. I'll jump over there to get that merged in ASAP to clear the way for this one

**Review by rosteen — COMMENTED** [review]
Specviz and Cubeviz look good, and Mosviz loads if I give it a dummy file as input. Is there a particular file or file format that Mosviz is looking for to actually load data?

I'll also note that closing the browser tab with the notebook in it doesn't result in graceful closing behavior, throwing the following error. Not sure if that's a "this PR" thing or a follow-up.

```ERROR:tornado.application:Uncaught exception GET /api/kernels/734dfc2c-d5ff-4d78-ac0d-a327af38cb8d/channels?session_id=6af159ca-2f51-473f-a436-7c653a00ee7c (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/api/kernels/734dfc2c-d5ff-4d78-ac0d-a327af38cb8d/channels?session_id=6af159ca-2f51-473f-a436-7c653a00ee7c', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 236, in get
    await super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/jupyter_server/base/zmqhandlers.py", line 279, in get
    await res
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/tornado/websocket.py", line 278, in get
    await self.ws_connection.accept_connection(self)
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/tornado/websocket.py", line 879, in accept_connection
    await self._accept_connection(handler)
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/tornado/websocket.py", line 962, in _accept_connection
    await self._receive_frame_loop()
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/tornado/websocket.py", line 1119, in _receive_frame_loop
    self.handler.on_ws_connection_close(self.close_code, self.close_reason)
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/tornado/websocket.py", line 576, in on_ws_connection_close
    self.on_connection_close()
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/tornado/websocket.py", line 568, in on_connection_close
    self.on_close()
  File "/Users/rosteen/opt/anaconda3/envs/clean/lib/python3.8/site-packages/jupyter_server/services/kernels/handlers.py", line 445, in on_close
    if km._kernel_connections[self.kernel_id] == 0:
KeyError: '734dfc2c-d5ff-4d78-ac0d-a327af38cb8d'```

**Comment by dtn5ah** [comment]
@rosteen The notebook configuration for mosviz uses our example dataset in the Mosviz Example notebook. Once we have more general parsers for mosviz, we'll replace them

I also noted the traceback on closing, but I thought I remembered seeing this elsewhere, so I didn't think it was related to this PR. Should probably ticket it

**Comment by rosteen** [comment]
Sure, but that dataset includes multiple files, and the command line expects a single filename as input - I should have been clearer, I'm wondering what filename to give to the command line call for Mosviz. Do I need to zip up those files, or give the directory they're in as the input filename?

**Comment by dtn5ah** [comment]
Ahh I see. I extract the folder and just feed it the folder. Perhaps it should support the zip file itself as well?

**Review by rosteen — APPROVED** [review]

**Review by javerbukh — APPROVED** [review]
Looks good!

**Comment by javerbukh** [comment]
Merging.

**Pull request merged**
