### PR TITLE
Mosviz: table row select/scroll

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements an API for select_row/next_row/previous_row on the table-viewer as well as up and down arrows and a play/pause button in the table toolbar.  ~~The UI/UX is not yet reviewed/finalized, but currently looks like:~~

**Paused**:
Screen Shot 2021-10-22 at 3 37 30 PM

**Playing**:
Screen Shot 2021-10-22 at 3 42 29 PM

with the following alternative to consider for the "active" play state:

Screen Shot 2021-10-22 at 3 37 45 PM

Changing the delay time (in seconds) while playing immediately updates on the next iteration (although the change using the up/down buttons in the number select is not applied until clicking away - this is a vue internal design and does allow scrolling without a ton of internal updates).

Before ready for review:
- [x] support for table paging (clicking next or cycling beyond the limits of a page should extend to the next page AND select that page in the table).  

Future Considerations:
* Do we want to keep the arrow buttons? 
* Do we want to continue to pursue keyboard-bindings?

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by rosteen** [comment]
Looks great, although I would love to see some test coverage if possible. 

The only thing that didn't behave as I hoped was that I started with a 5 second delay, decided that was too slow, and decreased the delay while in "play" mode. Turned out I had to actually pause and then play again to get the new delay to register, I had hoped it would be applied automatically after the next row iteration.

**Review by PatrickOgle — APPROVED** [review]
Scroll and play GUI buttons work nicely on a simulated, pipeline-processed NIRSpec MOS dataset.  Using this new functionality brings up some new issues to be considered separately:
1) The 3 viewers populate independently giving a distracting flashing effect when going from one row to the next
2) The paging function is independent of the select function, so you can inadvertently go to another page and select/play through rows on a different page than the one being viewed. Maybe the selection should jump to the first row when paging.

**Comment by kecnry** [comment]
@rosteen - changing the delay does update on the next iteration once the change in the widget is registered.  Previously I had this only when the `change` event was fired (which requires the widget to lose focus by clicking away or hitting tab).  I just changed it so that it also fires on a mouse press, so that it immediately updates when clicking on the up/down buttons within the number widget.  But if you enter a number with the keyboard, it will still wait until the widget loses focus (to avoid a number of complications and performance issues when clearing the entry altogether or entering a double digit number: if we were to trigger on a keypress, entering "15" would first set the cycle at 1 second until the "5" is also entered, which in my opinion is more frustrating than waiting for the change event to fire).  Let me know what you think!

I also added some simple tests to make sure next/prev_row work and handle wrapping correctly.  Let me know if you think anything else should be covered.

@PatrickOgle - good points.  For the second one, we should definitely keep an eye out for user feedback, I'm not entirely sure what makes the most intuitive sense.  I did test, and the UI buttons introduced here still act as I think I'd expect if you manually change pages (the page will snap back to the active highlighted row), although I can see how in some cases where you're "browsing" future pages while the play feature is active, that might not be ideal.

**Review by rosteen — APPROVED** [review]
> if we were to trigger on a keypress, entering "15" would first set the cycle at 1 second until the "5" is also entered, which in my opinion is more frustrating than waiting for the change event to fire). Let me know what you think!
>

I agree! I like the way it works now, looks good to me. Thanks for adding the test coverage.

**Pull request merged**
