### PR TITLE
add incantation to auto-download the data cube

### PR DESCRIPTION
**Pull request by eteq**
This is a pretty simple thing that just updates the cubeviz example to auto-download (with a pretty progress bar if `tqdm` is installed...) the manga example dataset.

### CODE REVIEW

**Comment by SaOgaz** [comment]
Wouldn't it be better to link to the box link with the smaller file?  Or is the idea that someone external could run it...

**Comment by eteq** [comment]
@SaOgaz - definitely for external. Where possible (and in this case it's easy because SDSS manages the archive), we want to use that so these notebooks are usable by anyone.

(Also it's really hard to automate box downloads unless we make a static link, and this isn't our data.)

**Comment by eteq** [comment]
@SaOgaz - although I guess the idea would be you can just manually put in the "fixed" version if we like as a backup option (i.e. "if it's there, use that")?

**Comment by brechmos-stsci** [comment]
@SaOgaz @eteq   You guys good with the way it is, or is there going to be a modification?

**Comment by brechmos-stsci** [comment]
Talked with both and they said it was ready. Did a quick ck and appeared to work.

**Pull request merged**
