### PR TITLE
data-menu: API hints

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request moves API hint toggles from the plugin to the app-level and implements API hints for the data-menu.

https://github.com/user-attachments/assets/ddf63d27-ef7c-459c-abd0-b893dffdd95b

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone. Bugfix milestone also needs an accompanying backport label.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by camipacifici** [comment]
I really like it!
The only thing that took me a tiny bit to figure out is the toggle for keeping the hints available for copy/paste. I kept clicking on the lock instead of on the icon and nothing was happening. Then I clicked on the icon. I think it is because the tooltip is also on the lock.

**Comment by kecnry** [comment]
@gibsongreen mentioned suggestions for the icon as well, maybe we can get a custom icon from @Jenneh for that down the road.  I couldn't find anything off-the-shelf as a single icon that worked well 🫤

**Review by gibsongreen — APPROVED** [review]
All the code changes look good to me and I really like the hints at the app-level!

I also tried clicking on the lock and agree about the tooltip, but got used to it so I’m for whichever path forward works best.

The other icon suggestion was in a followup effort to possibly update the `< >` to `<API>`. As long as the width works out I think it would add a lot of clarity.

**Comment by cshanahan1** [comment]
This looks good! Is this not complete for all plugins yet? I don't see hints for aperture photometry

**Comment by kecnry** [comment]
This PR only brings to the data-menu.  Previous PRs have exposed hints for all plugins with public APIs (aperture photometry is not one of those yet).

**Review by cshanahan1 — APPROVED** [review]

**Pull request merged**
