### PR TITLE
Line Lists: Success message in plugin

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to see where we can move the success message from Line Lists to somewhere more permanent that user cannot miss because it contains instructions of what to do next.

Unblocks:

* #1368 

### TODO

- [x] Is permanent text field sufficient? If not, where? Hint text.
- [x] Should we remove the Snackbar messages completely? Nah.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)? [🐱](https://jira.stsci.edu/browse/JDAT-2513)

### CODE REVIEW

**Comment by kecnry** [comment]
How about just adding something like "Toggle visibility of loaded lines in section below" to the end of the existing hint text: "Select a line list to load"?  That way the UI doesn't add a new entry that jumps down and we don't need to place the name of the line list in the message.  We might also want to consult @Jenneh for a final decision, but at least getting something in now will let us move on with the blocked PR.

Screen Shot 2022-06-10 at 9 02 39 AM

**Comment by pllim** [comment]
@kecnry , I think I applied the changes as you suggested.

**Review by kecnry — APPROVED** [review]
I think this is probably sufficient for now and then let's see if @Jenneh has other ideas.  If/when we optimize plotting the lines, we can also consider just having the lines plot immediately on load and then this probably can be removed.

**Comment by kecnry** [comment]
Since this is literally just updating text in the UI, can we consider this "trivial" and merge so we can also get #1368 in?

**Comment by pllim** [comment]
@kecnry , I would agree with you but I might be biased. 😆

**Pull request merged**
