### PR TITLE
Cubeviz contour

### PR DESCRIPTION
**Pull request by javerbukh**
`Removed outdated GIF`

Current implementation of a contour overlay, looking for feedback.

1) What kinds of things will be plotted as an overlay? (i.e., The current slice of another viewer, moment map, etc.) If something could be plotted as an overlay is not currently implemented, can you link to an example implementation or code?

2) What options should be available to a user for contour settings? I assume levels, color of contours, presence of labels, opacity, what else?

3) Are there ways that levels are found automatically? In Patrick's example notebook, the contours were at `max_level/10.`, `max_level/100.`, and so on. Should I include linear and exponential contour level options, in addition to potential others?

I'd appreciate any input from @PatrickOgle, @eteq, and any other interested parties on this.

### CODE REVIEW

**Comment by PatrickOgle** [comment]
The present implementation is good for presenting contours of cube slices.   Will it work for 2D products that don't change with slice?  I would like to import a 2D image into one of the viewers, create the contours, and have them overplotted on the slices as one scrubs through the cube.  The contours would not change with slice in this use case.

**Comment by nmearl** [comment]
Is there a technical reason why you have to specify a secondary _viewer_ as opposed to just a secondary _data set_?

**Comment by javerbukh** [comment]
@nmearl , no, this is purely for the purposes of seeing if/how it works. Secondary data set is a much better approach!

@PatrickOgle Instead of importing a 2D image, can I use a function that converts the selected data cube into a 2D image (potentially like `cube_sum=np.sum(sci, axis=0)` in the original contour concept notebook). If so, what kind of other functions would it be helpful to make contours of?

**Comment by javerbukh** [comment]
Aug-04-2020 14-37-15

Latest commits adds clearer directions for `contour_overlay` concept + development notebook. `Visible` checkbox does not work.

Also, adding `bqplot.Contour` should add to the `viewer.figure` the same way `bqplot.Mark` does (similar to [this notebook](https://github.com/spacetelescope/jdaviz/blob/master/notebooks/concepts/mosviz_overplot_slit_example.ipynb)), instead it stays static and does not follow the `image` when it is in `Pan/Zoom` mode.

Aug-04-2020 14-40-20

**Comment by PatrickOgle** [comment]
Contours do appear to be flipped up-down.  The indexing convention in numpy arrays could be a potential cause of this.

**Comment by PatrickOgle** [comment]
Can you point me to the test datacube so I can try to validate the contour levels?

**Comment by PatrickOgle** [comment]
I verify that the contour levels are similar to what I expect
MANGA_DS9_contours
.  Here is are the same contour levels (0.01526,0.1526,0.3053,1.018) displayed in SAOimage DS9 (in image coordinates)

**Comment by PatrickOgle** [comment]
Also need the capability to over-plot contours of a different (WCS-matched) image on the cube viewer.

**Comment by PatrickOgle** [comment]
> @nmearl , no, this is purely for the purposes of seeing if/how it works. Secondary data set is a much better approach!
> 
> @PatrickOgle Instead of importing a 2D image, can I use a function that converts the selected data cube into a 2D image (potentially like `cube_sum=np.sum(sci, axis=0)` in the original contour concept notebook). If so, what kind of other functions would it be helpful to make contours of?

Users would want to overplot contours of, for example:
1) Collapsed cube
2) 0th, 1st, and moments (flux, velocity, velocity dispersion
3) Line maps
4) Some other wavelength band (radio, X-ray, UV, etc...)

All of these have in common: Some 2D image that we would read in and make contours of.

**Comment by maartenbreddels** [comment]
> Also, adding `bqplot.Contour` should add to the `viewer.figure` the same way `bqplot.Mark` does (similar to [this notebook](https://github.com/spacetelescope/jdaviz/blob/master/notebooks/concepts/mosviz_overplot_slit_example.ipynb)), instead it stays static and does not follow the `image` when it is in `Pan/Zoom` mode.

This seems like a bug in bqplot-image-gl, I can try to fix this.

**Comment by rosteen** [comment]
FYI toggling the "Visible" checkbox off and then back on triggers an error for me:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in _handle_msg(self, msg)
    674                 if 'buffer_paths' in data:
    675                     _put_buffers(state, data['buffer_paths'], msg['buffers'])
--> 676                 self.set_state(state)
    677 
    678         # Handle a state request.

~/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in set_state(self, sync_data)
    543                     from_json = self.trait_metadata(name, 'from_json',
    544                                                     self._trait_from_json)
--> 545                     self.set_trait(name, from_json(sync_data[name], self))
    546 
    547     def send(self, content, buffers=None):

~/opt/anaconda3/envs/viz_dev/lib/python3.8/contextlib.py in __exit__(self, type, value, traceback)
    118         if type is None:
    119             try:
--> 120                 next(self.gen)
    121             except StopIteration:
    122                 return False

~/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/traitlets/traitlets.py in hold_trait_notifications(self)
   1129                 for changes in cache.values():
   1130                     for change in changes:
-> 1131                         self.notify_change(change)
   1132 
   1133     def _notify_trait(self, name, old_value, new_value):

~/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/ipywidgets/widgets/widget.py in notify_change(self, change)
    604                 # Send new state to front-end
    605                 self.send_state(key=name)
--> 606         super(Widget, self).notify_change(change)
    607 
    608     def __repr__(self):

~/opt/anaconda3/envs/viz_dev/lib/python3.8/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1174                 c = getattr(self, c.name)
   1175 
-> 1176             c(change)
   1177 
   1178     def _add_notifiers(self, handler, name, type):

~/projects/jdaviz/jdaviz/configs/cubeviz/plugins/contour_overlay/contour_overlay.py in _observe_visible(self, event)
    179     def _observe_visible(self, event):
    180         if event["new"] and hasattr(self, "figure_current_marks"):
--> 181             self.app.get_viewer(self.overlayed_viewer).figure.marks = self.figure_current_marks[self.figure_overlay_on]
    182         elif event["new"]==False and hasattr(self, "figure_original_marks"):
    183             self.app.get_viewer(self.overlayed_viewer).figure.marks = self.figure_original_marks[self.figure_overlay_on]

KeyError: <jdaviz.configs.cubeviz.plugins.viewers.CubeVizImageView object at 0x7fdd28a7ab20>
```

**Comment by maartenbreddels** [comment]
I guess this can be closed now https://github.com/glue-viz/glue-jupyter/pull/199 is merged.

**Comment by javerbukh** [comment]
Agreed! Closing now.

**Pull request closed without merging**
