### PR TITLE
TST: Test against Python 3.11

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to see how badly things break in Python 3.11 (using RC2).

### Blocked by

* https://github.com/glue-viz/glue/issues/2340
* https://github.com/astropy/regions/issues/475
    * https://github.com/astropy/regions/pull/476

### No longer an issue

* https://github.com/h5py/h5py/issues/2146 (glue stopped pulling it for Python 3.11, see https://github.com/glue-viz/glue/pull/2321)

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set?
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Nope... regions and h5py need to catch up first. We can revisit this PR when they do. (So close!)

**Comment by pllim** [comment]
Hmm the dev deps now installed but looks like it is going to time out. 😬

**Comment by dhomeier** [comment]
Installing (building yourself, probably) `h5py` for py311 at least at this time, for rc2, requires `libhdf5-dev` (possibly also `libopenblas-dev`, but that's probably for numpy/scipy) in the `apt` libs, and `hdf5` from `brew`.

**Comment by pllim** [comment]
I didn't mean to build h5py from source. The released version wasn't working but since you said it is supposed to work now, let's see.

**Comment by dhomeier** [comment]
From what I can tell from the log, it has to build the wheel itself. See glue-viz/glue#2321 for reference.

**Comment by pllim** [comment]
That is kinda painful for something that we don't even use here.

**Comment by pllim** [comment]
We can now officially add Python 3.11 to our CI. 😸

**Review by rosteen — APPROVED** [review]

**Pull request merged**
