### PR TITLE
Mixin for plugin_opened and use for compass

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request moves the logic in LineAnalysis to act differently if the plugin is opened or closed into the `PluginTemplateMixin` to be available to all plugins, and then used in the compass plugin to only re-draw the compass when the plugin is opened.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
A quick test with Compass (without #1152) seems very promising!

If we want to focus on Compass, Imviz viewer also manually redraw at two other places but we have leave those unless performance becomes a problem again:

https://github.com/spacetelescope/jdaviz/blob/b2e6c8dc265d0531a2706855e2ff73873cc08025/jdaviz/configs/imviz/plugins/viewers.py#L188

https://github.com/spacetelescope/jdaviz/blob/b2e6c8dc265d0531a2706855e2ff73873cc08025/jdaviz/configs/imviz/plugins/viewers.py#L197

**Comment by kecnry** [comment]
> If we want to focus on Compass, Imviz viewer also manually redraw at two other places

I think in both of these cases, `set_compass` will see `self.compass is None` and exit immediately.  Once opened, the plugin will set `viewer.compass = self` for the appropriate viewer and the compass should then update as expected.  But I didn't check thoroughly that it is never called when it shouldn't be.

**Comment by pllim** [comment]
Please rebase to pick up new matrix, thanks!

**Review by pllim — APPROVED** [review]
I don't see any reason not to do this.

**Review by javerbukh — APPROVED** [review]
I can confirm the code is code. Nice work! 😄

**Pull request merged**
