### PR TITLE
Fix size calculation for model parameters array

### LINKED ISSUE #2158: [BUG] Using cubeviz.get_model_parameters after cube fitting raises error
### Jdaviz component

Cubeviz

### Description

This morning, I tried to do a cube fit and then get the parameter arrays out with `cubeviz.get_model_parameters()`. This returned an IndexError (indexd 45 is out of range for array of size 45). I wonder if the string labels for the components are getting 1-indexed somehow - I imagine it's something along those lines anyway.

### How to Reproduce

1. Run a model fit without and then with "Cube Fit" selected.
3. Try to run `[helper].get_model_parameters()` in the notebooks.

### Expected behavior

We're supposed to get a dictionary out that contains arrays of the fitted model parameters at each spaxel.

### Browser

_No response_

### Jupyter

_No response_

### Software versions

This was using the current release (3.4.0) of Jdaviz.

[🐱](https://jira.stsci.edu/browse/JDAT-3306)

### PR DESCRIPTION
**Pull request by rosteen**
Fixes #2158 . I also removed the `_3d` that was getting tacked on to the label for the cube models, since by default the labels for those in the plugin now get `cube-fit ` prepended to the suggested label. Basically, there might not be fitted parameters for every spaxel (due to masking and such), so relying on the length of the arrays of x and y spaxel locations was unreliable.

### CODE REVIEW

**Comment by rosteen** [comment]
I'll try to add a test that would catch this tomorrow.

**Comment by rosteen** [comment]
I added a test, this should be good to go.

**Comment by rosteen** [comment]
FYI the CodeCov upload failed, not sure why. The coverage should be better than indicated above.

**Comment by pllim** [comment]
That codecov upload failure should be transient. It asks us to provide token but PR from a fork can't access the token anyway. So upload without token when we have a lot of pushes get sketchy with the API limits.

**Comment by rosteen** [comment]
I switched milestone to 3.5 since this actually changes the returned keys and messes up at least one `jdat_notebooks` notebook. I'll update the changelog in a moment.

**Review by kecnry — APPROVED** [review]
LGTM with the accompanying update to the jdat notebook.  Thanks!

**Review by cshanahan1 — APPROVED** [review]

**Pull request merged**
