### PR TITLE
Fix "fixed" parameter option in model fitting

### PR DESCRIPTION
**Pull request by rosteen**
Now actually fixes the specified parameters when model fitting.

### CODE REVIEW

**Comment by rosteen** [comment]
@javerbukh Good catch, slipped my mind that I have a separate initializer function specifically to handle polynomials. I'll update that later today.

**Comment by rosteen** [comment]
@javerbukh Fixed the bug you found. The most recent test run failed due to a download/connection problem.

**Comment by dtn5ah** [comment]
Quick thing I found. If I leave the  Equation Editor blank and try to FIT anyways, it still apparently tries to fit anyways, even though the equation editor is a required field, I get the below traceback, with no indication the equation editor field is missing.

image


Might I suggest if the user leaves that field is blank, raise an error like what happens once you click on the Equation Editor, don't enter anything, and click off?

image

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
f:\stsci\gitrepos\jdaviz\envpr246\lib\site-packages\ipyvue\VueTemplateWidget.py in _handle_event(self, _, content, buffers)
     48             event = content.get("event", "")
     49             data = content.get("data", {})
---> 50             getattr(self, 'vue_' + event)(data)
     51 
     52 

f:\stsci\gitrepos\jdaviz\envpr246\lib\site-packages\jdaviz\configs\default\plugins\model_fitting\model_fitting.py in vue_model_fitting(self, *args, **kwargs)
    293         """
    294         models_to_fit = self._reinitialize_with_fixed()
--> 295         fitted_model, fitted_spectrum = fit_model_to_spectrum(
    296             self._spectrum1d,
    297             models_to_fit,

f:\stsci\gitrepos\jdaviz\envpr246\lib\site-packages\jdaviz\configs\default\plugins\model_fitting\fitting_backend.py in fit_model_to_spectrum(spectrum, component_list, expression, run_fitter)
     58         return _fit_3D(initial_model, spectrum)
     59     else:
---> 60         return _fit_1D(initial_model, spectrum, run_fitter)
     61 
     62 

f:\stsci\gitrepos\jdaviz\envpr246\lib\site-packages\jdaviz\configs\default\plugins\model_fitting\fitting_backend.py in _fit_1D(initial_model, spectrum, run_fitter)
     84     """
     85     if run_fitter:
---> 86         output_model = fit_lines(spectrum, initial_model)
     87         output_values = output_model(spectrum.spectral_axis)
     88     else:

f:\stsci\gitrepos\jdaviz\envpr246\lib\site-packages\specutils\fitting\fitmodels.py in fit_lines(spectrum, model, fitter, exclude_regions, weights, window, **kwargs)
    360         #
    361 
--> 362         ignore_units = getattr(model_guess, model_guess.param_names[0]).unit is None
    363 
    364         fit_model = _fit_lines(spectrum, model_guess, fitter,

AttributeError: 'NoneType' object has no attribute 'param_names'
```

**Comment by rosteen** [comment]
@dtn5ah Good point, see most recent commit for a fix to that.

**Comment by rosteen** [comment]
@javerbukh let me know offline that this seems to have broken the cube fitting:

```
Traceback (most recent call last):
  File "/Users/javerbukh/anaconda3/envs/model_fixed_parameter/lib/python3.8/site-packages/specutils/utils/quantity_model.py", line 44, in __getattr__
    if hasattr(self.unitless_model, nm):
  File "/Users/javerbukh/anaconda3/envs/model_fixed_parameter/lib/python3.8/site-packages/specutils/utils/quantity_model.py", line 44, in __getattr__
    if hasattr(self.unitless_model, nm):
  File "/Users/javerbukh/anaconda3/envs/model_fixed_parameter/lib/python3.8/site-packages/specutils/utils/quantity_model.py", line 44, in __getattr__
    if hasattr(self.unitless_model, nm):
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded
```

I remember this cropping up before but not what the resolution was, I'll try to track down and fix the cause today.

**Comment by rosteen** [comment]
@javerbukh As discussed offline today, I disabled the use of the `fixed` parameter option for the cube fitting case. We're leaving that problem to be solved at a later date once we're in less of a time crunch.

**Comment by javerbukh** [comment]
Testing now, I ran pretty much the same thing I did in one of my earlier comments in this PR and got the following error:
`TraitError: The 'poly_order' trait of a ModelFitting instance must be an int, but a value of '' <class 'str'> was specified.`

I believe changing the `poly_order` traitlet to `Any` or `Unicode` would fix this.

**Comment by PatrickOgle** [comment]
I get an error like this when I specify a model name 'L' that does not exist.  Can we more gracefully have a message
that says "One or more model components have not been named or defined."  and another more generic message:
"There may be a problem with the model equation". I could create a github issue for this if warranted.:

NameError
   L
name 'L' is not defined
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/envs/jdaviz16/lib/python3.8/site-packages/ipyvue/VueTemplateWidget.py in _handle_event(self, _, content, buffers)
     48             event = content.get("event", "")
     49             data = content.get("data", {})
---> 50             getattr(self, 'vue_' + event)(data)
     51 
     52 

~/Desktop/jdat/jdaviz/jdaviz/configs/default/plugins/model_fitting/model_fitting.py in vue_model_fitting(self, *args, **kwargs)
    267         values
    268         """
--> 269         fitted_model, fitted_spectrum = fit_model_to_spectrum(
    270             self._spectrum1d,
    271             self._initialized_models.values(),

~/Desktop/jdat/jdaviz/jdaviz/configs/default/plugins/model_fitting/fitting_backend.py in fit_model_to_spectrum(spectrum, component_list, expression, run_fitter)
     58         return _fit_3D(initial_model, spectrum)
     59     else:
---> 60         return _fit_1D(initial_model, spectrum, run_fitter)
     61 
     62 

~/Desktop/jdat/jdaviz/jdaviz/configs/default/plugins/model_fitting/fitting_backend.py in _fit_1D(initial_model, spectrum, run_fitter)
     84     """
     85     if run_fitter:
---> 86         output_model = fit_lines(spectrum, initial_model)
     87         output_values = output_model(spectrum.spectral_axis)
     88     else:

~/miniconda3/envs/jdaviz16/lib/python3.8/site-packages/specutils/fitting/fitmodels.py in fit_lines(spectrum, model, fitter, exclude_regions, weights, window, **kwargs)
    360         #
    361 
--> 362         ignore_units = getattr(model_guess, model_guess.param_names[0]).unit is None
    363 
    364         fit_model = _fit_lines(spectrum, model_guess, fitter,

AttributeError: 'NoneType' object has no attribute 'param_names'

**Comment by rosteen** [comment]
@PatrickOgle I wasn't able to track down where exactly that NameError warning is getting created, so I'm catching the AttributeError and sending a snackbar error message when this happens. The NameError showing what's wrong with the model equation will still appear below the app, but not the long error trace.

**Pull request merged**
