### PR TITLE
MNT: Bump glue-jupyter minversion pinning to 0.11.1

### LINKED ISSUE #1117: TST: glue-jupyter 0.11.0 broke our CI
### TODO

- [ ] Revert #1119

### Blocks

* #1140
* #1101 

### Original post

I reran a previously successful run, which now picked up glue-jupyter 0.11.0 released today, and it broke: https://github.com/spacetelescope/jdaviz/runs/5326228099?check_suite_focus=true

```
_________________________ test_region_spectral_spatial _________________________

jdaviz_app = Application(config='cubeviz', events=['call_viewer_method', 'close_snackbar_message', 'data_item_selected', 'destroy_v... hsla(0,0%,100%,.35) !important;\n}\n\n.no-hint .v-text-field__details {\n  display: none !important;\n}\n</style>\n'))
spectral_cube_wcs = WCS Keywords

Number of WCS axes: 3
CTYPE : 'RA---TAN'  'DEC--TAN'  'FREQ'  
CRVAL : 0.0  0.0  0.0  
CRPIX : 0.0  0.0 ...0  0.0  
PC2_1 PC2_2 PC2_3  : 0.0  1.0  0.0  
PC3_1 PC3_2 PC3_3  : 0.0  0.0  1.0  
CDELT : 1.0  1.0  1.0  
NAXIS : 0  0

    def test_region_spectral_spatial(jdaviz_app, spectral_cube_wcs):
        data = Data(flux=np.ones((256, 128, 128)), label='Test Flux', coords=spectral_cube_wcs)
        jdaviz_app.data_collection.append(data)
    
        jdaviz_app.add_data_to_viewer('spectrum-viewer', 'Test Flux')
        jdaviz_app.add_data_to_viewer('flux-viewer', 'Test Flux')
    
        jdaviz_app.get_viewer("spectrum-viewer").apply_roi(XRangeROI(5, 15.5))
    
        flux_viewer = jdaviz_app.get_viewer("flux-viewer")
        # We set the active tool here to trigger a reset of the Subset state to "Create new"
>       flux_viewer.toolbar.active_tool = flux_viewer.toolbar.tools['bqplot:rectangle']

../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/jdaviz/tests/test_subsets.py:91: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:606: in __set__
    self.set(obj, value)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:595: in set
    obj._notify_trait(self.name, old_value, new_value)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:1219: in _notify_trait
    self.notify_change(Bunch(
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/ipywidgets/widgets/widget.py:606: in notify_change
    super(Widget, self).notify_change(change)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:1229: in notify_change
    return self._notify_observers(change)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:1266: in _notify_observers
    c(event)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/glue_jupyter/common/toolbar_vuetify.py:63: in _on_change_active_tool
    change.new.activate()
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/glue_jupyter/bqplot/common/tools.py:166: in activate
    super().activate()
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/glue_jupyter/bqplot/common/tools.py:43: in activate
    super().activate()
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/glue_jupyter/bqplot/common/tools.py:29: in activate
    viewer.toolbar.active_tool = None
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:606: in __set__
    self.set(obj, value)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:595: in set
    obj._notify_trait(self.name, old_value, new_value)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:1219: in _notify_trait
    self.notify_change(Bunch(
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/ipywidgets/widgets/widget.py:606: in notify_change
    super(Widget, self).notify_change(change)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:1229: in notify_change
    return self._notify_observers(change)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/traitlets/traitlets.py:1266: in _notify_observers
    c(event)
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/glue_jupyter/common/toolbar_vuetify.py:58: in _on_change_active_tool
    change.old.deactivate()
../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/jdaviz/configs/cubeviz/plugins/tools.py:33: in deactivate
    self.viewer.remove_event_callback(self.on_mouse_event)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <jdaviz.configs.cubeviz.plugins.viewers.CubevizProfileView object at 0x7fe84[342](https://github.com/spacetelescope/jdaviz/runs/5326228099?check_suite_focus=true#step:6:342)6df0>
callback = <bound method SelectSlice.on_mouse_event of <jdaviz.configs.cubeviz.plugins.tools.SelectSlice object at 0x7fe8433c83d0>>

    def remove_event_callback(self, callback):
        """
        Remove a callback function for mouse and keyboard events.
        """
>       self._events_for_callback.pop(callback)
E       KeyError: <bound method SelectSlice.on_mouse_event of <jdaviz.configs.cubeviz.plugins.tools.SelectSlice object at 0x7fe8433c83d0>>

../../.tox/py39-test-alldeps-cov/lib/python3.9/site-packages/glue_jupyter/bqplot/common/viewer.py:149: KeyError
```

Suspect: glue-viz/glue-jupyter#279

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to revert #1119 . We can only do this when `glue-jupyter` is released (0.11.1?) with glue-viz/glue-jupyter#296 in it.

Fixes #1117

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by dhomeier** [comment]
`glue-jupyter` 0.11.1 is released.

**Review by pllim — COMMENTED** [review]
I cannot approve my own PR but I approve. 😆

**Comment by pllim** [comment]
Thanks, @dhomeier !

**Comment by pllim** [comment]
Hrrmmmm... lots of stuff dropped Python 3.7, maybe that's why it is hanging. I need to open a follow up PR to drop Python 3.7 altogether.

**Review by kecnry — APPROVED** [review]

**Pull request merged**
