### PR TITLE
TST: update remote data test

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request updates test values for a change in the remote data

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by bmorris3 — APPROVED** [review]
Looks good.

Separate question: is there a pipeline/calibration version header card or similar? It'd be great to have an assertion in the tests that fails first and loudly to indicate that this is the problem in the future.

**Comment by bmorris3** [comment]
RE my comment above, maybe these cards are relevant:
```
SDP_VER = '2022_4a '           / Data processing software version number        
PRD_VER = 'PRDOPSSOC-059'      / S&OC PRD version number used in data processing
OSS_VER = '8.4.5.2 '           / Observatory Scheduling Software (OSS) version n
CAL_VER = '1.8.2   '           / Calibration software version number            
CAL_VCS = 'RELEASE '           / Calibration software version control sys number
```

**Comment by kecnry** [comment]
I'd like @pllim to look at this before merge.  Feel free to push directly to my branch if you want to add that test on top of this (or can do it as a separate PR later).

**Comment by pllim** [comment]
Pipeline version can change and would cause no difference, so I doubt adding pipeline version check would help. Also if reference files change but reprocessed using the same pipeline version, it might also fail.

**Review by pllim — APPROVED** [review]
The differences are not shocking. LGTM. Thanks!

**Pull request merged**
