### PR TITLE
DO NOT MERGE: Test glue-astronomy PR 82

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to test https://github.com/glue-viz/glue-astronomy/pull/82 to see if it can address https://github.com/spacetelescope/jdaviz/issues/1967

### CODE REVIEW

**Comment by dhomeier** [comment]
https://github.com/glue-viz/glue-astronomy/actions/runs/3959396433/jobs/6782165867#step:5:21

is `install_requires` overriding `devdeps` here??

**Comment by pllim** [comment]
Probably. I forgot the fork branch doesn't have tag. Let's see if the second commit would allow the install.

**Comment by dhomeier** [comment]
Looks like the test was broken by numpy/numpy#23039; not sure if that is a `bqplot` issue now.

**Comment by dhomeier** [comment]
scipy/scipy#17811

**Comment by pllim** [comment]
It was green. Experiment done.

**Pull request closed without merging**
