### PR TITLE
WIP: line flux plugin

### PR DESCRIPTION
**Pull request by javerbukh**
Example plugin which will show users how to add their own.

### CODE REVIEW

**Comment by nmearl** [comment]
This looks nice, but just a couple thoughts off the bat (which you may not yet have gotten to):

1. I'd say the purpose of the example plugin workflow is to document the process of extending jdaviz through a notebook first. I.e. without having to include new stuff in the repo. For example, the user would define the `LineFlux` class in a cell in their notebook, then add it manually (that is, not through the registry), to the section of the UI they want it to live. (This would require exposing an api for adding the plugin to specific parts of the UI, which is outside the purview of the ticket, but which I'd probably work on).
2. The next iteration of the documentation would describe moving the plugin out of the notebook to some entry point install that gets picked up by jdaviz at runtime.

**Comment by javerbukh** [comment]
> This would require exposing an api for adding the plugin to specific parts of the UI, which is outside the purview of the ticket, but which I'd probably work on

So is the idea to take the code that is in this ticket, cut it, copy it into a notebook, and then attempt to weave it back into jdaviz externally? Shouldn't the API to do this come first?

> moving the plugin out of the notebook to some entry point install that gets picked up by jdaviz at runtime.

Does this functionality already exist in jdaviz? If so, what is the process to do this look like?

**Comment by javerbukh** [comment]
@eteq , you mentioned yesterday you envisioned a 4 step process for this issue. Do you think you could detail those 4 steps here?

**Comment by nmearl** [comment]
> So is the idea to take the code that is in this ticket, cut it, copy it into a notebook, and then attempt to weave it back into jdaviz externally? Shouldn't the API to do this come first?

The api already supports this.

> Moving the notebook to some entry point install sounds reasonable but having the user build a plugin in a notebook using javascript does not.

I'm not sure what you mean here, the user doesn't need to use any javascript to get the plugin.

**Comment by javerbukh** [comment]
Outdated, closing and opening new PR soon.

**Pull request closed without merging**
