### PR TITLE
Add data file format identification and dialog prompt

### PR DESCRIPTION
**Pull request by havok2063**
Starting this PR so it can be reviewed/discussed.  This PR builds off #158 and adds functions for identifying an input file format and application configuration.  This functionality is needed by MAST.  The idea here is to have some mechanism for identifying an input file format and expected configuration and prompt the user when 1.) no valid format is found, 2.) an incorrect configuration is given compared to the pre-built ones, or 3.) when a file being is being loaded in the wrong configuration.  A dialog window is triggered with more information.  

Currently there is a `prompt_data` decorator on `app.load_data` and `SpecViz.load_data`.  This decorator checks the input data filename against a table of valid file formats, in `.core.data_formats`, similar to `astropy.io.registry` and `specutils` table of formats.  A file is matched against all the formats listed in a registered data table, validated using an associated "identifier" function in `.core.data_identifiers`, and the first item that matches is considered to be the valid format of the file.  It also returns the expected application configuration for that file format.       

If there's any mismatch, a message is broadcast which triggers the dialog prompt.  Currently the dialog window is purely informative and the application continues to try to load the data regardless.  I wanted the dialog to prompt the user to continue loading data anyway or stop, but I couldn't quite figure out how to make a blocking widget. The dialog is defined in a new `components` registry, which is loaded during application configuration.   This is meant to capture new Vue components that aren't really plugins or toolbar items but you still want to have a state and integrate with the larger application.  

Consider this PR a work in progress.  I still need to do a bunch of cleanup but some outstanding questions are:
- [ ] Should the data identifiers live in `jdaviz` or in `specutils`?  I somewhat prefer here if we can do so without duplicating effort.  I don't really like tying data formats to only those defined in `specutils`. 
- [ ] What should the (post) behavior of the dialog window be?
- [ ] Is the handling of the generic components satisfactory?  Am I missing something?

### CODE REVIEW

**Comment by havok2063** [comment]
I've updated this PR after discussion with @eteq and @nmearl.  I've removed all of the spectral identifier code, and moved new manga identifiers into `specutils`.   See the following PR, https://github.com/astropy/specutils/pull/702.  The logic to identify a registered `specutils` file format is now entirely in `specutils`.  

I've simplified the mapping between file format and configuration to a dictionary.  I've retained the `get_valid_format` function but repurposed it to use `specutils.io.registers.identify_spectrum_format` instead, which checks for a valid `Spectrum1D` file format.  When no file format is found, a fallback mapping using the dimensionality of the data is used to map to a recommended configuration.  

I've removed the `prompt_data` decorator from the `load_data` methods.  The `prompt_data` function is now a standalone function that can optionally be called as needed.  To see what the prompt looks like try the following:
```
from jdaviz.app import Application
from jdaviz.core.data_formats import prompt_data
app = Application(configuration='specviz')
data = '/Users/bcherinka/Work/notebooks/datb/manga-7495-12704-LOGCUBE.fits'
prompt_data(app, data)
```

**Comment by havok2063** [comment]
The functions to identify file formats and an expected application configuration have been split into PR #355 .  This PR contains relevant additions for 1.) adding general Vue non-plugin components to the application  and 2.) for generating a dialog "data" prompt when there's a mismatch between the input data and the existing application configuration.

**Comment by pllim** [comment]
This has conflicts now. Is this PR still relevant?

**Comment by havok2063** [comment]
This PR is old at this point but potentially still relevant.  It hasn't been rebased in quite some time.  I'll convert it to a draft PR and try to retool it.

**Comment by pllim** [comment]
Has this been superseded by #623 ?

**Comment by pllim** [comment]
Yes, I think so.

**Pull request closed without merging**
