### PR TITLE
Remove unwanted data label input

### PR DESCRIPTION
**Pull request by rosteen**
We shouldn't be passing `data_label` to `get_data_from_viewer` here, because we want whatever data is currently displayed regardless of label.

### CODE REVIEW

**Review by ibusko — APPROVED** [review]
LGTM, and didn't break anything I tried.

**Review by javerbukh — APPROVED** [review]
Looks good, however I'm blocked from merging by the same test as the Imviz parser. Do we need @duytnguyendtn to override this as well?

**Comment by rosteen** [comment]
I just rebased and force pushed, I think that should fix it.

**Comment by javerbukh** [comment]
It worked! Merging.

**Pull request merged**
