### PR TITLE
DOC: Radial profile text and screenshots

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to add more radial profile text and screenshots to the documentation.

https://jdaviz--1148.org.readthedocs.build/en/1148/imviz/plugins.html#simple-aperture-photometry

[🐱](https://jira.stsci.edu/browse/JDAT-2193)

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Ignore the dev failure; it is a known bug in astropy dev that will be fixed very soon.

**Comment by rosteen** [comment]
I think it might be confusing to the users that the screenshots have two subsets defined - I assume that the radial profiles shown are for the red subset, but how would they know? The text updates are good but I recommend updating the screenshots to only have one circular subset defined in the viewer.

**Review by javerbukh — APPROVED** [review]

**Comment by PatrickOgle** [comment]
@pllim The new text and plots look good I would also expand the first sentence in the section to this:

"This plugin performs simple aperture photometry and plots a radial profile for one object within an interactively selected region. A typical workflow is as follows:

**Comment by pllim** [comment]
RTD passed and we have enough approvals. There is no need for full CI so I canceled them. Merging. Thanks, everyone!

**Pull request merged**
