### PR TITLE
DOC: Pin sphinx!=7.2.0, glue-core!=1.13.1

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to build docs again while we debug over at #2379 

Also:

* https://github.com/glue-viz/glue/issues/2437

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
Still does not work. And @astrofrog said he might come patch stuff "later". Should I wait it out or stop using intersphinx for the affected modules?

https://github.com/glue-viz/glue/pull/2436#issuecomment-1682634290

**Comment by astrofrog** [comment]
I can fix it within the next 3 hours if you like!

**Comment by pllim** [comment]
Would be greatly appreciated since it is blocking our PRs. Thanks, Tom!

**Comment by astrofrog** [comment]
Can you try updating intersphinx URL to:

https://github.com/glue-viz/glue-jupyter/blob/3274465098d0a4b7e25af693cfe97cf3cccf3943/docs/conf.py#L58

**Comment by pllim** [comment]
@astrofrog , why `latest` and not `stable`?

**Comment by astrofrog** [comment]
I haven't updated stable yet for glue-core yet but will do shortly.

**Comment by pllim** [comment]
Superseded by #2381 

It's been a crazy day.

**Pull request closed without merging**
