### PR TITLE
MNT: glue-core v1.9.0 is bad glue

### PR DESCRIPTION
**Pull request by pllim**
### Description

Close #2135

### CODE REVIEW

**Comment by pllim** [comment]
The dev job failure signifies that something needs fixing upstream in glue-core.

**Comment by rosteen** [comment]
For some reason I thought we needed 1.9.0 for the unit conversion work, but since the tests aren't failing here I guess not? I'm ok with doing this for now instead of changing the moment test.

**Comment by pllim** [comment]
Re: unit conversion -- good point, but that work is currently in a separate branch, not in `main`.

**Comment by pllim** [comment]
Also the `!=` pin does not prevent future releases to be included, so we do not have to undo anything.

**Pull request merged**
