### PR TITLE
fix: make standalone work with matplotlib >= 3.9.0

### PR DESCRIPTION
**Pull request by maartenbreddels**
Unclear what the real underlying issue is. Code comments give a possible explanation.

Fixes https://github.com/spacetelescope/jdaviz/issues/2921

### CODE REVIEW

**Comment by pllim** [comment]
Let me try to close/re-open and see if the non-OSX standalone jobs would run.

**Comment by rosteen** [comment]
Hm, the numpy-related error in the Windows build is new to me:

```
Run ./standalone/dist/jdaviz/jdaviz-cli imviz&
Traceback (most recent call last):
  File "numpy\core\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\core\multiarray.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\core\overrides.py", line 8, in <module>
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "numpy\__init__.py", line 144, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\__config__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\core\__init__.py", line 50, in <module>
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "D:\a\jdaviz\jdaviz\standalone\dist\jdaviz\jdaviz-cli.exe"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "jdaviz-cli-entrypoint.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "matplotlib_inline\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "matplotlib_inline\backend_inline.py", line 6, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "matplotlib\__init__.py", line 172, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "matplotlib\cbook.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "numpy\__init__.py", line 149, in <module>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
[2420] Failed to execute script 'jdaviz-cli-entrypoint' due to unhandled exception!
```

**Comment by pllim** [comment]
Usually we see this when some package is using new numpy 2.0 ABI and some not.

**Comment by pllim** [comment]
`you should not try to import numpy from its source directory` is confusing though.

**Review by rosteen — APPROVED** [review]
As Maarten mentioned offline, this error is present on main (which I hadn't noticed). So I'm approving this.

**Comment by pllim** [comment]
Well, one less error to worry about. Thanks, all!

**Comment by pllim** [comment]
@rosteen , do we need to backport? I was not sure.

**Pull request merged**
