### PR TITLE
Set popup verbosity to warnings

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to stop emitting popup messages unless it is warnings or worse. This is because you can still see the mundane info stuff in the history logger. I have always been annoyed by all the popup messages when I load any of the viz.

With this patch, for instance, you will only see these when you open up the history logger thingy if nothing goes wrong on load.

Screenshot 2022-06-02 125711

This is a direct follow-up of #1352 

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
I'm all in favor of this, as long as the success messages aren't ever _relied_ on to communicate essential information.  I think we're slowly getting away from any of those cases (for example: automatically generated data labels from plugins used to only be visible from the snackbar, but now is visible in the plugin with options to either plot or not), but I'm not sure if any are left or not.

With this change, we also can start using success/info level snackbars more often for logging purposes without having to avoid them for annoyance concerns.

**Comment by pllim** [comment]
> we also can start using success/info level snackbars more often for logging purposes

Now that you mention this... `'debug'` is a valid option but the cake is a lie?

https://github.com/spacetelescope/jdaviz/blob/410361e248b367c41863a72fc7f405c40dc562c8/jdaviz/app.py#L310-L318

**Comment by pllim** [comment]
> the success messages aren't ever _relied_ on to communicate essential information

This is a GUI, so if something is successful, it should be obvious enough without the annoying popup? We should not recreate the Clippy experience.

**Review by javerbukh — APPROVED** [review]

**Comment by javerbukh** [comment]
I will say in regards to @kecnry's point, the line lists plugin relies on a snackbar message communicating to the user that the lines are hidden by default and need to be manually turned on. Otherwise the user will click "load list" and not see any change. That might just be a flaw with the plugin though.

**Comment by kecnry** [comment]
> the line lists plugin relies on a snackbar message communicating to the user that the lines are hidden by default and need to be manually turned on

I think we should address this in the plugin itself (and maybe in the docstring for the API case).  

> then I can set mine to warning and stop opening PRs

I think even if we add custom settings, etc, it's still useful to change the default as long once we address cases like the line list case @javerbukh brought up.

**Comment by pllim** [comment]
> as long once we address cases like the line list case

Should I open a new issue about the line list and have it block this PR then?

**Comment by pllim** [comment]
Would something like #1388 work for Line Lists?

**Comment by pllim** [comment]
I'll wait to rebase until after #1388 is merged then. Thanks!

**Comment by pllim** [comment]
Since this got 2 approvals and is unblocked. I will merge when CI passes. Thanks for the reviews!

**Pull request merged**
