### PR TITLE
Change moment input field text to 'rest wavelength'

### PR DESCRIPTION
**Pull request by rosteen**
Clarify this text slightly.

### CODE REVIEW

**Review by pllim — APPROVED** [review]

**Comment by pllim** [comment]
Do you want to backport this?

**Comment by rosteen** [comment]
> Do you want to backport this?

I don't think it's that urgent/important. Plus I don't think we'll do a 3.8.3 release before 3.9.

**Comment by kecnry** [comment]
Hang on - #2697 had just done the exact opposite 🤔

**Comment by rosteen** [comment]
> I think we DO NOT want "rest" and instead want either "central" or "observed", right? Perhaps a duplicate ticket was created forgetting that we had already done this but it just wasn't in the released version yet?

Hmmm, looks like that's possible. I see you reached out to Patrick, we'll see what he says.

**Comment by rosteen** [comment]
Also I totally misread the "from" and "to" in the Jira ticket, I'll open a PR to correct this after Patrick clarifies. Looks like he opened a Jira issue not realizing it had already been changed, which was confusing.

**Comment by pllim** [comment]
Should I revert this PR?

**Comment by rosteen** [comment]
> Should I revert this PR?

Sure, if it's quick you can revert it before I open another PR with the correct change.

**Comment by pllim** [comment]
OK, please see https://github.com/spacetelescope/jdaviz/pull/2753 . Sorry for merging too quickly!

**Pull request merged**
