### PR TITLE
Update Example Notebooks

### PR DESCRIPTION
**Pull request by duytnguyendtn**
This PR quickly fixes a few things:

1. The "Minimal Specviz" notebook originated as a concept notebook, but ended up serving the place as our example Specviz notebook when it actually became executable, rather than just pseudocode as our other concept notebooks are. But, despite the name, it isn't as "minimal" as the other example notebooks. I've moved marked this notebook as a concept one and replaced it with a spare nb I've been using for specviz that I created for the 6th Hackhour. 
2. The Cubeviz and Mosviz notebooks have been renamed to match the new styling
3. TODO: The specviz notebook should be updated with a better representative spectra (though the one in my notebook hasn't been reviewed yet? Perhaps a scientist should review this dataset and see if it might work?)

### CODE REVIEW

**Comment by eteq** [comment]
Leaving one quick thought here: the spectrum now in the specviz example is a pretty spectrum, but it looks like an AGN to me.  So the later parts of the notebook would need to be updated to be a more appropriate fit for that spectrum. (perhaps @PatrickOgle can suggest something there since it's closer to his science than mine?)

**Review by ibusko — CHANGES_REQUESTED** [review]
I had trouble with the science usecase. I couldn't make a region that encompasses the region to be fitted. Even though the region I select displays correctly, when `get_spectra('Subset 1')` is executed, it returns a very narrow region. I am guessing it is just a 1-data point wide region. If I keep trying by re-selecting, the returned region slowly departs from what is on the display. 

Maybe I am forgetting something about how to use the GUI; if that is the case, that is an issue in itself. Meaning, it would be good to have an explanation on the notebook on how exactly to operate with regions.

**Review by rosteen — COMMENTED** [review]
I know this was a quick fix, but I have lots of thoughts and I think it would be pretty low effort to address at least some of them. Others might be better for a follow-up issue to add detail to the example notebooks.

- I don't like loading the data before displaying the app, I think it's nice to have the app up and see the data and snackbar message appear. 
- Do we even need the "Science Use Case" section? I'd advocate for removing it, I think. The only Specviz-specific things there are selecting a region and retrieving that data from the app, which were already shown earlier. Modeling with astropy and plotting with matplotlib can be learned elsewhere.
- Probably worth noting that the result of doing specviz.get_spectra('Subset 1') under "Subset Retrieval" is the whole spectrum, but with a mask applied.
- Maybe demo how to go from the Glue region returned by `specviz.app.get_subsets_from_viewer` to an astropy/specutils region? I don't remember how to do this off the top of my head.
- Top import of specutils is never used.
- I don't know if "Basic Machinery" really makes sense as the title for the imports and warning suppression. Maybe something like "Setup"? Could also include the code snippet to make the notebook full-width here.
- I feel like since you go into more detail here than e.g. the barebones Cubeviz example notebook, it's worth including a quick intro section stating that this is demoing the way to do these things with the code API and that most of them (panning/zooming, saving png) have UI ways to do them too.

**Comment by duytnguyendtn** [comment]
I think I've addressed all of @rosteen's comments, except for 

> Maybe demo how to go from the Glue region returned by `specviz.app.get_subsets_from_viewer` to an astropy/specutils region? I don't remember how to do this off the top of my head.

I feel this one may warrant a separate PR if we want to include this functionality.

@PatrickOgle The more I sat on it, the more I think @rosteen's point makes sense. The Science Usecase probably isn't as appropriate here as I originally thought.

**Comment by duytnguyendtn** [comment]
@ibusko I've removed the Science Usecase, so hopefully everything works now?

**Review by rosteen — APPROVED** [review]
Looks good to me, thanks for incorporating my suggestions.

**Review by robelgeda — APPROVED** [review]
I had some pare time and was able to check this out, It looks good to me.

One minor note, it worth checking if  [`jdaviz/docs/quickstart.rst`](https://github.com/spacetelescope/jdaviz/blob/main/docs/quickstart.rst#in-a-jupyter-notebook) is out of date. It seems fine but I think its worth a second look.

**Review by ibusko — APPROVED** [review]
It's working now!

**Pull request merged**
