### PR TITLE
Voila styling tweaks

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request fixes some inconsistencies with CSS styling when embedded in voila, including:
* styling of toolbar buttons (circle vs rectangular highlighting)
* horizontal overflow in the plugin tray

**Before**:

Screen Shot 2021-11-10 at 3 01 20 PM

Note how the active state on the buttons are incorrect and the plugin tray has a horizontal scrollbar.  Scrolling to the far right shows just how much it overflowed:

Screen Shot 2021-11-10 at 3 01 32 PM

**After**:
Screen Shot 2021-11-10 at 3 02 26 PM

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by rosteen — CHANGES_REQUESTED** [review]
I confirmed that the tools have a square highlight now, and that the plugin tray looks better. However, this seems to have introduced a new styling bug where the default height of the app is smaller (leading to the viewers looking a bit squished). The whole app then resizes to be larger when one of the plugins is opened in the tray:

Screen Shot 2021-11-08 at 10 09 54 AM

Screen Shot 2021-11-08 at 10 10 01 AM

It seems like the app starts at (and stays at) the larger size on main. This is in Firefox, btw.

**Comment by kecnry** [comment]
@rosteen - interesting, I don't see that on my end, including with firefox.  Can you confirm if its the box-sizing change (by removing lines 137-140, which will revert the fix to the tray overflow) that introduces that bug?

**Review by duytnguyendtn — COMMENTED** [review]
After talking to Kyle, it appears a lot of the behavior is browser/system specific; I'm having difficulties tracking things down on my machine. Hence, I'll report what I see and have that there. I will note, I am unable to reproduce Ricky's window resizing issue in the comments: https://github.com/spacetelescope/jdaviz/pull/958#pullrequestreview-800258571

Here's a screenshot of cubeviz:
image

So the plugin icon is a square orange 👍 and here's what happens when I intentionally squish the plugin tray to force it to wrap I've included multiple images of different "squish levels":
image

Maybe (definitely) my frontend sense isn't refined enough to note what's different between these and main, but hopefully me putting this out there is somehow useful? 🤷‍♀️

**Comment by kecnry** [comment]
Since this might still have some browser-dependence, I updated the original description with before and after screenshots of the two issues this PR tries to address.  Minimizing the plugin tray to a small width does have bad styling consequences, but I think that applies in notebooks as well so I'll consider that out of scope here and make sure we have a ticket to address it at some point.

**Review by rosteen — APPROVED** [review]
I was going to do what you suggested and delete those lines, but I figured first I'd try starting fresh from a clean environment and...that seems to have fixed the problem with the height that I was seeing. So I'm calling this good.

**Comment by rosteen** [comment]
@duytnguyendtn Any objection to counting your comments as our second approval (or...at least eyes on it 👀 ) and merging this?

**Pull request merged**
