### PR TITLE
Cubeviz to use wcs1d-fits from specutils to write out fitted cube

### LINKED ISSUE #2044: jdaviz-cube writer should also write out uncertainty
**Reporter:** pllim

In https://github.com/spacetelescope/jdaviz/pull/2012 , custom writer we added to write out fitted 3D cube only serializing SCI and MASK extensions in FITS file. If the cube has uncertainty, that also should be serialized out to the file. Usually, the order goes like this:

1. Primary header
2. SCI
3. UNCERT
4. MASK

Some telescope use ERR, IVAR, VAR (and so on) instead of UNCERT. I do not know of any official global convention for this.

Care also needs to be given to automatically translate different uncertainty types in this writer into a valid FITS HDU that can be read in exactly the same (roundtripping).

Currently, a lot of operations do not propagate uncertainty, so probably not high priority to implement? Nice to have in case someone has a cube with the uncertainty and wants to use this writer (outside of Cubeviz plugin).

Also see:

* astropy/specutils#592
* https://github.com/astropy/specutils/pull/1009

[🐱](https://jira.stsci.edu/browse/JDAT-3130)

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to remove the unreleased `jdaviz-cube` writer we added in #2012 and use the improved specutils `wcs1d-fits` writer that Derek modifed in https://github.com/astropy/specutils/pull/1009 .

Close #2044

### Blocked by

- [x] `wcs1d-fits` encounters error with bool mask, so need https://github.com/astropy/specutils/pull/1051
- [x] Update specutils pin again when https://github.com/astropy/specutils/pull/1051 is released (>1.10)
- [x] https://github.com/astropy/specutils/pull/1009 and the fix above need to be released and then we have to update minversion pin for specutils.
- [x] If this PR does not make it to jdaviz v3.4, we also need to modify change log (and doc?) to withdraw a released feature.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
I thought @dhomeier fixed this in his specutils PR? 🤯 

```
>           self._bitpix = DTYPE2BITPIX[data.dtype.name]
E           KeyError: 'bool'
```

**Comment by dhomeier** [comment]
Yes, should have, but it's not in 1.10.0 yet.

**Comment by pllim** [comment]
I think at long last, this PR is finally ready because upstream fix has been released since.

**Comment by rosteen** [comment]
Hm, this works for writing out a model fit cube, but interestingly, it fails if you try to write out the original data cube that was loaded into Cubeviz (at least that's what I'm seeing with the example notebook). That also fails to write on `main` with `format="jdaviz-cube"` though, and based on the title of this PR is maybe out of scope.

**Comment by pllim** [comment]
> it fails if you try to write out the original data cube that was loaded into Cubeviz

Pretty sure that was a separate ticket. I don't think we support complete I/O roundtripping anywhere yet.

**Comment by rosteen** [comment]
> > it fails if you try to write out the original data cube that was loaded into Cubeviz
> 
> Pretty sure that was a separate ticket. I don't think we support complete I/O roundtripping anywhere yet.

In that case I'll go ahead and approve this.

**Review by rosteen — APPROVED** [review]

**Comment by pllim** [comment]
Rebased to see if RTD would report back this time. Thanks for the review!

**Pull request merged**
