### PR TITLE
fix: workaround for blank tabbed viewers after selection

### LINKED ISSUE #1677: [BUG] Cubeviz: Tabbed viewer is blank on initial selection
See the video below for a demonstration. Essentially, if you drag the second image viewer in Cubeviz to be tabbed inside the first viewer, when switching to the other viewer it will show as blank until something like a resize (of the viewer or browser) forces an update, at which point the data will display as expected. The expected behavior is that you can switch between viewer tabs and have the data display normally. 

CC @maartenbreddels 

https://user-images.githubusercontent.com/39831871/192567959-9b16e481-0646-426c-82cf-b7a000a1c9b6.mov

### PR DESCRIPTION
**Pull request by mariobuikhuizen**
### Description

Fixes #1677

### After merging this

- Open a follow-up issue to revert this PR when https://github.com/bqplot/bqplot/pull/1531 is released upstream and we also would have to bump our bqplot minversion.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by pllim** [comment]
We're still trying to figure out the change log check situation w.r.t. branched release model here, hence the current check failure.

Otherwise, this patch seems to fix the Cubeviz viewer issue. Thanks!

**Review by duytnguyendtn — APPROVED** [review]
Fixed the behavior on my end! Thanks @mariobuikhuizen!

Though I will say it still flashes blank for me before it resizes properly. Before we forget, @mariobuikhuizen do you know why this happens at all? (that being, turns entirely blank)

**Review by kecnry — APPROVED** [review]
Works on my end, thanks!  Just needs to be rebased and the change log entry moved to the 3.0.2 section (or I can do that and force push to your branch if you'd like?).

**Comment by mariobuikhuizen** [comment]
@duytnguyendtn I don't know why it turns blank. I will take a short look if I can find that out.

**Pull request merged**
