### PR TITLE
Concept notebook for cube collapse prototype

### PR DESCRIPTION
**Pull request by bmorris3**
### Description

With the goal of supporting uncertainty, mask, and unit propagation in model fits to collapsed spectral cubes in Cubeviz, a pair of PRs are in progress upstream:
* https://github.com/astropy/astropy/pull/14175 
* https://github.com/glue-viz/glue-astronomy/pull/81

Since those PRs are converging, I'm opening this one to discuss a prototype cube collapse method for jdaviz which demonstrates the upstream improvements. Running the notebook requires that you have the dev branch of glue-astronomy and my branch of astropy in the above PR. [Here's a handy link to the rendered notebook for ease of viewing in the browser](https://github.com/bmorris3/jdaviz/blob/d5e0aa6d5399ccfad1aa60e8044d04a0f42a1719/notebooks/concepts/collapse_cube.ipynb). 

Suppose you have a 3D spectral cube and you want to take the mean along the two spatial dimensions, within a spatial subset "Subset 1", to produce a 1D spectrum. The proposed method works like this: 
```python
nddata = collapse_cube(
    cubeviz_helper, statistic='mean', spatial=True, 
    subset='Subset 1', show_in_viewer=True
)
```
The resulting `NDDataArray` has propagated uncertainties and masks from the spectral cube, which we can pass off to the model fitting plugin.

### CODE REVIEW

**Comment by pllim** [comment]
Re: live collapse -- I had mentioned concern before about doing it live because it does not scale with big data. To collapse, you need the whole cube in memory and that defeats the purpose of memory map.

**Comment by kecnry** [comment]
The notebook function itself seems reasonable enough to me to move forward if everything upstream gets adopted (although would then need to wait on an astropy release/pin).

I do think to make it work live would require some rethinking (and either integration into glue or acting on callbacks to re-attach uncertainties).  But I also think we could make this its own plugin(s) - I'd still advocate for separate collapse and spectral extraction plugins for the two cases for the axis - and then providing warnings in other plugins (model fitting, etc) when selecting a spatial subset which indicates uncertainties are unavailable and pointing to the new plugin to do proper extraction with uncertainties.

**Comment by rosteen** [comment]
I think this is looking pretty good. As noted by Kyle and Pey Lian, I'm less sure about using it for the live collapse, but it would at least be good (I think) for the `Collapse` plugin. A couple comments:
1) Do you need to disable `add_data` if both `spectral` and `spatial` are set to `True`? Currently that case would evaluate the `spectral` code block and try to add the fully collapsed data to the spectrum viewer.
2) The subset label needs to be included in the new data label for the collapsed data, to differentiate multiple collapses with the same statistic but different subsets.
3) Spectral collapse appears to be broken, I get an error about missing a translator for `Quantity` if I try to use spectral collapse instead of spatial collapse.

**Comment by bmorris3** [comment]
> Spectral collapse appears to be broken

Thanks for this catch, @rosteen! This is fixed in [09bbe55](https://github.com/spacetelescope/jdaviz/pull/1969/commits/09bbe5511cbc1617d347e6182bc5362c5b162be8).

**Comment by bmorris3** [comment]
> disable add_data if both spectral and spatial are set to True

> The subset label needs to be included in the new data label for the collapsed data, to differentiate multiple collapses with the same statistic but different subsets.

Both implemented in a0fecdc.

**Comment by bmorris3** [comment]
This approach was adopted and implemented in https://github.com/spacetelescope/jdaviz/pull/2039.

**Pull request closed without merging**
