### PR TITLE
spinner while stretch histogram data updating

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements a spinner showing when the data for the stretch histogram is updating.

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by camipacifici** [comment]
Tested with a very big image and it worked really well. Thank you!

**Comment by camipacifici** [comment]
And now I broke it... :( I will try to reproduce the problem and see if it is just a glitch or an actual problem.

**Comment by camipacifici** [comment]
Ok, the problem is with the toggle "limit histogram to current zoom limits". When toggling it, the spinner is just a flash, but the histogram is taking a longer time to settle.

**Comment by kecnry** [comment]
I _think_ I managed to fix the main issue as well as the flickering spinner sometimes seen for updates that are immediately skipped.  Sometimes though the image viewer seems to process its update before the callback is sent to the stretch histogram, resulting in a "delayed" start of the spinner.  I'm not sure there is much we can do about these cases.  But the spinner should show whenever the histogram itself is processing an update.

Here is what I currently see on my end.

https://github.com/spacetelescope/jdaviz/assets/877591/391e65b6-f04f-482e-af2a-4c5d19130ceb

**Review by gibsongreen — APPROVED** [review]
This is also working for me when data is first loaded and when the zoom is updated and the histogram is limited to said zoom!

**Pull request merged**
