### PR TITLE
BUG: Fix transposed moment result

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to pull out the moment fix from #1040 into its own PR.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by camipacifici — APPROVED** [review]
Works for me!

**Comment by javerbukh** [comment]
I'm seeing this for moment 2 (in the right viewer), is that how it's supposed to look? Also, when I first create the moment, the viewer is all black. I need to deselect the moment 2 data and reselect it in order to view it.

**Comment by pllim** [comment]
@javerbukh , did you forget to attach a screenshot? Moment 2 looks weird because I think it is wrong anyway, see astropy/specutils#931 . Moment 0 and Moment 1 should now show the correct rotation.

Re: deselect and reselect -- Yes, I noticed the same thing too. Also the red overlay from subset in some cases is real annoying and clicking the eye on that layer does not do anything. Problems for another day.

**Review by javerbukh — APPROVED** [review]
@pllim 🤦‍♂️ I did, I'll attach it to this for record keeping but you are right that moment 0 and 1 look good!
Screen Shot 2022-02-23 at 8 31 41 AM

**Comment by pllim** [comment]
I can't keep track of what is already in JIRA and what is not. Feel free to open tickets for the remaining issues as needed. Thanks!

**Pull request merged**
