### PR TITLE
Unit conversion refactor

### LINKED ISSUE #280: Specviz Unit Conversion with subset selected
Trying to convert units with a subset selected in the spectrum viewer gives this output and 
error messages, but works when there is no subset selected :

unit_conversion_with_subset

---------------------------------------------------------------------------
IncompatibleAttribute                     Traceback (most recent call last)
~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/data.py in get_mask(self, subset_state, view)
   1384         try:
-> 1385             return subset_state.to_mask(self, view=view)
   1386         except IncompatibleAttribute:

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/subset.py in to_mask(self, data, view)
    727     def to_mask(self, data, view=None):
--> 728         x = data[self.att, view]
    729         result = (x >= self.lo) & (x <= self.hi)

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/data.py in __getitem__(self, key)
    570 
--> 571         return self.get_data(key, view=view)
    572 

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/data.py in get_data(self, cid, view)
   1360         else:
-> 1361             raise IncompatibleAttribute(cid)
   1362 

IncompatibleAttribute: World 0

During handling of the above exception, another exception occurred:

IncompatibleAttribute                     Traceback (most recent call last)
~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/ipyvue/VueTemplateWidget.py in _handle_event(self, _, content, buffers)
     48             event = content.get("event", "")
     49             data = content.get("data", {})
---> 50             getattr(self, 'vue_' + event)(data)
     51 
     52 

~/Desktop/jdat/jdaviz/jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py in vue_unit_conversion(self, *args, **kwargs)
    170 
    171             #TODO: Fix bug that sends AddDataMessage into a loop
--> 172             self.app.add_data_to_viewer("spectrum-viewer", selected_data_label)
    173 
    174         else:

~/Desktop/jdat/jdaviz/jdaviz/app.py in add_data_to_viewer(self, viewer_reference, data_label, clear_other_data)
    576         if data_id is not None:
    577             data_ids.append(data_id)
--> 578             self._update_selected_data_items(viewer_item['id'], data_ids)
    579         else:
    580             raise ValueError(

~/Desktop/jdat/jdaviz/jdaviz/app.py in _update_selected_data_items(self, viewer_id, selected_items)
    863                                               viewer_id=viewer_id,
    864                                               sender=self)
--> 865             self.hub.broadcast(add_data_message)
    866 
    867         # Remove any deselected data objects from viewer

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/hub.py in broadcast(self, message)
    213             logging.getLogger(__name__).info("Broadcasting %s", message)
    214             for subscriber, handler in self._find_handlers(message):
--> 215                 handler(message)
    216 
    217     def __getstate__(self):

~/Desktop/jdat/jdaviz/jdaviz/configs/specviz/plugins/unit_conversion/unit_conversion.py in _on_viewer_data_changed(self, msg)
     73         viewer = self.app.get_viewer('spectrum-viewer')
     74 
---> 75         self._viewer_data = self.app.get_data_from_viewer('spectrum-viewer')
     76 
     77         self.dc_items = [layer_state.layer.label

~/Desktop/jdat/jdaviz/jdaviz/app.py in get_data_from_viewer(self, viewer_reference, data_label, cls, include_subsets)
    401                     if cls is not None:
    402                         handler, _ = data_translator.get_handler_for(cls)
--> 403                         layer_data = handler.to_object(layer_data,
    404                                                        statistic=statistic)
    405 

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue_astronomy/translators/spectrum1d.py in to_object(self, data_or_subset, attribute, statistic)
    142             return data_kwargs
    143 
--> 144         data_kwargs = parse_attributes(
    145             [attribute] if not hasattr(attribute, '__len__') else attribute)
    146 

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue_astronomy/translators/spectrum1d.py in parse_attributes(attributes)
    109                     mask = None
    110                 else:
--> 111                     mask = data.get_mask(subset_state=subset_state)
    112                     mask = ~mask
    113 

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/data.py in get_mask(self, subset_state, view)
   1385             return subset_state.to_mask(self, view=view)
   1386         except IncompatibleAttribute:
-> 1387             return get_mask_with_key_joins(self, self._key_joins, subset_state, view=view)
   1388 
   1389     def __setitem__(self, key, value):

~/miniconda3/envs/unit_conversion/lib/python3.8/site-packages/glue/core/joins.py in get_mask_with_key_joins(data, key_joins, subset_state, view)
    103                             "contain a single component.")
    104 
--> 105     raise IncompatibleAttribute

IncompatibleAttribute:

### PR DESCRIPTION
**Pull request by javerbukh**
This is the current draft of the refactor of the unit conversion plugin. I originally tried to make it as viewer agnostic as possible, but the smoothest implementation requires some reliance on the 1d spectrum viewer. This also makes it easier to make unit tests for this plugin. Some other thoughts:

1. Fixes #280 
2. The ghost bqplot marks bug appears if you create subsets for different unit versions of the same spectra and then deselect them.
3. The plugin no longer automatically switches to new units spectrum after the `apply` button is pressed. Instead, it behaves like other jdaviz plugins where the data is created and added to the drop down, along with a snackbar message notifying the user of the status of the conversion.
4. If a spectrum is converted, a "_units_copy_" version will be created with the flux and spectral axis units in the spectrum label. If the user tries to convert a variant of the original spectrum (original or any of the "units_copy" versions) into a new units combination that already exists, a snackbar message will appear to notify the user that it already exists and no other action will be taken.

Once the direction of this refactor is agreed upon, the next steps will be to create tests and to update the documentation relating to unit conversions.

### CODE REVIEW

**Review by rosteen — COMMENTED** [review]
I've haven't quite looked at everything, but overall it's looking good so far. I like the new snackbar message if the requested units already exist in a spectrum. I think there are a few improvements that would make this better:

- Maybe store `original_flux_units` and `original_spectral_units` and check that the user isn't asking for those, in addition to checking the labels of the existing conversions?
- You're doing the actual unit conversion processing before checking and warning if the conversion has already been done before. It would be better to check the existing labels based on the requested units and not do the conversion if the data already exists.
- You could also rearrange things slightly and check for existing converted data matching the request in the case that you're starting from the original data as well. I think you implied in (4) that this is supposed to happen, but it doesn't seem to work.

Unrelated to the above points, it would be nice to be able to input a conversion factor to apply to the desired units (e.g. requesting 1e-17 erg/(cm^2 s Angstrom))

I'll also note that I haven't been able to trigger the ghost marks bug.

**Comment by ibusko** [comment]
From the limited exercising I did with the new code, it seems the bugs have been fixed and the behavior is as described.

**Review by ibusko — APPROVED** [review]
From the rather limited exercising I did with the new code, it seems the bugs have been fixed and the behavior is as described.

**Comment by javerbukh** [comment]
@rosteen You make some great points and I addressed the 3rd point in the newest commit. I'm working on a solution for the first point and will try to have that in the next commit (some time tomorrow morning). As for the second point, I do a lot of the checking of the incoming units in `process_unit_conversion` and I hesitate to move code out of there or duplicate it in order to check if a conversion has already been done, although I do agree that it would be more optimized.

**Review by rosteen — APPROVED** [review]
LGTM. I added ~10 converted spectra and never saw the flickering bug from the auto-switching.

**Comment by javerbukh** [comment]
@rosteen Since I'm the original author and not technically present for this week of the sprint, can you please merge this PR?

**Comment by rosteen** [comment]
Done! Didn't realize I was the second approval, somehow.

**Pull request merged**
