### PR TITLE
MOSViz configuration and data loading

### PR DESCRIPTION
**Pull request by nmearl**
This PR introduces the mosviz configuration and associated data loading methods. It also includes the new table viewer adapted from the glue-jupyter ipyvuetify table viewer.

Requires glue-viz/glue-jupyter#198.

### CODE REVIEW

**Comment by nmearl** [comment]
Thanks for the review!

1. Don't select the mos table. It's implicit to the viewer, but we gets shown until we figure a way to hide it in other viewers.
2. I'm not sure what you mean, can you say more?
3. Yes.
4. I think this is a consequence of the weird faked image data. Something in the constructed fits headers might be off.

**Comment by javerbukh** [comment]
1. Got it
2. In cubeviz, when a user runs `app.load_data('data'), it is parsed and loaded automatically (flux in the flux viewer, uncertainty in the uncertainty viewer, etc.). Will that be implemented here or in a future PR?
3. Got it.
4. Ok, that all makes sense, thank you!

**Comment by dtn5ah** [comment]
In loading the nirspec data @nmearl provided me, I ran into the following error once on the mosviz example notebook in `mosviz.load_images` (the last line in cell 3):

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-de21bb1396a1> in <module>
     20 mosviz.load_2d_spectra(spectra_2d)
     21 print(images)
---> 22 mosviz.load_images(images)

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\jdaviz\configs\mosviz\helper.py in load_images(self, data_obj, data_labels)
     60             for each item in ``data_obj`` if  ``data_obj`` is a list.
     61         """
---> 62         self.app.load_data(data_obj, parser_reference="mosviz-image-parser",
     63                            data_labels=data_labels)
     64 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\jdaviz\app.py in load_data(self, file_obj, parser_reference, **kwargs)
    264             # If the parser returns something other than known, assume it's
    265             #  a message we want to make the user aware of.
--> 266             msg = parser(self, file_obj, **kwargs)
    267 
    268             if msg is not None:

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\jdaviz\configs\mosviz\plugins\parsers.py in mos_image_parser(app, data_obj, data_labels)
    190 
    191     for i in range(len(data_obj)):
--> 192         app.data_collection[data_labels[i]] = data_obj[i]
    193 
    194     _add_to_table(app, data_labels, 'Images')

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\core\data_collection.py in __setitem__(self, key, data)
    380         if not isinstance(data, Data):
    381 
--> 382             handler, preferred = data_translator.get_handler_for(data)
    383 
    384             data = handler.to_data(data)

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\config.py in get_handler_for(self, data_or_class)
    564                                 "type Data to {0}".format(data_or_class.__name__))
    565             else:
--> 566                 raise TypeError("Could not find a class to translate objects of "
    567                                 "type {0} to Data".format(data_or_class.__class__.__name__))
    568         return handler, preferred

TypeError: Could not find a class to translate objects of type str to Data
```
I checked what `images` contained, and it returned the following:
```
['F:\\STScI\\gitRepos\\jdaviz\\notebooks\\level3\\mosviz_cutouts\\227.fits', 'F:\\STScI\\gitRepos\\jdaviz\\notebooks\\level3\\mosviz_cutouts\\227.fits', 'F:\\STScI\\gitRepos\\jdaviz\\notebooks\\level3\\mosviz_cutouts\\227.fits', 'F:\\STScI\\gitRepos\\jdaviz\\notebooks\\level3\\mosviz_cutouts\\227.fits', 'F:\\STScI\\gitRepos\\jdaviz\\notebooks\\level3\\mosviz_cutouts\\227.fits']
```
Any ideas?

**Comment by nmearl** [comment]
@javerbukh 
> In cubeviz, when a user runs `app.load_data('data'), it is parsed and loaded automatically (flux in the flux viewer, uncertainty in the uncertainty viewer, etc.). Will that be implemented here or in a future PR?

No, there's no intent to auto-populate the viewers because it relies on the user selecting a row, which is dependent on there being data in the table, which might not be the case immediately (i.e. until the user populates the table). Perhaps in the future, when we parse directly from a table-like object auto-selecting e.g. the first row may be default. But currently we don't do that for the user automatically.

@dtn5ah 

> I checked what images contained, and it returned the following:

Weird! Does the following return `True`?

```python
import Path

all([Path(path).is_file() for path in images])
```

**Comment by dtn5ah** [comment]
@nmearl Welp... this is frustrating, can't reproduce the error. If I had to guess, I think I was being stupid and mistyped the paths... 

Anyways, the data loads now! But checking a box in the table viewer doesn't seem to do anything. Manually selecting the data in the viewer causes a "list index out of range" error:
ezgif-1-9c217d37101b
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\viewers\image\state.py in _reference_data_changed(self, *args)
    178                     # so we do this here manually.
--> 179                     self._on_xatt_world_change()
    180                     self._on_yatt_world_change()

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\utils\matplotlib.py in wrapper(*args, **kwargs)
    159         if len(DEFER_DRAW_BACKENDS) == 0:
--> 160             return func(*args, **kwargs)
    161 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\viewers\image\state.py in _on_xatt_world_change(self, *args)
    269                     if self.x_att_world == world_ids[-1]:
--> 270                         self.y_att_world = world_ids[-2]
    271                     else:

IndexError: list index out of range

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\ipyvue\VueTemplateWidget.py in _handle_event(self, _, content, buffers)
     48             event = content.get("event", "")
     49             data = content.get("data", {})
---> 50             getattr(self, 'vue_' + event)(data)
     51 
     52 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\jdaviz\app.py in vue_data_item_selected(self, event)
    810         viewer_id, selected_items = event['id'], event['selected_items']
    811 
--> 812         self._update_selected_data_items(viewer_id, selected_items)
    813 
    814     def _update_selected_data_items(self, viewer_id, selected_items):

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\jdaviz\app.py in _update_selected_data_items(self, viewer_id, selected_items)
    837             [data] = [x for x in self.data_collection if x.label == label]
    838 
--> 839             viewer.add_data(data)
    840 
    841             add_data_message = AddDataMessage(data, viewer,

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue_jupyter\view.py in add_data(self, data, color, alpha, **layer_state)
    115         data = validate_data_argument(self._data, data)
    116 
--> 117         result = super().add_data(data)
    118 
    119         if not result:

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\viewers\common\viewer.py in add_data(self, data)
    205         # Create layer artist and add to container. First check whether any
    206         # plugins want to make a custom layer artist.
--> 207         layer = get_layer_artist_from_registry(data, self) or self.get_data_layer_artist(data)
    208 
    209         if layer is None:

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue_jupyter\bqplot\image\viewer.py in get_data_layer_artist(self, layer, layer_state)
     67         else:
     68             cls = BqplotImageLayerArtist
---> 69         return self.get_layer_artist(cls, layer=layer, layer_state=layer_state)
     70 
     71     def get_subset_layer_artist(self, layer=None, layer_state=None):

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue_jupyter\view.py in get_layer_artist(self, cls, layer, layer_state)
    140 
    141     def get_layer_artist(self, cls, layer=None, layer_state=None):
--> 142         return cls(self, self.state, layer=layer, layer_state=layer_state)
    143 
    144     def initialize_layer_options(self):

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue_jupyter\bqplot\scatter\layer_artist.py in __init__(self, view, viewer_state, layer_state, layer)
     26     def __init__(self, view, viewer_state, layer_state=None, layer=None):
     27 
---> 28         super(BqplotScatterLayerArtist, self).__init__(viewer_state,
     29                                                        layer_state=layer_state, layer=layer)
     30 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue_jupyter\compat.py in __init__(self, viewer_state, layer_state, layer)
     33 
     34         if self.state not in self._viewer_state.layers:
---> 35             self._viewer_state.layers.append(self.state)
     36 
     37         self.zorder = self.state.zorder

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\echo\containers.py in append(self, value)
     50     def append(self, value):
     51         super(CallbackList, self).append(self._prepare_add(value))
---> 52         self.notify_all()
     53 
     54     def extend(self, iterable):

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\echo\containers.py in notify_all(self, *args, **kwargs)
     43     def notify_all(self, *args, **kwargs):
     44         for callback in self.callbacks:
---> 45             callback(*args, **kwargs)
     46 
     47     def __repr__(self):

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\echo\containers.py in __call__(self, *args, **kwargs)
    164 
    165     def __call__(self, *args, **kwargs):
--> 166         self.function(*args, **kwargs)
    167 
    168 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\echo\containers.py in callback(*args, **kwargs)
    187 
    188         def callback(*args, **kwargs):
--> 189             self.notify(instance, wrapped_list, wrapped_list)
    190 
    191         dcb.function = callback

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\echo\core.py in notify(self, instance, old, new)
    123             return
    124         for cback in self._callbacks.get(instance, []):
--> 125             cback(new)
    126         for cback in self._2arg_callbacks.get(instance, []):
    127             cback(old, new)

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\viewers\image\state.py in _layers_changed(self, *args)
    192             return
    193 
--> 194         self._update_combo_ref_data()
    195         self._set_reference_data()
    196         self._update_syncing()

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\viewers\image\state.py in _update_combo_ref_data(self)
    218 
    219     def _update_combo_ref_data(self):
--> 220         self.ref_data_helper.set_multiple_data(self.layers_data)
    221 
    222     def _update_combo_att(self):

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\core\data_combo_helper.py in set_multiple_data(self, datasets)
    520         for data in unique_data_iter(datasets):
    521             self.append_data(data, refresh=False)
--> 522         self.refresh()
    523 
    524     def append_data(self, data, refresh=True):

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\core\data_combo_helper.py in refresh(self, *args)
    443 
    444     def refresh(self, *args):
--> 445         self.choices = [data for data in self._datasets]
    446         self.refresh_component_ids()
    447 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\core\data_combo_helper.py in choices(self, choices)
     84         with delay_callback(self.state, self.selection_property):
     85             prop = getattr(type(self.state), self.selection_property)
---> 86             prop.set_choices(self.state, choices)
     87 
     88     @property

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\echo\core.py in __exit__(self, *args)
    536 
    537         for p, args in notifications:
--> 538             p.notify(*args)
    539 
    540 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\utils\matplotlib.py in wrapper(*args, **kwargs)
    158 
    159         if len(DEFER_DRAW_BACKENDS) == 0:
--> 160             return func(*args, **kwargs)
    161 
    162         # Don't recursively defer draws. We just check the first draw_idle

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\viewers\matplotlib\state.py in notify(self, *args, **kwargs)
     33     @defer_draw
     34     def notify(self, *args, **kwargs):
---> 35         super(DeferredDrawSelectionCallbackProperty, self).notify(*args, **kwargs)
     36 
     37 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\echo\core.py in notify(self, instance, old, new)
    123             return
    124         for cback in self._callbacks.get(instance, []):
--> 125             cback(new)
    126         for cback in self._2arg_callbacks.get(instance, []):
    127             cback(old, new)

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\viewers\image\state.py in _reference_data_changed(self, *args)
    178                     # so we do this here manually.
    179                     self._on_xatt_world_change()
--> 180                     self._on_yatt_world_change()
    181 
    182     def _layers_changed(self, *args):

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\echo\core.py in __exit__(self, *args)
    536 
    537         for p, args in notifications:
--> 538             p.notify(*args)
    539 
    540 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\utils\matplotlib.py in wrapper(*args, **kwargs)
    158 
    159         if len(DEFER_DRAW_BACKENDS) == 0:
--> 160             return func(*args, **kwargs)
    161 
    162         # Don't recursively defer draws. We just check the first draw_idle

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\viewers\matplotlib\state.py in notify(self, *args, **kwargs)
     33     @defer_draw
     34     def notify(self, *args, **kwargs):
---> 35         super(DeferredDrawSelectionCallbackProperty, self).notify(*args, **kwargs)
     36 
     37 

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\echo\core.py in notify(self, instance, old, new)
    123             return
    124         for cback in self._callbacks.get(instance, []):
--> 125             cback(new)
    126         for cback in self._2arg_callbacks.get(instance, []):
    127             cback(old, new)

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\utils\matplotlib.py in wrapper(*args, **kwargs)
    158 
    159         if len(DEFER_DRAW_BACKENDS) == 0:
--> 160             return func(*args, **kwargs)
    161 
    162         # Don't recursively defer draws. We just check the first draw_idle

f:\stsci\gitrepos\jdaviz\envpr209\lib\site-packages\glue\viewers\image\state.py in _on_xatt_world_change(self, *args)
    268                         world_ids = self.reference_data.pixel_component_ids
    269                     if self.x_att_world == world_ids[-1]:
--> 270                         self.y_att_world = world_ids[-2]
    271                     else:
    272                         self.y_att_world = world_ids[-1]

IndexError: list index out of range
```

**Comment by javerbukh** [comment]
@dtn5ah I had to manually select data for each viewer. `Image X` in the top left, `2D Spectrum X` in the top right, and `1D Spectrum X` below that. Selecting formats that do not fit cause that error, which would be good to handle.

**Comment by dtn5ah** [comment]
@javerbukh Ahh I gotcha. Selecting the right combination in the right viewer did it (I guess this is why we need documentation :P)

**Comment by nmearl** [comment]
> Anyways, the data loads now! But checking a box in the table viewer doesn't seem to do anything. Manually selecting the data in the viewer causes a "list index out of range" error:

@dtn5ah as Jesse mentioned, you're trying to add a 1D data set to the image viewer (that only accepts 2D) data. But also (for both @dtn5ah and @javerbukh), selecting the checkboxes in the table viewer are for creating subsets, you do not need to check them for any other reason; and:

> I had to manually select data for each viewer. Image X in the top left, 2D Spectrum X in the top right, and 1D Spectrum X below that. Selecting formats that do not fit cause that error, which would be good to handle.

You really don't need to be selecting the data individually for each viewer. Instead, just select the row of the table:


Screen-Recording-2020-07-30-at-4 54 01-PM

**Comment by javerbukh** [comment]
@nmearl @dtn5ah Ah, I believe that is the way it works with the glue-jupyter PR, which I had not added. Thanks for clarifying!

**Pull request merged**
