### PR TITLE
TST: Omit specreduce dev from devdeps

### LINKED ISSUE #1877: TST: Fix failing tests in devdeps job
As seen in #1873. Need to investigate failures of Specviz2d tests that use https://stsci.box.com/shared/static/exnkul627fcuhy5akf2gswytud5tazmw.fits . Maybe the file is too old and we need to use a real JWST 2D spectrum from MAST.

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to omit dev version of specreduce from devdeps because that package is undergoing a lot of API changes.

Close #1877 

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by rosteen** [comment]
@kecnry @ojustino I'll leave it to one of you to approve this, in case you object.

**Review by kecnry — APPROVED** [review]
I think this is the best/only way to go until specreduce is stable enough that we can remove the exact minor-version pin.

Maybe we should also add a comment in `setup.cfg` to remind us to add this back when we do loosen up the version there?

**Comment by ojustino** [comment]
No objections from me, though I do support adding a reminder for the future in `setup.cfg`.

**Comment by pllim** [comment]
I added it back to `tox.ini` but commented out with a comment. Is that good enough?

**Comment by pllim** [comment]
Tsk tsk CI didn't kick off

**Comment by ojustino** [comment]
You have the requisite approval already, but I still think a reminder couldn't hurt for the sake of whomever ends up changing this in the future.

**Comment by pllim** [comment]
> I still think a reminder couldn't hurt 

I agree but I guess I just think the reminder being in `tox.ini` is closer to where it should be done.

**Comment by pllim** [comment]
Should I also open a follow-up issue?

**Review by ojustino — APPROVED** [review]
I support creating a follow-up issue; that fits with standard procedure here.

**Comment by pllim** [comment]
Thanks for the reviews!

**Pull request merged**
