### PR TITLE
snackbar queue: better handling of loading interrupts

### LINKED ISSUE #1246: [BUG] Cubeviz: Cube fitting progress snackbar appears inconsistently
**Describe the bug**
The fitting-in-progress cube fitting snackbar message does not get shown consistently. It seems like if there's a previous snackbar message still shown when "Apply to Cube" is clicked in the Model Fitting plugin, the cube fitting snackbar message won't show up at all. If you wait until there are no other snackbar messages, the in progress snackbar will show up, although it seems like sometimes it does not remain visible for the whole duration of the fitting. We need to debug the code controlling when this is shown and removed.

**To Reproduce**
1. Run the CubevizExample notebook.
2. Open Model Fitting and fit any simple model to the spectrum
3. While the "Model fit finished" snackbar message is still visible, click the "Apply to Cube" button.

**Expected behavior**
A snackbar message with the rotating "in progress" icon will be visible for the entire duration of cube fitting.

**Screenshots**

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request is to address loading snackbar messages from being ignored if a current snackbar is being displayed.  The new behavior is that a message with `loading=True` will immediately interrupt the current queue and will show indefinitely until another message is pushed to the queue, at which point THAT message will show first and then the queue will continue with the message that was first interrupted.

This should be thoroughly tested in the app with real use-cases, but can also be tested manually with something like:

```
from jdaviz.core.events import SnackbarMessage
from time import sleep

for i in range(5):
    msg = SnackbarMessage(f"message {i}", color='info', sender=None)
    specviz.app.hub.broadcast(msg)

sleep(6)

# interrupt with loading message (should interrupt during "message 1")
msg = SnackbarMessage(f"LOADING INTERRUPT (3s)", loading=True, sender=None)
specviz.app.hub.broadcast(msg)

sleep(3)

# clear loading, show this message, then continue wherever the loop was interrupted, in order
msg = SnackbarMessage(f"LOADING COMPLETE", color='success', sender=None)
specviz.app.hub.broadcast(msg)
```

which gives the following behavior:

https://user-images.githubusercontent.com/877591/163448803-e7406972-2d69-47f1-a14e-345f00f2c7f0.mov

Fixes #1246

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by javerbukh** [comment]
I tried to add a 0 order polynomial using model fitting and after I set "plot in center viewer" and click `apply to cube`, I get an infinite loop of error messages in my console saying:
```
WARNING: Model is linear in parameters; consider using linear fitting methods. [astropy.modeling.fitting]
WARNING:astropy:Model is linear in parameters; consider using linear fitting methods.
```

**Comment by kecnry** [comment]
This should not affect console messages at all.  Are you sure they're infinite and not just one per-spaxel if you chose entire cube?  (I get about 15, but the fitting is still successful)

But it does seem at least in this case, that the loading snackbar was clearing early.... I think I've fixed that now.

**Comment by javerbukh** [comment]
Looks good now, will continue with testing. Thanks!

**Review by rosteen — APPROVED** [review]
LGTM, I agree that all the linear parameter warnings from astropy fitting are annoying and should be filtered out somehow, but they aren't due to this PR. I couldn't come up with a way to interrupt the loading message, since other operations like line loading have to wait for the fitting to finish anyway, but I ran the code snippet you included and it seemed fine.

I did have a minor scare that things were broken, but it turned out I hadn't installed the most up to date `glue-astronomy` in the environment I was using yet.

**Review by javerbukh — APPROVED** [review]
Looks good! Ditto what @rosteen said about the warnings but I agree with his conclusion.

**Pull request merged**
