### PR TITLE
Implement redshift slider in Specviz

### PR DESCRIPTION
**Pull request by rosteen**
Intended to close https://github.com/spacetelescope/jdaviz/issues/336. Still have two major features to add/debug: exposing methods to set the slider parameters from the Specviz helper class, and updating the redshift values in the Glue Data objects so that the output data will have the slider redshift.

I had implemented code for the second feature, but updating the `coords` attribute of the Data object was causing the axis to revert to pixel coordinates instead of world coordinates. Still trying to figure out an elegant way to avoid that.

### CODE REVIEW

**Comment by rosteen** [comment]
@eteq I believe this now handles everything laid out as the basic functionality in https://github.com/spacetelescope/jdaviz/issues/336 except the "bonus" of updating internal Glue data representations, since it turned out to be a huge pain to do that without messing up the axes. Currently retrieving the spectra with the helper `get_spectra` method respects the slider value, but using the app-level `get_data_from_viewer` does not.

I also provided methods to set the bounds and redshift in the Specviz helper, to wit: `specviz.set_redshift_slider_bounds(lower=0.4, upper=0.6)` and `specviz.set_redshift(0.33)`. I couldn't decide on a good naming scheme, so currently those same functions handle setting the slider if it's in RV mode, it just doesn't do any intelligent checking to make sure you're not trying to set silly values.

**Comment by javerbukh** [comment]
Some comments:
1) Load Common Stellar line lists, hide all, select about 4, then move the redshift slider -> all lines reappear and are redrawn for every move of the slider. This redrawing happens repeatedly after a long slider move and does not let me cancel or do anything else. This interaction did not happen with RV selected, however (this is hard to explain, but at some point in loading and unloading line lists, I saw them working as intended with RV. When I switched back to Redshift, it worked just as well).
2) Received the following traceback while working with the line lists, probably when trying to press the "X" while lines were still being rendered on the plot.
```---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/jdaviz-dev-2/lib/python3.8/site-packages/ipyvue/VueTemplateWidget.py in _handle_event(self, _, content, buffers)
     51                 getattr(self, 'vue_' + event)(data, buffers)
     52             else:
---> 53                 getattr(self, 'vue_' + event)(data)
     54 
     55 

~/Documents/jdadf_notebooks/jdaviz/jdaviz/configs/default/plugins/line_lists/line_lists.py in vue_remove_list(self, listname)
    361         updates the "show" value in the astropy table to False..
    362         """
--> 363         lc = self.list_contents[listname]
    364         name_rests = []
    365         for line in lc["lines"]:

KeyError: 'Common Stellar'
```
3) When I created a custom line, I already had my RV set to 800, however the custom line was plotted at its rest value. When I moved the slider, the line quickly moved to the right location and from then on reacted accordingly. Redshift worked just as well in this scenario. The lines are also very responsive which is awesome to see!

Overall this is amazing work!! I think by applying redshift values when creating custom lines and by fixing all lines loading when only a few are selected, this will be ready to go!

**Comment by rosteen** [comment]
@javerbukh  I fixed the application of the slider redshift on custom line creation. 

The behavior with hiding the lines and then having them replot is due to a bug that leads to the `show` column in the astropy table not getting set to `False` when the hide all button is pressed, which isn't related to this PR. I think that's best addressed in a follow-on issue/PR.

**Review by javerbukh — APPROVED** [review]
@rosteen Sounds good, and the custom line list interaction makes sense now. Nice work!

**Review by ibusko — APPROVED** [review]
I get the same behavior as @javerbukh pointed out. Although it doesn't fix itself by going to RV and back to redshift. I got the server hosed a couple times during the redraw process. But apart from this unrelated bug, it seems to be working as expected, that is, the lines _do_ move according to the slider position.

**Comment by rosteen** [comment]
I created #381 as a follow-up to address the `Hide All` button. I'm going to wait to merge this until I demo it at our internal sprint review and (hopefully) get a thumbs-up from @eteq .

**Comment by eteq** [comment]
To summarize some out-of-band discussion on this: the underlying glue object is not completely synced up with the redshift slider value, so the helper accessor is needed to get the redshift value.  This is not ideal because it means the "internal" and "helper-level" data are not fully consistent.  But given the complexity, @rosteen is planning to make an issue to update that, and we'll proceed with this without that. (There are some questions about how desirable that is, but we can discuss it in the follow-on issue).

Also, one thought from me just now: can the spinner up/down arrows be completely hidden? I don't think they really add much to what the slider bar offers and take up valuable real-estate...

**Comment by ibusko** [comment]
@eteq : Good point about the spinner. It came to my mind now: what is the meaning of a spinner for real numbers? Is it dependent on the number of decimal places displayed in the field, or is it defined by a (maybe implicit) format spec?  It looks like a potential place for user confusion. I agree that, if possible, it should be hidden or removed.

**Comment by rosteen** [comment]
So I looked into hiding the spinner buttons already, and the only way I found was through some custom CSS on the page, which I haven't been able to figure out how to get working yet. It seems like I should be able to specify a `<style>` section in the vuetify template, but I haven't succeeded so far.

The benefit of those buttons, currently, is that they increment the redshift by the `step` value (set to 0.001 by default for the redshift), whereas moving the slider with your mouse generally moves it by much more than that, due to the resolution of your mouse position in the browser/how precisely you can move your mouse.

**Comment by rosteen** [comment]
Hm, I've been overthinking the buttons...if I don't specify that the text field is a `number` and do some manual float conversion I can get rid of them. And you can still increment by the `step` value by using the up/down arrow keys on your keyboard. I'll commit this momentarily...

**Comment by rosteen** [comment]
@eteq See the issue I just linked above for followup.

**Comment by ibusko** [comment]
This looks good! The spurious re-paint of the de-selected lines is gone. Super!

Although, when playing with the redshift/rv text field, I found buggy behavior. Once I typed a negative value, I couldn't get back to positive values without toggling back and forth between redshift and RV modes. At some point, maybe because I pressed the wrong key, I got a stack trace for "ValueError: could not convert string to float: ''.

**Comment by rosteen** [comment]
Note that the `get_spectra` change depends on https://github.com/astropy/specutils/pull/722, which hasn't been merged yet.

**Comment by eteq** [comment]
In an out-of-band discussion (including @PatrickOgle @camipacifici @orifox, @ibusko), I think we settled on adding a `use_redshift_from_specviz` or similar keyword to the method that gets the spectrum from the Specviz helper, which would have three options:

* `True`: the returned spectrum has the redshift from the slider
* `False`: the returned spectrum has whatever it's redshift was at input
* `'warn'` (or similar): The returned spectrum is the same as `True`, but if the redshift has been changed from its input value, show a warning that indicates this, and includes an explicit instruction like "set use_redshift_from_specviz to True if you want to not see this warning".

**Comment by rosteen** [comment]
Implemented, @eteq - note that as said above this PR is also waiting on specutils 722.

**Review by javerbukh — APPROVED** [review]
This looks great! One minor thing I noticed was that if I load a list, then set a redshift value, clear that list, then load it again, I need to press `show all` in order for the lines to appear. 

This seems like something that should not hold up merging of this ticket so if it's a simple fix, I can check again after that commit, or I can merge once I get the OK from you @rosteen .

**Comment by rosteen** [comment]
@javerbukh That would be something to change in a follow up ticket. The cause is that currently when you delete a list, the lines aren't actually removed from the backend astropy Table, they just sit there with the `show` column set to `False`. I did a bit of poking at it while working on another PR to try to actually delete the lines from the table, but was having some difficulties.

**Comment by rosteen** [comment]
Did a bit of commit cleanup and a final doc improvement, merging.

**Pull request merged**
