### PR TITLE
MNT: Remove unused code from Imviz parser

### PR DESCRIPTION
**Pull request by pllim**
### Description

This pull request is to address a small oversight from #1056 .

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set? Milestone is only currently required for PRs related to Imviz MVP.
- [x] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by ibusko — APPROVED** [review]
Simple enough. Tests still pass, so we can assume that the code is in fact not being used. Or is that a too strong assumption?

**Comment by duytnguyendtn** [comment]
> Simple enough. Tests still pass, so we can assume that the code is in fact not being used. Or is that a too strong assumption?

The code is at the end of the method, so the method returns regardless of if it fires (in my head at least)

**Review by duytnguyendtn — APPROVED** [review]
I don't see how this deletion could affect anything, so I'm happy since the tests pass. Thanks for the patch!

**Comment by pllim** [comment]
Yes, pretty sure this was an oversight on my part when I originally implemented delayed linking. Thanks for the reviews and merge!

**Pull request merged**
