### PR TITLE
MNT: Add PR auto labeler

### PR DESCRIPTION
**Pull request by pllim**
This would automatically label new PRs according to the given rules using [actions/labeler](https://github.com/actions/labeler). With this in place, here is the new triage workflow for humans:

1. Wait for labeler to get done.
2. Manually add any relevant labels that are not covered by the rules, if applicable.

If you manually add labels too early, you might encounter this bug: actions/labeler#112

You can see it in action (pun?) over at `astropy`:

Screenshot 2021-04-22 152208

### CODE REVIEW

**Review by rosteen — APPROVED** [review]
Looks very useful, thanks!

**Review by ibusko — APPROVED** [review]
I believe the way to test this is to actually merge it and then see its effects when we submit new PRs? Anyways, it looks correct from a cursory examination as per github instructions on how to do this.

**Comment by pllim** [comment]
> the way to test this

One could also unleash this on a fork and try it out over there, but probably much easier to merge and "test it live".

**Comment by rosteen** [comment]
I'm fine with "live testing" this and making changes later if needed.

**Pull request merged**
