### PR TITLE
Updated broken sample notebook link

### PR DESCRIPTION
**Pull request by ojustino**
### Description

The "Sample JDAT Notebooks" link broke, so I changed it to one that I assume points to the same information.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [ ] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Review by kecnry — APPROVED** [review]
Thanks @ojustino!  I'm curious how/why the URL changed and if there is any chance it'll change again... but for now this does the trick!

**Review by rosteen — APPROVED** [review]
New link looks right to me, thanks! Like Kyle, I wonder when this changed and hope it won't change again...

**Comment by ojustino** [comment]
I think a lot of links on the site changed sometime in the past few months. I had favorites for certain pages on JWST's instruments that are now broken, too. I don't know for sure, but I assume things will be more stable now that JWST data has transitioned from public to private.

**Comment by pllim** [comment]
We run linkcheck in the cron jobs but I don't know who is getting notified when it fails. I don't think I do.

https://github.com/spacetelescope/jdaviz/actions/workflows/ci_cron_weekly.yml

**Pull request merged**
